### ISSUE TITLE
Resize Image: creates recursive resizes also for thumbnails

### ISSUE THREAD

**Issue by bogdannedelcu** [firebase/extensions#10]
I activated the resize extention on my Storage bucket.
I have photos inside a folder in the storage.

When uploading a picture, the extension keeps creating thumb in thumb folders and images

folder has a file named: _200x200.jpg and another folder thumb inside which has the same content.

Extension and bucket are in Europe-West

Thank you,
Bogdan

**Comment by Salakar** [comment]
Hey @bogdannedelcu 👋 - looks like this is a duplicate of #7 - will reply there. Thanks

**Comment by bogdannedelcu** [comment]
Duplicate. Closing
