### ISSUE TITLE
storage-resize-images doesn't respect "keep original image" setting

### ISSUE THREAD

**Issue by GusRuss89** [firebase/extensions#100]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **storage-resize-images**
- Configuration values (redact info where appropriate):
  - **240x240,600x600**
  - **max-age=2592000**
  - **Delete original: No**

### [REQUIRED] Step 3: Describe the problem

The extension seems to have trouble respecting my settings. I have a staging project and a production project. On my staging project I installed it and it worked properly out-of-the-box, but in my production project, the first time I installed it it didn't do anything at all. I uninstalled and re-installed, and this time it worked, but it also deleted the original image (opposite of my configuration option). I uninstalled and re-installed again and the same image deletion issue happened.

#### Steps to reproduce:

Install the extension, configure with the settings shown above.

##### Expected result

When a new image is uploaded, create two resized versions (240x240 & 600x600) and keep the original.

##### Actual result

Sometimes nothing happens at all. Other times the resized versions are there but the original gets deleted.

**Comment by rosariopfernandes** [comment]
@GusRuss89 Sorry you ran into this and thanks for reporting it.

---

@Salakar I suspect the JavaScript code is returning Truthy:

https://github.com/firebase/extensions/blob/506f56b6a98b4197dd8799e46b16ccb8ca4c564d/storage-resize-images/functions/lib/config.js#L23

Apparently, we forgot to run `npm run build` before v.0.1.2 release. (if that's the case, it might be fixed in #42 which is only missing a second review). Let me know what you think

**Comment by Ehesp** [comment]
Thanks @rosariopfernandes - once #42 gets resolved this will indeed be fixed. We're working on getting commit hooks setup to ensure the JS/TS don't become out of sync.

**Comment by laurenzlong** [comment]
Thank you for reporting the bug @GusRuss89 ! This is quite a serious issue, so we're removing v0.1.2. You can now go to Firebase Console, and click on the "update" button. (It'll actually downgrade the extension to v0.1.1). Our website and console has been updated also, so when you install a new instance of Resize Images, it will be installing v0.1.1. 

Next week, we hope to release v0.1.3 which will bring back the feature, and also add the feature in  #42
