### ISSUE TITLE
Recursive delete errors with Cloud Resource Manager API  Error

### ISSUE THREAD

**Issue by jimmykane** [firebase/extensions#102]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

Extension delete user data latest 0.1.2 

#### Steps to reproduce:

Used recursive delete 

##### Expected result
Run smoothly
##### Actual result
```
'HTTP Error: 403, Cloud Resource Manager API has not been used in project 242713487388 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project=242713487388 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.',
```

**Comment by Ehesp** [comment]
Hello @jimmykane, have you visited the link provided and enabled the API?

**Comment by jimmykane** [comment]
Yes I did and I enabled the api.

Then I tried to delete eg my user , but since some hours now the logs
(failed or no) are not coming in. Will try again later.

The point here, why did I have to enable that api ?

**Comment by Ehesp** [comment]
Just trying to figure out what's going on here. What state is/was your project in when installing the extension? Is it freshly created or is it in use?

cc @laurenzlong I'm not sure whether this error related to extension usage or more generic project usage (e.g. managing the Firebase project).

**Comment by jimmykane** [comment]
Project is live with the extension on since launch of the extensions. 
Project is live about 4 or more months now. 

I have not touched the google cloud console for the project (eg toggle things) I have exclusively managed it via firebase web because its so great and easy. 

All is running fine, this is not a serious per se bug, but rather surprised that it needed to enable that API

**Comment by jimmykane** [comment]
(after the api was enabled all run as they should in regards to the extension + config)

**Comment by laurenzlong** [comment]
Hi @jimmykane thanks for filing! That API is used by us in order to grant the extension the appropriate IAM permissions to your project. However, that API is normally turned on automatically for all new projects. I'm not sure why it was turned off if you yourself didn't touch the Cloud Console. We don't manage that API so I'm don't know what might have happened. 

I'm glad to hear that your extension is now running without issues. I'm going to close this issue now, but please feel free to comment again if you see this happening again.
