### ISSUE TITLE
[firestore-bigquery-export] Inconsistent versions being displayed

### ISSUE THREAD

**Issue by gregfenton** [firebase/extensions#1024]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-bigquery-export**
- Extension version: **0.1.10**

### [REQUIRED] Step 3: Describe the problem

Not understanding where the `firebase ext:upgrade` is getting its information from.  Either there is an inconsistency or there is information I can't seem to find from other `firebase` commands?

#### Steps to reproduce:

```bash
➜  firebase ext:list
i  extensions: ensuring required API firebaseextensions.googleapis.com is enabled...
✔  extensions: required API firebaseextensions.googleapis.com is enabled
i  extensions: list of extensions installed in roman-stage:
┌────────────────────────────────────┬───────────┬───────────────────────────┬────────┬─────────┬─────────────────────┐
│ Extension                          │ Publisher │ Instance ID               │ State  │ Version │ Your last update    │
├────────────────────────────────────┼───────────┼───────────────────────────┼────────┼─────────┼─────────────────────┤
│ firebase/firestore-bigquery-export │ firebase  │ firestore-bigquery-export │ ACTIVE │ 0.1.10  │ 2020-11-24 15:44:56 │
└────────────────────────────────────┴───────────┴───────────────────────────┴────────┴─────────┴─────────────────────┘


➜  firebase ext:update fsbq-export-act
i  extensions: ensuring required API firebaseextensions.googleapis.com is enabled...
✔  extensions: required API firebaseextensions.googleapis.com is enabled
i  extensions: Checking project IAM policy...
✔  extensions: Project IAM policy OK
i  extensions: Updating fsbq-export-act from version firebase/firestore-bigquery-export@0.1.20 to version firebase/firestore-bigquery-export@0.1.24.
```

##### Expected result

The versions displayed in the above output are consistent (e.g. in Firebase Console >> Extensions, I see `0.1.10-rc.1` as the version I have installed, and `0.1.24` appears to be the latest release).

##### Actual result

I see four values being displayed:
1. `0.1.10` in `firebase ext:list`
2. `0.1.10-rc.1` in Firebase Console >> Extensions
3. `0.1.20` and `0.1.24` in `firebase ext:update`

I understand `0.1.24` but I cannot explain the discrepancies of the other values?
And I found the value of `0.1.20` comes from my `firebase.json`.

It might be helpful to indicate in the console output where these values are coming from.

**Comment by cabljac** [comment]
Closing, versions should all be synched now as of 0.1.26 at least.
