### ISSUE TITLE
[firestore-bigquery-export] Confusing prompt wording during upgrade

### ISSUE THREAD

**Issue by gregfenton** [firebase/extensions#1025]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-bigquery-export**
- Extension version: **0.1.24**

#### Steps to reproduce:

Here's the console output of my upgrade effort:

```bash
➜  firebase git:(main) firebase ext:update fsbq-export-act
i  extensions: ensuring required API firebaseextensions.googleapis.com is enabled...
✔  extensions: required API firebaseextensions.googleapis.com is enabled
i  extensions: Checking project IAM policy...
✔  extensions: Project IAM policy OK
i  extensions: Updating fsbq-export-act from version firebase/firestore-bigquery-export@0.1.20 to version firebase/firestore-bigquery-export@0.1.24.
? Do you wish to continue? Yes
To update this instance, configure the following new parameters:

Project Id: Override the default project bigquery instance. This can allow updates to be directed to a bigquery instance on another project.
? Enter a value for Project Id: roman-stage

Wildcard Column field with Parent Firestore Document IDs (Optional): Creates a column containing a JSON object of all wildcard ids from a documents path.
? Which option do you want enabled for this parameter? Select an option with the arrow keys, and use Enter to confirm your choice. You may
 only select one option. (Use arrow keys)
❯ No
  Yes
```

##### Expected result

The prompts provided during the upgrade are understandable and instill confidence as I answer them to effect my production system.

##### Actual result

The wording of the last question phrased in the above output is confusing.  "Yes" and "No" do not seem to align to the new feature ("Wildcard Column field") or to the prompt ("Which option ... for this parameter").

##### Additional Information

The subsequent prompt is also disconcerting:

```
BigQuery Time Partitioning column name (Optional): BigQuery table column/schema field name for TimePartitioning. You can choose schema available as timestamp OR new custom defined column that will be assigned to the selected Firestore Document field below. Defaults to pseudo column _PARTITIONTIME if unspecified. Cannot be changed if Table is already partitioned.
? Enter a value for BigQuery Time Partitioning column name:
```

Unclear if simply pressing ENTER is how I opt out of this new capability?  And the wording of "Cannot be changed" is ... frightening.

It would be helpful to:
- describe how to keep the extension continuing to behave as it did prior to this update
- have a link to documentation describing these features in more detail
- recommendation as to what to do?

**Comment by dackers86** [comment]
Thnaks @gregfenton.

I agree this could be worded better, added to our project board for consideration. Thanks!

**Comment by dackers86** [comment]
Closing as related PR has been merged.
