### ISSUE TITLE
[firestore-send-email] Support child id path for mail collection 

### ISSUE THREAD

**Issue by CambodianCoder** [firebase/extensions#1026]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **\_** (`storage-resize-images`, `firestore-send-email`, etc)

`firestore-send-email`

### What feature would you like to see?

Describe the feature you would like to add, or how you'd like to see the extension change.

When setting up the firestore-send-email trigger extension, it asks for the name of the mail collection. The current setup seems to only support top-level collections, such as `mail`. When I configure the extension to use a nested collection path for the mail collection, such as `mail/users/{user-id}`, any documents/ mail templates written to the specified location do not result in an email being triggered.

### How would you use it?

Tell us how you'd use this feature in your app.

I want to categorize which emails are being sent out, by user. Currently, all the emails for every user just end up in the same top level collection, which makes it hard to identify the emails sent to a specific user. Allowing nested/child collection paths for the `mail ` collection will allow developers to very easily see and query for mail sent to a specific user.

**Comment by ankit-programmer** [comment]
I would like to implement this feature this weekend if someone else can't do it earlier.

**Comment by dackers86** [comment]
Hi @ankit-programmer.

This unlikely to implemented this week, a PR would be very welcome. Thanks!

**Comment by ankit-programmer** [comment]
@CambodianCoder I tried to categorize emails based on users as you requested (mail/users/{user-id}) and its working fine without any changes. Can you please try again and let me know?
