### ISSUE TITLE
Generic URL Shortener

### ISSUE THREAD

**Issue by drveresh** [firebase/extensions#1027]
### Step 1: Are you in the right place?

Yes, it is for a **firestore-shorten-urls-bitly**, and for a broad and generic solution, without having a dependency on Bitly or other single entity or service.

### Step 2: Extension name

This feature request is for extension: `firestore-shorten-urls-bitly`

### What feature would you like to see?

It is **not fair** to support only Bitly, there are hundreds of them in the market (tinyurl, etc.), and we should be able to configure custom services, with corresponding endpoints, API keys, a way to define request/response structure, and eventually return or set a short URL.  You should remove the 'bitly' name and make it generic like 'firestore-url-shortener'.

Also, we need a new **service to publish our custom extensions** as well, for advanced custom use cases for our customers.

### How would you use it?

I want to define my own custom URL shortening service and integrate it with my apps. Mainly to convert long URLs in the firestore or realtime database into short ones.

**Comment by drveresh** [comment]
I have opened a separate case(#10186790) with your web support team to look into it.

**Comment by microsudha** [comment]
I'm planning to use `firestore-shorten-urls-bitly`, but currently only `Bitly` is supported, how can I use other shortening service. Need a way to customize the url shortening service.

**Comment by dackers86** [comment]
@drveresh @microsudha 

Thanks the feedback, currently this extension is specifically for Bitly, but understand the need for more providers.

I'll add to our project board for discussion.

Out of curiosity, what other `providers`	would you like to use?

**Comment by drveresh** [comment]
@dackers86 I have several cases to choose different providers, like TinyURL, firelinks.io, or something else, depending on the features and API limits.  But, definitely, it should not stick to just one provider, like Bitly.

Your team has already [published it](https://firebase.google.com/products/extensions/firebase-firestore-shorten-urls-bitly?authuser=2&hl=en) and indirectly supports Bitly, and it is an **unfair** business practice!

I already requested for an invite to the internal extension development program, but **no response** for three months.  Please check with your team and update me on it, as I am skilled enough to develop a new one with custom providers asap.  

It shouldn't be prolonged for months!  Please share the concrete update on it, with timelines.

**Comment by dackers86** [comment]
Hi @drveresh.

Apologies for the delay, I have passed this on internally and will provide any updates.

**Comment by drveresh** [comment]
@dackers86 @cabljac Please share the latest updates. The entire global community of users and businesses is waiting for this feature for non-bitly and generic/custom URL shortener integration.  The short links are very fundamental and vital service to everyone, so your team should prioritize it asap without further delay.

**Comment by dackers86** [comment]
Hi @drveresh 

Good news! At the Firebase Summit, Google announced that developers now have the option to build their own extensions through the Firebase Extensions Alpha program.

The best option at this stage is to go to https://extensions.dev/ and scroll down to the `Build your own extension`.

Let me know if you need any more information.

**Comment by dackers86** [comment]
Closing until more information is required.

**Comment by drveresh** [comment]
@dackers86 Why did you close this when the real issue is still there where it is hard coded to use Bitly service forcefully? Is there any strategic partnership between Firebase and Bitly to increase only their business and block other services?

**Comment by i14h** [comment]
@drveresh while I agree it's great to support more url shorteners, we don't have any plans to do so in this extension. As Darren said you're welcome to start a new extension with more features and shorteners supported.

**Comment by drveresh** [comment]
@i14h @dackers86 My point is why is your team giving so much precedence to Bitly service/company? Technically, isn't it an absurd decision to design it just only for Bitly? This poor decision is literally blocking every other URL shortener service.  There must be a plan to update this extension to support other URL-shortening APIs/services before it falls into legal discriminatory and anti-competitor issues or litigations.

Rather than letting everybody build alternate extensions, you must make it generic to comply with your own terms of "single-purpose" or "no duplicate" experience.  I just hope that none of you aren't influenced or incentivized by Bitly company by any means.

This is absolutely not a fair process. I urge you once to reopen this and fix it asap!
