### ISSUE TITLE
storage-resize-images URL not accessible

### ISSUE THREAD

**Issue by patrinoua** [firebase/extensions#1029]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **`storage-resize-images`**
- Extension version: **v1**
- Configuration values (redact info where appropriate):
  - **\_**
  - **\_**

### [REQUIRED] Step 3: Describe the problem

I am using the `storage-resize-images extension` ( ext-storage-resize-images-generateResizedImage )
which in 90% of the cases works properly, but some times returns this:

```
{
  "error": {
    "code": 403,
    "message": "Permission denied."
  }
}
```

so the photo is not accessible.

### URL working properly
https://firebasestorage.googleapis.com/v0/b/buddies-production-e6f71.appspot.com/o/userPictures%2Fmrsblackgr%40gmail.com-iiddfTgfDohenr6S9QglSIm8vIf2%2FprofilePicture_500x500.jpg?alt=media&token=9ddad85f-a144-4cb1-862a-450f80c84c69

### URL that is **not** working properly
https://firebasestorage.googleapis.com/v0/b/buddies-production-e6f71.appspot.com/o/userPictures%2Fszaszoca%40gmail.com-9ouMJ3k6vGfOwBof5ecXGjqBFiC3%2FprofilePicture.jpg?alt=media&token=3d9efedd-7a91-4346-bce3-6d7480a74317

Can you please have a look?

Many thanks in advance,
Angela Patrinou

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.

##### Expected result
URL is always accessible

##### Actual result
URL sometimes return a 403

**Comment by dackers86** [comment]
Hi @patrinoua.

The image generated have an access token. Could it be that these tokens have expired? Or does this issue occur for newly generated images.

A new token could be potentially generated via the Firebase storage UI:

![image](https://user-images.githubusercontent.com/2060661/177176067-b572f304-994a-4ab1-a397-d7e76d8ec12a.png)

**Comment by dackers86** [comment]
That is strange, the url seems to ok when comparing the generated image url. 

Out of curiosity, do you have a rule set in your storage permissions that would not match the second image? For example:

`/userPictures/mrsblackgr@gmail.com-iiddfTgfDohenr6S9QglSIm8vIf2/`

`/userPictures/szaszoca@gmail.com-9ouMJ3k6vGfOwBof5ecXGjqBFiC3/`

`szaszoca@gmail.com-9ouMJ3k6vGfOwBof5ecXGjqBFiC3` may not be an allowed path?

**Comment by patrinoua** [comment]
There are no special rules no. 
Everything is the same and in 90% of the cases it works properly. 
If you'd like to see it in action, you can download buddies-app.com

**Comment by dackers86** [comment]
HI @patrinoua 

We are so unable to replicate this issue, we currently have a PR that allows all images to be `public` by default.

Would this be a potential solution, or would you prefer to keep the images secure to your app?

https://github.com/firebase/extensions/pull/1003

**Comment by patrinoua** [comment]
Looks good, looking forward to trying this once it's merged!

**Comment by patrinoua** [comment]
And thank you for investigating!

**Comment by patrinoua** [comment]
@dackers86 can we merge?

**Comment by patrinoua** [comment]
After some further investigation, I think the reason why this is not working is the fact that the URL that is being saved is the URL before resizing, which then gets deleted after the resize, and a new URL gets created.
This happens when the user navigates to the next screen before the upload is completed: 
The first url is saved and the second one (resized) is lost and hence it does not work properly.

So I will try to resize the photo on the client side using [expo-image-manipulator](https://www.npmjs.com/package/expo-image-manipulator) or some similar service.

Thank you for having a look on this, I will close the issue now.
