### ISSUE TITLE
[firestore-translate-text] Error "User Rate Limit Exceeded"

### ISSUE THREAD

**Issue by sreenath-n** [firebase/extensions#1033]
Getting the error "User Rate Limit Exceeded" when translating to 14 different languages at once:

```
LOCATION=asia-south1
LANGUAGES=bn,en,gu,hi,kn,ml,mr,ne,or,pa,sd,ta,te,ur
COLLECTION_PATH=translations
INPUT_FIELD_NAME=input
OUTPUT_FIELD_NAME=output
```

Functions Log:
```
Error when translating string: 'Cat' into language(s): 'hi' ApiError: User Rate Limit Exceeded
    at new ApiError (/workspace/node_modules/@google-cloud/common/build/src/util.js:58:15)
    at Util.parseHttpRespBody (/workspace/node_modules/@google-cloud/common/build/src/util.js:193:38)
    at Util.handleResp (/workspace/node_modules/@google-cloud/common/build/src/util.js:134:117)
    at /workspace/node_modules/@google-cloud/common/build/src/util.js:432:22
    at onResponse (/workspace/node_modules/retry-request/index.js:228:7)
    at /workspace/node_modules/teeny-request/build/src/index.js:233:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 403,
  errors: [
    {
      message: 'User Rate Limit Exceeded',
      domain: 'usageLimits',
      reason: 'userRateLimitExceeded'
    }
  ],
```

**Comment by yamankatby** [comment]
Hi @sreenath-n, Thank you for reporting this issue.

I couldn't reproduce the error, everything seems to be working properly. The `User Rate Limit Exceeded` error is thrown by google translate API if you [exceeded the per minute quota](https://cloud.google.com/translate/quotas#:~:text=If%20you%20exceed%20your%20quota,24%20hours%20to%20become%20effective.). Can you check and make confirm if it is.

**Comment by cabljac** [comment]
Closing as stale, if the issue is still happening, we can reopen.

**Comment by sc4321** [comment]
I also got Rate Limit Exceeded. My question is what kind of rate exceeded? Is it write requests per minute or upload data in Kbytes per minute exceeded? I use the free program now.
