### ISSUE TITLE
Request to use wildcard in cloud storage path for resized images

### ISSUE THREAD

**Issue by markrcummins** [firebase/extensions#104]
When uploading image to root (like a profile picture), would be great if I could store the resized image in a folder like users/{userId}/public/profile.

Currently, it creates a subdirectory in users literally named {userId}.

Unless there's a way to do it that I'm not figuring out. A point in the right direction would be greatly appreciated!

**Comment by karayu** [comment]
Hi Mark, 

Thanks so much for the feature request! Unfortunately this is not possible right now because Storage doesn't have access to the userid that is referenced. 

Thanks again for filing this and using extensions!
Kara

**Comment by granttj01** [comment]
@karayu 

Please see my [comment](https://github.com/firebase/extensions/issues/173#issuecomment-600587429) as I believe this would be a viable solution.
