### ISSUE TITLE
Resize-image-extension "firebase.extensions.storage-resize-images.v1.complete" event trigger can not be created

### ISSUE THREAD

**Issue by supratikkoley** [firebase/extensions#1042]
### [READ] Step 1: Are you in the right place?
YES
### Extension Configuration

- Extension name: **storage-resize-images** 
- Extension version: **0.1.28**
- Configuration values (redact info where appropriate):
  - **Events enabled**

### PROBLEM
Even if _Events_ is enabled for this extension, it can not be deployed with creating event trigger.

It's always showing -

`⚠  functions: HTTP Error: 400, Cannot create trigger projects/<project-id>/locations/us-central1/triggers/onimageresized-891786: The request was invalid: The request was invalid: invalid value for attribute 'type' in trigger.event_filters: "firebase.extensions.storage-resize-images.v1.complete"

⚠  functions: failed to create function projects/<project-id>/locations/us-central1/functions/onimageresized
Failed to create function projects/<project-id>/locations/us-central1/functions/onimageresized
`
It's stating that event type is not valid somehow. I think that probably it's not creating trigger in eventArc channel.
<img width="1376" alt="Screenshot 2022-07-14 at 11 52 58 PM" src="https://user-images.githubusercontent.com/41138817/179055054-dcc17c6d-dd95-4ac4-9ef1-d43ef95c3d51.png">

#### Steps to reproduce:

1. This code is creating problem. Whenever I try to create event listener for **stoarge-resiize-images** extension, the above mentioned error is happening.

`exports.onimageresized = onCustomEventPublished("firebase.extensions.storage-resize-images.v1.complete",
  (event) => {
    console.info("Received image resize completed event", event);
});
`

##### Expected result
It should be deployed
##### Actual result
Throwing error

`⚠  functions: HTTP Error: 400, Cannot create trigger projects/<project-id>/locations/us-central1/triggers/onimageresized-891786: The request was invalid: The request was invalid: invalid value for attribute 'type' in trigger.event_filters: "firebase.extensions.storage-resize-images.v1.complete"

⚠  functions: failed to create function projects/<project-id>/locations/us-central1/functions/onimageresized
Failed to create function projects/<project-id>/locations/us-central1/functions/onimageresized
`

**Comment by pavelgj** [comment]
@supratikkoley what's your firebase CLI version? (`firebase --version`)

**Comment by supratikkoley** [comment]
@pavelgj firebase CLI version: 11.2.2

**Comment by pavelgj** [comment]
There appears to be a bug in the Firebase CLI `11.2.*`. As a workaround please downgrade the CLI to `11.1.0`
`npm install -g firebase-tools@11.1.0`

**Comment by pavelgj** [comment]
Let's keep it open -- need to fix the issue in the latest version.

**Comment by pavelgj** [comment]
Actually, Firebase CLI is a more appropriate place to track this issue and someone else already filed an issue there as well. I'll close this issue in favour of https://github.com/firebase/firebase-tools/issues/4744
