### ISSUE TITLE
Image resice recoursively generate thumbnails until fails with too long filename

### ISSUE THREAD

**Issue by kirillshilin** [firebase/extensions#105]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** (`storage-resize-images`)
- Configuration values (redact info where appropriate):
Deployment locationDescription
europe-west2
Cloud Storage bucket for imagesDescription
packedoo-dev.appspot.com
Sizes of resized imagesDescription
200x200
Cloud Storage path for resized images (Optional)Description
Parameter not set
Cache-Control header for resized images (Optional)Description
Parameter not set

### [REQUIRED] Step 3: Describe the problem
![image](https://user-images.githubusercontent.com/16437090/68584843-fa4e9380-0480-11ea-9d5a-ca70a352cce7.png)

#### Steps to reproduce:

Installed image resize extension with default settings, Uploaded image to the default bucket, 
thumbnails started to be generated recursively until failed because of too long file name
(https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.

**Comment by Ehesp** [comment]
Hey @kirillshilin - this sounds like an issue which was discovered and solved in the `0.1.1` release. Can you confirm which version you're using?

**Comment by Ehesp** [comment]
Hey @kirillshilin - if you're still having issues on an upgraded version of the extension, please let me know & this can be reopened and investigated. Thanks!
