### ISSUE TITLE
[firestore-bigquery-export] GCP Incident causing missing BQ exports, how to resync?

### ISSUE THREAD

**Issue by MorenoMdz** [firebase/extensions#1060]
#### Steps to reproduce:

Hey there,

We noticed that we are missing a few rows from a specific hour on [May 6th, 2022](https://status.cloud.google.com/incidents/4Qvmd4q81VnA9RirCMqV), and a few of our collections that are automatically exported to BQ are missing rows during that time, now we are not so sure we are not missing data in other collections and would be good to resync our collections with BQ somehow.  

If we do use the npx script to resync, will it cause a lot of duplication in the dataset or is it smart enough to only add the data that is missing? 

##### Expected result

All data to be properly exported to BQ from Firestore.

##### Actual result

Data is missing in BQ for a few hours.

**Comment by cabljac** [comment]
Will need to look into whether the resync script merges or simply duplicates. If it duplicates then we should look into trying to fix this.

**Comment by cabljac** [comment]
So looking into this, it seems it will duplicate data. I think the safest practice is perhaps to move to a new table and instance and import to that?

**Comment by MorenoMdz** [comment]
> So looking into this, it seems it will duplicate data. I think the safest practice is perhaps to move to a new table and instance and import to that?

Interesting, just to confirm you did run the exporter multiple times to check if it is idempotent and ended up with duplicated data? I'll have to check with our data team if we we can use a different table as suggested

**Comment by cabljac** [comment]
Yes can confirm, I ran the script twice and it duplicated my test data.

**Comment by MorenoMdz** [comment]
> Yes can confirm, I ran the script twice and it duplicated my test data.

Gotcha, I think we will end up running it in a different table to validate how much data we are missing and moving over just the missing data. It would be good to improve the script to handle duplication and or update the documentation to be clear about it.

**Comment by cabljac** [comment]
Closing in favour of the feature request https://github.com/firebase/extensions/issues/1803
