### ISSUE TITLE
TTL support for firestore-send-email

### ISSUE THREAD

**Issue by tiagope** [firebase/extensions#1072]
### Extension name

This feature request is for extension: **firestore-send-email**

### What feature would you like to see?

Now with [TTL Support for Firestore](https://firebase.google.com/docs/firestore/ttl) would be great if **firestore-sen-email** implement a configuration possibility to determine expiration time of sended emails.

In configuration whe set the time, like 1 day, 1 week..... and would be created a *expireAt* field, and then we would create a TTL Policy.

### How would you use it?

The log of sended email from **firestore-send-email** normaly is not necessary and we have to create routines to clear the unecessary data.

**Comment by ottob** [comment]
I was just about to write the same feature request. This would be very useful!
