### ISSUE TITLE
html field not getting rendered in Email, rest is working fine

### ISSUE THREAD

**Issue by sanesanyo** [firebase/extensions#1073]
Hi all,
I have been testing firebase email trigger plugin. Everything has worked well so far except I have been facing a weird bug which I am not able to resolve as I also do not see any errors anywhere neither in the delivery results not in cloud function calls. Basically, the html field added in the collection is not getting rendered in the email sent, rest of the fields are working just fine. I tried different iterations, with plain div tags only and different other iterations, following are the few ones I tried:
<div>Welcome {{username}} to our portal</div>
Welcome to <code>@{{username}}</code> to our portal

I am not sure what am I getting wrong, therefore I would be extremely grateful if someone can help me out. I think there must be some trick I am missing somewhere.

FYI: I am testing it purely in the firebase console for now to see how it works and have not tried to add data in the collection from any SDKs yet.

Looking forward to your response.

Regards,
Sanyog

**Comment by dackers86** [comment]
Hi @sanesanyo 

Can you post an example of the collection document you have added?

My initial thoughts are that you are using template data and this could be overriding the content but would need a sample that we could replicate the issue with. Thanks!

**Comment by sanesanyo** [comment]
Hi @dackers86, it is very weird that it is working now. I had a text field in the document as well for cases where the email client does not render html but it seems that the plugin is sending the text field as the default email not the html field. So as soon as I got rid of text field and then try sending the email template again, html content is getting rendered. Do you know why that is happening?

Thanks a lot for your help.

**Comment by dackers86** [comment]
Thanks @sanesanyo.

Sending both should be ok to my knowledge. I'll add this to our project board for investigation.

**Comment by yamankatby** [comment]
Hi @sanesanyo @dackers86,

The `text` and `html` fields are not meant to be working together but to replace each other, which means if both fields are provided the text version will be shown only if the mail client doesn't support Html. However, if only the `text` field is provided it will be shown as the email body anyway.

```js
const message = {
  subject: "Message title",
  text: "Plaintext version of the message",
  html: "<p>HTML version of the message</p>"
};
```

**Comment by yamankatby** [comment]
Hi @sanesanyo,
Just tried to send an email with both `text` and `html` fields provided and it works just fine and renders the Html, same using templates.

Template document:
![Screen Shot 2022-07-29 at 16 20 54](https://user-images.githubusercontent.com/35961879/181770172-f160a465-9bdc-4c93-8102-0bb39d714cad.png)
Rendered email:
![Screen Shot 2022-07-29 at 16 20 20](https://user-images.githubusercontent.com/35961879/181770176-e4a55a9e-90fc-4597-8f3e-41c5462af832.png)

Can you try again and confirm that this is an ongoing issue?

**Comment by sanesanyo** [comment]
Hi @yamankatby, I tried again with the text field and it somehow seems to work now. Not sure what was the issue before. May be something I missed. Really weird. 

Thanks a lot for your help.
