### ISSUE TITLE
firebase.extensions.storage-resize-images.v1.complete Trigger permission denied

### ISSUE THREAD

**Issue by georgelviv** [firebase/extensions#1079]
### [READ] Step 1: Are you in the right place?
Yes

### [REQUIRED] Step 2: Describe your configuration

Extension name: **storage-resize-images**
Extension version: **0.1.28**
Configuration values (redact info where appropriate):
Events enabled

### [REQUIRED] Step 3: Describe the problem
I've deployed very simple function

```typescript 
import {onCustomEventPublished} from "firebase-functions/v2/eventarc";

export const customhandler = onCustomEventPublished(
    "firebase.extensions.storage-resize-images.v1.complete",
    (e) => {
      console.log("it works!", JSON.stringify(e));
    }
);

```

And trying to receive the appropriate log (which means my cloud functions are handling an event but seems like it doesn't work.

What I've found suspicious, firebase function created trigger in Eventarc, but it constantly having permissions denied in invocations chart (I've didn't change any permissions, only added owner roles to every service account just to make sure it's not related
![image](https://user-images.githubusercontent.com/9251831/182231443-742718e0-b410-404b-b417-8843fc89a265.png)
<img src="https://user-images.githubusercontent.com/9251831/182232540-5ec12ddb-7c34-443a-9658-c7279e4fb074.png" width="400" >

#### Steps to reproduce:
```
node v16.14.0
firebase-tools v11.4.1
```

1. Install the extension  `firebase/storage-resize-images@0.1.28`
2. Enable `firebase.extensions.storage-resize-images.v1.complete` event in extensions configuration
3. Create a new project with `$ firebase init functions`
4. Create same function as from [example](https://firebase.google.com/docs/functions/beta/custom-events) cloud function _firebase.extensions.storage-resize-images.v1.complete_
5. Deploy it
3. Upload any image to firebase storage, and wait until it will be resized
6. Check [Evanterc Trigger](https://console.cloud.google.com/eventarc/triggers) invocations, [Cloud Function Logs](https://console.cloud.google.com/functions)

##### Expected result
Cloud function should show logs and should execute. No permissions denied messages in Eventarc trigger

##### Actual result
Cloud function is not invoked, Permissions denied error in Eventarc  Trigger

Thanks in advance!

**Comment by dackers86** [comment]
Hi @georgelviv 

I'm currently unable to replicate having a working example with the following example:

```js

const { eventarc } = require("firebase-functions/v2");

exports.onimageresized = eventarc.onCustomEventPublished(
  "firebase.extensions.storage-resize-images.v1.complete",
  (event) => {
    console.log("event >>>>", event);
  }
);

```

![image](https://user-images.githubusercontent.com/2060661/182252187-72d5297c-0b0e-4da9-869f-55b052b8548b.png)



1. Could you confirm that you have deployed the function to the same project as the installed extension.
2. Provide the dependencies and the versions used for deploying the function.
3. List the node version used when installing and deploying your function.

Thanks!

**Comment by georgelviv** [comment]
Hi @dackers86 

Thanks for reply

1. Yes. 
.firebaserc
```json
{
  "projects": {
    "default": "drone-map-550bb"
  }
}
```
![image](https://user-images.githubusercontent.com/9251831/182304899-9530a024-8f4d-48b6-b0f5-cf325a02a05e.png)

2. 
package.json
```json
  "dependencies": {
    "firebase-admin": "^10.0.2",
    "firebase-functions": "^3.18.0"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.12.0",
    "@typescript-eslint/parser": "^5.12.0",
    "eslint": "^8.9.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-import": "^2.25.4",
    "firebase-functions-test": "^0.2.0",
    "typescript": "^4.5.4"
  }
```

3. `node v16.14.0` 
`firebase-tools 11.4.1`

**Comment by georgelviv** [comment]
I found the reason
The reason was with permissions. Pub/Sub service account didn't had enough permissions, more here

https://github.com/firebase/extensions/pull/967#issuecomment-1186171281

**Comment by dackers86** [comment]
Thanks @georgelviv. I'm glad the issue is resolved, we will look into updating the documentation or an alternative approach to avoid this issue int he future.
