### ISSUE TITLE
EventArc has permissions denied when using events on a non-enabled pubsub project.

### ISSUE THREAD

**Issue by dackers86** [firebase/extensions#1080]
- Extension name: storage-resize-images
- Extension version: 0.1.28
- Configuration values (redact info where appropriate):
  Events:
  - [x] firebase.extensions.storage-resize-images.v1.complete

There is an issue for users when calling events through event-arc.  Permissions are not available for pub-sub.

Please see https://github.com/firebase/extensions/pull/967#issuecomment-1186171281 and https://github.com/firebase/extensions/issues/1079

#### Steps to reproduce:

1. On a brand new project, install the extension and select the `complete` event stated above.
2. Deploy a new cloud function with the following example:

```js
import {onCustomEventPublished} from "firebase-functions/v2/eventarc";

export const customhandler = onCustomEventPublished(
    "firebase.extensions.storage-resize-images.v1.complete",
    (e) => {
      console.log("it works!", JSON.stringify(e));
    }
)
```
3. Resize an image through the extension.

##### Expected result

Your cloud function will successfully log out the new image resize event.

##### Actual result

Cloud function is not invoked, Permissions denied error in Eventarc Trigger.

**Comment by yamankatby** [comment]
Hi @dackers86,
Blocked due to waiting for feedback from a similar issue:
https://github.com/firebase/extensions/issues/1136
