### ISSUE TITLE
storage-resize-images add enable events as part of manifest configuration

### ISSUE THREAD

**Issue by georgelviv** [firebase/extensions#1088]
### [READ] Step 1: Are you in the right place?
Yes

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **storage-resize-images**

### What feature would you like to see?

Currently to enable events with **storage-resize-images** you need manually update the configuration with firebase ui. After re-deploy extensions with manifest, events are not enabled

### How would you use it?

Enable events will be part of the manifest configuration file

**Comment by yamankatby** [comment]
Hi @georgelviv,
Thank you for filling this issue, from your description this should be an issue for the CLI (firebase-tools) repo, can you please open this issue there?
https://github.com/firebase/firebase-tools

**Comment by georgelviv** [comment]
Hi @yamankatby 
Thanks, I will close this issue here

**Comment by yamankatby** [comment]
Hi @georgelviv,
Thank you for responding to my earlier request, however, while discussing this issue internally we thought we can provide more support here. Can you please confirm that this is still an ongoing issue and if yes can you provide more information that you think could be helpful?

**Comment by georgelviv** [comment]
Hi @yamankatby 
After update firebase-tools, I've found that after export configuration to local file manifest, it added two more new fields in *.env file
ALLOWED_EVENT_TYPES=firebase.extensions.storage-resize-images.v1.complete
EVENTARC_CHANNEL=projects/${param:PROJECT_ID}/locations/us-central1/channels/firebase

That what I was looking for

**Comment by yamankatby** [comment]
Hi @georgelviv,
Thank you for your feedback, added to the project to be considered.

**Comment by yamankatby** [comment]
Hi there,
Currently Blocked, Updating [CLI documentation](https://firebase.google.com/docs/cli#extensions-commands) required rather than Extensions.

**Comment by dackers86** [comment]
Closing as this is not an issue directly related to the extension.
