### ISSUE TITLE
[FR] Add resized image names to original image meta info

### ISSUE THREAD

**Issue by apps-transround** [firebase/extensions#11]
### [REQUIRED] Step 2: Extension name

This feature request is for extension: **\_** (`storage-resize-images`)

### Add resized image names as meta info to the original image 

To help discovering if resized images were created for an image add resized image path/name(s) as a meta information to the original image
Will help finding thumbnails without extra queries even with changing configurations.

**Comment by laurenzlong** [comment]
Thanks for the feature request!

**Comment by envyram** [comment]
I think this is a MUST needed feature

**Comment by Ehesp** [comment]
XFN Team: Related PRs https://github.com/firebase/extensions/pull/6 https://github.com/firebase/extensions/pull/42

**Comment by shankie-san** [comment]
Likewise, I think this is a must-have feature. I can compose the string to get the path of the resized image, but it's pretty long-winded as this extension appends (rather than prepends) the image size prior to the file extension, meaning that I've got to do some pretty complicated regex logic to get the resized image path.

**Comment by karayu** [comment]
Thanks so much for the feature request! This makes a lot of sense to track the original image. However, given you can have multiple Resize Image extensions for multiple phone sizes and this should be a two-way sync (the link should update if images get deleted), the implementation is a bit complicated. 

A more flexible solution seems like it would be a new extension that manages a Firestore collection to track all your images. This way, you'd be able to sort and update the records as files in Cloud Storage changes. 

I'm going to close this for now and track separately as a extension to mirror your Cloud Storaage bucket.
