### ISSUE TITLE
BigQuery Data Import Error - Multiple errors occurred during the request.

### ISSUE THREAD

**Issue by gnjuguna** [firebase/extensions#110]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** (`storage-resize-images`, `firestore-send-email`, etc)
- Configuration values (redact info where appropriate):
  - **\_**
  - **\_**

firestore-bigquery-export

### [REQUIRED] Step 3: Describe the problem

I am trying to import data from firestore to big query using "fs-bq-import-collection", but I am running into the error below after a couple of minutes.

"Inserted 300 row(s) of data into BigQuery
Inserting 300 row(s) of data into BigQuery

Error importing Collection to BigQuery: Error: Multiple errors occurred during the request. Please see the `errors` array for complete details.

1. Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
2. Invalid Credentials"

#### Steps to reproduce:

I ran the script `npx @firebaseextensions/fs-bq-import-collection` to import firestore data to bigquery. 

What happened? How can we make the problem occur?

Data started importing to big query, but after some 5 or so minutes, the import stopped with the error below.

Error importing Collection to BigQuery: Error: Multiple errors occurred during the request. Please see the `errors` array for complete details.

1. Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
2. Invalid Credentials"

This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.

##### Expected result

All records to be imported to bigquery

##### Actual result

Not all records imported. Failed afer a few minutes.

**Comment by laurenzlong** [comment]
Hey @IanWyszynski Do you have an idea of what might be causing this issue?

**Comment by IanWyszynski** [comment]
>Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.

This is bizzare. The import script is a pretty thin wrapper around the Firestore and BigQuery node.js APIs that doesn't deal with authentication at all. The error is likely coming from one of those two downstream sdks. Can you think of anything in the environment that the script was running in that might affect your GCP oauth credentials?

**Comment by jhuleatt** [comment]
You'll need [Application Default Credentials](https://cloud.google.com/docs/authentication/production#obtaining_and_providing_service_account_credentials_manually) set up in the environment that you're running the script in. The service account that you use will need the permission `bigquery.datasets.create`
