### ISSUE TITLE
Resize Image - Callback

### ISSUE THREAD

**Issue by ltbmedia** [firebase/extensions#111]
This feature request is for extension: **\_** (`storage-resize-images`)

It would be great to see a callback included in the extension to be able to get information about the new image that has been created.

For example, 
- you have the extension configured on a bucket
- you upload the original image to the bucket and await a callback
- when the new resized image has been created the callback includes information about that new image 

This would make the extension more useable and make it a lot easier to know when the image has been created, and easier to go fetch it.

Thanks.

**Comment by Ehesp** [comment]
Hey @ltbmedia

Just so I understand correctly, do you mean a data record/list of resized images? So, if I upload an image it gets resized but also a records gets added to a database somewhere?

Thanks!

**Comment by ltbmedia** [comment]
Hi there,

That would be one solution I guess.
But a cleaner approach in what I was asking would be -->

`storageRef.put(ORIGINAL_IMAGE).then((snapshot) => {

      // as this image was uploaded to a bucket with the resize-function configured
      // wait for callback to let us know the resized image(s) have completed
     // include data about the new resized image(s) so we can store & fetch

});`

Hope this helps,
Thanks

**Comment by AliakseiPaseishvili** [comment]
Hm I don't know where I need to write, but I agree with you.
Currently I am using React Native app with firebase inside, We added resize images extension to the project and found that when we got resized image we can't get url for it because it don't have access token(download URL) in Firebase Storage, while the parent image (which is not resized) have it.

**Comment by ltbmedia** [comment]
Hi Aliaksei,
You can get the resized image by using ->

let gsReference = this.storage.refFromURL('gs://your-bucket-name/' + filename + '_200x200' + fileExtension)

You can only call this and get the resized image from the bucket once the resize-function has completed, otherwise you get an error because the new resized image does not exist yet - only workaround is using a delay before calling that which isn't a great solution.

This is why we need a callback in the function to let us know that the new image exists, and has been completed. We also need the new image information so that we don't have to string together a reference url!

Hope this helps

**Comment by AliakseiPaseishvili** [comment]
@ltbmedia , very strange.
![image](https://user-images.githubusercontent.com/50828981/68881822-ecb63980-071e-11ea-9737-b9dbd0688ac6.png)
![image](https://user-images.githubusercontent.com/50828981/68881831-ef189380-071e-11ea-92f3-6dcf2ba735c6.png)
I added image directly to storage for testing resizing... and original image has download url, but resized not...
But on videos here , resized images have donwload URL... https://www.youtube.com/watch?v=zrpydDVFa3I&t=263s , https://www.youtube.com/watch?v=Sx7ijOnob54 , https://www.youtube.com/watch?v=9o8oenmUBYg&t=17s .

I will try to use your workaround, but for me it looks like a bug....

**Comment by rosariopfernandes** [comment]
@AliakseiPaseishvili the download url is only added after a call to `getDownloadUrl()` is made, as mentioned [here](https://github.com/firebase/extensions/issues/34#issuecomment-552595619)

**Comment by Ehesp** [comment]
Hi All - this is an interesting topic and is relatable across other Extensions. This is being reviewed internally for now, we'll let you know as soon as possible on how to correctly handle such a use-case. Thanks!

**Comment by madmacc** [comment]
A callback would be very useful.  I have done this as below but I found sometimes it takes longer to resize than 5 seconds so I increased it to 10 seconds.  This is still no guarantee it won't break.  
Is there no way to get a notification/callback of some kind?
```
 setTimeout(() => {
    this.downloadURL = this.storage.ref(thumbPath).getDownloadURL();
}, 5000);   
```

**Comment by laurenzlong** [comment]
@ltbmedia What if the extension can optionally publish to a PubSub topic after it finishes resizing the image? Would that solve your use case?

**Comment by ltbmedia** [comment]
Hi @laurenzlong, I guess if that is a way of knowing when the resize has completed then that would solve the initial issue. 

Would the published message also contain information about the resized image so that an additional call does not have to be made?

Thanks

**Comment by laurenzlong** [comment]
@ltbmedia What kind of information would you want?

**Comment by AliakseiPaseishvili** [comment]
as a workaround, I used firebase function that works for this case : ` functions.storage.object().onFinalize(callback)` - here I wrote logic, where we check what file is uploaded  and if it is an image - I check is it resized or not - if yes  - I am calling `getSignedUrl` method for our path and then add it to the firestore, where it should be.

**Comment by ltbmedia** [comment]
@laurenzlong downloadURL would be ideal or some reference to the image

**Comment by laurenzlong** [comment]
@ltbmedia If your desire is to simply know how to download the newly resized image, and not do any additional processing, then perhaps https://github.com/firebase/extensions/issues/11 is more suitable. As well, it would not be a good idea for us to auto generate download URLs on the resized image, since you should be in control of the access model of your file, there's a good explanation of the different types of download URLs in this [SO comment](https://stackoverflow.com/a/56010225), and we would not want  to be making the decision for you of what kind of a download URL to generate.

**Comment by madmacc** [comment]
@laurenzlong I don't think https://github.com/firebase/extensions/issues/11#issue-499273584 would solve this issue as there is still no "notification" of the change.  Also I delete the originals. 
If @AliakseiPaseishvili's solution works then it would solve the problem for me I think.

**Comment by ltbmedia** [comment]
Hi @laurenzlong, the biggest issue is not knowing when the resized image has completed - that’s why a callback or function as you suggested is needed.

If a downloadURL or other reference cannot be supplied I can use my own method to fetch the file, but at least I would know that it is ready.

**Comment by laurenzlong** [comment]
Thanks for the additional context @ltbmedia! We'll take this into consideration as we plan out our roadmap.

**Comment by karayu** [comment]
Hi @ltbmedia thanks so much for this feature request! 

We've reviewed this as a team and think that the best solution long term is better lifecycle management for an extension: a way to understand the status of an extension (when it's executing and when it has finished) and a way to trigger an action based on a status change from an extension. We're thinking through this problem long term and to @Ehesp's point, this is a feature that would benefit many extensions. 

Unfortunately, in the short-term, there is no easy fix for this. I'm closing this for now but we will be tracking this internally in our long term roadmaps. 

Thanks again for the feedback! 
Kara

**Comment by ltbmedia** [comment]
Hi @karayu, this is great news and look forward to hearing any progress on this 👍

**Comment by Mian-Zaid** [comment]
I have found the solution to it like i have to comment out the line which deleting the access token in the cloud function and now i have access to token of image after resizing but there is problem that if i have to change the configurations of extension the code is updated in cloud function so i have to change this line every time i change the configuration. i have attached the snippet of code which i have to change.
this solution works for me well but its not a solid solution.

its simple process



1. after installing the extension go to functions
2. then select **view details usage** its opens a screen from where you have to select **source**
3. form source find file named **FUNCTIONS/LIB/INDEX.JS** , Go to line 152 then comment this out
 code on line 152 : **delete metadata.metadata.firebaseStorageDownloadTokens;**
![vd](https://user-images.githubusercontent.com/38668413/80060773-cf488f80-8548-11ea-86c7-ea2a01d0a24a.PNG)
![file](https://user-images.githubusercontent.com/38668413/80060782-d7083400-8548-11ea-9d7c-7d3777a427c7.PNG)

**Comment by russellwheatley** [comment]
@Mian-Zaid You might be interested in tracking this PR which deletes that token: https://github.com/firebase/extensions/pull/279

**Comment by samuelkarani** [comment]
html solution

```
<picture>
  <source media="(max-width: 799px)" srcset="elva_800x800.jpg">
  <source media="(min-width: 800px)" srcset="elva.jpg">
  <img src="elva.jpg" alt="Elva">
</picture>
```

**Comment by findnizam** [comment]
anyone found the solution for this? Any callbacks to download the resized image?

**Comment by TravisJN** [comment]
I still can't find a viable solution to this issue. As many others have requested, it would be ideal to have a callback with the resized image's metadata that is invoked when the image processing is complete. Users would have complete control of what to do with the new image when it is done processing or they can simply ignore the callback.

**Comment by madmacc** [comment]
@TravisJN 
I have an Angular solution which involves polling for the file to see when it exists.  Not ideal but it works ok.

```
ngOnInit() {
    this.bucket = this.afStorage.storage.app.storage(environment.storageBucketChatFiles);
    // this.defaultBucket = this.afStorage.storage.app.storage();
    this.useDateInFileName = this.data.useDateInFileName;
    this.pathDirectory = this.data.pathDirectory;
    this.entityId = this.data.entityId;
  }

  toggleHover(event: boolean) {
    this.isHovering = event;
  }

  startUpload(event: FileList) {
    // The File object
    const file = event.item(0);
    if (file.size > (environment.imageUploadSizeLimit * 1024 * 1024)) {
      this.notificationService.alertError(`Please ensure that the size < ${environment.imageUploadSizeLimit}Mb`, 'File Size to Large');
      return;
    }
    if (this.supportedContentTypes.includes(file.type)) {
      // Image will be resized
      this.sizeNameSuffix = '_800x800';
    }
    // The storage path
    const path = this.generateStoragePath(file);
    // The main task
    let storageRef: firebase.storage.Reference;
    try {
      this.spinner.show('spinner-upload');
      storageRef = this.bucket.ref().child(path);
      if (this.sizeNameSuffix.length > 0) {
        this.fileUpload.storagePath = this.addResizeExtensionToName(path);
      } else {
        this.fileUpload.storagePath = path;
      }
      this.fbTask = storageRef.put(file);
      this.fbTask.catch(err => {
        console.log(err);
        this.notificationService
        .alertError(`Please check the type of the file and that the size < ${environment.imageUploadSizeLimit}Mb`, 'Error Uploading File');
        this.fileUpload.storagePath = null;
        return;
      });

      // Progress monitoring
      // this.percentage = this.task.percentageChanges();
      // this.snapshot   = this.task.snapshotChanges();

      // The file's download URL
      this.fbTask.then(async result => {
        if (this.sizeNameSuffix.length > 0) {
          // Is Image
          this.spinner.hide('spinner-upload');
          this.spinner.show('spinner-resize');
          const storageRefResized: firebase.storage.Reference = this.bucket.ref().child(this.fileUpload.storagePath);
          this.firebaseStorageService.keepTrying(10, storageRefResized).then(downloadUrl => {
            this.fileUpload.url = downloadUrl;
            this.spinner.hide('spinner-resize');
            this.dialogRef.close( { fileUpload: this.fileUpload } );
          }, err => {
            console.log(err);
          });
        } else {
          // Other type of file
          this.fileUpload.url = await storageRef.getDownloadURL();
          this.spinner.hide('spinner-upload');
          this.dialogRef.close( { fileUpload: this.fileUpload } );
        }
      });
        // Remove extension and add size
    } catch (err) {
      console.log(err);
      this.notificationService.alertError('Error', 'Error Uploading File');
      this.fileUpload.storagePath = null;
      return;
    } finally {
      this.spinner.hide('spinner-upload');
    }
  }

  // Determines if the upload task is active
  isActive(snapshot) {
    return snapshot.state === 'running' && snapshot.bytesTransferred < snapshot.totalBytes;
  }

  keepTrying(triesRemaining, storageRef: firebase.storage.Reference): Promise<any> {
    if (triesRemaining < 0) {
      return Promise.reject('out of tries');
    }
    return storageRef.getDownloadURL().then((downloadUrl) => {
      return downloadUrl;
    }, error => {
      switch (error.code) {
        case 'storage/object-not-found':
          return this.delay(2000).then(() => {
            return this.keepTrying(triesRemaining - 1, storageRef);
          });
        default:
          console.log(error);
          return Promise.reject(error);
      }
    });
  }
```

**Comment by smbowler** [comment]
Hello, any progress on the callback or lifecycle management status? I am running into the same issue as others on this thread - no ability to get the downloadURL + token for a resized image. Thank you!

**Comment by jaysonfrazer** [comment]
Really interested to know if a solid solution to this has been developed. Having to set timeout delay before checking for the download URL. Works in development, but really nervous putting this into production.

**Comment by madmacc** [comment]
@jaysonfrazer I am still using my polling method in production but check out this release and see if it has what we want.
https://github.com/firebase/extensions/releases/tag/storage-resize-images-v0.1.28
Let me know!

**Comment by CalvinJamesHeath** [comment]
I want to only update the firestore document when the resize is finished, since setting a timeout is a very bad solution.
