### ISSUE TITLE
How to set from address

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [firebase/extensions#112]
The email address to use as the sender’s address (if it’s not specified in the added email document).

Well, how do I do it, there is no example, no documentation on how to specify in the document, whats the key or something

**Comment by Ehesp** [comment]
Hello

When setting up the extension, you'll be promoted for an email which is used as the default 'from' address:

![image](https://user-images.githubusercontent.com/842078/69059808-284a4f80-0a0e-11ea-9d5c-8a1f6491672c.png)

If you don't include a `from` field in the document being added to Firestore, this email address will be used automatically.

Does that help?

**Comment by diego-lipinski-de-castro** [comment]
I tried to include a 'from' field in the document but it didnt work, the email used was the default still

**Comment by diego-lipinski-de-castro** [comment]
Well, actually, it worked, I dunno, yesterday I tested and I didnt worked, but right now, with the 'from' field it actually took it, so, yeah, thats it
