### ISSUE TITLE
storage-resize-images "firebase.extensions.storage-resize-images.v1.complete" event trigger function deploys but doesn't work

### ISSUE THREAD

**Issue by alexalget** [firebase/extensions#1136]
Extention name: storage-resize-images
Version: 0.1.28

My extention configuration:

Location: us-central1
Bucket: default
Sizes of resized images: 640x360,1120x630,1600x900,1920x1080
Deletion of original: false
path of new images: resized
specific paths to resize: (yes)
specific paths to ignore: none
cloud function memory: 1024 MB
Enabled events: true, channel: us-central1, event: firebase.extensions.storage-resize-images.v1.complete

I had multiple errors when trying to use trigger events for this extention and I think its important that someone adds this to the docs of this extention.

First firebase deploy function would throw the error:

[ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v2/eventarc' is not defined by "exports" in ".\functions\package.json"

To fix that I updated the following dependecies on my package.json in my project:
upgrade firebase-admin from ^10.0.2 to ^11.0.1.
upgrade firebase-functions from ^3.18.0 to ^3.22.0.
I found on a forum that those new versions added the v2 functions .
Then, I runned "npm ci" in my project to do a clean install of the dependecies.

Here is why I think users must be warned and you should provide a dependencies list when using custom trigger on this extention:

I was able to deploy the custom trigger function without issues after fixing the first error but the function would not work and eventarc wouldn't show any triggers on the eventarc section of cloud console.

Here's what firebase deploy would show when deploying the trigger (no errors):

C:\flutter_project\functions>firebase deploy --only functions:onimageresized

=== Deploying to 'flutter_project'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> functions@ lint C:\flutter_project\functions
> eslint .

+  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  functions: ensuring required API artifactregistry.googleapis.com is enabled...
+  functions: required API cloudfunctions.googleapis.com is enabled
+  functions: required API cloudbuild.googleapis.com is enabled
+  functions: required API artifactregistry.googleapis.com is enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (43.72 KB) for uploading
i  functions: ensuring required API pubsub.googleapis.com is enabled...
i  functions: ensuring required API cloudscheduler.googleapis.com is enabled...
+  functions: required API pubsub.googleapis.com is enabled
+  functions: required API cloudscheduler.googleapis.com is enabled
+  functions: functions folder uploaded successfully
i  functions: cleaning up build files...

+  Deploy complete!

Comparing this with someone else's deployment I noticed that when I was deploying the trigger function, the script would not mention anything about eventarc API so I guessed that I could update the firebase-tools to try to fix it.

Here is what i did:

-Upgrade firebase-tools from 10.0.1 to 11.1.0.
-Upgrade node-js from 14.x.x to 16.16 (lastest on Aug 2022).
-Disabled the event "complete" on the image resized extention.
-Tried to delete the trigger that I deployed before but threw an error that "onimageresized" function didn't exist. 
-Enabled the event "complete" on the image resized extention again.
-Deployed my "onimageresized" function again, now the script checks if the "eventarc.googleapis.com" API is enabled.

C:\flutter_project>firebase deploy --only functions:onimageresized

=== Deploying to 'flutter_project'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> lint
> eslint .

npm notice
npm notice New minor version of npm available! 8.11.0 -> 8.16.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.16.0
npm notice Run npm install -g npm@8.16.0 to update!
npm notice
+  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
+  functions: required API cloudfunctions.googleapis.com is enabled
+  functions: required API cloudbuild.googleapis.com is enabled
i  functions: preparing codebase default for deployment
i  functions: preparing functions directory for uploading...
i  functions: packaged C:\flutter_project\functions (43.49 KB) for uploading
i  functions: packaged C:\flutter_project\functions (43.72 KB) for uploading
i  functions: ensuring required API cloudscheduler.googleapis.com is enabled...
+  functions: required API cloudscheduler.googleapis.com is enabled
i  functions: ensuring required API artifactregistry.googleapis.com is enabled...
i  functions: ensuring required API run.googleapis.com is enabled...
i  functions: ensuring required API eventarc.googleapis.com is enabled...
i  functions: ensuring required API pubsub.googleapis.com is enabled...
i  functions: ensuring required API storage.googleapis.com is enabled...
+  functions: required API pubsub.googleapis.com is enabled
+  functions: required API eventarc.googleapis.com is enabled
!  functions: missing required API run.googleapis.com. Enabling now...
+  functions: required API artifactregistry.googleapis.com is enabled
+  functions: required API storage.googleapis.com is enabled
+  functions: required API run.googleapis.com is enabled
i  functions: generating the service identity for pubsub.googleapis.com...
i  functions: generating the service identity for eventarc.googleapis.com...
+  functions: functions folder uploaded successfully
i  functions: creating Node.js 16 function onimageresized(us-central1)...
+  functions[onimageresized(us-central1)] Successful create operation.
i  functions: cleaning up build files...

+  Deploy complete!

Then I tried again to trigger the my function but it didnt work, so I found that I had to grant permissions to PubSub.

-Go to PubSub suscriptions https://console.cloud.google.com/cloudpubsub/subscription/list
-Click on the onimageresized subscription ID (eventarc-us-central1-onimageresized-xxxxxx-sub-xxx)
-Click Edit at the top
-Check for a permission warning "Note: Cloud Pub/Sub needs the role roles/iam.serviceAccountTokenCreator granted to service account..." and click on GRANT.

Now the trigger works.

I hope that this steps or at least a list of dependecies versions can be added to the extention docs I think that it would save a ton of time for other new developers that might have older versions.

**Comment by yamankatby** [comment]
Hi @alexalget,
Thank you for providing this guide, already we have an ongoing PR that may be related to this issue. Can you please give it a look and see if it is solving your issue?

**Comment by alexalget** [comment]
> Hi @alexalget, Thank you for providing this guide, already we have an ongoing [PR](https://github.com/firebase/extensions/pull/1090) that may be related to this issue. Can you please give it a look and see if it is solving your issue?
> 
> #1090

Hey there, I reviewed your changes to the docs on the PREINSTALL.md but It doesnt solve all the issues that I needed to solve before using the events properly.

**Comment by yamankatby** [comment]
Hey @alexalget,
Thank you for your feedback, I'm trying to keep the guide generic so developers choose which permission/role to apply to the account. Can you please suggest to me the part you think it's not clear to embed in the guide?
