### ISSUE TITLE
TypeError: Cannot read property 'attachments' of undefined

### ISSUE THREAD

**Issue by Pavlo-Krostylov** [firebase/extensions#1144]
**Describe your configuration**
- Extension name: firestore-send-email
- Extension version: 0.1.18
- Configuration values:
- - Templates collection: mail-templates

**Describe the problem**
There is an issue with sending emails using templates. On previous version 0.1.17 everything was ok

**Steps to reproduce:**

1. Create a new template in mail-templates collection:
```json
{
  "TemplateName": {
    "attachments": [
      {
        "cid": "logo",
        "filename": "logo.png",
        "path": "https://firebasestorage.googleapis.com..."
      }
    ],
    "html": "<!DOCTYPE html PUBLIC ....",
    "subject": "New Email"
  }
}
```
2. Add a new document to the mail collection
``` javascript
let email = 'mail@mail.mail';
db.collection("mail").add({
    to: [email],
    template: {
        name: "TemplateName",
    }
});
```

**Expected result**
Sent letter based on the template

**Actual result**
```json
{
  "delivery": {
    "attempts": "1",
    "endTime": "August 19, 2022 at 12:46:56 PM UTC+3",
    "error": "TypeError: Cannot read property 'attachments' of undefined",
    "leaseExpireTime": "null",
    "startTime": "August 19, 2022 at 12:46:54 PM UTC+3",
    "state": "ERROR"
  }
}
```

**Comment by yamankatby** [comment]
Hi @Pavlo-Krostylov,
Thank you for filling this issue, my initial thoughts are that you don't have a document with `Document ID` of `TemplateName` in your `templates` collection. Can you please confirm that?

Note: The `TemplateName` must be the `Document ID` of the document not a `key` of a `map`. Example template doc:
```js
{
  subject: "@{{username}} is now following you!",
  html: "Just writing to let you know that <code>@{{username}}</code> ({{name}}) is now following you.",
  attachments: [
    {
     filename: "{{username}}.jpg",
     path: "{{imagePath}}"
    }
  ]
}
```

**Comment by Pavlo-Krostylov** [comment]
Hi @yamankatby No, I have 
I have 2 separate identical projects in the firebase
On the old one - all works
And on the new one, with the same identical settings - I catch an error:
`TypeError: Cannot read property 'attachments' of undefined`

I think the only difference is the "Trigger Email" extension, which was installed a few months ago on an old project

**Comment by yamankatby** [comment]
Hi @Pavlo-Krostylov,
Unfortunately, I couldn't reproduce the issue. The current latest version of the extension is `v0.1.19`, can you update and retry it?

If the issue still exists, can you take screenshots of the logs and documents templates/mail and maybe the configuration of the extension and share them here?

**Comment by Pavlo-Krostylov** [comment]
@yamankatby 
Thanks, I solved my problem
The problem was in the `space` in the `Document ID` name: " TemplateName"

**Comment by SammyROCK** [comment]
I ran into this issue and in my case I had a template named "password_reset".
Turned out that from version 0.1.13 to 0.1.19 the underline was no longer supported when naming a template

**Comment by sanesanyo** [comment]
I am running into this issue now. Weird thing is that I have exactly the same configuration in another firebase project & it works but in this new project, I am getting this attachment being undefined error. I have not defined attachments in my template nor I have am setting it when I am adding an object to mail collection. I have spent last 2 hours trying to figure out what is going on. Sometimes Firebase really takes soul out of me.
My template collection is called "handlebar". There I have a template with id: "WelcomeMail" which is as following:
{
html: "html code inside here",
subject: "Welcome @{{username}}"
}

Then when I add the following object in the mail collection, I get that above mentioned error:
{
template: 
{
data:  { username: "Test User"},
name: "WelcomeMail"
},
to: ["email@email.com"]
}
}

Like I said before, same configuration works in other firebase project but fails here. I really do not know what to do.

**Comment by SergeyDertan** [comment]
Have you solved this?
2025 and same issue
