### ISSUE TITLE
Infinite loop when trying to resize an image 

### ISSUE THREAD

**Issue by kalmicka** [firebase/extensions#1165]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: storage-resize-images
- Extension version: 0.1.29
- Configuration values (redact info where appropriate):
DELETE_ORIGINAL_FILE=on_success
FUNCTION_MEMORY=1024
IMAGE_TYPE=jpeg
IMG_BUCKET=${param:PROJECT_ID}.appspot.com
IMG_SIZES=80x80,640x640
IS_ANIMATED=true
LOCATION=europe-central2
MAKE_PUBLIC=false

### [REQUIRED] Step 3: Describe the problem
Trying to use the extension inside the emulator suite results in an infinite loop for me. The extension never stops and thus takes down the whole emulator.

#### Steps to reproduce:

For me this occurs in two separate projects. I installed the extension in the firebase console and then used the "firebase ext:export" command to get the settings into my emulator. I fired up the emulator and went to the "Storage" tab and uploaded an image to convert. The output of the console shows me that the image is being converted, however, instead of stopping it redoes the conversion, and again, and again, till I force the emulator to stop. 

##### Expected result

The conversion happens once and stops.

##### Actual result

The conversion happens and appends the specific image sizes it rendered and then starts over.

This is the console log I get:

`
functions: Beginning execution of "generateResizedImage"
>  {"bucket":"myapp-prod.appspot.com","imageSizes":["80x80","640x640"],"makePublic":false,"deleteOriginalFile":2,"imageTypes":["jpeg"],"animated":true,"severity":"INFO","message":"Started execution of extension with configuration"}
>  {"severity":"INFO","message":"Creating temporary directory: '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T'"}
>  {"severity":"INFO","message":"Created temporary directory: '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T'"}
>  {"severity":"INFO","message":"Downloading image file: 'PHOTO-2022-08-16-17-38-40.jpg'"}
>  {"severity":"INFO","message":"Downloaded image file: 'PHOTO-2022-08-16-17-38-40.jpg' to '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T/PHOTO-2022-08-16-17-38-40.jpg'"}
>  {"severity":"INFO","message":"Resizing image at path '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T/PHOTO-2022-08-16-17-38-40_80x80.jpeg' to size: 80x80"}
>  {"severity":"INFO","message":"Resizing image at path '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T/PHOTO-2022-08-16-17-38-40_640x640.jpeg' to size: 640x640"}
>  (node:49251) DeprecationWarning: uuidv4() is deprecated. Use v4() from the uuid module instead.
>  (Use `node --trace-deprecation ...` to show where the warning was created)
>  {"severity":"INFO","message":"Resized image created at '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T/PHOTO-2022-08-16-17-38-40_80x80.jpeg'"}
>  {"severity":"INFO","message":"Converting image from type, .jpg, to type jpeg."}
>  {"severity":"INFO","message":"Converted image to jpeg"}
>  {"severity":"INFO","message":"Uploading resized image to 'PHOTO-2022-08-16-17-38-40_80x80.jpeg'"}
>  {"severity":"INFO","message":"Resized image created at '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T/PHOTO-2022-08-16-17-38-40_640x640.jpeg'"}
>  {"severity":"INFO","message":"Converting image from type, .jpg, to type jpeg."}
>  {"severity":"INFO","message":"Uploaded resized image to '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T/PHOTO-2022-08-16-17-38-40_80x80.jpeg'"}
>  {"severity":"INFO","message":"Deleting temporary resized file: 'PHOTO-2022-08-16-17-38-40_80x80.jpeg'"}
>  {"severity":"INFO","message":"Deleted temporary resized file: 'PHOTO-2022-08-16-17-38-40_80x80.jpeg'"}
>  {"severity":"INFO","message":"Converted image to jpeg"}
>  {"severity":"INFO","message":"Uploading resized image to 'PHOTO-2022-08-16-17-38-40_640x640.jpeg'"}
>  {"severity":"INFO","message":"Uploaded resized image to '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T/PHOTO-2022-08-16-17-38-40_640x640.jpeg'"}
>  {"severity":"INFO","message":"Deleting temporary resized file: 'PHOTO-2022-08-16-17-38-40_640x640.jpeg'"}
>  {"severity":"INFO","message":"Deleted temporary resized file: 'PHOTO-2022-08-16-17-38-40_640x640.jpeg'"}
>  {"severity":"INFO","message":"Deleting original file from storage bucket: 'PHOTO-2022-08-16-17-38-40.jpg'"}
>  {"severity":"INFO","message":"Deleted original file from storage bucket: 'PHOTO-2022-08-16-17-38-40.jpg'"}
>  {"severity":"INFO","message":"Completed execution of extension"}
>  {"severity":"INFO","message":"Deleting temporary original file: 'PHOTO-2022-08-16-17-38-40.jpg'"}
>  {"severity":"INFO","message":"Deleted temporary original file: 'PHOTO-2022-08-16-17-38-40.jpg'"}
i  functions: Finished "generateResizedImage" in ~1s
>  {"bucket":"myapp-prod.appspot.com","imageSizes":["80x80","640x640"],"makePublic":false,"deleteOriginalFile":2,"imageTypes":["jpeg"],"animated":true,"severity":"INFO","message":"Initializing extension with configuration"}
>  {"bucket":"myapp-prod.appspot.com","imageSizes":["80x80","640x640"],"makePublic":false,"deleteOriginalFile":2,"imageTypes":["jpeg"],"animated":true,"severity":"INFO","message":"Initializing extension with configuration"}
i  functions: Beginning execution of "generateResizedImage"
i  functions: Beginning execution of "generateResizedImage"
>  {"bucket":"myapp-prod.appspot.com","imageSizes":["80x80","640x640"],"makePublic":false,"deleteOriginalFile":2,"imageTypes":["jpeg"],"animated":true,"severity":"INFO","message":"Started execution of extension with configuration"}
>  {"bucket":"myapp-prod.appspot.com","imageSizes":["80x80","640x640"],"makePublic":false,"deleteOriginalFile":2,"imageTypes":["jpeg"],"animated":true,"severity":"INFO","message":"Started execution of extension with configuration"}
>  {"severity":"INFO","message":"Creating temporary directory: '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T'"}
>  {"severity":"INFO","message":"Creating temporary directory: '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T'"}
>  {"severity":"INFO","message":"Created temporary directory: '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T'"}
>  {"severity":"INFO","message":"Created temporary directory: '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T'"}
>  {"severity":"INFO","message":"Downloading image file: 'PHOTO-2022-08-16-17-38-40_640x640.jpeg'"}
>  {"severity":"INFO","message":"Downloading image file: 'PHOTO-2022-08-16-17-38-40_80x80.jpeg'"}
>  {"severity":"INFO","message":"Downloaded image file: 'PHOTO-2022-08-16-17-38-40_80x80.jpeg' to '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T/PHOTO-2022-08-16-17-38-40_80x80.jpeg'"}
>  {"severity":"INFO","message":"Resizing image at path '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T/PHOTO-2022-08-16-17-38-40_80x80_80x80.jpeg' to size: 80x80"}
>  {"severity":"INFO","message":"Resizing image at path '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T/PHOTO-2022-08-16-17-38-40_80x80_640x640.jpeg' to size: 640x640"}
>  {"severity":"INFO","message":"Downloaded image file: 'PHOTO-2022-08-16-17-38-40_640x640.jpeg' to '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T/PHOTO-2022-08-16-17-38-40_640x640.jpeg'"}
>  (node:49252) DeprecationWarning: uuidv4() is deprecated. Use v4() from the uuid module instead.
>  (Use `node --trace-deprecation ...` to show where the warning was created)
>  {"severity":"INFO","message":"Resizing image at path '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T/PHOTO-2022-08-16-17-38-40_640x640_80x80.jpeg' to size: 80x80"}
>  {"severity":"INFO","message":"Resizing image at path '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T/PHOTO-2022-08-16-17-38-40_640x640_640x640.jpeg' to size: 640x640"}
>  (node:49253) DeprecationWarning: uuidv4() is deprecated. Use v4() from the uuid module instead.
>  (Use `node --trace-deprecation ...` to show where the warning was created)
>  {"severity":"INFO","message":"Resized image created at '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T/PHOTO-2022-08-16-17-38-40_80x80_80x80.jpeg'"}
>  {"severity":"INFO","message":"Converting image from type, .jpeg, to type jpeg."}
>  {"severity":"INFO","message":"Resized image created at '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T/PHOTO-2022-08-16-17-38-40_80x80_640x640.jpeg'"}
>  {"severity":"INFO","message":"Converting image from type, .jpeg, to type jpeg."}
>  {"severity":"INFO","message":"Converted image to jpeg"}
>  {"severity":"INFO","message":"Converted image to jpeg"}
>  {"severity":"INFO","message":"Resized image created at '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T/PHOTO-2022-08-16-17-38-40_640x640_80x80.jpeg'"}
>  {"severity":"INFO","message":"Converting image from type, .jpeg, to type jpeg."}
>  {"severity":"INFO","message":"Uploading resized image to 'PHOTO-2022-08-16-17-38-40_80x80_80x80.jpeg'"}
>  {"severity":"INFO","message":"Converted image to jpeg"}
>  {"severity":"INFO","message":"Uploading resized image to 'PHOTO-2022-08-16-17-38-40_80x80_640x640.jpeg'"}
>  {"severity":"INFO","message":"Uploading resized image to 'PHOTO-2022-08-16-17-38-40_640x640_80x80.jpeg'"}
>  {"severity":"INFO","message":"Resized image created at '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T/PHOTO-2022-08-16-17-38-40_640x640_640x640.jpeg'"}
>  {"severity":"INFO","message":"Converting image from type, .jpeg, to type jpeg."}
>  {"severity":"INFO","message":"Uploaded resized image to '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T/PHOTO-2022-08-16-17-38-40_80x80_80x80.jpeg'"}
>  {"severity":"INFO","message":"Deleting temporary resized file: 'PHOTO-2022-08-16-17-38-40_80x80_80x80.jpeg'"}
>  {"severity":"INFO","message":"Deleted temporary resized file: 'PHOTO-2022-08-16-17-38-40_80x80_80x80.jpeg'"}
>  {"severity":"INFO","message":"Uploaded resized image to '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T/PHOTO-2022-08-16-17-38-40_80x80_640x640.jpeg'"}
>  {"severity":"INFO","message":"Deleting temporary resized file: 'PHOTO-2022-08-16-17-38-40_80x80_640x640.jpeg'"}
>  {"severity":"INFO","message":"Deleted temporary resized file: 'PHOTO-2022-08-16-17-38-40_80x80_640x640.jpeg'"}
>  {"severity":"INFO","message":"Deleting original file from storage bucket: 'PHOTO-2022-08-16-17-38-40_80x80.jpeg'"}
>  {"severity":"INFO","message":"Converted image to jpeg"}
>  {"severity":"INFO","message":"Uploaded resized image to '/var/folders/27/fgz_yh1j2gv99hkr5g4p61pc0000gn/T/PHOTO-2022-08-16-17-38-40_640x640_80x80.jpeg'"}
>  {"severity":"INFO","message":"Deleting temporary resized file: 'PHOTO-2022-08-16-17-38-40_640x640_80x80.jpeg'"}
>  {"severity":"INFO","message":"Deleted temporary resized file: 'PHOTO-2022-08-16-17-38-40_640x640_80x80.jpeg'"}
`

Hope somebody can help me out here.

**Comment by louisthomaspro** [comment]
Hi, same for me. Seems that it's triggering the "generateResizedImage" function everytime a resized image is uploaded.
