### ISSUE TITLE
[firestore-bigquery-export] version confusion

### ISSUE THREAD

**Issue by ptxmac** [firebase/extensions#1171]
### [REQUIRED] Step 2: Describe your configuration

- Extension name:  `firestore-bigquery-export`
- Extension version: 0.1.23 / 0.1.25

### [REQUIRED] Step 3: Describe the problem

The github repository have version 0.1.23 as the newest release of `firestore-bigquery-export`
But on the firebase product page the latest version is reported as 0.1.23

#### Steps to reproduce:

Look at https://firebase.google.com/products/extensions/firebase-firestore-bigquery-export and notice the version field: 
![image](https://user-images.githubusercontent.com/56919/188145159-3445f5bd-86c3-4832-bfd3-bffb55c31d89.png)

Then have a look at https://github.com/firebase/extensions/releases or https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/CHANGELOG.md

Here we only have v0.1.23

0.1.25 is in the branch called "next" which I assume should mean unreleased?

##### Expected result

The latest version on github and firebase should be the same

##### Actual result

Much confusion since I have no idea if I'm running the right version!

**Comment by cabljac** [comment]
Investigating, it seems like the version in the source code on `next` and `master is now `0.1.26` but the latest release listed on github is `0.1.25`.

Seems like we need to do a release to sync things perhaps.

**Comment by cabljac** [comment]
Closing, fixed in a recent release, `0.1.26`.
