### ISSUE TITLE
firestore-bigquery-export - only one collection exported

### ISSUE THREAD

**Issue by JonesM87** [firebase/extensions#12]
### firestore-bigquery-export

Only one collection is exported, no way to sync multiple collections

**Comment by Ehesp** [comment]
Currently a single instance of the extension monitors one collection. To sync multiple collections, you can install the extension multiple times with configuration options specifically for your additional collection.

**Comment by JonesM87** [comment]
Thanks @Ehesp I somehow hadn't seen that you could install multiple instances of the extension

**Comment by felansu** [comment]
@JonesM87 i too, thanks for comment 👍
