### ISSUE TITLE
Video helper

### ISSUE THREAD

**Issue by giammin** [firebase/extensions#120]
### Extension name

doesn't exist yet

### What feature would you like to see?

an extension for reading video metadata as length, resolution, aspect ratio, etc etc and maybe generate a thumbnail

### How would you use it?

when a user upload a video file on the storage

**Comment by Ehesp** [comment]
Hello, thanks for the feature request! Could you also create a ticket [here](https://firebase.google.com/support/troubleshooter/report/features/) linking this issue as reference. Thanks!

**Comment by pietrop** [comment]
+1 on this, I'd also like to add if it could read other info like timecodes, eg rec run, free run, time of the day, relative to the file that would be 🙌

**Comment by jhuleatt** [comment]
This request has been recorded on the internal tracker of new extensions requests. Any other requests for brand new extensions that don't exist in this repository yet can be filed at https://firebase.google.com/support/troubleshooter/extensions/featurerequest
