### ISSUE TITLE
[All] Update firebase-functions and firebase-admin

### ISSUE THREAD

**Issue by joehan** [firebase/extensions#121]
For many (maybe all?) extensions, we use older versions of firebase-functions and firebase-admin. In order to use firebase emulators, we'll need to update these to at least firebase-functions > v3.0.0 and firebase-admin > v8.0.0. Since this is a breaking change to both packages, we should also carefully validate that each extension still works as intended after this change.

**Comment by laurenzlong** [comment]
Hey @Ehesp @Salakar can you make the appropriate updates?

**Comment by laurenzlong** [comment]
Done in https://github.com/firebase/extensions/pull/125
