### ISSUE TITLE
Delete User Data not triggering when user deleted by client SDK

### ISSUE THREAD

**Issue by fergusmeiklejohn** [firebase/extensions#122]
### Step 2: Describe your configuration

- Extension name: **\_** delete-user-data
- Configuration values:
  - **\_**asia-northeast1
  - **\_**userData/{UID},admins/{UID}
  - **\_**shallow

### Step 3: Describe the problem
The function is called and successfully deletes user data when I delete a user in the console, but not called when I delete a user using the WebSDK.

In the client, I call:

`var user = firebase.auth().currentUser;`
then
`user.delete()`

This successfully deletes the user but the function is not triggered.

#### Steps to reproduce:
I install and configure the delete user data function. It works as intended when deleting a user in the console but isn't triggered when deleting a user from the client. I tried uninstalling and installing it again. Same result.

##### Expected result
I expect the same to happen when I delete a user from the client or the console
##### Actual result
function only called when deleting a user from the console

**Comment by Ehesp** [comment]
Hey @fergusmeiklejohn

Thanks for the report. Would you be able to confirm when calling `user.delete()`, the user is no longer visible in the console?

**Comment by mlouli** [comment]
Hi @Ehesp, I have the same issue, and I can confirm that the user is no longer visible on the console when it is deleted.

The only difference is that I am making the call from the iOS client, so it deletes the user successfully but doesn't trigger the `delete-user-data` extension.

And as mentioned by @fergusmeiklejohn, when deleting the user from the console everything works fine.

And I also noticed that the service account created by the extension doesn't work either, by switching to the default one with `Editor` role it works fine, but again, only in the console and not from the clients.

**Comment by Ehesp** [comment]
Thanks for the information!

**Comment by fergusmeiklejohn** [comment]
Hi @Ehesp 
the function is now working. I'm calling user.delete() from the JS SDK and it's deleting the user and then triggering the function :-)

**Comment by jhuleatt** [comment]
This was caused by an issue in the Firebase Authentication back end and has been fixed: https://groups.google.com/d/msg/firebase-talk/ROXTbooVzlM/ZhhMefjqAwAJ
