### ISSUE TITLE
[storage-resize-images] Support imagemagick quality parameter

### ISSUE THREAD

**Issue by iamgoddog** [firebase/extensions#124]
This feature request is for extension: **storage-resize-images**

### What feature would you like to see?

I would like to be able to add the quality level somewhere, which will then be used by imagemagicks convert -quality somehow. 
Either per image (via image meta or header?) or the more likely use-case, per size, for instance in the size setting like: `WIDTHxHEIGHT[q100]` (optional quality)

### How would you use it?

I have different sizes of images where they would benefit from me being able to set the quality for that image instead the default quality. This is important for the larger images which can suffer more from bad quality.

**Comment by karayu** [comment]
Hi!

Thank you so much for this FR. As mentioned in #84, we're thinking about this in terms of building a new extension specifically for ImageMagick where we can surface a lot more of the functionality. We're tracking that internally so I'll close this for now.

Thank so much for using extensions!
Kara
