### ISSUE TITLE
Delete user data extension + Firebase stripe extension causes an error

### ISSUE THREAD

**Issue by tomasconnor** [firebase/extensions#1255]
### Discussed in https://github.com/firebase/extensions/discussions/1254

<div type='discussions-op-text'>

<sup>Originally posted by **tomasconnor** October  9, 2022</sup>
I have Delete user data extension and Firebase stripe extension. If I delete a user in the auth section, the Delete user data extension deletes all records about the user. At the same time, I have auto delete enabled in the Firebase stripe extension settings. Everything is deleted correctly, including the customer object in the Stripe dashboard, however, a 404 error appears in the Stripe error log.

```
{
  "error": {
    "code": "resource_missing",
    "doc_url": "https://stripe.com/docs/error-codes/resource-missing",
    "message": "No such customer: 'cus_Ma34mdpBTy0zFv'",
    "param": "id",
    "type": "invalid_request_error"
  }
}
```

Does anyone else have the same problem?</div>

**Comment by cabljac** [comment]
This seems to be a 404 because `delete-user-data` has deleted the user before the stripe extension does, and then the record isn't there. I don't think this would be a bug in either extension?
