### ISSUE TITLE
[firestore-bigquery-export] Add collection group path template to import script

### ISSUE THREAD

**Issue by jsnee** [firebase/extensions#1261]
### [REQUIRED] Step 2: Extension name

This feature request is for extension: **firestore-bigquery-export**
### What feature would you like to see?

I'd like to see the import script have an option to provide a path template parameter so that the importer could populate `path-params`

### How would you use it?

This would be used to populate the `path-params` of imported records that are part of a collection group import as they currently do get imported without a value. If implemented, the `path-params` could be utilized in queries regardless of if the record was imported by the script or exported by the extension.

**Comment by cabljac** [comment]
This was resolved in https://github.com/firebase/extensions/pull/982 and the import script should now support path params.
