### ISSUE TITLE
firestore-bigquery-export fs-bq-import-collection import script not found

### ISSUE THREAD

**Issue by diginikkari** [firebase/extensions#13]
### Step 2: Describe your configuration

- Extension name: firestore-bigquery-export

### Step 3: Describe the problem

In the IMPORT_EXISTING_DOCUMENTS.md guide there is guide to run `Run npx @firebaseextensions/fs-bq-import-collection` script. This gives an error: 

404 @firebaseextensions/fs-bq-import-collection@latest' is not in the npm registry.

#### Steps to reproduce:

run 

`npx @firebaseextensions/fs-bq-import-collection@latest`

##### Expected result

runs the script 

##### Actual result

> npm ERR! 404 Not Found - GET https://registry.npmjs.org/@firebaseextensions%2ffs-bq-import-collection - Not found

**Comment by rosariopfernandes** [comment]
@diginikkari I believe the correct script is `npx @firebaseextensions/firestore-bigquery-change-tracker`. I sent a PR fixing the guide (see #15). Good catch!

**Comment by masashi-sutou** [comment]
@rosariopfernandes I tried `npm install @ firebaseextensions/firestore-bigquery-change-tracker` and the installation was successful, but `npx @ firebaseextensions/firestore-bigquery-change-tracker` cannot find the command.

**Comment by rosariopfernandes** [comment]
@masashi-sutou You probably don't have npx installed. As described in this [post](https://stackoverflow.com/a/52018825/5861618), npx is "A tool for executing Node packages.", which means it will run `npm install` behind the scenes before executing the package (in case you don't have that package installed yet).

`npx` comes bundled with `npm` version 5.2+, so I'd recommend updating npm if you wish to use npx.

**Comment by PVSPHANINDRA** [comment]
@rosariopfernandes npx is working properly with other packages. Seems like there is an issue with the command `npx @firebaseextensions/firestore-bigquery-change-tracker`

**Comment by xXCalleManXx** [comment]
I get the following output when running the commpand `$npx @firebaseextensions/firestore-bigquery-change-tracker`
`command not found: firestore-bigquery-change-tracker`

**Comment by rosariopfernandes** [comment]
@PVSPHANINDRA @xXCalleManXx You're right! The `firestore-bigquery-change-tracker` package should expose a `fs-bq-import-collection` command, but after installing the package, that command  is not found. I've also pointed this out [here](https://github.com/firebase/extensions/pull/15#issuecomment-536770560). Let's wait for a Firebaser to comment on it.

**Comment by rosariopfernandes** [comment]
The problem was: the script `@firebaseextensions/fs-bq-import-collection` was still marked as private (for Googlers only).

But it has now been made public (see full discussion in #15) :)

Running `npx @firebaseextensions/fs-bq-import-collection` should work just fine now.

**Comment by diginikkari** [comment]
Yes, confirmed it as fixed.
