### ISSUE TITLE
Error when resizing image TypeError: Cannot set property 'resizedImage' of undefined

### ISSUE THREAD

**Issue by Timtech4u** [firebase/extensions#130]
Hello, I installed the Resize Image Extension but it breaks with the following error:
```
Error when resizing image TypeError: Cannot set property 'resizedImage' of undefined
```

Screenshot:
![Screenshot from 2019-12-10 09-50-06](https://user-images.githubusercontent.com/11256481/70513731-772d6580-1b32-11ea-9b0d-927c2b7dc476.png)

**Comment by rosariopfernandes** [comment]
@Timtech4u Thanks for filing this issue. But we might need some more information in order to be able to reproduce the problem:
- Which version of the storage-resize-images extension are you using?
- What configuration parameters did you use to setup the extension?

**Comment by Timtech4u** [comment]
I used the default parameters and the Firebase UI.

It works now when I switch using the CLI command.

`firebase ext:install storage-resize-images --project=projectId`

**Comment by utsav1322** [comment]
Hello, I'm Facing Same Issue
Error when resizing image TypeError: Cannot set property 'resizedImage' of undefined
&
Error when deleting temporary files { Error: ENOENT: no such file or directory, unlink

storage-resize-images extension version 0.1.3
configuration parameters 
-Deployment location 
us-central1
-Sizes of resized images
200*200,500*500,1240*1240
-Deletion of original file
false
-other's are default unset

I have upload it from sdk 
    firebase": "6.3.0",
    "firesql": "2.0.2",
    "linq2fire": "1.0.22",
    "react": "16.8.3",
    "react-native": "0.59.9",
I try installing extension from both way console and cli none of them work for me


![1Screenshot from 2019-12-11 13-21-48](https://user-images.githubusercontent.com/31151641/70602505-9b647180-1c1a-11ea-9388-f1173ce12fb6.png)

**Comment by utsav1322** [comment]
yet its not resizing its getting undefined on line 140 of index.js in lib

**Comment by Cybergebi** [comment]
I setup the Extension for the First Time yesterday and i get exactly the same Error

**Comment by laurenzlong** [comment]
@Ehesp can you try to repro?

**Comment by Ehesp** [comment]
I'm struggling to reproduce this. I've tried an existing instance and a totally fresh one but I can't trigger this error.

Could I ask how you are uploading an image?

If I were to stake a guess, when the image is added, we pass it's data into the resizer function, which attempts to assign a `metadata.resizedImage` field on-top of the original images metadata. I think that depending on *how* the image is uploaded (e.g. web console vs an SDK), that image may not be created with an original metadata field, therefore this error occurs as it's trying to assign a property to something which doesn't exist.

A simple fix would be to change [this line](https://github.com/firebase/extensions/blob/next/storage-resize-images/functions/src/index.ts#L173) to `metadata: objectMetadata.metadata || {},`.

I'd be interested to see though why no metadata is being created by default, to understand where that happens.

**Comment by Cybergebi** [comment]
I'm using the Google Cloud Storage Client for PHP.
The Upload is successful and the picture is also correct. The Error appears on every image i upload.

**Comment by thomasmburke** [comment]
I have reproduced the issue by running the following command and supplying the following inputs:

`firebase ext:install storage-resize-images --project=projectId`

i  extensions: ensuring necessary APIs are enabled...
⚠  extensions: missing necessary APIs. Enabling now...
✔  extensions: all necessary APIs are enabled
i  extensions: Resize Images will be granted the following access to project ${projectID}
- Storage Admin (Full control of GCS resources.)
? Would you like to continue? Yes
i  extensions: answer the questions below to configure your extension:

Deployment location: Where should the extension be deployed? You usually want a location close to your Storage bucket. For help selecting a location, refer to the location selection guide (https://firebase.google.com/docs/functions/locations).
? Which option do you want enabled for this parameter? Select an option with the arrow keys, and use Enter to confirm your choice. You may only select one option. **Iowa (us-central1)**

Cloud Storage bucket for images: To which Cloud Storage bucket will you upload images that you want to resize? Resized images will be stored in this bucket. Depending on your extension configuration, original images are either kept or deleted.
? Enter a value for Cloud Storage bucket for images: **${projectID}.appspot.com**

Sizes of resized images: What sizes of images would you like (in pixels)? Enter the sizes as a comma-separated list of WIDTHxHEIGHT values. Learn more about how this parameter works (https://firebase.google.com/products/extensions/storage-resize-images).
? Enter a value for Sizes of resized images: **750x750**

Deletion of original file: Do you want to automatically delete the original file from the Cloud Storage bucket? Note that these deletions cannot be undone.
? Which option do you want enabled for this parameter? Select an option with the arrow keys, and use Enter to confirm your choice. You may only select one option. **Yes**

Cloud Storage path for resized images (Optional): A relative path in which to store resized images. For example, if you specify a path here of thumbs and you upload an image to /images/original.jpg, then the resized image is stored at /images/thumbs/original_200x200.jpg. If you prefer to store resized images at the root of your bucket, leave this field empty.
? Enter a value for Cloud Storage path for resized images: **tom-new-resize-bucket**

Cache-Control header for resized images (Optional): This extension automatically copies any Cache-Control metadata from the original image to the resized images. For the resized images, do you want to overwrite this copied Cache-Control metadata or add Cache-Control metadata? Learn more about Cache-Control headers (https://developer.mozilla.org/docs/Web/HTTP/Headers/Cache-Control). If you prefer not to overwrite or add Cache-Control metadata, leave this field empty.
? Enter a value for Cache-Control header for resized images: 

✔  extensions: successfully installed Resize Images, its Instance ID is storage-resize-images.
i  extensions: usage instructions:


-------------------------------------------------------------------------------------------------

At this point my function is ready to use. When I upload a file via the console it works as expected. It deletes the uploaded image (images.jpeg in my case) and places the resized image in the following location: gs://${projectID}.appspot.com/tom-new-resize-bucket

However,I encounter this error when I use the **gsutil** tool to copy a file from my local machine to that GCS bucket. I observe that the original image is not there and there is no resized image.

gsutil version: 4.44
firebase-tools version: 7.10.0

**Comment by Ehesp** [comment]
Right, thanks for the feedback. It would make sense then that depending on *how* the image is uploaded, the metadata object assigned to the original image can be `undefined` or an empty object leading to this issue.

I'll get a PR up which ensures metadata is always present.

**Comment by Ehesp** [comment]
I've confirmed that was the issue (and replicated). PR up fixes it.

**Comment by theavijitsarkar** [comment]
Until the code is merged, it can be solved by passing a metadata inside the metadata.

```
File.save(imageBig,{
                    metadata: { contentType: mimeType, metadata :{resizedImage:false }},
                    public: true,
                    validation: 'md5'
                },function(error) {
```

**Comment by ashanker2** [comment]
Is there an ETA for merging this PR?
https://github.com/firebase/extensions/pull/142

**Comment by laurenzlong** [comment]
We are planning to release #142 this Thurs

**Comment by ashanker2** [comment]
Thank you @laurenzlong

**Comment by CyrusZei** [comment]
a good thing would be to add the option for the extension to either do the check if the image does need to resize or not. 

this code should be an option that you can set in the settings for this extension or else you won't have control over it if say you have another cloud function that will listen for the finalize trigger on firebase storage?

<img width="686" alt="Screenshot 2020-06-19 at 03 07 33" src="https://user-images.githubusercontent.com/5053903/85086104-07cbb900-b1da-11ea-91ef-2769fd8cee46.png">
