### ISSUE TITLE
Cannot add fields (field: old_data)

### ISSUE THREAD

**Issue by keochansothea** [firebase/extensions#1312]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** (`storage-resize-images`, `firestore-send-email`, etc)
- Extension version: **\_**
- Configuration values (redact info where appropriate):
  - **\_**
  - **\_**

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.

##### Actual result

I cannot create a schema view using command line npx @firebaseextensions/fs-bq-schema-views.

Command line:
npx @firebaseextensions/fs-bq-schema-views --non-interactive --project=codecanyon---flutter-news --dataset=sale_daily_report --table-name-prefix=record --schema-files=./sale_daily_report_view.json

sale_daily_report_view.json:
{
    "fields": [
      {
        "name": "item_count",
        "type": "number"
      },
      {
        "name": "sale_count",
        "type": "number"
      },
      {
        "name": "total_sale",
        "type": "number"
      },
      {
        "name": "update_dt",
        "type": "timestamp"
      }
    ]
  }

Result:
{"severity":"WARNING","message":"Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail"}
BigQuery creating schema view sale_daily_report_schema_sale_daily_report_view_changelog:
Schema:
{"fields":[{"name":"item_count","type":"number","extractor":"item_count"},{"name":"sale_count","type":"number","extractor":"sale_count"},{"name":"total_sale","type":"number","extractor":"total_sale"},{"name":"update_dt","type":"timestamp","extractor":"update_dt"}]}
Query:
SELECT
  document_name,
  document_id,
  timestamp,
  operation,
  `codecanyon---flutter-news.sale_daily_report.firestoreNumber`(JSON_EXTRACT_SCALAR(data, '$.item_count')) AS item_count,
  `codecanyon---flutter-news.sale_daily_report.firestoreNumber`(JSON_EXTRACT_SCALAR(data, '$.sale_count')) AS sale_count,
  `codecanyon---flutter-news.sale_daily_report.firestoreNumber`(JSON_EXTRACT_SCALAR(data, '$.total_sale')) AS total_sale,
  `codecanyon---flutter-news.sale_daily_report.firestoreTimestamp`(JSON_EXTRACT(data, '$.update_dt')) AS update_dt
FROM
  `codecanyon---flutter-news.sale_daily_report.sale_daily_report_raw_changelog`
BigQuery created schema view sale_daily_report_schema_sale_daily_report_view_changelog

{"code":400,"errors":[{"message":"Provided Schema does not match Table codecanyon---flutter-news:sale_daily_report.sale_daily_report_schema_sale_daily_report_view_changelog. Cannot add fields (field: old_data)","domain":"global","reason":"invalid"}],"response":{"headers":{"alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","cache-control":"private","content-encoding":"gzip","content-type":"application/json; charset=UTF-8","date":"Fri, 25 Nov 2022 07:12:59 GMT","etag":"oAWcoyK77jfxYHk6b0JD+w==","server":"ESF","transfer-encoding":"chunked","vary":"Origin, X-Origin, Referer","x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN","x-xss-protection":"0"}},"message":"Provided Schema does not match Table codecanyon---flutter-news:sale_daily_report.sale_daily_report_schema_sale_daily_report_view_changelog. Cannot add fields (field: old_data)"}
Provided Schema does not match Table codecanyon---flutter-news:sale_daily_report.sale_daily_report_schema_sale_daily_report_view_changelog. Cannot add fields (field: old_data)

**Comment by JeremyWalters** [comment]
Also getting it. **Cannot add fields (field: old_data)**

**Comment by dackers86** [comment]
An update has been added for this issue.

Please use to the latest version `0.4.4`.

Source: https://www.npmjs.com/package/@firebaseextensions/fs-bq-schema-views)

**Comment by dackers86** [comment]
Any future updates can also be tracked [here](https://github.com/firebase/extensions/issues/1300).
