### ISSUE TITLE
Getting the following bug: "TypeError: Cannot read property 'attachments' of undefined", same configuration works fine in another firebase project

### ISSUE THREAD

**Issue by sanesanyo** [firebase/extensions#1371]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: firestore-send-email
- Extension version: 0.1.20

### [REQUIRED] Step 3:   I am getting the following error when I add a new object to my mail collection: TypeError: Cannot read property 'attachments' of undefined
I am using exactly the same configuration in another project and things work just fine. I do not understand what is going on.

#### Steps to reproduce: 
My template collection is called "handlebar". There I have a template with id: "WelcomeMail" which is as following:
{
html: "html code inside here",
subject: "Welcome @{{username}}"
}

Then when I add the following object in the "mail" collection:
{
template:
{
data: { username: "Test User"},
name: "WelcomeMail"
},
to: ["email@email.com"]
}
}

My plugin configuration is as following:  Email document collection called "mail", Template collection called "handlebar", user collection called "users"

What happened? How can we make the problem occur?
This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.

##### Expected result
Successful delivery

##### Actual result
Getting the following error: TypeError: Cannot read property 'attachments' of undefined

**Comment by sanesanyo** [comment]
I just noticed one thing when I compare the logs of the two projects: in one where everything just runs, I do not see the following log:
ext-firestore-send-email-processQueuesock2ntwrfft checking missing template 'WelcomeMail'
ext-firestore-send-email-processQueuesock2ntwrfft template 'WelcomeMail' has been found

I am getting a sense that it has to be do with the template name. May be I need to use camel casing here? But then why does it work in other project (there I have an older version of the plugin 0.1.19)

**Comment by sanesanyo** [comment]
So I found the issue, it had to do with the naming of the template. Can you please at least mention this in your documentation?? No where I saw that the template name cannot start with a capital letter. Now when I use "welcomeMail" instead of "WelcomeMail", it works. Seriously, I did not have to waste so much of my time if you had this explicit in your documentation.

**Comment by cabljac** [comment]
Hi there, I don't think the casing is the issue, I attempted to reproduce this and `WelcomeTest` worked fine for me on `0.1.20`.

**Comment by sanesanyo** [comment]
@cabljac Like I said, when I compared the logs between the two projects I saw that strange difference which forced me to believe it had to do with the name (also I saw in a previous closed issue where _ in the name caused same bug) because why it cannot find it first but then it finds the template but in the other plugin it worked just fine?? And why did it started working just fine as soon as I used camel casing? How do you explain this?

**Comment by cabljac** [comment]
It could be something to do with the extension not loading the template until being reconfigured. I will try again to reproduce this bug.
