### ISSUE TITLE
(firestore-bigquery-export)  🔍 Generate views of exported Cloud Firestore data in BigQuery

### ISSUE THREAD

**Issue by jhuleatt** [firebase/extensions#139]
# Extension name

```
firestore-bigquery-export
```

# Feature

The[ _Export Collections to BigQuery_ extension](https://firebase.google.com/products/extensions/firestore-bigquery-export/) sends realtime, incremental updates from a specified Cloud Firestore collection to BigQuery. This raw changelog contains all the raw data needed to monitor a Cloud Firestore collection, but understanding the data requires more advanced BigQuery knowledge.

A new schema-views script, called `fs-bq-schema-views`, generates views on top of the raw changelog so that you can more easily see the current state of your data. When you run the script, you supply a schema file that specifies what fields you want to view and what types to apply to them.

# Usage

The schema-views script (`fs-bq-schema-views`) can be run at any time to generate a view of the raw changelog data in BigQuery. It is non destructive, so it does not modify the underlying data.  This script is [already published on npm](https://www.npmjs.com/package/@firebaseextensions/fs-bq-schema-views), but won't be officially supported until the full usage instructions are finalized.

This GitHub issue will be used to collect feedback and track the work of releasing the script and its documentation.

# PRs

- [x]  #161 document the schema-views script
- [x]  #138 allow custom descriptions to be specified for columns

**Comment by imikim** [comment]
The created view is empty for me.

I first ran `fs-bq-import-collection` which successfully imports and the `contracts_raw_latest` view also works.

After that, I ran `fs-bq-schema-views` which seems to have run successfully, creating the new views: `contracts_schema_contracts_latest` and `contracts_schema_contracts_changelog`.

However **both of these new views return no results** on query.

**Comment by karayu** [comment]
@russellwheatley do you mind taking a look?

**Comment by Salakar** [comment]
I believe this has now been implemented - both the linked PRs have since been merged & released - so will go ahead and close this, thanks!

@imikim please could you raise your issue separately via a new issue, though I think https://github.com/firebase/extensions/issues/298 has already been raised which relates to your issue.
