### ISSUE TITLE
🐛 [storage-image-resizes] resized images are corrupted sometimes

### ISSUE THREAD

**Issue by bhr** [firebase/extensions#1390]
### Describe your configuration

- Extension name: `storage-resize-images`
- Extension version: 0.1.32
- Configuration values (redact info where appropriate):
  - Cloud Functions location: europe-west1
  - Cloud Storage bucket for images: <project-id>.appspot.com
  - Sizes of resized images: 240x240,960x960,1920x1920
  - Deletion of original file: false
  - Make resized images public (Optional): false
  - Cloud Storage path for resized images (Optional): thumbs
  - Paths that contain images you want to resize (Optional): Parameter not set
  - List of absolute paths not included for resized images (Optional): <redacted>
  - Cache-Control header for resized images (Optional): Parameter not set
  - Convert image to preferred types: jpeg, webp, false
  - Output options for selected formats (Optional): Parameter not set
  - GIF and WEBP animated option (Optional):  true
  - Cloud Function memory: 1024
  - Backfill existing images: true

### Describe the problem

When new images are uploaded to the Firestore Storage container, some of the resized images are corrupted. The issue started happening a few months ago. Looking at the output, it happens for around 10% of resize operations.

There are errors in the logs (attached) that the file could not be found/deleted.

The image in question is at storage path `images/5Eg2idVngShf92rlBO7Juwcss1k2/posts/OAMCQJpgeCyrUMgc5heb/7d661743-5b17-4d03-9728-72760036b903.jpeg`

[downloaded-logs-20230105-185432.csv](https://github.com/firebase/extensions/files/10353710/downloaded-logs-20230105-185432.csv)

#### Steps to reproduce:

Upload an image to firestore storage

##### Expected result

- all images resized without corruption

##### Actual result

- image resized is corrupted ((modified) screenshots attached)
<img width="444" alt="Screenshot 2023-01-05 at 8 13 40 PM" src="https://user-images.githubusercontent.com/557660/210828064-09a74acd-f72a-4376-b375-ed08f5f57012.png">
<img width="632" alt="Screenshot 2023-01-05 at 8 15 02 PM" src="https://user-images.githubusercontent.com/557660/210828091-69074ab6-b4d8-4e11-91a2-bf57515ed865.png">

**Comment by cabljac** [comment]
Thanks, will look into this.

**Comment by cabljac** [comment]
I haven't been able to reproduce this so far at all, is it still happening?

**Comment by pr-Mais** [comment]
@bhr closing as stale, feel free to open a new issue if you this is still persisting for you.
