### ISSUE TITLE
Firebase Biq Query extension - Exceeded rate limits: too many api requests per user per method for this user_method

### ISSUE THREAD

**Issue by madmacc** [firebase/extensions#1394]
**Configuration**
firebase-admin: 9.12.0
firebase-functions: 3.24.1
firebase/firestore-bigquery-export@0.1.24

**Issue**
I have the firebase extension for streaming data to Big Query installed https://extensions.dev/extensions/firebase/firestore-bigquery-export.

Each month I run a job to import data into my Firestore collection in batches. This month I imported 2706 rows but only 2646 made it into Big Query (60 less).

I am getting the following errors from the extension: 
![fb_bq-ext-bug](https://user-images.githubusercontent.com/43654472/211384136-2e0c3f5f-cb77-4e5e-8a61-9dc4fe641d50.png)

Error: Exceeded rate limits: too many api requests per user per method for this user_method. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas
Error: Process exited with code 16 at process.
I contacted Firebase support and they suggested I upgrade to the latest firebase admin and function packages but these have breaking changes. Updating the latest version of firebase-admin gave me errors. I have not got any more help from them and it is still happening for multiple collections.

The options I see are:

1. Update to the latest firebase-admin and firebase-functions packages and change my code to work with the breaking changes. I think this is unlikely to help.
2. Update the firebase extension to the latest version from 0.1.24 to 0.1.29 which now includes a flag called "Use new query syntax for snapshots" which can be turned on. I can't find much information about this. I have now done this but will not find out until next month if it works as it is hard to replicate in dev.
3. Increase the Big Query quota somehow.
4. Slow down the data being entered into Firestore or add it daily/weekly rather than monthly.

If I look in the GCP logs using the query:
```
protoPayload.status.code ="7"
protoPayload.status.message: ("Quota exceeded" OR "limit")
```

![fb_bq-ext-bug-2](https://user-images.githubusercontent.com/43654472/211384068-c094ba0d-53a3-484d-8f23-389447215acf.png)

Here is my code in Nodejs:

```
 const platformFeesCollectionPath = `platformFees`;
  const limit = 500;
  let batch = db.batch();
  let totalFeeCount = 0;
  let counter = 0;

  for (const af of applicationFees) {
    const docRef = db.collection(platformFeesCollectionPath).doc();
    batch.set(docRef, { ...af, dateCreated: getTimestamp(), dateModified: getTimestamp() })

    counter++;
    if (counter === limit || counter === applicationFees.length) {
      await batch.commit();
      console.log(`Platform fees batch run for ${counter} platform fees`);
      batch = db.batch();
      totalFeeCount = totalFeeCount + counter;
      counter = 0;
    }
  }

  if (applicationFees.length > limit) {
    // Need this commit if there are multiple batches as the applicationFees.length does not work
    await batch.commit();
    totalFeeCount = totalFeeCount + counter;
  }
  
  if (counter > 0) {
    console.log(`Platform fees batch run for ${totalFeeCount} platform fees`);
  }
```

https://stackoverflow.com/questions/75044455/firebase-biq-query-extension-exceeded-rate-limits-too-many-api-requests-per-u

**Comment by madmacc** [comment]
I am still getting this issue after updating to the latest version of the Firebase Big Query extension.
This is a serious issue as now I can't be sure if my data is correct in Biq Query.

**Comment by cabljac** [comment]
Just to provide more information about the `new query syntax`, this was to address a different bug, in situations where the rows contained lots of data, and the query wasn't efficient enough (and failed due to memory issues)

**Comment by cabljac** [comment]
I can look into this, though it may be difficult to reproduce. Maybe you've looked already, but is there anything in your quotas `https://console.cloud.google.com/iam-admin/quotas` and check if there's anything which could be tripping up for you?

**Comment by madmacc** [comment]
At the moment I am updating my data in Firestore in batches of 500 documents. 
I guess this would potentially mean up to 500 updates per second which is over the quotas I have listed below.
I have changed my batch size to 10 which should be around 10 updates per second.
I will see how this goes and report back the results.

This does mean if I have to update 2000 rows it will take 200s instead of 4s though.
If the errors stop I will slowly increase the batch size.

**Error 1:**
Exceeded rate limits: too many api requests per user per method for this user_method
https://cloud.google.com/bigquery/quotas#api_request_quotas
Maximum number of API requests per second per user per method is 100 requests

![image](https://user-images.githubusercontent.com/43654472/217935383-eed83fcd-8f89-4b85-ab8f-d04cb46aa80f.png)

**Error 2:**
Exceeded rate limits: too many table update operations for this table

Based on the error it looks like the rate issue is with the "Maximum rate of table metadata update operations per table" quota here: https://cloud.google.com/bigquery/quotas#standard_tables
This is **5 operations per 10 seconds**
I'm not sure why the Firebase BQ extension is updating the table metadata as I would think it would just be updating the data e.g. the rows.

Even if I change my batch size to 1 that would still be around 1 update per second which is twice the limit (assuming it updates the metadata every row update). So hopefully this is not a metadata update every row update.

> Your project can make up to five table metadata update operations per 10 seconds per table. This limit applies to all table metadata update operations, performed by the following:
> Google Cloud console
> The bq command-line tool
> BigQuery client libraries
> The following API methods:
> [tables.insert](https://cloud.google.com/bigquery/docs/reference/v2/tables/insert)
> [tables.patch](https://cloud.google.com/bigquery/docs/reference/v2/tables/patch)
> [tables.update](https://cloud.google.com/bigquery/docs/reference/v2/tables/update)
> [DDL](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language) statements on tables
> This limit also includes the combined total of all load jobs, copy jobs, and query jobs that append to or overwrite a destination table. This limit doesn't apply to DML operations.
> If you exceed this limit, you get an error message like Exceeded rate limits: too many table update operations for this table. This error is transient; you can retry with an exponential backoff.
> 
> To identify the operations that count toward this limit, you can [Inspect your logs](https://cloud.google.com/bigquery/docs/reference/auditlogs#bigqueryauditmetadata_format).

**Comment by rmkol** [comment]
Hey @madmacc. Did you solve this problem? We are currently facing it too and it's not clear how to fix it.
We've updated our extension to the latest available version but it didn't help, we are still getting "**Exceeded rate limits: too many table update operations for this table.**" error, which is weird as I thought this extension switched to "streaming inserts" and thus "**5 operations per 10 seconds**" limitation should not be applied, as per https://cloud.google.com/bigquery/quotas#streaming_inserts.

**Comment by madmacc** [comment]
> Hey @madmacc. Did you solve this problem? We are currently facing it too and it's not clear how to fix it. We've updated our extension to the latest available version but it didn't help, we are still getting "**Exceeded rate limits: too many table update operations for this table.**" error, which is weird as I thought this extension switched to "streaming inserts" and thus "**5 operations per 10 seconds**" limitation should not be applied, as per https://cloud.google.com/bigquery/quotas#streaming_inserts.

No I did not manage to solve it and google have not been much help.
The firebase team just point to the BigQuery team and say it is not their problem.

I have managed to reduce it by reducing the batch size to 3 from 500 for my overnight updates.

**Comment by dackers86** [comment]
Hi All.

I am working on samples to recreate this issue, so far without any luck. Given the example scripts above, and updating to 50000 records - all records are synced without issue - even running multiple times:

```js
const admin = require("firebase-admin");
admin.initializeApp({ projectId });

const db = admin.firestore();

const getTimestamp = () => admin.firestore.Timestamp.now();

(async () => {
  const platformFeesCollectionPath = `28062023`;
  const limit = 500;
  let batch = db.batch();
  let totalFeeCount = 0;
  let counter = 0;

  const applicationFees = Array.from({ length: 50000 }, (_, i) => i).map(
    (i) => ({
      fee: i,
      name: `fee-${i}`,
      description: `fee-${i}`,
      amount: i,
      currency: "USD",
    })
  );

  for (const af of applicationFees) {
    const docRef = db.collection(platformFeesCollectionPath).doc();
    batch.set(docRef, {
      ...af,
      dateCreated: getTimestamp(),
      dateModified: getTimestamp(),
    });

    counter++;
    if (counter === limit || counter === applicationFees.length) {
      await batch.commit();
      console.log(`Platform fees batch run for ${counter} platform fees`);
      batch = db.batch();
      totalFeeCount = totalFeeCount + counter;
      counter = 0;
    }
  }

  if (applicationFees.length > limit) {
    // Need this commit if there are multiple batches as the applicationFees.length does not work
    await batch.commit();
    totalFeeCount = totalFeeCount + counter;
  }

  if (counter > 0) {
    console.log(`Platform fees batch run for ${totalFeeCount} platform fees`);
  }
})();
``` 

![image](https://github.com/firebase/extensions/assets/2060661/4d8866d5-6996-4a22-91f2-17b6c827552d)

**Comment by dackers86** [comment]
Previous issues with this type of error are based on metadata table updates. The above examples showing `patch updates`, seem to also add to this as the potential issue.

Would it be possible for any developers to  provide the configuration of their extensions. I would be able to better create the conditions of the updates, namely:

- table_partitioning
- time_partitioning_field_type
- use_new_snapshot_query_syntax
- wildcard_ids

**Comment by rmkol** [comment]
@dackers86 we are using the latest extension version - 0.1.32, and it was installed with the following configuration:

- TABLE_PARTITIONING - NONE
- TIME_PARTITIONING_FIELD_TYPE - omit
- USE_NEW_SNAPSHOT_QUERY_SYNTAX - no
- WILDCARD_IDS - false
- cloud function min instances - 0
- cloud function max instances - 3000

We never tweaked it manually, aside from lowering "cloud function max instances" to see if it improves the situation, but it didn't.

It's important to note that we are not doing batch inserts on our side to the related Firestore collection. Instead, we do singular insertions with ~3 TPS. And even with such a low TPS we are seeing these exceptions every now and then:
<img width="1461" alt="image" src="https://github.com/firebase/extensions/assets/5159296/57329010-f2d0-46f7-9449-b258362f7aa2">

Again, what strikes our eyes is that we are getting "Exceeded rate limits: too many table update operations for this table." error, which technically should not happen if the extension is using streaming inserts, as per https://cloud.google.com/bigquery/quotas#streaming_inserts (if my understanding is correct).

**Comment by dackers86** [comment]
A new update has been released this week to fix the above issues, detailed can found here https://github.com/firebase/extensions/pull/1616.

To summarise:

Lifecycle events now exist which means we no longer need to run the table/view initialisation on every sync.

Additionally, an Cloud Task functions has now been included to provide configurable throttling of tasks ensuring that too many sync requests do not overload the BQ APi.

Please upgrade to `v0.1.33` to access this new update.

**Comment by rmkol** [comment]
Thanks @dackers86. This update helped a lot. Seeing much less errors from BQ now, and even when we do get some, it's still fine because the extension is now integrated with Cloud Tasks, meaning the records don't get lost on failure anymore. It's funny, we were about to start implementing our own solution with Pub/Sub, to fix these issue and to ensure 100% eventual data consistency, and then you pushed this update, which already covers it both :)

**Comment by madmacc** [comment]
Yes thanks @dackers86 and your team for getting this fix sorted. 
Really appreciate the work and great to know we are being listened too!

Onwards and upwards for Firebase extensions 🚀

**Comment by madmacc** [comment]
@dackers86 I have noticed that I have started getting these errors again. It may be that my volume has increased.
I am running v0.1.33

```
bigquery.googleapis.com
…bigquery.v2.TableService.PatchTable
…prod_export/tables/members_raw_changelog
ext-bq-export-members@hiv…
Exceeded rate limits: too many table update operations for this table. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas
```
![image](https://github.com/firebase/extensions/assets/43654472/f87a0800-f599-4583-9bcb-308b7f393896)

**Comment by dackers86** [comment]
Hi @madmacc 

Hmmm this is strange, the latest updates are intended to run table updates when the extension installs or reconfigures. 

These errors should no longer be happening per sync request. Let me check the release notes to check when fix was added. Is there are reason, why you have remained on version `v0.1.33`?

**Comment by madmacc** [comment]
@dackers86 My apologies. It turns out I was using v0.1.30. I was testing the updated version on other collections before upgrading my largest collection.

I have now upgraded to the latest version and will keep an eye on it.
Thanks for the quick response.

**Comment by madmacc** [comment]
> @dackers86 My apologies. It turns out I was using v0.1.30. I was testing the updated version on other collections before upgrading my largest collection.
> 
> I have now upgraded to the latest version and will keep an eye on it. Thanks for the quick response.

This appears to be working fine now I have updated.
I have increased the batch size and will report back in a couple of weeks.
