### ISSUE TITLE
[firestore-send-email] missing custom event channel locations

### ISSUE THREAD

**Issue by ottob** [firebase/extensions#1408]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: `firestore-send-email`
But might apply to https://github.com/firebase/extensions/pull/1303 too.

### What feature would you like to see?

Additional channel locations for custom events.

Right now I can only see 4 options:
<img width="639" alt="Screenshot 2023-01-13 at 10 27 14" src="https://user-images.githubusercontent.com/67104/212286961-d732d68a-1798-4081-a3b7-b143886561c2.png">
But https://cloud.google.com/eventarc/docs/locations lists more locations, specifically `europe-west3` that I wanted to use.

I tried to search in this repo if it was a simple list to update and submit a PR, but I could not find anything.

### How would you use it?

Have the event channel in the same location as my functions and firestore.

**Comment by ottob** [comment]
Thanks for adding these lifetime events @yamankatby 
Perhaps you know why there only are four locations?

I also have a second question regarding this functionality.
I wanted to use these events to solve https://github.com/firebase/extensions/issues/1072
My idea was: on a mail success event I would write an `expireAt` timestamp field in the mail document that was processed.
But this would cause the firestore-send-email extension function to run again and send the success event again.
When my function run for the second time I can check if the `expireAt` field exists and abort and not trigger an infinite loop.

But it would be nice if there was a way to updated the mail document and not trigger the `processWrite` function that sends the event again. Maybe by adding a skipProcessing field? Or is there another way that I'm missing?

**Comment by cabljac** [comment]
Hi, thanks for raising this! I will have a look into it. In the meantime I have opened a PR to support a TTL field [here](https://github.com/firebase/extensions/pull/1410). Hopefully we can get it in the next release :)

**Comment by ottob** [comment]
Excellent and thanks for creating that PR! Looking forward to being able to use it in the future.

I noticed that you added TTL options for hour, day, week, month and year. We wanted to expire documents after 3months. I guess that would not be possible then? 
How about if the user could input the TTL in number of hours?
I understand that this might be harder to use (launching calc.exe :)) but it would also be more flexible. What do you think?

**Comment by cabljac** [comment]
good point, perhaps number of hours is nicer. With nicer options for parameter inputs we could have something easier to use, but flexibility seems more important here. I'll look into that

**Comment by dackers86** [comment]
Although the eventArc locations cannot be set within an extension. It looks like this could be managed at least asking for locations in the firebase tools [project](https://github.com/firebase/firebase-tools/blob/ee1da271a98fcaa2207ff0b0bd750853383ee021/src/extensions/askUserForEventsConfig.ts#L100).

I've pinged for feedback to see if this anything we can help with.

**Comment by BenJackGill** [comment]
Any update on this? Our project is setup in `australia-southeast1` and so I need to choose that same location for the channel, but right now that is not possible.

**Comment by pr-Mais** [comment]
Some updates here: this list of locations is limited to these 4 regions only as mentioned [here in the EventArc docs](https://cloud.google.com/eventarc/docs/third-parties/create-channels#create-channel), closing since it's not related to extensions.
