### ISSUE TITLE
Trigger Email - SendGrid Dynamic Templates

### ISSUE THREAD

**Issue by solutionpark** [firebase/extensions#1409]
Trigger Email: Is there a way to trigger the Dynamic Templates on SendGrid? I don't like creating a Firebase Template Collection Admin Tool because this functionality is already on SendGrid. (HTML Edit)

**Comment by cabljac** [comment]
There isn't currently support for this unfortunately. As it's fairly custom, I've added the `pending-interest` label and if this garners a lot of interest we can consider adding it as a feature :)

**Comment by solutionpark** [comment]
@cabljac , that's still great news. Thanks. It should not much trouble to dispatch the 2 parameters. In the meantime, I write my own cloud function for SendGrid. But I like to switch back to a Firebase-supported Extension. Saves the time we will spend more on next User Features ;)

**Comment by dunethomas** [comment]
Yes, please add this. I'd rather not find my custom solution out of sync with firebase changes.

**Comment by StevenSnary** [comment]
I'd like this feature added as well - thanks!
