### ISSUE TITLE
The Delivery State is showing "SUCCESS" but actual emails are not coming

### ISSUE THREAD

**Issue by Fiviza** [firebase/extensions#1417]
We are trying to use the Firebase Tigger Email extension. Upon creating a new record in the emails collection, the delivery state is showing as 'SUCCESS' but actual emails are not coming through. Please see attached screenshot. Please help.
![Screenshot](https://user-images.githubusercontent.com/112520219/214188739-1b129945-321b-4b13-8000-7c1ade76b9b0.jpg)

**Comment by dackers86** [comment]
Hi @Fiviza 

Your email response code of `250` suggests that the email has been successfully sent. 

Could you ensure that this has not ended up in a `junk mail` folder, or or if the `to` address is the correct email address?

**Comment by Fiviza** [comment]
Hi,

I verified that the emails are not ending up in junk mail and the addresses
are also correct.

I tried sending email to various gmail, hotmail, non-gmail and non-hotmail
email addresses. So far I found it working for only one email and that is
***@***.***

Following are the logs from bluehost email servers. The red entries were
not delivered and the green entry worked. In all cases I got the 250 OK
response.

2023-01-24 16:52:20 1pKT5Q-004H6N-0R <= ***@***.*** H=
63.238.178.107.gae.googleusercontent.com ([127.0.0.1])
[107.178.238.63]:21993 I=[50.87.248.47]:587 P=esmtpsa
X=TLS1.2:ECDHE-RSA-AES256-GCM-SHA384:256 CV=no A=
***@***.*** S=624 id=
***@***.*** T="This is from
firebase" from ***@***.***> for ***@***.***

2023-01-24 17:07:16 1pKTJs-0007YO-IY <= ***@***.*** H=
63.238.178.107.gae.googleusercontent.com ([127.0.0.1])
[107.178.238.63]:21625 I=[50.87.248.47]:587 P=esmtpsa
X=TLS1.2:ECDHE-RSA-AES256-GCM-SHA384:256 CV=no A=
***@***.*** S=630 id=
***@***.*** T="Hello from Firebase"
from ***@***.***> for ***@***.***

2023-01-24 17:12:49 1pKTPF-000ClJ-7o <= ***@***.*** H=
63.238.178.107.gae.googleusercontent.com ([127.0.0.1])
[107.178.238.63]:50691 I=[50.87.248.47]:587 P=esmtpsa
X=TLS1.2:ECDHE-RSA-AES256-GCM-SHA384:256 CV=no A=
***@***.*** S=636 id=
***@***.*** T="Hello from Firebase"
from ***@***.***> for ***@***.***

As per bluehost support, the issue is on the Firebase side.

Note: All to and from mails are working for the email address
***@***.*** while using it from outlook or webmail.

Regards
Vijay

**Comment by Fiviza** [comment]
This issue can be closed. We are now using Sendgrid to route the email message and it is working fine.
