### ISSUE TITLE
firestore-send-email: Warn message "message 'undefined' is not a valid object - please add as an object or firestore map, otherwise you may experience unexpected results." logged when using handlebar templates

### ISSUE THREAD

**Issue by sceee** [firebase/extensions#1418]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-send-email**
- Extension version: **0.1.20**
- Configuration values (redact info where appropriate):

### [REQUIRED] Step 3: Describe the problem

When using the trigger email extension with handlebar templates (and no explicit `message` field), the following warning message is logged each time an email is scheduled:
```
message 'undefined' is not a valid object - please add as an object or firestore map, otherwise you may experience unexpected results.
```

#### Steps to reproduce:

Schedule emails by adding an email as follows to the outbound queue:
```
await firestore()
  .collection("mail")
  .add({
    to: ["someone@example.com"],
    template: {
      name: "templatename",
      data: {
        some: "Data",
      },
    },
  });
```

Check the Logs of the `ext-firestore-send-email-processQueue` Cloud function. They emit the following warning message each time an email is sent:
```
message 'undefined' is not a valid object - please add as an object or firestore map, otherwise you may experience unexpected results.
```

This does not make sense as the message field is not required to be there when using handlebar templates.

##### Expected result

No warning is logged that the message field is undefined when using the trigger email extension with handlebar templates.

##### Actual result
See above.

**Comment by dackers86** [comment]
HI @sceee 

Would it be possible to share the template `firestore document` you are using for this example?

**Comment by sceee** [comment]
Hi @dackers86 ,

the used templates are all structured like this:
```
{
html: "<div>...</div>"
subject: "Some subject"
text: "Some text"
}
```

These are individual fields in the firestore document. Emails are also sent correctly, it's just the annoying warning in the logs.

**Comment by cabljac** [comment]
just reproduced this. I'll need to look into when exactly we need the message field (e.g whether we can have templates but still need a message) and then implement a fix for the next release. Thanks!

**Comment by gitdast** [comment]
The same issue ...log full of this. Luckily - emails were sent.

**Comment by dmvvilela** [comment]
Same thing here. E-mails not being sent. Good thing is that I did not upgrade it on prod, only on dev project. Is there a way to downgrade a firebase extension??

**Comment by sceee** [comment]
@dmvvilela in your case it then seems to be something different, probably you need to open another issue for your problem.
This particular issue was "just" about the false warning when using handlebar templates, emails are still being sent as written above.

**Comment by dmvvilela** [comment]
Hmm, weird thing is as I updated I tested and it was working fine. Then now nothing happens on email document and show that warning on console..
Did you change those time to live new config in some regard?

**Comment by gitdast** [comment]
I'm with version 0.1.19 (different, that @sceee ), but the same result - warning + emails are sent with success.

**Comment by dmvvilela** [comment]
That version works, @sceee version also works.. 1.22 stopped sending for me. I sent Firebase a request already.

**Comment by fitimvata** [comment]
@cabljac i have the same issue after upgrade to version 0.1.22. 

```javascript
 admin
    .firestore()
    .collection("mails")
    .add({
      to: values.email,
      template: {
        data: {
            phoneNumber: '012345',
        },
        name: "test-template",
      },
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
    }),
```
The bug was introduced  in this commit https://github.com/firebase/extensions/commit/f4bfb28d74208e2cc6c82fb63b655b76ad7ff9d1 i think.

<img width="1627" alt="Screenshot 2023-02-13 at 12 10 25 PM" src="https://user-images.githubusercontent.com/12052390/218442649-df8bda42-0595-49b5-9204-e1f0dbf93070.png">

When new email is created using template property, delivery is not send because message property is not defined.

**Comment by rogiervandenberg** [comment]
Same here, version 0.1.22 does not send emails with a template.

**Comment by Mendistern** [comment]
Have the same problem, everything worked fine till the .22 version update. now no emails are being sent. unless I'm manually adding the document without a template (hence, the problem isn't in the configuration).

**Comment by dackers86** [comment]
@dmvvilela A new release has been added, please update to the latest version.
