### ISSUE TITLE
unwanted deployed backfill cloud function

### ISSUE THREAD

**Issue by vr** [firebase/extensions#1420]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** storage-resize-images
- Extension version: **\_** 0.1.33
- Configuration values (redact info where appropriate):
  - **\_** DO_BACKFILL=false
  - **\_**

### [REQUIRED] Step 3: Describe the problem
I expect the cloud function that is specific for the backfill usage to *not* be deployed if `DO_BACKFILL` is `false` and currently it is.

#### Steps to reproduce:
- set DO_BACKFILL=false
- deploy
- look at deployed cloud functions

##### Expected result
to not have the backfill cloud function

##### Actual result
having the backfill cloud function

**Comment by vr** [comment]
i don't get why this cloud fucntion is needed if i don't need the backfill feature ?

**Comment by dackers86** [comment]
As all functions are installed as part of the Firebase Extension installation, there currently no way to specify which functions to include based on the Installation.

You could potentially remove this function manually. Although, I wouldn't normally recommend removing functions in case they cause issues with the installed extension.
