### ISSUE TITLE
Firebase does not install/uninstall extensions. AUTH_PERMISSION_DENIED error

### ISSUE THREAD

**Issue by yaroslav-ishanov** [firebase/extensions#1445]
- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: `algolia/firestore-algolia-search`
- Extension version: **0.5.14**
- Configuration values (redact info where appropriate):
 (not relevant since the error comes from GCP resource deployment problems) 

### [REQUIRED] Step 3: Describe the problem

Firebase does not allow to install/uninstall extensions. Both web view and the CLI do not work. When trying to install an extension following errors are outputted:

```
{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"AUTH_PERMISSION_DENIED","domain":"serviceusage.googleapis.com","metadata":{"service":"serviceusage.googleapis.com","permission":"serviceusage.services.enable","resource":"redacted"}}],"statusMessage":"Forbidden","requestPath":"https://serviceusage.googleapis.com/v1/projects/redacted/services/artifactregistry.googleapis.com:enable","httpMethod":"POST"}}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-algolia-search-123/resources/mods-api-enable-iam: {"ResourceType":"deploymentmanager.v2.virtual.enableService","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission denied to enable service [iam.googleapis.com]\nHelp Token: AVUsNs0kKLZRW52Ot6RZuDsrcRQ7Cv06wM5zW0WK6qcOMNN6M2zPOpgJ2GmymEBtoBXCFNhtdFAiFvcO1klpBnyDZj8A9iMpALCUmVyMabcZbxZ8","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.PreconditionFailure","violations":[{"type":"googleapis.com","subject":"?error_code=110002&service=serviceusage.googleapis.com&permission=serviceusage.services.enable&resource=redacted"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"AUTH_PERMISSION_DENIED","domain":"serviceusage.googleapis.com","metadata":{"service":"serviceusage.googleapis.com","permission":"serviceusage.services.enable","resource":"redacted"}}],"statusMessage":"Forbidden","requestPath":"https://serviceusage.googleapis.com/v1/projects/redacted/services/iam.googleapis.com:enable","httpMethod":"POST"}}
```

The GCP project has all those services already enabled

#### Steps to reproduce:

1. Create a google cloud user with Owner permissions
2. Create a new firebase project3. 
3. Install algolia extension4. 
4. Configure the extension and click install5. 5. 

The installation should fail with the PERMISSION_DENIED error 'some resources may not have been deployed'

**Comment by yaroslav-ishanov** [comment]
<img width="969" alt="Screenshot 2023-02-06 at 17 06 34" src="https://user-images.githubusercontent.com/106477927/217008204-b9f4f106-888f-41a2-b35a-84e913a645c5.png">
Here's what the web view shows

**Comment by cabljac** [comment]
Hi there, this is probably better to be raised in the algolia repo [here](https://github.com/algolia/firestore-algolia-search)

I can look into trying to reproduce this and investigate though.

**Comment by huangjeff5** [comment]
Hey! I took a look, this seems to be a service account permissions issue with your project.

Could you go into Google Cloud Console, click on the left sidebar, navigate to "IAM and Admin", and look for a service account with the pattern PROJECT_NUMBER@cloudservices.gserviceaccount.com? (Replacing project number with your own project number). 

You need to add the Editor role to that service account, and then try installing/uninstalling again.

**Comment by dackers86** [comment]
This appears to be platform related, a solution has been provided.

Happy to re-open should we get anymore information/feedback.
