### ISSUE TITLE
[firestore-bigquery-export] BigQuery Export extension stores way too much information about reference fields

### ISSUE THREAD

**Issue by samatcolumn** [firebase/extensions#1453]
### [READ] Step 1: Are you in the right place?

Yes I am

### [REQUIRED] Step 2: Describe your configuration

- Extension name: firestore-bigquery-export
- Extension version: 0.1.25
- Configuration values (redact info where appropriate): Not applicable

#### Steps to reproduce:

Just add a document to Firestore with a reference type:
```js
db.collection('foo').add({
  field: db.collection('bar').doc('abc')
});
```

##### Expected result

I think the information in BigQuery should closely correspond to what is stored in Firestore. If we look at [the documentation](https://firebase.google.com/docs/firestore/storage-size#field-size) we can see that a reference field is stored as just a string with 16 extra bytes of information.

In BigQuery I'd expect a simple object like: `{ _ref: path }` which lets me know that it is a reference and gives me the full path, but nothing else.

This current format makes things very hard to analyze and also means that the size in BIgQuery is much much larger than the size in Firestore.

##### Actual result

The reference is stored stringified with a lot of junk:
```json
{
   "field":{
      "_firestore":{
         "_settings":{
            "projectId":"REDACTED",
            "firebaseVersion":"8.8.0",
            "libName":"gccl",
            "libVersion":"2.6.0 fire/8.8.0"
         },
         "_settingsFrozen":false,
         "_serializer":{
            "timestampsInSnapshots":true
         },
         "_projectId":"REDACTED",
         "_lastSuccessfulRequest":0,
         "_preferTransactions":true,
         "_clientPool":{
            "concurrentOperationLimit":100,
            "activeClients":{
               
            }
         }
      },
      "_path":{
         "segments":[
            "bar",
            "abc"
         ]
      }
   }
}
```

**Comment by samatcolumn** [comment]
@cabljac we updated from 0.1.25 to 0.1.31 and it seems like this has changed but the change was not documented anywhere?

**Comment by cabljac** [comment]
@samatcolumn  hm strange, i will look into this. Thanks for bringing to my attention! 

So the issue currently seems to be fixed? Perhaps this was a side-effect of some other change
