### ISSUE TITLE
Unable to update schema views using npx command

### ISSUE THREAD

**Issue by ebingeorgedct** [firebase/extensions#1454]
### [READ] Step 1: Are you in the right place?
Yes, I am

### [REQUIRED] Step 2: Describe your configuration

- Extension name: firestore-bigquery-export
- Extension version: 0.1.30
- Configuration values (redact info where appropriate):
1. Cloud Functions location :europe-west1
2.BigQuery Dataset location : europe-west1
3.Project Id : vega-stage-ff934
4.Collection path : sessions
5.Dataset ID: vega_ai
6.Table ID:sessions

#### Steps to reproduce:

I am unable to update the schema views for any of my extensions. I am trying to remove a field that i had added earlier using the below command.(Reference Link: https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md)

I am using the following command
npx @firebaseextensions/fs-bq-schema-views --non-interactive --project=vega-stage-ff934 --dataset=vega_ai --table-name-prefix=sessions --schema-files=./sessions.json

##### Expected result
It should update the schema successfully

##### Actual result
I get the following error
{"code":"app/duplicate-app","message":"The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initializeApp() once. But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name."}
The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initializeApp() once. But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name.

This used to work before. I think the last time i tried was before 2 weeks.

**Comment by tgpsantos** [comment]
I'm having a similar error when importing all the data from a collection. I haven't used this extension in a while and decided to give it a try an hour ago 

The error I'm getting is 
`Error importing Collection to BigQuery: Error: The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initializeApp() once. But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name.`

And here's a print with the settings
![imagem](https://user-images.githubusercontent.com/48353485/218182643-0c24a98b-9467-470b-9cb5-c64cb82200ed.png)

**Comment by jodik** [comment]
Runnin older version solves the issue for the time being:
npx @firebaseextensions/fs-bq-schema-views@0.4.4 --non-interactive ...

**Comment by cabljac** [comment]
should be fixed now, ping if this still occurs on the latest published version of the script :)

**Comment by tgpsantos** [comment]
I pulled the _next_ branch a couple hours ago (I noticed the fix was merged in to the branch) and run the import script directly. Looks like it worked, thanks!
