### ISSUE TITLE
[firestore-send-email] unable to send email with template. no email send or delivery status

### ISSUE THREAD

**Issue by cingh-jasdeep** [firebase/extensions#1466]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name:firestore-send-email
- Extension version: 0.1.22
- Configuration values (redact info where appropriate):
![console firebase google com_project_digisign-touch-suggestion-box_extensions_instances_firestore-send-email_tab=config](https://user-images.githubusercontent.com/5167015/218971868-3e9d8628-754c-49a3-9e37-4802f5368de8.png)

### [REQUIRED] Step 3: Describe the problem
unable to send email with template. no email send or delivery status

#### Steps to reproduce:

What happened? How can we make the problem occur?
setup data as follows
![Screenshot 2023-02-15 at 1 52 16 PM](https://user-images.githubusercontent.com/5167015/218972617-0874282e-a80c-4e5d-a2a2-797fd0b98b1d.png)
![Screenshot 2023-02-15 at 1 53 18 PM](https://user-images.githubusercontent.com/5167015/218972627-0ce424b5-7bf5-44af-9dfa-92270444f18c.png)
![Screenshot 2023-02-15 at 1 52 57 PM](https://user-images.githubusercontent.com/5167015/218972633-29019f88-810d-47f4-921f-1045e6b4ff2f.png)

##### Expected result
Email should be sent after the document is added to firestore.

##### Actual result
No email was sent and no delivery status.

Note:
There are log entries, so cloud function execution is there but no delivery status.
![Screenshot 2023-02-15 at 1 56 07 PM](https://user-images.githubusercontent.com/5167015/218973067-b2f97aae-0c0e-496e-875a-9283adfc26d6.png)

**Comment by cabljac** [comment]
potentially a duplicate of https://github.com/firebase/extensions/issues/1418

**Comment by gabrielgallardoe** [comment]
I have the same problem with 0.1.22 version: no delivery document appear on the firestore document and email not send.
Notice that I use this extension on two projects, one with 0.1.21 version works perfectly.

**Comment by gabrielgallardoe** [comment]
The 0.1.23 versión fix my problem.
https://github.com/firebase/extensions/issues/1418#issuecomment-1431907896

**Comment by cingh-jasdeep** [comment]
i see delivery status now, but message is not delivered to gmail addresses!
I see a "Be careful with this message warning"

**Comment by dackers86** [comment]
Hi @cingh-jasdeep 

Is that an error in the logs or the resulting document? 

No message like that exists in the code extension codebase?

**Comment by cingh-jasdeep** [comment]
![Screenshot 2023-02-16 at 3 02 00 PM](https://user-images.githubusercontent.com/5167015/219325443-51a6a851-37e7-4354-8932-3f75601da801.png)

**Comment by dackers86** [comment]
Thanks the screenshot, this looks to be internal gmail warning and a separate issue?

Is the extension work as expected overall for you? Maybe a new could add documentation on advising for Gmail messages like this?

**Comment by cingh-jasdeep** [comment]
yes! you are right.
As is see, this is probably related to my SMTP server.
closing this issue as resolved.
