### ISSUE TITLE
[firestore-bigquery-export] Error importing Collection to BigQuery: Error: Value for argument "limit" is not a valid integer.

### ISSUE THREAD

**Issue by RianHoorelbeke** [firebase/extensions#1470]
When I introduce the following values, I get an error message:

? What is your Firebase project ID? ****
? What is the path of the the Cloud Firestore Collection you would like to import from? (This may, or may not, be the same Collection for which you plan to mirror changes.) dim_stock
? Would you like to import documents via a Collection Group query? No
? What is the ID of the BigQuery dataset that you would like to use? (A dataset will be created if it doesn't already exist) firestore_dim_stock
? What is the identifying prefix of the BigQuery table that you would like to import to? (A table will be created if one doesn't already exist) dim_stock
? How many documents should the import stream into BigQuery at once? 300
? Where would you like the BigQuery dataset to be located? southamerica-east1
? Would you like to run the import across multiple threads? No
? Would you like to use the new optimized snapshot query script? No
? Would you like to use a local firestore emulator? No

Importing data from Cloud Firestore Collection: dim_stock, to BigQuery Dataset: firestore_dim_stock, Table: dim_stock_raw_changelog
Error importing Collection to BigQuery: Error: Value for argument "limit" is not a valid integer.

Any idea what is causing this?

**Comment by shunnagahara** [comment]
@RianHoorelbeke 

I met same problem

and when I tried to do again as non-interactive mode, It worked well

like this

```
npx @firebaseextensions/fs-bq-import-collection \
  --non-interactive \
  --project=******* \
  --source-collection-path=stores \
  --query-collection-group=false \
  --dataset=firestore_export \
  --table-name-prefix=stores \
  --batch-size=300 \
  --dataset-location=asia-northeast1 \
  --multi-threaded=.false \
  --use-new-snapshot-query-syntax=.false \
  --use-emulator=.false
```

I don't know why it worked well though,,,

**Comment by cabljac** [comment]
Same error message as raised here https://github.com/firebase/extensions/issues/911 , possibly related

**Comment by cabljac** [comment]
It seems like this is an error thrown in the `query.limit` method here https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/scripts/import/src/index.ts#L187

though i haven't been able to reproduce yet

**Comment by cabljac** [comment]
Are you getting any relevant logs in gcp you can share?

**Comment by piotr-plenti** [comment]
same story :(

**Comment by cabljac** [comment]
@piotr-plenti  does this happen in interactive mode, or non-interactive mode?

**Comment by titanium-cranium** [comment]
I had exactly the same issue as described above.  The first time I attempted this in the terminal in interactive mode it seemed to go fine, then threw an error saying that it couldn't parse the JSON because it was too large (error 413).  

When I tried running this again in interactive mode, I decreased batch size to 1 but the script never started and instead return the same error @RianHoorelbeke described above. 

> Error importing Collection to BigQuery: Error: Value for argument "limit" is not a valid integer. 


Multiple configurations in interactive mode all failed.

When I started the script in non-interactive mode, using batch size of 1, the script ran fine.

Best guess, when the script crashes there's some leftover config somewhere that is required in the interactive mode but ignored when non-interactive?

**Comment by locatejp** [comment]
I ran basically the same query twice in the attached image (sensitive data blurred out) and you can see that it worked for non-interactive mode as others have stated.  I changed every setting that I could think of in interactive mode none were successful to get it to work.  That means that anyone that follows the tutorial and doesn’t choose interactive mode will get stuck indefinitely.  As such, this seems like a high priority.  

As a current workaround, the non-interactive code mentioned by @shunnagahara worked for me.  I’m going to paste it below again for convenience.  I hope this post is helpful.

```
![Screenshot (23)](https://github.com/firebase/extensions/assets/6493376/dba3f046-e26a-4b05-8d33-db96c0be1b3d)
```
