### ISSUE TITLE
Can't Delete Directory of Files

### ISSUE THREAD

**Issue by ccjernigan** [firebase/extensions#148]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: delete-user-data

### What feature would you like to see?

What I currently see is that deleting files from Google Cloud Storage requires an explicit path for a single file.  This works if all users have filenames that follow the exact same naming rules.  E.g. {DEFAULT}/{UID}-pic.png

What I want to see is the ability to delete everything under a particular path.  E.g. {DEFAULT}/{UID}/*

### How would you use it?

I store user files under a path like:
{DEFAULT}/{UID}/

Under that path, there are an arbitrary number of files with randomly generated UUIDs.  When the user delete's their account, I'd like to be able to purge all of these files automatically.  With the current version of the extension, I am not able to delete these files because I don't know their names ahead of time.

**Comment by Ehesp** [comment]
I *think* this should be possible... There isn't a way to directly delete a directory in Firebase/Google storage, however it looks as though `deleteFiles` accepts a `prefix` parameter.

I'll give this a go and see if it works with a directory & file.
