### ISSUE TITLE
Big Query Export Schema Error

### ISSUE THREAD

**Issue by Mindcooler** [firebase/extensions#1480]
### Discussed in https://github.com/firebase/extensions/discussions/1479

<div type='discussions-op-text'>

<sup>Originally posted by **Mindcooler** March  1, 2023</sup>
Hi,

I am trying to apply schemas to raw data using this fs-bq-schema-views script ( following this guide https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md)

However, I am getting this error:
{"code":"app/duplicate-app","message":"The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initializeApp() once. But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name."}
The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initializeApp() once. But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name.

Any help appreciated!
</div>

**Comment by cabljac** [comment]
Hmm this shouldn't be happening really, perhaps it's hitting an old version somehow - can you try adding `@latest` and see if the problem persists?

```
npx @firebaseextensions/fs-bq-schema-views@latest \
  --non-interactive \
  --project=${param:PROJECT_ID} \
  --dataset=${param:DATASET_ID} \
  --table-name-prefix=${param:TABLE_ID} \
  --schema-files=./test_schema.json
  ```

**Comment by Mindcooler** [comment]
@cabljac Many thanks. I got it working by adding @latest,. Although it works correctly only on interactive mode, but that is sufficient for me.
