### ISSUE TITLE
problem with JFIF type:  the size is appended after the .extension 

### ISSUE THREAD

**Issue by ammar-aboukhriba** [firebase/extensions#1482]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: `storage-resize-images` 
- Extension version: 0.1.34
- Configuration values (redact info where appropriate):
  - Sizes of resized images: 200x200,400x400,800x800
  - Convert image to preferred types: false
  

### [REQUIRED] Step 3: Describe the problem
when uploading images with type JFIF, the size is appended after the .extension not before.
It works fine with other image types. 

##### Expected result
fileName_200x200.jfif
fileName_400x400.jfif
fileName_800x800.jfif

##### Actual result
fileName.jfif_200x200
fileName.jfif_400x400
fileName.jfif_800x800

**Comment by dackers86** [comment]
Hi @ammar-aboukhriba 

`JFIF` types are not supported in this extension. The extension uses the following dependency to resize the images, this library does not contain a output option for that type.

Do you require this file type for a specific use case?

**Comment by ammar-aboukhriba** [comment]
We don't have a specific use case for this type but one of the clients uploaded some images and it causes error while creating the URLs because we expected the usual format. 
It would be good to at least fix the appending of the size to the file name rather than the actual resizing.

**Comment by cabljac** [comment]
Reproduced this. Only happens in production (on the emulator it doesn't try to resize, but we should make sure we log)

**Comment by cabljac** [comment]
Ah the issue here is that storage records the content type as a jpeg for some reason. Interesting


![Uploading Screenshot 2023-03-03 at 10.59.38.png…]()

**Comment by cabljac** [comment]
Investigating further, I think jfif is supported (uses same compression as jpeg). I will open a PR fixing this.

**Comment by cabljac** [comment]
Related: https://github.com/firebase/firebase-admin-node/issues/2095
