### ISSUE TITLE
 Stream Collections to BigQuery , race condition

### ISSUE THREAD

**Issue by liberathor** [firebase/extensions#1493]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: `Stream Collections to BigQuery`
- Extension version: 0.1.30
- Configuration values:
extensions was installed from terminal like: 
`firebase ext:install firestore-bigquery-export --params=/Users/technology/WebstormProjects/wokky-api/cli/bigquery/active_extensions/appUsersData_acceptedMissions_items.env --project=workky-datexco --force --non-interactive `

appUsersData_acceptedMissions_items.env: 
`LOCATION=us-central1
DATASET_LOCATION=us
COLLECTION_PATH=appUsersData/{userid}/acceptedMissions/{missionId}/items
COLLECTION_GROUP_QUERY=true
DATASET_ID=MasterDB
TABLE_ID=appUsersData_acceptedMissions_items
WILDCARD_IDS=false
TIME_PARTITIONING_FIELD_TYPE=omit
TABLE_PARTITIONING=NONE`

### [REQUIRED] Step 3: Describe the problem

When I do multiple db operations (create or update or delete, etc) a same firestore subcollection document in less than a second a race condition generated. And only the first operation firestore is registered in bigquery database.

##### Expected result

register all operations in subcollection or at least the las operation in firestore subcollection/collection recorded in bigquery.

##### Actual result

the subcollection is not synced correctly in biquery when multiples firestore db operations are triggered at the same time or less than a second.

**Comment by cabljac** [comment]
Thanks, i've added this to our project board for investigation

**Comment by cabljac** [comment]
Looking into this at the moment, haven't been able to reproduce it just yet -

I'm confused as you've specified `COLLECTION_GROUP_QUERY` which is currently not a parameter of the extension

It is a parameter of the import script (these *should* match really, i will make sure they do after https://github.com/firebase/extensions/pull/1464/ is merged)

Do you know if you have the same issue when installing from the console?

**Comment by liberathor** [comment]
Thanks for the quiestion, COLLECTION_GROUP_QUERY  paramis only used  [https://github.com/firebase/extensions/blob/9f8d7fd6048bcaa7b5bc505cebe2e90494359e33/firestore-bigquery-export/guides/IMPORT_EXISTING_DOCUMENTS.md]( to import data command). And I leave here but is not necessary to activate this extension.
