### ISSUE TITLE
[SOLVED] Unexpected token '?' after running the fs-bq-schema-views script

### ISSUE THREAD

**Issue by TheFebrin** [firebase/extensions#1501]
### Step 2: Describe your configuration

- Extension name: **fs-bq-schema-views** 

### Step 3: Describe the problem

After following the [README](https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md#common-schema-file-configuration-mistakes) and running the command, the script starts running, but in the end, the only feedback I get is `Unexpected token '?'`.

#### Steps to reproduce:
```
febrin@febrin:~/Desktop$ npx @firebaseextensions/fs-bq-schema-views --non-interactive --project=${MY_PROJECT} --dataset=${MY_DATASET} --table-name-prefix=my_table --schema-files=schema.json
Unexpected token '?'
```
or shorter version
```
febrin@febrin:~/Desktop$ npx @firebaseextensions/fs-bq-schema-views
Unexpected token '?'
```

##### System info
```
febrin@febrin:~/Desktop$ uname -r
5.19.0-32-generic

febrin@febrin:~/Desktop$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

febrin@febrin:~/Desktop$ npx --version
10.2.2

febrin@febrin:~/Desktop$ npm --version
8.5.1

febrin@febrin:~/Desktop$ node --version
v12.22.9
```

**Comment by TheFebrin** [comment]
I marked it as solved, after installing the latest node and `firebase-tools` the script started to work 🎉 

It would be perfect if the error line was more informative 😄

**Comment by cabljac** [comment]
ah nice, i was going to ask what version. My first guess was some compatibility issue with node v12, but glad it's sorted.
