### ISSUE TITLE
Delete User Data - Search function URL doesn't work

### ISSUE THREAD

**Issue by Surk217** [firebase/extensions#1505]
- Extension name: Delete User Data
- Extension version: 0.1.15
- Configuration values: Search function URL - https://<FUNCTION-NAME>?userId={UID}

#### Steps to reproduce:

Hey,
I configured the Delete User Data extension and everything worked great.
Now I have a new collection in my DB and I need a custom function to get the documents related to the user.

I wrote the function and it works, it accepts the userId as a query.
After adding the function URL to the extension configuration nothing happens.
I tried to delete a user and the function wont call.

##### Expected result
The document paths returned by the function should be deleted

##### Actual result
The document paths returned by the function aren't deleted

**Comment by cabljac** [comment]
Hey, thanks for raising this. Could you provide a snippet of your function code if possible? Do you get any relevant logs from the extension functions?

**Comment by Surk217** [comment]
The function returns a list of chat docs that need to be deleted when the user is deleted

I don't see any logs from the extension that are relevant to my custom function

```
exports.deleteUserDocPaths = functions.region('europe-central2').https.onRequest(async (req, res) => {
    const userId = req.query.userId?.toString()

    if (!userId) {
        res.send([])
        return;
    }

    const chats = await getUserChats({ userId })
    const chatsPaths: string[] = []

    chats.forEach((chat) => {
        chatsPaths.push(getChatRef({ chatterIds: chat.chattersIds }).path)
    })

    res.send(chatsPaths)
})
```

**Comment by cabljac** [comment]
Thanks, i think i've reproduced this bug. I will look into it

**Comment by cabljac** [comment]
ah I believe i've found the issue.

When provided with a custom search function, we make a POST request in the following manner:
```
  const response = await fetch(config.searchFunction, {
    method: "POST",
    body: JSON.stringify({ uid }),
    headers: { "Content-Type": "application/json" },
  });
  ```
  
This means that the `userId` should be extracted from the body of the request rather than the query parameter. Something like this should work:

```typescript
exports.deleteUserDocPaths = functions.region('europe-central2').https.onRequest(async (req, res) => {
    // extract from the body instead:
    const userId = req.body?.uid?.toString()

    if (!userId) {
        res.send([])
        return;
    }

    const chats = await getUserChats({ userId })
    const chatsPaths: string[] = []

    chats.forEach((chat) => {
        chatsPaths.push(getChatRef({ chatterIds: chat.chattersIds }).path)
    })

    res.send(chatsPaths)
})
```
Sorry, this isn't clear from the documentation, and perhaps we can make it more consistent by allowing query params like in your snippet.

Can you see if this works for you?
