### ISSUE TITLE
Facing issues while implementing firebase extentions:-email trigger

### ISSUE THREAD

**Issue by kikisrijita** [firebase/extensions#154]
### [REQUIRED] Step 2: Trigger Email

This feature request is for extension:  (firestore-send-email)

### What feature would you like to see?
while using this extension with valid details, the status field is stuck into PROCESSING..

### How would you use it?

THIS IS MY CODE SNIPPET

/*************---------EMAIL TRIGGER FUNCTION SETUP-----------*********/

![email2](https://user-images.githubusercontent.com/41786724/71717997-e3546e00-2e3f-11ea-838c-62eddec31730.PNG)
 exports.onItemCreation = functions.firestore.document('user_master/{userId}')
 .onCreate(async(event) => {
     const itemDataSnap = await event.data()
     return db.collection('email').add({
        to: ['srijitakiki10@gmail.com'],
        message: {
          subject: 'Your new user is here !',
          html: 'Hey your new user:'+ itemDataSnap.first_name +'had just signed into Xpert App with authId:' + itemDataSnap.phone_no +'.'
        }
      }).then(() => console.log('Queued email for new xpert'));
 });

**Comment by Ehesp** [comment]
Hi kikisrijita

What are you using for your SMTP provider? This usually happens when `nodemailer` cannot fully connect to the STMP provider, even though it may exist.

**Comment by kikisrijita** [comment]
I am using AmazonSES as my smtp provider.

**Comment by mbleigh** [comment]
Do you see any error messages in the Cloud Functions logs associated with the extension? The function is most likely crashing and there may be more details in the logs.

**Comment by kikisrijita** [comment]
Yes its showing error while delivering message ..And **Error: getaddrinfo
ENOTFOUND**

**Comment by Ehesp** [comment]
@kikisrijita this indicates that you have entered SMTP provided aren't working correctly as they're not accepting the credentials. The extension is stuck on `PROCESSING` due to the SMTP provider not returning a response code.

Going to close this one for now, happy to assist further though in this issue.

**Comment by Ross-Rawlins** [comment]
I getting this issue when issue when using gmail with no logged errors/

**Comment by devkongfa** [comment]
Same issue with gmail. Also I noticed this seems to happen around midnight to 1am.
