### ISSUE TITLE
Image Resize : AVIF working only for one size mentioned and not for others

### ISSUE THREAD

**Issue by MiltonAkash** [firebase/extensions#1540]
###

### [REQUIRED] Step 2: Describe your configuration

- Extension name: `storage-resize-images`
- Extension version: Latest one
- Configuration values (redact info where appropriate):
  - sizes: 300x300,600x600,1200x1200
  - formats: [webp,avif,jpeg]

### [REQUIRED] Step 3: Describe the problem

AVIF is created only for 300x300 size and not for the other two

#### Steps to reproduce:

Add different sizes and add different formats along with AVIF and check

**Comment by cabljac** [comment]
Hi! I think this is now resolved in the latest version of the extension. I'll close this as resolved for now. If the issue persists then i'm happy to reopen.

<img width="576" alt="Screenshot 2023-11-21 at 10 50 29" src="https://github.com/firebase/extensions/assets/32874567/3b130150-3906-4c29-8cd8-f4b43cf264e0">
