### ISSUE TITLE
Can't install the extension anymore

### ISSUE THREAD

**Issue by vovahost** [firebase/extensions#1547]
### [READ] Step 1: Are you in the right place?
https://extensions.dev/extensions/firebase/delete-user-data

### [REQUIRED] Step 2: Describe your configuration
No configuration

### [REQUIRED] Step 3: Describe the problem
The Next button in Installation button is disabled in step "2
- Review APIs enabled and resources created"
- Install button missing completely

#### Steps to reproduce:
- Go to https://extensions.dev/extensions/firebase/delete-user-data
- Click Install in Firebase Console
- Select a project

##### Expected result
Can install the Extension

##### Actual result
Can't install the extension. Install button is missing

![Screenshot 2023-05-04 040713](https://user-images.githubusercontent.com/33025410/236104711-084ffc49-1bee-471c-8a9b-1b2e32cfc77f.png)

**Comment by puf** [comment]
Hey @vovahost, *firebaser here*

This seems to happen when Storage is not enabled in your Firebase project. So go to the Storage tab in the Firebase console, and complete the initialization there - even if you don't (want to) use Cloud Storage in your Firebase project.

This provisioning of Storage used to happen automatically when you'd create a new project, but is now only done on demand.

**Comment by vovahost** [comment]
Will give it a try. Thank you.
Could you also add Storage as a dependency so it asks me to Enable it like the other extensions do?

**Comment by vovahost** [comment]
@puf I was able to install the extension after enabling storage but I have another issue. Updating this [delete-user-data](https://extensions.dev/extensions/firebase/delete-user-data) extension in another project will start the update process and hang forever. If I close the Update window using the top left X button after a few minutes, it just shows me that the extension wasn't updated.

**Comment by puf** [comment]
Hey Valid, that sounds like a different issue - so I recommend opening a new issue for it.

**Comment by TheRedSpy15** [comment]
> Hey @vovahost, _firebaser here_
> 
> This seems to happen when Storage is not enabled in your Firebase project. So go to the Storage tab in the Firebase console, and complete the initialization there - even if you don't (want to) use Cloud Storage in your Firebase project.
> 
> This provisioning of Storage used to happen automatically when you'd create a new project, but is now only done on demand.

I have storage enabled on my project, and I'm experiencing this issue

This doesn't seem limited to this extension
https://github.com/stripe/stripe-firebase-extensions/issues/526

**Comment by cabljac** [comment]
> > Hey @vovahost, _firebaser here_
> > This seems to happen when Storage is not enabled in your Firebase project. So go to the Storage tab in the Firebase console, and complete the initialization there - even if you don't (want to) use Cloud Storage in your Firebase project.
> > This provisioning of Storage used to happen automatically when you'd create a new project, but is now only done on demand.
> 
> I have storage enabled on my project, and I'm experiencing this issue
> 
> This doesn't seem limited to specific extensions [stripe/stripe-firebase-extensions#526](https://github.com/stripe/stripe-firebase-extensions/issues/526)

It might be that this extension requires storage, firestore, and realtime database enabled on the project. Are any of these not enabled?

**Comment by TheRedSpy15** [comment]
> > > Hey @vovahost, _firebaser here_
> > > This seems to happen when Storage is not enabled in your Firebase project. So go to the Storage tab in the Firebase console, and complete the initialization there - even if you don't (want to) use Cloud Storage in your Firebase project.
> > > This provisioning of Storage used to happen automatically when you'd create a new project, but is now only done on demand.
> > 
> > 
> > I have storage enabled on my project, and I'm experiencing this issue
> > This doesn't seem limited to specific extensions [stripe/stripe-firebase-extensions#526](https://github.com/stripe/stripe-firebase-extensions/issues/526)
> 
> It might be that this extension requires storage, firestore, and realtime database enabled on the project. Are any of these not enabled?

All of those are enabled on my project. Can't speak for the others having the same issue

**Comment by TheRedSpy15** [comment]
While trying to update the extension again. I noticed there's a single warning printed to the console:
` ID or name found in config.`

**Comment by NashIlli** [comment]
Same, cant update any extension

**Comment by jackstruck** [comment]
Firebase support has indicated this is resolved
