### ISSUE TITLE
Trigger Cloud Function after Extension has finished

### ISSUE THREAD

**Issue by linxydmhg** [firebase/extensions#155]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: storage-resize-images

### What feature would you like to see?

I would like to be able to run a my own cloud function after the ResizeImage has finished because right now one of the most basic use-cases is problematic to achieve using the extension. 
OR
Give the extension function some sort of "Update Database Fields" where you could set something 
like
 
```
[Update@ /users/{userId}] fields=[
  userThumbnail: ExFn.GeneratedThumbnail.200x200.path,
  userImage: ExFn.OriginalImage.path,
]

[Update@ /animals/{petId}/owners/{userId}] fields=[
  ownerThumbnail: ExFn.GeneratedThumbnail.400x400.path,
]
```
Fields like {userId, petId} would need to be provided in the File Metadata for this to work

### How would you use it?

I want to change a users profile image, and then update a 'profileImageThumbnail' field in the database, so that the UI can display the image. 

Right this only works halfway, because we never know when the extension function has finished, so we are forced to prematurely set the 'profileImageThumbnail' property on the document, but then the Ui will fail and throw an exception when obtaining the image since it has not yet been created in the storage bucket. 
A solution right now is to add some sort of delay, so the extension function has time to do its work, but this is not optimal and can also fail. Another one would be to implement a custom storageTrigger cloud function that parses the path, and using metadata you could hack it together, but this entirely defeats the purpose of the extension function and is cumbersome and complex.  

Or maybe there is a solution that works and already exists?

**Comment by Ehesp** [comment]
Hi @linxydmhg 

Thanks for the detailed explanation. Right now, the best option would be a custom cloud function which listens to new Storage files being added.

**Comment by houdayec** [comment]
> ### [READ] Step 1: Are you in the right place?
> Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
> [Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.
> 
> ### [REQUIRED] Step 2: Extension name
> This feature request is for extension: storage-resize-images
> 
> ### What feature would you like to see?
> I would like to be able to run a my own cloud function after the ResizeImage has finished because right now one of the most basic use-cases is problematic to achieve using the extension.
> OR
> Give the extension function some sort of "Update Database Fields" where you could set something
> like
> 
> ```
> [Update@ /users/{userId}] fields=[
>   userThumbnail: ExFn.GeneratedThumbnail.200x200.path,
>   userImage: ExFn.OriginalImage.path,
> ]
> 
> [Update@ /animals/{petId}/owners/{userId}] fields=[
>   ownerThumbnail: ExFn.GeneratedThumbnail.400x400.path,
> ]
> ```
> 
> Fields like {userId, petId} would need to be provided in the File Metadata for this to work
> 
> ### How would you use it?
> I want to change a users profile image, and then update a 'profileImageThumbnail' field in the database, so that the UI can display the image.
> 
> Right this only works halfway, because we never know when the extension function has finished, so we are forced to prematurely set the 'profileImageThumbnail' property on the document, but then the Ui will fail and throw an exception when obtaining the image since it has not yet been created in the storage bucket.
> A solution right now is to add some sort of delay, so the extension function has time to do its work, but this is not optimal and can also fail. Another one would be to implement a custom storageTrigger cloud function that parses the path, and using metadata you could hack it together, but this entirely defeats the purpose of the extension function and is cumbersome and complex.
> 
> Or maybe there is a solution that works and already exists?

I'm having the same need as you. It could be great to select a source folder, because for now, the extension is not optimised at all. 

It means that the only solution is to create a new bucket for every kind of data / images type we have if we want to have specific treatments on each of them. However, it is very common to have for instance, a users_pictures folder with profile pictures and users_banners with banners on profile or something similar, but the needs of resizing or completely different. I know once resized, images do not weight a lot, but still, we have on large scale, potentially dozens of MB/GB of unused data.

**Comment by i14h** [comment]
@linxydmhg Thanks for the feedback! This functionality is something we're evaluating on the backend and will revisit if implemented.
