### ISSUE TITLE
[firestore-send-email] Can't update to latest version

### ISSUE THREAD

**Issue by vovahost** [firebase/extensions#1551]
## Describe your configuration

- Extension name: firestore-send-email
- Extension version: firebase/firestore-send-email@0.1.20

## Describe the problem
Can't update from version firebase/firestore-send-email@0.1.20 to firebase/firestore-send-email@0.1.25

#### Steps to reproduce:
When there's a message saying there's a newer version available.
And Clicking "Update extension" will open the Update page and the "Update extension version" page.
And Clicking on Update button will start the update process but it will never end.

##### Expected result
Extension is updated.

##### Actual result
Extension doesn't update

![Screenshot 2023-05-12 050900](https://github.com/firebase/extensions/assets/33025410/925d2446-f6cf-443c-ac99-a5aa746929c7)

**Comment by vovahost** [comment]
Looks like all extensions which would get stuck in the update process are now updated to the latest version, without me doing anything. I'm just assuming that the Firebase team solved the issue.

**Comment by cabljac** [comment]
Will close this, not sure what the issue was but it seems solved.

**Comment by iamandreadompe** [comment]
I'm in the same situation...
<img width="895" alt="Screenshot 2023-05-17 alle 11 59 20" src="https://github.com/firebase/extensions/assets/57131689/f6f9ea1c-20e4-4f2c-9b56-b10420a3a248">
