### ISSUE TITLE
[storage-resize-images] Support for animated avif

### ISSUE THREAD

**Issue by saumyakswain** [firebase/extensions#1553]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **storage-resize-images** 

### What feature would you like to see?

Support for animated avif similar to animated webp. Animated avif is supported on all major browsers on all major platforms so it should be worth supporting. 

### How would you use it?

Use it the same way as animated webp.

**Comment by jauntybrain** [comment]
Hi @saumyakswain!

Looking into Sharp [documentation](https://sharp.pixelplumbing.com/api-output#avif), it does not currently support animated AVIF. Since we are using Sharp to process images, animated AVIF cannot be processed with the extension.

Closing this issue for now.

**Comment by saumyakswain** [comment]
Thanks @jauntybrain for taking a look. Hopefully sharp supports animated avifs soon 🤞
