### ISSUE TITLE
Typo in documentation?

### ISSUE THREAD

**Issue by samirsd** [firebase/extensions#1554]
excerpted from the docs here: https://extensions.dev/extensions/firebase/storage-resize-images

`**Paths that contain images you want to resize**
Restrict storage-resize-images to only resize images in specific locations in your Storage bucket by supplying a comma-separated list of absolute paths. For example, specifying the paths /users/pictures,/restaurants/menuItems will resize any images found in any subdirectories of /users/pictures and /restaurants/menuItems.
You may also use wildcard notation for directories in the path. For example, /users/*/pictures would _exclude_ any images in any subdirectories of /users/foo/pictures as well as any images in subdirectories of /users/bar/pictures, but also any images in subdirectories of /users/any/level/of/subdirectories/pictures.`

Is this correct? "You may also use wildcard notation for directories in the path. For example, /users/*/pictures would _exclude_ any images..." that seems like a typo or am I missing something

**Comment by cabljac** [comment]
I believe that's a typo, good catch! thanks.
