### ISSUE TITLE
User data deletion trigger firing, yet not deleting any data resulting in time-out or error.

### ISSUE THREAD

**Issue by JamesLamusse** [firebase/extensions#1558]
### My Configuration

- Extension name: Delete User Data
- Extension version: firebase/delete-user-data@0.1.16
- Configuration values (redact info where appropriate):
  - Realtime database url instance (affix-card-default-rtdb.europe-west1.firebasedatabase.app)
  - Location: europe-west1
  - Path: "users/{UID}/" **_I have also tried_** "users/{UID}"

- My Realtime database contains data under 'users/' as shown below:
![image](https://github.com/firebase/extensions/assets/54526726/51adfba3-2d4d-4195-8f65-086ddfbf599f)

### The Problem

User data from users/{UID} not being deleted from the realtime database.

#### Steps to reproduce:

![image](https://github.com/firebase/extensions/assets/54526726/4230bae4-6307-4a47-8f4a-cbfb6a35d81b)

Shown in the logs image that I got from Google Cloud. 

I triggered the function when I deleted a user either in the authentication manager in the firebase dashboard or on my application, both resulted in either a time-out or error.

##### Expected result

Data under users/{UID} removed.

##### Actual result

As shown above in the logs is the result, the cloud storage data is deleted but not the realtime database data.

This is the final log for the trace **_t6x5rsjramdn_**

`{
  "textPayload": "Function execution took 58573 ms, finished with status: 'error'",
  "insertId": "jmdafd7z1c6",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "project_id": "affix-card",
      "region": "europe-west1",
      "function_name": "ext-delete-user-data-clearData"
    }
  },
  "timestamp": "2023-05-16T07:06:18.638000658Z",
  "severity": "DEBUG",
  "labels": {
    "execution_id": "t6x5rsjramdn"
  },
  "logName": "projects/affix-card/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "trace": "projects/affix-card/traces/0c8f9f862c32af209dd0931599f388b6",
  "receiveTimestamp": "2023-05-16T07:06:18.642845871Z"
}
`

**Comment by vjamrich** [comment]
I was facing the same issues.
Just modify the Realtime database url instance value followingly:

- original `affix-card-default-rtdb.europe-west1.firebasedatabase.app`
- new `affix-card-default-rtdb`

Additionally, make sure the location is set correctly

**Comment by cabljac** [comment]
Seems like we should update the regex validation for that parameter
