### ISSUE TITLE
Unbind Bitly from URL Shorten Extension

### ISSUE THREAD

**Issue by drveresh** [firebase/extensions#1578]
It is a follow-up on the [issues/1027](https://github.com/firebase/extensions/issues/1027).

It's been more than a year since I reported and yet I do not see any action on this unfair issue.

As explained, it has to be a broad and generic solution, without having a dependency on Bitly or a single entity or service.

We are still blocked from integrating other URL-shortening APIs through this extension!

Please share the concrete plan on this asap.

**Comment by i14h** [comment]
Hi drveresh, 
As said before, the team is stretched thin with other tasks and priorities. If you'd like, clone the extension, add the functionality and we'll be happy to review it. And then you can publish it under your own publisher on [extensions.dev](https://extensions.dev)
