### ISSUE TITLE
storage-resize-images@0.1.36 -  'image/jpg' is not supported

### ISSUE THREAD

**Issue by loic-hamdi** [firebase/extensions#1587]
Hi,

I have this log message for jpg images: 

```textPayload: "Image type 'image/jpg' is not supported, here are the supported file types: image/jpeg, image/png, image/tiff, image/webp, image/gif, image/avif"```

It is very surprising that a .jpg extension would not be supported?

**Comment by naturalnick** [comment]
image/jpeg is the MIME type for JPEG files which includes both .jpeg and .jpg extensions.

image/jpg is not supported, but it could be programmed in to revert to image/jpeg should someone provide  image/jpg.
