### ISSUE TITLE
Update failed Resize Images and Trigger Email from Firestore

### ISSUE THREAD

**Issue by ian-sayles** [firebase/extensions#1650]
Tried updating the Resize images and trigger email to the latest version and both failed with different error messages:

Email:
failed to determine location for cloud function "processQueue": resource "processQueue" location must be a nonempty string: resource "processQueue" location must be a nonempty string

Images:
resource "backfillResizedImages" location must be a nonempty string

Without uninstalling the extension I can't seem to get the install to run again so can see about fixing the above errors.

**Comment by dackers86** [comment]
Thanks @ian-sayles 

We are looking into this. Although not ideal, a current working around appears to involve trying the `try reinstalling` twice.

1. The first will cause the error.
2. Try reinstall will fail the first time.
3. It will install on a second attempt.

**Comment by cabljac** [comment]
Closing as we believe this to be resolved. If this reoccurs then I am happy to reopen and investigate further.
