### ISSUE TITLE
[delete-user-data] is still using pre-GA v0.1 and v1beta1 endpoints

### ISSUE THREAD

**Issue by zigapovhe** [firebase/extensions#166]
- Extension name: **\_** (`delete-user-data`)
- Extension version: **\_** 0.1.2

I've received an email from Google Cloud Platform today, as a reminder, that I'm still calling the pre-GA v0.1 and v1beta1 endpoints of the App Engine and Cloud Functions metadata server. They said that these legacy endpoints are scheduled to be turned down on April 30, 2020. After April 30, 2020, requests to the v0.1 and v1beta1 endpoints will no longer be supported and may return HTTP 404 NOT FOUND responses. They attached a file that shows you which extensions use old endpoints and there was 'delete-user-data' extension. 

I'm not an expert, but they are saying that you are probably using an old Google client library which is making requests to the legacy endpoints. 

The endpoints extension is calling are either: 

Endpoint | URI
-- | --
v0.1 | http://metadata.google.internal/0.1/meta-data/…
v1beta1 | http://metadata.google.internal/computeMetadata/v1beta1/…
-- | --

but should be using http://metadata.google.internal/computeMetadata/v1/…

[Here's a link](https://cloud.google.com/compute/docs/migrating-to-v1-metadata-server#supported-google-libraries)

I'm afraid that if you don't update these libraries, the extension will stop working after April 30, 2020

**Comment by Ehesp** [comment]
@laurenzlong the `specVersion` for every extension is using `v1beta`. I'm not 100% sure what happens behind the scenes, but is the change to fix this issue just this version or does it require internal changes too?

**Comment by laurenzlong** [comment]
specVersion is completely separate from what this warning message is about. @zigapovhe please update your extension to v0.1.3, which has the latest firebase-admin dependency (that's probably what caused the warning email, see https://cloud.google.com/compute/docs/migrating-to-v1-metadata-server#supported-google-libraries)
