### ISSUE TITLE
[firestore-send-email] Allow specifying from name in "Default FROM address" in configuration

### ISSUE THREAD

**Issue by jcapogna** [firebase/extensions#167]
###  Extension name

This feature request is for extension: firestore-send-email

### What feature would you like to see?

I would like to be able to specify a name in the "Default FROM address" configuration field. 
Currently only a raw email address passes the validation rules for the field. 

This could either be done as a separate configuration option or by allowing email addresses of the following format: "My App \<noreply@myapp.com\>".

Specifying email addresses of the format "My App \<noreply@myapp.com\>" works when manually specifying the 'from' field, so I believe this just change is just to modify what is allowed for the configuration of the "Default FROM address" option. 

### How would you use it?

This would allow the default from address to be more user friendly, instead of just the raw email.

**Comment by Ehesp** [comment]
Hey @jcapogna - could you confirm whether [this regex](https://regex101.com/r/H4gvGO/2) covers your use cases? Think it should!

**Comment by jcapogna** [comment]
@Ehesp That looks good to me
