### ISSUE TITLE
🐛 [storage-resize-images] Increase function memory past 2GB

### ISSUE THREAD

**Issue by glyphdev123** [firebase/extensions#1719]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: `storage-resize-images`

### What feature would you like to see?

Hello, is there any way to increase the function memory more than 2GB? Currently the dropdown for the config only allows 512MB, 1GB and 2GB. 

<img width="499" alt="Screenshot 2023-08-28 at 10 13 16 PM" src="https://github.com/firebase/extensions/assets/136295392/cc9088c1-4d6f-4982-bf8f-d885674716d6">

I also wonder, what is the `function memory` paramater in the `advanced configuration`? I've tried to set that to 8GB, but it does not seem to have an effect. 
<img width="497" alt="Screenshot 2023-08-28 at 10 14 09 PM" src="https://github.com/firebase/extensions/assets/136295392/06fe7c0e-16fb-4f5a-b7fb-6ec54ddc9adc">

### How would you use it?

Sure! We're dealing with really large images. Seems like the extension crashes with an out of memory error when dealing with them  so I'd like to try increasing memory in order for it to work on them 😭

See below: 
<img width="1187" alt="Screenshot 2023-08-28 at 10 15 29 PM" src="https://github.com/firebase/extensions/assets/136295392/37ff7fee-14ee-4132-8395-bed09ba05bf1">

**Comment by glyphdev123** [comment]
Update: 

Looks like a temporary workaround i found is to modify the memory explicitly in:

https://console.cloud.google.com/functions/edit/{location}/ext-storage-resize-images-generateResizedImage

But, I'd be much more comfortable with a proper configurable solution

**Comment by TangrisJones** [comment]
Hey @dackers86 just checking in on this one, any timeline on the fix? Thanks!
