### ISSUE TITLE
🐛 [firestore-bigquery-export] Extension doesn't export firestore data that was imported

### ISSUE THREAD

**Issue by Bytamine** [firebase/extensions#1721]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: firestore-bigquery-export
- Extension version: 0.1.35
- Configuration values (redact info where appropriate):
  - Cloud Functions location: northamerica-northeast1
  - BigQuery Dataset location: northamerica-northeast1
  - Collection path: andrew-test-collection
  - Dataset ID: andrew_test_collection
  - Table ID: andrew_test_collection
  Other settings are default.

### [REQUIRED] Step 3: Describe the problem
I'm trying to migrate firestore database from us-east1 to northamerica-northeast1 and I have a bunch of firestore-bigquery-export extensions I need to migrate as well. So I set up a test extension and did a test collection migration (Google Cloud Firestore Import/Export, using cloud storage as a storage). Data was migrated successfully but I don't see the exported data in BigQuery. So I tried to add document manually and in that case extension has exported the document successfully. Same with deletion and updates - they work fine. It's like only imports are somehow ignored.
I've checked logs and queues, but found nothing interesting, except couple of warning during the extension creation
```
No valid table reference is available. Skipping partitioning
Cannot partition an existing table andrew_test_collection_andrew_test_collection_raw_changelog
```

Is it possible to debug or somehow understand why the imported data is ignored by the extension?

**Comment by cabljac** [comment]
I think what's probably happening is that the migration writes to the new firestore instance using some kind of batch write operation.

I don't think batch writes will trigger an onWrite cloud function event, which is how the extension works:
https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/functions/src/index.ts#L95

I'll have a think if there's a best solution and get back to you

**Comment by cabljac** [comment]
We have an update for this extension almost released where it will optionally backfill data onInstall. Once that is available then you should be able to first migrate the firestore collection, and then install or reconfigure the extension instance to point at the migrated data, with backfill enabled. It should then export your collection from the new location.

Until that is released you _could_ try manually importing via out import script (which is essentially going to be replaced by the lifecycle update).

Let me know if you have any more questions!

**Comment by Bytamine** [comment]
Thank you very much @cabljac!
I'll use the import script for now.
