### ISSUE TITLE
resize with different parameters for  specific folder from storage

### ISSUE THREAD

**Issue by anthowm** [firebase/extensions#173]
### Step 2: storage-resize-images

This feature request is for extension: storage-resize-images. 

### What feature would you like to see?

Maybe this is a question, there is a way to apply differents parameters for specific folders ? 
ex.
I have 2 folders: 
/profile --> I want 40x40 and 180x180
/Images --> I want 200x300, etc.

### How would you use it?

Well I want to avoid extra billing from Images that I don't want.

**Comment by rosariopfernandes** [comment]
It is possible to have more than one instance of the same extension, so my recommendation would be having 2 different instances of the storage-resize images. You can configure the first instance to resize images from `<your-bucket-url>/profile` with the sizes `40x40,180x180` while the second instance resizes images from `<your-bucket-url>/Images` with the size `200x300`.

**Comment by Ehesp** [comment]
Hey, yep what @rosariopfernandes said is the recommended solution at the moment.

**Comment by anthowm** [comment]
@Ehesp It not works can you reopen ? read stackoverflow thanks!

**Comment by anthowm** [comment]
@Ehesp sorry for bothering but can you reopen this?

**Comment by granttj01** [comment]
@Ehesp The solution above does not work as @anthowm says. Can we add this functionality please?

To do this we could do the following:

1) Add a config value to config.js
```imageDir: process.env.IMG_DIR,```

2) Add a new logging method
```
export const imagePathInvalid = () => {
  console.log("Image path does not match, no processing is required")
};
```

3) Check for a match between the value we extract [here](https://github.com/firebase/extensions/blob/c7396cd55a18dacba091e21bd94b1d54b3225e72/storage-resize-images/functions/src/index.ts#L69)
```const fileDir = path.dirname(filePath);```
and config.imageDir.
To also take into consideration glob matching we could utilise [minimatch](https://github.com/isaacs/minimatch), or equivalent to allow config to be say
```<somedirectory>/*/<imageDirectory>```

What do you think?
