### ISSUE TITLE
🐛 [firestore-send-email] Attachments not being attached

### ISSUE THREAD

**Issue by gruppler** [firebase/extensions#1739]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: `firestore-send-email`
- Extension version: `0.1.27`
- Configuration values (redact info where appropriate):
  - SMTP connection URI: `smtp://app@redacted.com:redacted@smtp.office365.com:587`
  - Email documents collection: `mail`
  - Default FROM address: `Redacted <noreply@redacted.com>`
  - Firestore TTL type: `never`
  - Firestore TTL value: `1`

### [REQUIRED] Step 3: Describe the problem
Attachment files are not being included with emails. The email is sent and received without error, but there is simply no attachment. I am uploading the file to Google Storage and passing the file's download URL in the "path" attribute. This had been working in the past, so I assume an extension update broke something. I have tried using the "href" attribute instead of "path" but it did not remedy the problem. Again, there are no error messages, simply no attachments.

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.

1. Upload a file to Google Storage.
2. Retrieve the file's download URL.
3. Create an email document with a message and an attachment, specifying the original `filename`, and specifying `path` or `href` as the URL.
4. Open the received email.

##### Expected result
Received email contains message and attachment.

##### Actual result
Received email contains only message, no attachment.

**Comment by marknesh** [comment]
Hello @gruppler,

I have just tested this out, and I received the file attachment. Could you please provide the snippet of the code that you used to send the email that also includes the attachment?

**Comment by gruppler** [comment]
Thank you for the reply. Here is my generalized function for sending emails:

```
export const SEND_EMAIL = async function (
  { dispatch, state },
  { to, cc, replyTo, subject, message, attachments }
) {
  let mailRef;
  let data = {
    createdBy: state.user.id,
    to,
    message: {
      subject,
      html: message,
      text: formatPlainText(message),
    },
  };
  if (cc) {
    data.cc = cc;
  }
  if (replyTo) {
    data.replyTo = replyTo;
  }
  if (attachments) {
    data.attachments = attachments;
  }
  mailRef = await db.collection("mail").add(data);
  // ...
}
```

Here is an example of its usage:
```
// ...

let attachments = cloneDeep(attachments).map((doc) => ({
  filename: doc.file.name,
  href: doc.file.url,
}));

await dispatch("SEND_EMAIL", {
  to: customerEmails,
  cc: userEmail,
  replyTo: userEmail,
  subject,
  message,
  attachments,
});
```

What is most confusing to me is the fact that this code used to work, and now it doesn't, though it hasn't changed.

**Comment by marknesh** [comment]
@gruppler This seems to be the problem.
> if (attachments) {
>     data.attachments = attachments;
>   }

`attachments` is a property inside the **message field**, hence why you are receiving an email with the message but **no attachment**. Therefore is should be:
> if (attachments) {
>     data.message.attachments = attachments;
>   }

**Comment by gruppler** [comment]
Thank you so much for helping me! I tracked down the commit that broke this and it was much further back in time than I thought!
