### ISSUE TITLE
Image resize extension not working

### ISSUE THREAD

**Issue by mrinal2305** [firebase/extensions#174]
When i trying to open resized image ,it didn't open and when i open image in browser it go to "https://console.firebase.google.com/u/0/undefined"  url and show 404 error and when i try to open in firebase Spinner run for infinite times ,and not showing any result.
![Screenshot from 2020-01-23 17-43-28](https://user-images.githubusercontent.com/45876327/72983839-49615f00-3e08-11ea-8333-79a0045f47a5.png)

**Comment by oseiasmribeiro** [comment]
The images generated by the ResizeImages extension do not enter the Storage with Access Token. If I select the image in the Storage Console -> Access Location (in the right panel) -> Create Access Token, solves the problem for the current selected image. The Token should be created automatically.

**Comment by thefirestrings666** [comment]
Hello!

I would like to know if it's possible to allow token automatically without going to the console 

Thanks in advance for your help 

Have a nice day
