### ISSUE TITLE
🐛 [firestore-send-email] Sending attachments from a stream raises error

### ISSUE THREAD

**Issue by verscph** [firebase/extensions#1742]
### Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### Step 2: Describe your configuration

- Extension name: **firestore-send-email**
- Extension version: **0.1.27**
- Configuration values (redact info where appropriate):
  - SMTP connection URI: smtp://app@redacted.com:redacted@smtp.redacted.com:587
  - Email documents collection: mail
  - Default FROM address: Redacted <noreply@redacted.com>
  - Firestore TTL type: never
  - Firestore TTL value: 1

### Step 3: Describe the problem

Sending attachments from a stream raises an error:
`Error: Value for argument "data" is not a valid Firestore document. Couldn't serialize object of type "ReadStream" (found in field "message.attachments.`0`.content"). Firestore doesn't support JavaScript objects with custom prototypes (i.e. objects that were created via the "new" operator).`

I followed the documentation on https://nodemailer.com/message/attachments/ and added as an attachment:
```
{  // stream as an attachment
    filename: 'text4.txt',
     content: fs.createReadStream('file.txt')
},
```

#### Steps to reproduce:

Code:
```
admin.firestore().collection('mail').add({
    to: recipient, 
    message: {
        subject: subject, 
        text: 'Please find the data you exported in attach...', 
        attachments: [{
            filename: filename,
            encoding: 'base64',
            content: fs.createReadStream(process.env.EXPORT_FOLDER + filename, { encoding: 'base64' })
        }],
    }
});
```

I tried without specifying the encoding, and with encoding 'binary', which both raise the same error.

##### Expected result
A new document in the mail collection

##### Actual result
The console output shows:
```
Error: Value for argument "data" is not a valid Firestore document. Couldn't serialize object of type "ReadStream" (found in field "message.attachments.`0`.content"). Firestore doesn't support JavaScript objects with custom prototypes (i.e. objects that were created via the "new" operator).
```

I checked whether the stream itself does not raise an error using:
```
try {
        fs.createReadStream(process.env.EXPORT_FOLDER + filename);
} catch (error) {
       console.log(`Error reading file ${process.env.EXPORT_FOLDER + filename}: ` + error);
}
```

**Comment by cabljac** [comment]
The problem here is that Firestore cannot store a ReadStream, there is not a firestore data type for that. The way to support this would probably be a feature where we introduce some custom field in firestore to reference a storage object, and then the extension creates a ReadStream during its execution (i think).

Currently this behaviour is not supported, so I will close this and reopen as a [feature request.](https://github.com/firebase/extensions/issues/1802)
