### ISSUE TITLE
🐛 [firestore-bigquery-export] Firestore Time Partitioning field value null

### ISSUE THREAD

**Issue by qashier-ray-foo** [firebase/extensions#1745]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: `firestore-bigquery-change-tracker`
- Extension version: `0.1.35`
- Configuration values (redact info where appropriate):
  - BigQuery SQL table Time Partitioning option type(Optional): MONTH
  - BigQuery Time Partitioning column name(Optional): transactionDate
  - Firestore Document field name for BigQuery SQL Time Partitioning field option(Optional): transactionDate
  - BigQuery SQL Time Partitioning table schema field(column) type(Optional): TIMESTAMP

### [REQUIRED] Step 3: Describe the problem
The Firestore `Timestamp` field got converted into `object` during [serialize](https://github.com/firebase/extensions/blob/d2b5a1240c5752851c116d3c3e2792045616cfb4/firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts#L142) and cause [isValidPartitionTypeDate](https://github.com/firebase/extensions/blob/d2b5a1240c5752851c116d3c3e2792045616cfb4/firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/partitioning.ts#L54) checking return `false` and thus set `null` as the value for the column

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.

1. Install the extension with the configuration values as above or can refer to the screenshot below
2. Create a new document in firestore with `transactionDate` field using `Timestamp` type
3. Validate the query data in `BigQuery`

##### Expected result
It should be able to set the `Timestamp` field value from **Firestore** into **BigQuery**

##### Actual result
<img width="631" alt="Screenshot 2023-09-19 at 1 12 57 PM" src="https://github.com/firebase/extensions/assets/127077496/9375afe7-4cb1-41f7-9a5a-f1a3993c01ec">
<img width="1091" alt="Screenshot 2023-09-19 at 1 13 48 PM" src="https://github.com/firebase/extensions/assets/127077496/1e44427d-9937-4677-bd6a-68dc3a1b7baa">
<img width="646" alt="Screenshot 2023-09-19 at 1 14 11 PM" src="https://github.com/firebase/extensions/assets/127077496/8deff688-10a4-471d-91b2-42ade39f7ae2">

![Screenshot 2023-09-19 at 1 15 12 PM](https://github.com/firebase/extensions/assets/127077496/7629bbed-ed04-4b7a-9460-e9330df4e4f6)

**Comment by guneemwelloeux** [comment]
I'm having the exact same issue, with this version but also older versions as well. I've been trying to get this to work, to no avail for more than a year now.

**Comment by cabljac** [comment]
Hey there, i'm investigating this now. That error reported does seem to indicate that its not interpreting the date correct, though a firestore timestamp should have `type` object, as far as i understand. I haven't been able to reproduce it just yet in testing, but I will try and fix this ASAP

**Comment by cabljac** [comment]
<img width="976" alt="Screenshot 2023-11-13 at 13 43 09" src="https://github.com/firebase/extensions/assets/32874567/15f96fe6-67e0-4e27-99f7-8ca31e5e4b0a">
hmm i deployed the extension from a local source and it seemed to add the partition field correctly. Maybe there's some version mismatch with the change tracker
