### ISSUE TITLE
image cannot read property startswith of undefined

### ISSUE THREAD

**Issue by codersmoon** [firebase/extensions#175]
Hİ.I use google cloud firebase image extantion for image resizing ( for google cloud storage images ) ; but i get this error :

`TypeError: Cannot read property 'startsWith' of undefined
at Object.exports.isImage (/srv/functions/lib/validators.js:18:48)
at Object.<anonymous> (/srv/functions/lib/index.js:47:32)
at Generator.next (<anonymous>)
at /srv/functions/lib/index.js:22:71
at new Promise (<anonymous>)
at __awaiter (/srv/functions/lib/index.js:18:12)
at exports.generateResizedImage.functions.storage.object.onFinalize (/srv/functions/lib/index.js:44:82)
at cloudFunction (/srv/node_modules/firebase-functions/lib/cloud-functions.js:131:23)
at /worker/worker.js:825:24
at <anonymous>`

**Comment by Ehesp** [comment]
Hi @codersmoon please could you provide more details about your setup:

- Version of extension
- Arguments which you set it up with
- Replication flow

Thanks

**Comment by oseiasmribeiro** [comment]
I also having the same problem. I used  images captured by image_picker and image_cropper in Flutter to login with firebase.

**Comment by Ehesp** [comment]
So this error would be thrown when no `contentType` exists. How are you uploading this image? What is being uploaded?

**Comment by oseiasmribeiro** [comment]
The user uploads a photo from the gallery or the camera, after then uploads for Firebase Storage.
I'm using this function on the flutter:
`Future<void> uploadImage() async{
    FocusScope.of(context).requestFocus(FocusNode());
    FirebaseUser firebaseUser = await _firebaseAuth.currentUser();
    if(firebaseUser != null){
      if(_imageAvatar != null){
        StorageReference folderRoot = _firebaseStorage.ref();
        StorageReference fileReference = folderRoot.child("imageUser").child("${firebaseUser.uid}.jpg");
        StorageUploadTask storageUploadTask = fileReference.putFile(_imageAvatar);
        storageUploadTask.events.listen((StorageTaskEvent storageTaskEvent) {
          _signUpBloc.inValueUserStatus.add(storageTaskEvent.type);
          // grava no Firestore a url da imagem
          storageUploadTask.onComplete.then((StorageTaskSnapshot storageTaskSnapshot) async {
            String url = await storageTaskSnapshot.ref.getDownloadURL();
            _firestoreDBInfo.setImageUrlUser(firebaseUserId: firebaseUser.uid, url: url);
          });
        });
      }
    }
  }`

**Comment by codersmoon** [comment]
i use node.js app on google cloud run for image upload to google cloud storage.if i upload with firebase console works perfectly; but i use my app , images do not contain content type.İt doesn't work when changing the content type after uploading.like this :
`gsutil -h "Content-Type:image/jpg" \`
i ı do this , images get content type;but again not work .ty.

**Comment by Ehesp** [comment]
Thanks, I'll take a look into both situations.

**Comment by codersmoon** [comment]
my cloud run node js version is different from firebase image ext.

**Comment by oseiasmribeiro** [comment]
The images generated by the ResizeImages extension do not enter the Storage with Access Token. If I select the image in the Storage Console -> Access Location (in the right panel) -> Create Access Token, solves the problem for the current selected image. The Token should be created automatically.

**Comment by Ehesp** [comment]
https://github.com/firebase/extensions/pull/183
