### ISSUE TITLE
Misleading documentation for firestore-counter

### ISSUE THREAD

**Issue by xrossapp** [firebase/extensions#176]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: Distributed counters.

### [REQUIRED] Step 3: Describe the problem

Referring to Distributed Counters, documentation states:
Here are some features of this extension:
Scales from 0 updates per second to at least 10,000 per second.

Documentation for Cloud Firestore states this limit:
Maximum writes per second per database 10,000 (up to 10 MiB per second).

So, Counters can't scale beyond that.

As I talked with Firebase support, they acknowledged this discrepancy in the documentation and I was asked to file an issue.
This is obviously not a bug, but this needs to be updated so that it doesn't causes any confusion.

Firebase support statement:
"Please file an issue in our GitHub repository so that we can update our extension description to be less ambiguous"

#### Steps to reproduce:
Refer to documentation for Distributed counters.
And quotas and limits for Cloud Firestore.

**Comment by laurenzlong** [comment]
https://github.com/firebase/extensions/pull/179
