### ISSUE TITLE
SMTP password "There was an error creating a secret"

### ISSUE THREAD

**Issue by cganoe** [firebase/extensions#1782]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: firestore-send-email
- Extension version: 0.1.28

#### Steps to reproduce:

I am trying to configure the extension. I am assuming that I am supposed to enter my SMTP password into the field for it and then click "Create secret", but when I click the button, a small box pops up saying: "There was an error creating a secret".

I see the same error whether on the initial install attempt or if I install the extension and try to add the password via Manage Configuration later.

##### Expected result
Secret would be created when clicking "Create secret", or additional information/documentation should be available on how to correct the error.
##### Actual result
Error message
<img width="762" alt="Screenshot 2023-10-30 at 10 57 02 AM" src="https://github.com/firebase/extensions/assets/30124444/1cd1ef7a-b8e0-44cc-b08d-88a2db524010">

**Comment by cganoe** [comment]
Looks like this is the error message associated with it:
`Constraint constraints/gcp.resourceLocations violated for [orgpolicy:projects/############] attempting to create a secret in [global]. For more information, see https://cloud.google.com/resource-manager/docs/organization-policy/defining-locations."`

**Comment by marknesh** [comment]
Hello @cganoe 

Is the project `ipath-dev-blaze` under an organization?

**Comment by cganoe** [comment]
Yes. I'm guessing from what I'm reading elsewhere is that the extension is trying to create the secret globally, but the organizational constraints on the locations where secrets can be created is causing the issue.

**Comment by marknesh** [comment]
Secrets are accessed globally across Google Cloud. But since you have a location constraint, you can create a secret with a User Managed replication policy. This allows you to select a location where you want the secret to be stored. Before creating a secret, you can select the location as shown below.

![secret-manager](https://github.com/firebase/extensions/assets/54584597/bdeab575-d11e-430d-a058-cef93b355d77)

**Comment by marknesh** [comment]
Since you have location constraints, try creating a secret `firestore-send-email-SMTP_PASSWORD` and manually add the locations where you want the secrets to be stored. But they should match the locations in the Resource Location Restriction Policy for your organization.

**Comment by huangjeff5** [comment]
Yep that's the right idea. Note that you'll have to use the manifest workflow (adding an 'extensions' section to your firebase.json and running `firebase deploy` or `firebase deploy --only=extensions`). There isn't a way to customize the secret via Console installation.

**Comment by cabljac** [comment]
Seems like we should mention this in the documentation maybe, thanks @marknesh
