### ISSUE TITLE
🐛 [firestore-bigquery-export] path_params becomes null when imported.

### ISSUE THREAD

**Issue by RyosukeNishi** [firebase/extensions#1814]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **[firestore-bigquery-export]**
- Extension version: **0.1.36**
- Configuration values (redact info where appropriate):
<img width="646" alt="スクリーンショット 2023-11-21 13 02 30" src="https://github.com/firebase/extensions/assets/46443906/a1819fba-8438-40ec-95e5-b7ccf8da67ca">
<img width="646" alt="スクリーンショット 2023-11-21 13 03 42" src="https://github.com/firebase/extensions/assets/46443906/408c4f79-edca-4bf5-8727-ca376bca1cf8">

#### Steps to reproduce:
```
npx @firebaseextensions/fs-bq-import-collection \
  --non-interactive \
  --project $YOUR_PROJECT_NAME \
  --source-collection-path bookmarks \
  --query-collection-group true \
  --dataset firestore_export \
  --table-name-prefix bookmarks \
  --batch-size 300 \
  --dataset-location us \
  --multi-threaded true \
  --use-new-snapshot-query-syntax true \
  --use-emulator false
```

What happened? How can we make the problem occur?
This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.

- `path_params` becomes null.

##### Expected result
<img width="209" alt="スクリーンショット 2023-11-21 13 19 58" src="https://github.com/firebase/extensions/assets/46443906/88a75495-9747-42a1-98fd-3cb67f1d9098">

##### Actual result
<img width="205" alt="スクリーンショット 2023-11-21 13 20 04" src="https://github.com/firebase/extensions/assets/46443906/77f4089d-d551-4a51-924f-3fd3c44f3049">

**Comment by cabljac** [comment]
I think if you're using path_params you will need to specify them in the arguments of the import script, does the following work?

```
npx @firebaseextensions/fs-bq-import-collection \
  --non-interactive \
  --project $YOUR_PROJECT_NAME \
  --source-collection-path users/{user_id}/bookmarks \
  --query-collection-group true \
  --dataset firestore_export \
  --table-name-prefix bookmarks \
  --batch-size 300 \
  --dataset-location us \
  --multi-threaded true \
  --use-new-snapshot-query-syntax true \
  --use-emulator false
  ```

**Comment by waleed8y** [comment]
- [ ] - - [ ] uyyhyf@pavelgj

**Comment by RyosukeNishi** [comment]
@cabljac 
No, it didn't. I got this error.
```
Error importing Collection to BigQuery: Error: Invalid collectionId 'users/{user_id}/bookmarks'. Collection IDs must not contain '/'.
```

I also tried this,
```
fs-bq-import-collection \
  --non-interactive \
  --project develop-andpad-40 \
  --source-collection-path users/{user_id}/bookmarks \
  --query-collection-group false \
  --dataset firestore_export \
  --table-name-prefix bookmarks \
  --batch-size 300 \
  --dataset-location us \
  --multi-threaded true \
  --use-new-snapshot-query-syntax true \
  --use-emulator false
```

and got this error.
```
Error importing Collection to BigQuery: Error: You must provide at least 1 row to be inserted.
```

**Comment by RyosukeNishi** [comment]
@cabljac 
By the way, the version of npm package does not seem to be up to date ([ref](https://www.npmjs.com/package/@firebaseextensions/fs-bq-import-collection)).

**Comment by cabljac** [comment]
PR to bump deps in import script: https://github.com/firebase/extensions/pull/1822

**Comment by cabljac** [comment]
Hey @RyosukeNishi, there were a couple of issues with the import script which I've resolved, and published a new version. Let me know if this resolves the issue, thanks for your patience!

**Comment by RyosukeNishi** [comment]
@cabljac 
The issue is not resolved. 

Related issue: https://github.com/firebase/extensions/issues/1829

**Comment by RyosukeNishi** [comment]
@cabljac 
By the way, are you sure that `users/{user_id}/bookmarks` is a collection group query? Judging from the documents below, I suspect it's not .

https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/README.md
> Use Collection Group query: Do you want to use a [collection group](https://firebase.google.com/docs/firestore/query-data/queries#collection-group-query) query for importing existing documents? Warning: A collectionGroup query will target every collection in your Firestore project that matches the 'Existing documents collection'. For example, if you have 10,000 documents with a sub-collection named: landmarks, this will query every document in 10,000 landmarks collections.

https://firebase.google.com/docs/firestore/query-data/queries#collection-group-query
> The landmarks collection group consists of all collections with the ID landmarks, and you can query it using a collection group query. For example, this collection group query retrieves all museum landmarks across all cities:
```
...
 it := client.CollectionGroup("landmarks").Where("type", "==", "museum").Documents(ctx)
...
```

Any resources by which you confirmed that the representation `users/{user_id}/bookmarks` falls into the definition of a collection group query?

**Comment by RyosukeNishi** [comment]
I'm mentioning the things above because [you suggested](https://github.com/firebase/extensions/issues/1814#issuecomment-1820632913) that I set `--query-collection-group true`.

**Comment by cabljac** [comment]
yup you're right there, i was mixing up wildcards with path params with the import script. I have a fix going in soon for the backfill onInstall import

**Comment by cabljac** [comment]
OK so you're completely correct that e.g `users/{user_id}/bookmarks` is not a collection group query, however if you want `path_params` to be populated you have to provide a path with wildcard parameters. The extension will currently still perform a group query with the last segment of the path.
