### ISSUE TITLE
🐛 [firestore-bigquery-export] Firestore documents are not imported even if I answer "Yes" to the question "Import existing Firestore documents into BigQuery?"

### ISSUE THREAD

**Issue by RyosukeNishi** [firebase/extensions#1818]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-bigquery-export**
- Extension version: **0.1.37**
- Configuration values (redact info where appropriate):
<img width="644" alt="スクリーンショット 2023-11-22 16 20 59" src="https://github.com/firebase/extensions/assets/46443906/a91eb608-98e1-4794-966c-baaca0850186">
<img width="647" alt="スクリーンショット 2023-11-22 16 21 08" src="https://github.com/firebase/extensions/assets/46443906/de3470a8-0d9b-4470-ac6a-62cd5bf8e757">
<img width="642" alt="スクリーンショット 2023-11-22 16 21 21" src="https://github.com/firebase/extensions/assets/46443906/1c72d8a0-2529-4da8-be20-80972ab33574">

#### Steps to reproduce:
- Install the extension with the configuration parameters above.

What happened? How can we make the problem occur?
This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.

##### Expected result
- The existing Firestore documents are imported to BigQuery.

##### Actual result
- The existing Firestore documents are **NOT** imported to BigQuery.

**Comment by cabljac** [comment]
Thanks for raising this, looking into it now. Any relevant logs?

**Comment by angelcervera** [comment]
Hi @cabljac I'm able to import automatically when is a collection, but looks it's not working with collection groups.

**Comment by marcucio** [comment]
I'm on firebase/firestore-bigquery-export@0.1.43 and it does not ask me if I want to backfill documents when creating the extension in the firebase UI
