### ISSUE TITLE
sudo npx @firebaseextensions/fs-bq-import-collection doesn't work

### ISSUE THREAD

**Issue by mohamedaboelmagd** [firebase/extensions#182]
I tried to import collection without sudo too.

* Output `sudo npx @firebaseextensions/fs-bq-import-collection doesn't work`

`sudo npx @firebaseextensions/fs-bq-import-collection
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/.npm/_npx/4016/lib/node_modules/@firebaseextensions/fs-bq-import-collection/node_modules/grpc/build'
gyp ERR! System Linux 4.15.0-66-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/home/.npm/_npx/4016/lib/node_modules/@firebaseextensions/fs-bq-import-collection/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/.npm/_npx/4016/lib/node_modules/@firebaseextensions/fs-bq-import-collection/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /home/.npm/_npx/4016/lib/node_modules/@firebaseextensions/fs-bq-import-collection/node_modules/grpc
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/home/.npm/_npx/4016/lib/node_modules/@firebaseextensions/fs-bq-import-collection/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/.npm/_npx/4016/lib/node_modules/@firebaseextensions/fs-bq-import-collection/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/.npm/_npx/4016/lib/node_modules/@firebaseextensions/fs-bq-import-collection/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.15.0-66-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/.npm/_npx/4016/lib/node_modules/@firebaseextensions/fs-bq-import-collection/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/.npm/_npx/4016/lib/node_modules/@firebaseextensions/fs-bq-import-collection/node_modules/grpc
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok 
? What is your Firebase project ID? careerograph-e9963
? What is the path of the the Cloud Firestore Collection you would like to import from? (This may, or may not, be the same Collection for which you plan t
o mirror changes.) careerPaths
? What is the ID of the BigQuery dataset that you would like to use? (A dataset will be created if it doesn't already exist) firestore_export
? What is the identifying prefix of the BigQuery table that you would like to import to? (A table will be created if one doesn't already exist) careerPath
s
? How many documents should the import stream into BigQuery at once? 300
Importing data from Cloud Firestore Collection: careerPaths, to BigQuery Dataset: firestore_export, Table: careerPaths_raw_changelog
Error importing Collection to BigQuery: Error: Cannot find module '@google-cloud/firestore'`

* Output `npx @firebaseextensions/fs-bq-import-collection doesn't work`

`npx @firebaseextensions/fs-bq-import-collection
? What is your Firebase project ID? careerograph-e9963
? What is the path of the the Cloud Firestore Collection you would like to import from? (This may, or may not, be the same Collection for which you plan t
o mirror changes.) domains
? What is the ID of the BigQuery dataset that you would like to use? (A dataset will be created if it doesn't already exist) firestore_export
? What is the identifying prefix of the BigQuery table that you would like to import to? (A table will be created if one doesn't already exist) domains
? How many documents should the import stream into BigQuery at once? 300
Importing data from Cloud Firestore Collection: domains, to BigQuery Dataset: firestore_export, Table: domains_raw_changelog
Error importing Collection to BigQuery: Error: EACCES: permission denied, open '/home/.config/gcloud/application_default_credentials.json'`

I have run `sudo gcloud auth application-default login` to auth user

**Comment by Ehesp** [comment]
@mohamedaboelmagd try running this command without the `sudo` part. At a guess, I think the `/home/.config` directory has your user permissions.

**Comment by mohamedaboelmagd** [comment]
> @mohamedaboelmagd try running this command without the `sudo` part. At a guess, I think the `/home/.config` directory has your user permissions.

Importing data from Cloud Firestore Collection: domains, to BigQuery Dataset: firestore_export, Table: domains_raw_changelog
Error importing Collection to BigQuery: Error: EACCES: permission denied, open '/home/mohamed/.config/gcloud/application_default_credentials.json'

This file is empty

**Comment by mohamedaboelmagd** [comment]
I solve it by 
> sudo npm i -g @firebaseextensions/fs-bq-import-collection
> sudo fs-bq-import-collection
