### ISSUE TITLE
🐛 [firestore-bigquery-export] Upgrades clears existing BQ table, import existing documents (via extension) does not work

### ISSUE THREAD

**Issue by djfinnoy** [firebase/extensions#1827]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-bigquery-export**
- Extension version: **0.1.37**
- Configuration values (redact info where appropriate):
  - **collection path: users/{user_id}/cards**
  - **import existing: yes**
  - **everything else is default**

### [REQUIRED] Step 3: Describe the problem
I have encountered two issues:

I was prompted to update to `v0.1.37`. After doing so, I discovered that the destination BigQuery table had been emptied of previous data.

Originally I imported the data via the CLI. However, I set up a new instance of the extension for a different collection today, and noticed that the `Import existing: yes` option had appeared in the UI. I selected `yes`, but unfortunately the newly created BQ table is not getting populated.

#### Steps to reproduce:
Update the extension for a collection that has previously been exported to BQ, notice that the BQ table is emptied after updating.

Create a new export for some subcollection that exists across multiple instances of a collection, eg `something/{id}/something`.
Select `import existing: yes`.
Notice that the newly created BQ table is empty.

##### Expected result
Newly created BQ tables should be populated when `import existing: yes`.
Updating the extension should not cause data loss.

##### Actual result
The opposite of the expected results

**Comment by cabljac** [comment]
Thanks for raising this, we've had some issues with 0.1.37, and 0.1.38 should be available very soon, having just been published.

**Comment by cabljac** [comment]
In the latest version of the extension, we have rolled back the built-in onInstall backfill feature, until we can be sure it doesn't cause additional issues. This should resolve the issue. Closing this, if the issue persists in the latest version of the extension then I am happy to reopen.
