### ISSUE TITLE
🐛 [firestore-bigquery-export] fs-bq-import-collection converts date

### ISSUE THREAD

**Issue by Bytamine** [firebase/extensions#1828]
Hello,
I'm not sure if it's a bug, but this is definitely not expected behavior.
We have a date field in firestore documents that looks like this
```"timestamp":{"_seconds":1658938338,"_nanoseconds":149000000}```
firestore-bigquery-export extension works fine, it exports the document as is, timestamp field is unchanged in BigQuery.

But fs-bq-import-collection script for some reason converts the date during the import to this format
```"timestamp":"2022-07-27T16:12:18.149Z"```

I can probably convert it in BigQuery after the import, but still, not what I expected to see.

**Comment by lblwsam** [comment]
@dackers86 Would you be able to know anything about this bug?

**Comment by cabljac** [comment]
I know why this is happening, The import script has always been serialising the data and then recording it in BQ. Recently we fixed an issue with the change-tracker package (that both the import script and the extension rely on), because timestamps were unable to be deserialised (and as just an object rather than a date, were unable to used as a partition type in BQ).

What version of the extension firestore-bigquery-export are you using which keeps it the same, may i ask?

**Comment by Bytamine** [comment]
@cabljac 0.1.36

**Comment by cabljac** [comment]
Yeah, the reason they're converted to dates is so that bigquery can use them as a partition field. We can potentially look at an alternative solution if this causes a big problem

**Comment by cabljac** [comment]
I think perhaps the better solution, if timestamps are expected to be stored in their object form within the data, is not to serialise them differently, and just directly deserialize after we've extracted them as the partition column value.

**Comment by Bytamine** [comment]
It's kind of a breaking change. If we have some extensions older than 0.1.37, they will continue working without serialization, and newly added ones will serialize timestamps. So to make the data consistent we'll have to update all extensions to latest version.

**Comment by cabljac** [comment]
Hi there @Bytamine,   @lblwsam We're retracting this breaking change in a new version, which should be published at some point today, here's the release PR: https://github.com/firebase/extensions/pull/1835
