### ISSUE TITLE
[firestore-bigquery-export] Add an option to run the import script on multi threads when you install the extension.

### ISSUE THREAD

**Issue by RyosukeNishi** [firebase/extensions#1831]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **firestore-bigquery-export**

### What feature would you like to see?

Describe the feature you would like to add, or how you'd like to see the extension change.

Add an option to run the import script on multi threads when you install the extension.
<img width="468" alt="スクリーンショット 2023-11-24 19 36 57" src="https://github.com/firebase/extensions/assets/46443906/93eb1164-0d28-4af2-baf4-5acc4805bf3d">

### How would you use it?
Currently, we cannot run the import script on multi threads if we set DO_BACKFILL to true when installing the extension.
DO_BACKFILL option would be more usable if we could run the script on multi threads.

**Comment by cabljac** [comment]
From my understanding, the `npx` import script has the capability for multiple threads, which speeds up importing when performing the import locally.

The new backfill feature works by queuing sequential tasks, would there be a significant benefit in having each task start multiple threads?

**Comment by RyosukeNishi** [comment]
@cabljac 
Thank you for giving me supplementary information.
> The new backfill feature works by queuing sequential tasks

I didn't know that. Now I agree with you that running each task on multiple threads does not have so much benefit.

By the way, are the queued tasks proccessed in a strictlysequential way, or are they somehow proccessed concurrently? For example, A FIFO Queue in AWS SQS behaves like literally a queue, which means a task never runs before its precedence completes. A Standard Queue, on the other hand, allows tasks to run concurrently. I suppose that a concurrency mechancis like AWS Standard Queue would be beneficial if it doesn't exist at the moment.

**Comment by cabljac** [comment]
Currently just in a sequential way. Cloud tasks would support concurrent processing. The main reason things are done sequentially (as far as I understand) is that we want to know when to update the processing state for the extension. We could use a firestore field to track the number of tasks completed, though with concurrent tasks we would have to take care not to hit the rate limit for writes to a firestore field. We do something like this with `firestore-counter` actually, sharding the count.

I've thought about this before, and have a solution in mind for managed concurrent threads of tasks more generally, which i might put together into an npm package when i have more free time btw

I'm going to close this feature request for now, we could perhaps reopen as a discussion, or if i put together that package I can let you know! :) Thanks
