### ISSUE TITLE
🐛 [firestore-bigquery-export] On-install backfill option does not appear in the config page.

### ISSUE THREAD

**Issue by RyosukeNishi** [firebase/extensions#1850]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-bigquery-export**
- Extension version: **0.1.41**
- Configuration values (redact info where appropriate):
  - Everything set default.

#### Steps to reproduce:

Try to install the extension from console.

##### Expected result
Backfill option appears.

##### Actual result
It does not.

**Comment by cabljac** [comment]
Hi, we've rolled this feature back until we can be sure it all works correctly, it was causing too many issues. We will look to re-release it soon.

**Comment by ViniciusSossela** [comment]
any news on this?

**Comment by marcucio** [comment]
not sure why this is closed, it is still an issue

**Comment by pr-Mais** [comment]
This is being tracked on #1890.
