### ISSUE TITLE
🐛 [firestore-bigquery-export] Access Denied: BQ Project:Dataset Name: Permission bigquery.datasets.get denied on dataset BQ Project:Dataset Name: (or it may not exist).

### ISSUE THREAD

**Issue by Hunnainwali** [firebase/extensions#1861]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-bigquery-export** 
- Extension version: **0.1.41** 

Cross project connection between Firestore and BigQuery with below configuration settings. 

<img width="703" alt="Screenshot 2023-11-30 at 2 06 29 PM" src="https://github.com/firebase/extensions/assets/64936324/e16c285d-4d62-49f5-b29b-36cc9c8a16b4">

#### Steps to reproduce:

I attempted to establish a cross-project connection between Firestore and BigQuery.

After installation, contrary to expectations, no dataset was created. The Error Logs in the Firestore collection indicated "Not found: Dataset..."

For another instance, instead of defining a new dataset, I used the same dataset and location region that already existed in BigQuery. However, the Error Logs in the Firestore collection now state "Access Denied: Dataset Project_Name:Dataset_Name: Permission bigquery.datasets.get denied on dataset Project_Name:Dataset_Name (or it may not exist)."

##### Expected result

I have two different project in google cloud, one for Firestore and other for BigQuery, but extension is not creating any dataset or table, nor able to access existing dataset in BigQuery. 

Note: 
Permission for
**Dataset shows**
BigQuery Data Owner -> firebase-measurement@system.gserviceaccount.com has BigQuery
**Google Project**
IAM -> BigQuery Data Owner/Editor

##### Actual result

No dataset and table is being created. And Firestore logs produce error that either dataset does not exist or don't have permission to access.

**Comment by jauntybrain** [comment]
Hi @Hunnainwali, thanks for providing a detailed issue report!

I see you specified that [firebase-measurement@system.gserviceaccount.com](mailto:firebase-measurement@system.gserviceaccount.com) has the BigQuery `dataEditor` role. 

However, as per [documentation](https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/POSTINSTALL.md#configuring-alternative-bigquery-project), you need to grant the `dataEditor` role in the BigQuery project IAM to the following service account:

`ext-${param:EXT_INSTANCE_ID}@${param:PROJECT_ID}.iam.gserviceaccount.com`

**Comment by pr-Mais** [comment]
Feel free to open a new issue if the issue persists after following @jauntybrain comment.
