### ISSUE TITLE
🐛 [firestore-bigquery-export] Import existing firestore documents into big query not available in the options

### ISSUE THREAD

**Issue by EmilioNicolas** [firebase/extensions#1881]
### Describe your configuration

- Extension name@version:  (`firebase/firestore-bigquery-export@0.1.42`)

### Describe the problem

The option that I expect to be in my configuration is not available and I cannot find it in the config process. Isn't it available anymore?

I have already my Firestore collection full of documents and I want them to be imported. Otherwise, I cannot use the extension.

[screenshot.pdf](https://github.com/firebase/extensions/files/13559408/screenshot.pdf)

**Comment by cabljac** [comment]
Hi there, this feature was included in a recent version of the extension and then rolled back, as there were a few breaking changes/issues that needed to be addressed. For now you can use the npx import script to import existing documents.

Closing for now as we are already tracking the re-release of the lifecycle import
