### ISSUE TITLE
🐛 [firestore-bigquery-export] Fails to install

### ISSUE THREAD

**Issue by hffmnn** [firebase/extensions#1882]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-bigquery-export**
- Extension version: **0.1.43**
- Configuration values (redact info where appropriate):
 ```
BigQuery Dataset location
  eu
Project Id
  <redacted>
Collection path
  some/{valid}/path/{to}/something
Enable Wildcard Column field with Parent Firestore Document IDs (Optional)
  true
Dataset ID
  firestore_export_eu
Table ID
  sequence_revision
BigQuery SQL table Time Partitioning option type (Optional)
  NONE
BigQuery Time Partitioning column name (Optional)
 Parameter not set
Firestore Document field name for BigQuery SQL Time Partitioning field option (Optional)
  Parameter not set
BigQuery SQL Time Partitioning table schema field(column) type (Optional)
  omit
BigQuery SQL table clustering (Optional)
  Parameter not set
Maximum number of synced documents per second (Optional)
  Parameter not set
Backup Collection Name (Optional)
  Parameter not set
Transform function URL (Optional)
  Parameter not set
Use new query syntax for snapshots
  yes
Cloud KMS key name (Optional)
Parameter not set
```

### [REQUIRED] Step 3: Describe the problem

When trying to install the extension into our firebase project it fails. The corresponding logs look like this:
<img width="618" alt="Screenshot 2023-12-05 at 20 42 20" src="https://github.com/firebase/extensions/assets/352753/2da39193-d7cd-4f0c-9109-62b229c119d6">

The failing build step looks like this:

```
{
  insertId: "some id"
  labels: {2}
  logName: "projects/<redacted>/logs/cloudbuild"
  receiveTimestamp: "2023-12-05T19:28:13.719147855Z"
  resource: {2}
  severity: "INFO"
  textPayload: "Step #2 - "build": ERROR: failed to initialize analyzer: validating registry write access: ensure registry read/write access to europe-west3-docker.pkg.dev/<redacted>/gcf-artifacts/ext--firestore--bigquery--export--t21i--seq--rev--curr--setup_big_query_sy/cache:latest"
  timestamp: "2023-12-05T19:28:13.453794820Z"
}
```
#### Steps to reproduce:

- Got an info that the Artifact Respository needs to be enabled for this project, so I pressed the enable button
- Filled in the above configuration values

##### Expected result

- Installation runs through.

##### Actual result

- Installation fails.

---
Any idea what might be wrong?

**Comment by cabljac** [comment]
Thanks, i'll try and reproduce this now

**Comment by huangjeff5** [comment]
Are you using a service account to deploy? If so, can you share the service account and what roles it has?

**Comment by hffmnn** [comment]
Oookay. So I uninstalled and reinstalled. And it worked without any problem.

Maybe a hickup or timing problem between creating the artifact in the repository and accesssing it in cloud build?
