### ISSUE TITLE
🐛 [storage-resize-images] No longer maintaining aspect ratio

### ISSUE THREAD

**Issue by alibeniaminali** [firebase/extensions#1889]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** (`storage-resize-images`)
- Extension version: **\_**(`0.2.2`)
- Configuration values (redact info where appropriate):
  - **\_**
  - Cloud Functions location
     europe-west2
  - Cloud Storage bucket for images
     southern-digisuite.appspot.com
  - Sizes of resized images
     1503x902
  - Deletion of original file
     true
  -  Make resized images public (Optional)
      true
  -  Cloud Storage path for resized images (Optional)
     Parameter not set
  -  Paths that contain images you want to resize (Optional)
     /digisuites/*/properties/*/floorplan
  -  List of absolute paths not included for resized images (Optional)
     Parameter not set
  -  Cloud Storage path for failed images (Optional)
      Parameter not set
  -  Cache-Control header for resized images (Optional)
      Parameter not set
  -  Convert image to preferred types
      false
  -  Output options for selected formats (Optional)
      Parameter not set
  -  Sharp constructor options for resizing images (Optional)
     Parameter not set
  -  GIF and WEBP animated option (Optional)
      false
  -  Cloud Function memory
     1024
  -  Backfill existing images
     false
  - **\_**

#### Steps to reproduce:

- What happened? 
   -  We have several firebase projects that all use the image resizing tool, all the projects have the exact same configurations but have different versions of the resizing tool extension. On our latest project we have noticed that the newer version of the resizing tool is not maintaining the aspect ratio of the original images uploaded.  We are uploading images that are 1000x1000 pixels. On our latest projects the images are converted to 1000x902 and on the previous projects the same images are converted to 902x902 as we are expecting.

##### Expected result
Images resized 902x902
##### Actual result
Images resized 1000x902

**Comment by Negativchik** [comment]
Hi! It seems that the default behavior was changed in this commit:
https://github.com/firebase/extensions/commit/9653f60cdec0f5dadeae3282ec86e153ad715378
To work around this issue, you need to modify the config by adding
{"fit":"inside"}
in the "Sharp constructor options for resizing images" field.

**Comment by alibeniaminali** [comment]
@Negativchik Brilliant, that fixed the issue. Thanks a lot for your help! 
I wasn't able to find the update in the documentation, perhaps was a recent change.

**Comment by th0rgall** [comment]
For future reference, ` {"fit":"inside"}` is now part of the default Sharp options since v2.0.7, see issue #2106, PR https://github.com/firebase/extensions/pull/2115 and the [changelog entry](https://github.com/firebase/extensions/blob/797d012813e9277216cd540aafa3372ef76ab6ca/storage-resize-images/CHANGELOG.md#version-027) for v2.0.7.
