### ISSUE TITLE
🐛 [firestore-bigquery-export] No option for importing old data when setting up extention

### ISSUE THREAD

**Issue by marcucio** [firebase/extensions#1890]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: firebase/firestore-bigquery-export@0.1.43
- Extension version: 0.1.43
- Configuration values (redact info where appropriate):
Happens with default configuration

### [REQUIRED] Step 3: Describe the problem
There is no 
option to import existing documents when setting up the extention

![Screenshot 2023-12-21 110738](https://github.com/firebase/extensions/assets/919902/a68d79c5-8eaa-4d9e-a525-1c2f28458c26)
![Screenshot 2023-12-21 110752](https://github.com/firebase/extensions/assets/919902/88efc717-37fc-4fe9-929a-5f79ce81cd4a)

#### Steps to reproduce:

go to the extensions page in firebase console, install the bigquery extension

##### Expected result
To see be asked to import old data

##### Actual result
No option to import old data

**Comment by Naihell** [comment]
They removed this function on v0.1.41 release (fix - rollback backfill feature)

**Comment by pr-Mais** [comment]
Related https://github.com/firebase/extensions/issues/1850#issuecomment-1829560294

**Comment by ViniciusSossela** [comment]
any news?
