### ISSUE TITLE
[BUG] Mail not synced to MailChimp after linking email credentials 

### ISSUE THREAD

**Issue by kristijandraca** [firebase/extensions#19]
### [READ] Step 1: Are you in the right place?

Yes.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: auth-mailchimp-sync

#### Steps to reproduce:

1. Create anonymous user
2. Link email credential to that user

##### Expected result

An email address from email credential should sync to MailChimp.

##### Actual result

Did not sync.

**Comment by Ehesp** [comment]
Currently the function only runs on user create, rather than an update. Will have to check whether this is possible via triggers.

**Comment by Ehesp** [comment]
Unfortunately this isn't possible at the moment, as the `UserBuilder` for functions only provides `onCreate` and `onDelete` handlers: https://firebase.google.com/docs/reference/functions/functions.auth.UserBuilder

**Comment by kristijandraca** [comment]
Ok, but this leaves this plugin pretty much unusable since it won't update email on linking credential, and another big situation, is when the user decides to change his email.

**Comment by rphlmr** [comment]
In case we store user profiles in a collection (name, mail, uid), is it possible to imagine an option for the "update" trigger of this extension ?

**Comment by Ehesp** [comment]
Let me bring this one up with the team. Generally it would be a totally different extension if it triggered on collection change. Here's something which *may* work:

1. Auth user create: Updates Mailchimp + creates a record in a collection, with an email.
2. If a users email changes (via manual update on the users part), this automatically removes the email and updates Mailchimp with the new one.

This does however totally change the flow so it'll need some discussion. Thanks!

**Comment by karayu** [comment]
Thanks so much for the feature request! It sounds like this would need to be a new extension. 

Do you mind filing a feature request for this so we can track it? 
https://firebase.google.com/support/troubleshooter/report/features/

I'm closing this issue for now since it's unfortunately not a change to the current extension.
