### ISSUE TITLE
🐛 [storage-resize-images]  error resizing some images

### ISSUE THREAD

**Issue by jasan-s** [firebase/extensions#1904]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **storage-resize-images**
- Extension version: **@0.2.2**
- Configuration values (redact info where appropriate):
  - **Convert image to preferred types: webp, avif**

### [REQUIRED] Step 3: Describe the problem

getting the following error:
> Error when resizing image [Error: /tmp/xxxxxxxxx-xxxxxx-xxxxx-xxxxx-xxxxxxxxxxxxxxxx: bad seek to 131992
heif: Invalid input: Unspecified: Bitstream not supported by this decoder (2.0)

#### Steps to reproduce:
try resizing the following image to .avif and .webp
![wTzGeycid4g12zHqns8c](https://github.com/firebase/extensions/assets/13863953/64662f3b-9edc-4cc7-b874-6c19c46618f4)

What happened? How can we make the problem occur?
This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.

**Comment by pr-Mais** [comment]
This image is `avif` per its metadata, I was able to reproduce the error.
```
$ heif-info -d 294454783-64662f3b-9edc-4cc7-b874-6c19c46618f4.png   

MIME type: image/avif
main brand: avif
compatible brands: mif1, miaf
Box: ftyp -----
size: 24   (header size: 8)
major brand: avif
minor version: 0
compatible brands: mif1,miaf
```
The metadata shows it's a 10-bit avif, which is not supported in Sharp, see the comment https://github.com/lovell/sharp/issues/2688#issuecomment-830863196
```
heif-info -d 294454783-64662f3b-9edc-4cc7-b874-6c19c46618f4.png | grep bit
| | | high_bitdepth: 1
| | | twelve_bit: 0
| | | bits_per_channel: 10,10,10
```
I will close this as not supported.
