### ISSUE TITLE
[firestore-counter] Use handler namespace for all exported functions

### ISSUE THREAD

**Issue by joehan** [firebase/extensions#191]
Describe your configuration

- Extension name: firestore-counter
- Extension version: any
### [REQUIRED] Step 3: Describe the problem
We currently define some exported functions using the normal functions namespace instead of the handlers (ie https://github.com/firebase/extensions/blob/next/firestore-counter/functions/src/index.ts#L77). This is misleading - any triggers declared within the code will be ignored in favor of those in extension.yaml. We should switch these to use the handler namespace.

No rush on this since it doesn't break anything, it just makes the code less readable.

**Comment by russellwheatley** [comment]
Hi @joehan, apologies, I'm not quite sure what you're asking 😅. The exported function names match the `resource.name` in the `extension.yaml` file. Could you please elaborate what you want to change the names to?

**Comment by russellwheatley** [comment]
cc @jeohan friendly ping

**Comment by laurenzlong** [comment]
What Joe means is that

```
export const worker = functions.firestore
  .document(
    process.env.INTERNAL_STATE_PATH + WORKERS_COLLECTION_ID + "/{workerId}"
  )
  .onWrite(...)
```
should be:
```
export const worker = functions.handlers.firestore.document
  .onWrite(...)
```
Same applies for the other functions in this extension. Could you please make a PR to address this?
