### ISSUE TITLE
[firestore-translate-text] add shouldUpdate option to config

### ISSUE THREAD

**Issue by balazsorban44** [firebase/extensions#194]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **\_** `firestore-translate-text`

### What feature would you like to see?

I propose adding a configuration option to be able to decide if an update on the input should be propagated to the translations after creation.

It is a nice feature keeping translations in sync with the original text, in case it is not an issue that the text was machine-translated.

In other situations, I believe it is hardly the case the translated text is good enough to be published immediately. Therefore, I suggest that when creating the translation, translate the text as before, but on subsequent changes, update the translations only if the new `config.shouldUpdate` option is set to `true`. This could default to `true`, so current flows should not break.

Added a PR(#195) myself for review.
### How would you use it?

I develop a multi-language website, where the content on the main page is saved in Firestore, and there exists an Admin dashboard from where those texts can be edited. I would like to be nice with the admin and suggest him translations when he creates the texts. But if he decides to do small modifications to the original text, right now it would result in changing every other language texts as well (which he probably had to tinker). This is only my use case though, I can imagine there are others who would benefit from an "only recommend the first time translation".

**Comment by karayu** [comment]
Thanks for the feedback Balázs! Thank you as well for using Firebase Extensions. We really appreciate that you made a feature request to solve this issue. 

The team discussed this new feature at length and unfortunately we decided that it might be a confusing experience for some users. It sounds like with this implementation, the original text and the translations might fall out of sync, which might be confusing for other users. Could we suggest having your translator still use the automatic translations as a guide but input their own translations else where? This way, you could keep the machine translation and manual translations both. 

I'm going to close this issue and feature request for now but if we see more use cases like yours, we can reconsider. 

Thanks again for using Firebase Extensions!
