### ISSUE TITLE
🐛 [STORAGE_RESIZE_IMAGES] Images resized do NOT maintain aspect ratio

### ISSUE THREAD

**Issue by alexdhill** [firebase/extensions#1941]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: storage-resize-images
- Extension version: 0.2.2
- Configuration values (redact info where appropriate):
  - Cloud Storage Bucket: default
  - Sizes of Resized Images: 1080x720,1920x1080
  - Deletion of Original File: Delete on any resize attempt
  - Convert Image to Preferred Types: webp
  - Cloud Function Mem: 1GB

#### Steps to reproduce:

 1. Install Resize Images [firebase/storage-resize-images@0.2.2] and set the resize dimensions to "1080x720"
 2. Upload an image to storage that is greater in size (in both dimensions) that the specified resize amount, and with a different aspect ratio: I used a 5000x2500 (WxH) jpeg

##### Expected result

A resized .webp of size 1080x540

##### Actual result

A resized .webp of size 1080x720

##### Extra Comments

I have tried this with an extreme case as well, setting the resize to dimensions to 720x10000 so that an image of size 5000x2500 *should* be resized to about 720x360, instead it creates a new image of size 720x2500.

**Comment by pr-Mais** [comment]
Check this issue https://github.com/firebase/extensions/issues/1889#issuecomment-1864603042
Update your configurations field `Sharp constructor options for resizing images` to have the desired fit, e.g.:
```
{ "fit": "inside" }
```

**Comment by alexdhill** [comment]
This works, is there a way to mark this as needs documentation or?
