### ISSUE TITLE
Cannot read property 'fields' is undefined when running fs-bq-schema-views

### ISSUE THREAD

**Issue by Tovock** [firebase/extensions#196]
Updated all schema views without issue, but when checking data noticed on field was null, reviewed and noticed the mistake in the json. Corrected and attempted to run the script again. It will do the changelog fine, but after it finishes and moves to do latest it displays "Cannot read property 'fields' is undefined ". Also after the failure to check ran again using the previous json that worked fine before and get the same results with the changelog being correct and it failing on the latest.

**Comment by tptshoe** [comment]
I'm experiencing the same issue. Here's the tail end of the console output I see:
```
BigQuery created schema view ClientOrders_schema_ClientOrders_changelog

{}
Cannot read property 'fields' of undefined
```

**Comment by Ehesp** [comment]
Hi @Tovock - please could you follow the issue template. Your version / config setup would be great too, so we can help debug.

**Comment by asikand** [comment]
This is also happening to me. 

We are using firestore-bigquery-export to send data from a Firestore collection to BigQuery. The file `raw_changelog` and `raw_latest` files are fine but I am now unable to update `schema` table that is generated. I run the query that is generated by the fs-bq-schema-views extension and it does not update the 'schema' table with the most recent data. 

I thought I will run `npx @firebaseextensions/fs-bq-schema-views` to regenerate it but I get the same error as @tptshoe when I try to run it.

**Comment by asikand** [comment]
We are using this data in production so if anyone could take a look at this issue for us we would greatly appreciate it.

**Comment by caesarivs** [comment]
I'm having the same issue as well, I created a schema.json file according to [the guide](https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md) and ran the script specifying that one schema.json file.

The script created the schema_changelog table correctly, but then, apparently, it tried to create the schema_latest from an empty json:

```
BigQuery created schema view schema_changelog

{}
Cannot read property 'fields' of undefined
```

If I try to run the script again I get an error saying the Routine "firestoreArray" already exists on my dataset, so I have to manually delete all persistent functions created by the script on my dataset before trying again

**Comment by Ewarrender** [comment]
Same problem here. The 'changelog' schema view is created but the 'latest' schema view isn't.

```
...
BigQuery created schema view accounts_schema_typed_changelog

{}
Cannot read property 'fields' of undefined
```

**Comment by Ewarrender** [comment]
Got it working by doing the following:

1) Clone https://github.com/joaqcid/extensions.git and checkout the **run-manual-import** branch
2) cd extensions/firestore-bigquery-export/firestore-bigquery-change-tracker
3) npm i
4) cd ../scripts/gen-schema-view/
5) npm i
6) npm run gen-schema-views

Ignored errors and everything worked.

```
BigQuery created view accounts_schema_typed_latest
done.
```

**Comment by stari4ek** [comment]
https://github.com/joaqcid/extensions.git is a bit out of date.
original `next` branch can be used with next changes applied:
* merge https://github.com/firebase/extensions/pull/257
* switch to local setup, as described in https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/DEVSETUP.md with `gen-schema-view` added to the list.

Here is the branch with those steps applied and workaround for https://github.com/firebase/extensions/issues/247: https://github.com/stari4ek/extensions/tree/next-devsetup
