### ISSUE TITLE
[FR] Make Translate Text even cooler! 

### ISSUE THREAD

**Issue by karayu** [firebase/extensions#2]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Extension name

This feature request is for extension: firestore-translate-text 

### What feature would you like to see?
I want Translate Text to get its own mascot! Perhaps an olympics bear? 

### How would you use it?

I would make stickers out of the new mascot.

**Comment by laurenzlong** [comment]
Closing this, I'm assuming this is a test issue. Although Olympic bear stickers would be cool...
