### ISSUE TITLE
[BUG] name of resized image is missing original image name if there was no file type extension

### ISSUE THREAD

**Issue by emrebicer** [firebase/extensions#20]
### [READ] Step 1: Are you in the right place?
Yes
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** (`storage-resize-images`)
- Configuration values (redact info where appropriate):
  -Size:64x64
  -Cloud Storage Path: empty
### [REQUIRED] Step 3: Describe the problem
I just added storage-resize-images extension to my firebase project, it is working as expected when i upload an image manually from the firebase console, but the problem is that whenever i use 

```terminal
storageRef.putString()
```
function to upload base64 url encoded image to the firebase storage cloud, the compressed image will be created but its name is only _64x64 (not original_64x64).

Obviously i am resizing images as 64x64.

Since the created file doesn't contain a unique name it is unaccessible for me dynamically...Is there something am i missing?

#### Steps to reproduce:
Install storage-resize-images extension to my firebase project.(web)
##### Expected result
storage-resize-images extension to create an image file using the "original.jpeg" image as "original_64x64.jpeg"
##### Actual result
The extension generated the image as expected but the naming was wrong, it is _64x64.jpeg instead of original_64x64.jpeg

**Comment by Salakar** [comment]
Hey @emrebicer thanks for reporting this issue, will get this looked at.

**Comment by Salakar** [comment]
You can set a file extension when using `putString` by  specifying a the file name when creating a storage reference:

```js
const imageStorageRef = firebase.storage().ref('images/space.jpg');
// ...
imageStorageRef.putString(/* ... */) // ..
```

Is there some other case where it would never set a file extension?

**Comment by emrebicer** [comment]
Looks like 

> You can set a file extension when using `putString` by specifying a the file name when creating a storage reference:
> 
> ```js
> const imageStorageRef = firebase.storage().ref('images/space.jpg');
> // ...
> imageStorageRef.putString(/* ... */) // ..
> ```
> 
> Is there some other case where it would never set a file extension?

After adding ".jpg" at the end of my file names the problem went away. It looks like a proper solution for me. Closing the issue, thank you :).

**Comment by christophe-g** [comment]
Still experiencing this when an uploaded file does not have an extension.

I am aware that I can check whether filename has an extension before uploading, but IMO the resize image extension should be able to handle case without file extension. 

Can this be re-opened ?

![image](https://user-images.githubusercontent.com/1168053/70697580-133ba600-1cc6-11ea-807e-89a6d5cc5e8f.png)

**Comment by laurenzlong** [comment]
@Salakar We should support file names without file type extensions. Can you work on a PR to fix this?

**Comment by laurenzlong** [comment]
Actually I see it's fixed in https://github.com/firebase/extensions/pull/134 :)
