### ISSUE TITLE
🐛 [firestore-send-email] The `delivery.info` entry is missing after upgrading to 0.1.32.

### ISSUE THREAD

**Issue by KoheiKanagu** [firebase/extensions#2004]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-send-email**
- Extension version: **0.1.32**
- Configuration values (redact info where appropriate):
  - **DEFAULT_FROM=kingu.dev <support@kingu.dev>**
  - **DEFAULT_REPLY_TO=support@kingu.dev**
  - **MAIL_COLLECTION=mails_v1**
  - **SMTP_CONNECTION_URI=smtps://apikey@smtp.sendgrid.net:465**
  - **SMTP_PASSWORD=projects/${param:PROJECT_NUMBER}/secrets/firestore-send-email-SMTP_PASSWORD/versions/latest**
  - **TEMPLATES_COLLECTION=mailTemplates_v1**
  - **TTL_EXPIRE_TYPE=never**
  - **TTL_EXPIRE_VALUE=1**

### [REQUIRED] Step 3: Describe the problem

After upgrading to 0.1.32, `delivery.info.accepted`, `delivery.info.messageId`, `delivery.info..response` is missing.

#### Steps to reproduce:

1. Upgraded to 0.1.32

##### Expected result

`delivery.info` should not be missing.

##### Actual result

v0.1.31
![スクリーンショット 2024-03-26 16 06 18](https://github.com/firebase/extensions/assets/6175794/006d7941-658d-41f8-9fc5-493d89072107)

v0.1.32
![スクリーンショット 2024-03-26 16 06 42](https://github.com/firebase/extensions/assets/6175794/de790dab-7930-4b9c-b5ff-998cdd40b3e6)

**Comment by pr-Mais** [comment]
I can reproduce, looking into it.

**Comment by Aconcagua-CTO** [comment]
Hi guys, not sure if this is related.  I upgraded from 0.1.29 to 0.1.32 yesterday, and my mails are failing with 
"Error: String expected for `text`"
![image](https://github.com/firebase/extensions/assets/115178814/91a9257a-06e5-46ab-9f64-cf34db26b8b6)

I send my messages using html, and always kept text: null. 
This was working on 0.1.29, but not on 0.1.32. 

I'll keep testing on my side and let you know if I find anything else. 

Regards

**Comment by pr-Mais** [comment]
@Aconcagua-CTO are you using sendgrid?

**Comment by Aconcagua-CTO** [comment]
Yes

**Comment by pr-Mais** [comment]
Tried with the following and it was sent successfully (using SendGrid)

![Screenshot 2024-03-26 at 5 44 21 PM](https://github.com/firebase/extensions/assets/41123719/2c4009ab-4fb3-4a95-838c-2f6c8d223ab2)

**Comment by Aconcagua-CTO** [comment]
In my case, I'm using _emailTemplates_ collection to populate my emails. 
I just confirmed that the template now needs non-empty _text_ field to work. 
On production, extension is 0.1.29 and _text_ field is not in the emailTemplate collection. 
On 0.1.32 I tested with a null text field
![image](https://github.com/firebase/extensions/assets/115178814/bca3d5d1-9016-4351-af5e-0222a1b59615)
 It failed
Tested an empty string and it failed
![image](https://github.com/firebase/extensions/assets/115178814/c9e4020d-b285-425b-9895-5db718733a85)

Now I'm testing a single space and it's working again
![image](https://github.com/firebase/extensions/assets/115178814/c6f0d1f5-d80c-4151-889c-dd8a8eb9823a)

Seems we have separate issues :D

**Comment by pr-Mais** [comment]
@Aconcagua-CTO interesting, might also be related to the last update to SendGrid, checking now.

**Comment by pr-Mais** [comment]
@Aconcagua-CTO I faced some issues using the templates collection as well, mostly caused by the new SendGrid transporter. We can get back the old transporter which appears to use SendGrid v2, but this will remove the support for Dynamic Templates. Thinking of introducing a new param for users who would like to use v3.

**Comment by Aconcagua-CTO** [comment]
Sorry to hear that.
I'm fine with my workaround for now.  I don't use sendgrid templates.
And the space in the text field shouldnt cause problems if you revert the
change.

New param sounds good.

Regards

**Comment by belwalravi** [comment]
Hi,
I am also facing a similar kind of issue, after upgrading to the latest version of the extension I am not able to send mails, while using collection templates. Can someone assist with this?

<img width="481" alt="Screenshot 2024-04-04 at 6 34 01 PM" src="https://github.com/firebase/extensions/assets/129403751/f08d4b73-f3f3-4eb3-9c8a-127fee54204c">

**Comment by Aconcagua-CTO** [comment]
Hi @belwalravi did you try adding a field "text" with a single space?  Look at my past message.

**Comment by belwalravi** [comment]
Yes @Aconcagua-CTO I read those comments.  Could be please let me know how will the object be looking in my case with text. I mean where should I place this text.

**Comment by Aconcagua-CTO** [comment]
In my case I'm using it on the _emailTemplates_ collection
I added a field on each document
The field name is "text" 
The value is " "
 Like this
![image](https://github.com/firebase/extensions/assets/115178814/2eb1cc50-791c-4453-a762-5e55fff11081)

Hope it helps

**Comment by belwalravi** [comment]
This is how my template collection doc is. If you are talking about this? Do you mean I should keep the text field here?

![Uploading Screenshot 2024-04-04 at 8.03.23 PM.png…]()

**Comment by belwalravi** [comment]
Thanks @Aconcagua-CTO bro it helped. Mail are getting delivered now. Now we need to add a text field with a space to get your code working.

**Comment by Aconcagua-CTO** [comment]
Yes, that was the collection I was referring to. 
Glad to help!
