### ISSUE TITLE
Encountering problems with the latest update

### ISSUE THREAD

**Issue by ahmad5149** [firebase/extensions#2026]
In my previous version of the extension, there was an option available to select the **Import existing Firestore documents into BigQuery?** and **Existing Documents Collection name** fields. However, upon installing the new extension for the updated collection, these options are no longer visible. Additionally, after installation, it fails to import the old Firestore data into BigQuery.

Furthermore, during the installation of the new extension, there was an option
![new](https://github.com/firebase/extensions/assets/66243399/d039c875-277b-448a-8826-718a5ba79e14)
![old](https://github.com/firebase/extensions/assets/66243399/7218f200-eedc-4859-bc11-af5bf23b5c2f)
 to modify the extension ID. However, today, upon installing a new one, this option is no longer presented. Interestingly, when attempting to install another extension, the same option is provided. I am uncertain as to why this inconsistency is occurring. Please refer to the attached screenshot for clarification.

**Comment by pr-Mais** [comment]
This is intentional, please find the reason why in #2003 and #2000. Meanwhile, you can use the [import script](https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/guides/IMPORT_EXISTING_DOCUMENTS.md) to backfill your existing docs into BigQuery.
