### ISSUE TITLE
🐛 [Stream Firestore to BigQuery 0.1.48] Export no longer works

### ISSUE THREAD

**Issue by GD-MarcoBug** [firebase/extensions#2048]
Hello everyone,
the Firestore export to BigQuery no longer works for me since version 0.1.48.
No more data is transferred.
When I set up a new customer, the dataset Firestore_Export is still created, but no export tables are created. With the previous versions, everything worked without any problems. 

The basic configuration settings are the same.
Is this a known problem?

Best regards
Marco

**Comment by pr-Mais** [comment]
> When I set up a new customer, the dataset Firestore_Export is still created, but no export tables are created. With the previous versions, everything worked without any problems.

Could you please elaborate more? Do you mean when you install a new instance of the extension, the export table isn't created hence no changes are recorded?

**Comment by j05u3** [comment]
same, no export tables created and for me it says `processing` for hours 
<img width="992" alt="image" src="https://github.com/firebase/extensions/assets/7897132/f207d523-a9cd-4c1b-b458-28c32449a2ce">

**Comment by pr-Mais** [comment]
@j05u3 thanks for sharing your issue, we're looking into it.

**Comment by jauntybrain** [comment]
Hi @j05u3 and @GD-MarcoBug, thank you for reporting this issue. Could you please share the configuration settings of your installed Stream Firestore to BigQuery extensions? Feel free to redact any sensitive information.

**Comment by pr-Mais** [comment]
Also wondering if you installed a new instance of the extension or updated from a previous version?

**Comment by GD-MarcoBug** [comment]
Hi @pr-Mais and @jauntybrain,
first of all, many thanks for the quick support.
The problem occurs both with a new instance and when updating to the latest version.
The following is a basic configuration, for new instances, it gets stuck in processing (last screenshot):
<img width="641" alt="Bildschirmfoto 2024-04-16 um 09 11 51" src="https://github.com/firebase/extensions/assets/155531176/002b6674-7826-4092-b8e9-7bff3acb09fe">

<img width="634" alt="image" src="https://github.com/firebase/extensions/assets/155531176/9f0e0e10-4ad3-46fb-aa8e-ada13874575a">

<img width="630" alt="image" src="https://github.com/firebase/extensions/assets/155531176/23c4a830-3020-426f-ac99-e97a8bbdc1f4">


<img width="959" alt="image" src="https://github.com/firebase/extensions/assets/155531176/b83487ef-dd7b-4980-b70f-32a0440ef888">

**Comment by GD-MarcoBug** [comment]
For your information. The problem also occurs with 0.1.44.
Since 20240412

**Comment by joeframpton** [comment]
I found that when I tried to stream from firestore in project A to bigquery in project B, I had to manually add the function's service account permissions in project B. The extension would then be able to add the dataset and table in bigquery. However, the extension would be stuck on processing until I manually added the required routines in BigQuery too.

**Comment by olegdater** [comment]
@joeframpton what are those "the required routines in BigQuery " and how to add them? eager to make it work again 😀

**Comment by cabljac** [comment]
@GD-MarcoBug do you know if the extension works on versions before 0.1.44?

**Comment by cabljac** [comment]
Investigating this now, testing a fix. Thanks for your patience!

**Comment by krishnamshah** [comment]
Same issue here. Creation of the tables does not work.

**Comment by joeframpton** [comment]
> @joeframpton what are those "the required routines in BigQuery " and how to add them? eager to make it work again 😀

Hi, so the workaround I managed to implement (which autoinstalled the routined for me - alternatively you can install them following this: https://cloud.google.com/bigquery/docs/samples/bigquery-create-routine) was the following:

1. Run the fs-bq-import-collection script across projects (although it failed too - [Issue raised here](https://github.com/firebase/extensions/issues/2055). This created the dataset and table in bigquery in the second project
2. Imported a schema using fs-bq-schema-views to the bigquery in the second project
3.  Installed this extension to set up the stream across projects - and then manually added the service account from this extension to have BigQuery Data Editor & Cloud Datastore User in the second project
4. Run the fs-bq-import-collection script to import the data to bigquery in the original project
5. Set up the service account from the second project to have permissions in the first project
6. In Big Query in the second project, access the data from the original project's big query and merge into the data that's being streamed from step 3

That's what worked for me! There might be superfluous steps in there but I hope this is helpful

**Comment by Matan** [comment]
:wave: eagerly waiting for the fix, thanks for working on it!, in the meantime, is possible to run import script multiple times to update existing / updated documents? I'm running it but it skips over existing updated documents in my collections. I'm effectively looking for an "upsert" mechanic to hold me over until the extension is fixed.

I've also removed the extension and reinstalled the last known good extension version (0.1.42), but no updates are making it through to BigQuery.

Thanks, any help will be appreciated.

**Comment by cabljac** [comment]
Today hopefully!

**Comment by olegdater** [comment]
>firebase/firestore-bigquery-export@0.1.49

I still see same problem

>Runtime Status: Processing
>Configuring BigQuery Sync.

table not created and errors in console: Unhandled error ApiError: Not found: Table

<img width="572" alt="Screenshot 2024-04-20 at 07 11 13" src="https://github.com/firebase/extensions/assets/24967/8d956bfd-095a-4f45-b8bb-378d00f53296">

**Comment by cabljac** [comment]
Strange, it had fixed it for me. I will investigate further.

**Comment by cabljac** [comment]
I believe it *could* be an issue with the onConfigure logic but I won't get a chance to look at it and release until Monday, most likely. If it's urgent you could try installing a fresh instance of the extension as a workaround.

**Comment by cabljac** [comment]
It may be intended behaviour not to create a table onConfigure actually, you might need to install a fresh instance to create the table

**Comment by olegdater** [comment]
i was creating a new extension installation for 0.1.49, not just refreshing already existing one

or what do you mean "install a fresh instance to create the table"?

**Comment by cabljac** [comment]
In that case I'll try and reproduce it again tomorrow  and see what's going wrong. Must be something else up with it, as the RC worked yesterday. Thanks for your patience

**Comment by cabljac** [comment]
I'm having trouble reproducing the bug today with 0.1.49, do you have any additional logs?

**Comment by cabljac** [comment]
@olegdater I don't believe you can have multiple firestore fields in a comma separated list, for

"Firestore Document field name for BigQuery SQL Time Partitioning field option (Optional)"

Our regex validation will need to be changed to reflect this, right now that field has no validation. I will open a new issue to track this.

**Comment by olegdater** [comment]
thanks @cabljac ! confirmed, it now works 🎉
