### ISSUE TITLE
[Translate Text in Firestore] Translating field with an array of strings does not work on add document but on update.

### ISSUE THREAD

**Issue by amin79** [firebase/extensions#2054]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Configure for a field of array of strings.

- Extension name: [Translate Text in Firestore]
- Extension version:  firebase/firestore-translate-text@0.1.16
- Configuration values (redact info where appropriate):
  - **\_**
  - **\_**

### [REQUIRED] Step 3: It does not translate the text of array of string when create the document.
 But when I update the field again, it will translate it.

When I create the document:
<img width="566" alt="Screenshot 2024-04-16 at 11 57 01" src="https://github.com/firebase/extensions/assets/33101184/d45f07fd-4f54-4c5a-8723-b98935a5e335">

When I update the field:
<img width="568" alt="Screenshot 2024-04-16 at 11 59 03" src="https://github.com/firebase/extensions/assets/33101184/19637f53-f1ef-40e3-8d9f-bacd4d804fea">

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.

**Comment by cabljac** [comment]
Hey I'm looking into this now. Can you share your config values for the extension?

**Comment by cabljac** [comment]
I can't seem to reproduce this. Can you please provide

1. The extension config for the instance of the extension where this bug occurs
2. Any relevant logs from the deployed function

<img width="330" alt="Screenshot 2024-04-23 at 13 32 18" src="https://github.com/firebase/extensions/assets/32874567/9e42b8f8-358c-4b29-ab41-b3bc41877869">

**Comment by amin79** [comment]
I tested it again and found out that this was my problem. 
On updating the document I forget to pass the existing translated fields.
Sorry for that...

**Comment by cabljac** [comment]
The issue is resolved?

**Comment by amin79** [comment]
Yes, thank a lot
