### ISSUE TITLE
Send Mail: New Template Collection Not Found

### ISSUE THREAD

**Issue by MichaelRShelton** [firebase/extensions#209]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: firestore-send-email
- Extension version: 0.1.3

### [REQUIRED] Step 3: Describe the problem
I added a new template to an already working extension deployment, but it said the template did not exist even though the logs say it was loaded, causing it to error out. I had to redeploy the extension using the same configurations for the new data to be loaded. This is similar to what happened in #92 

#### Steps to reproduce:

1. Have a working templates and mail collection
2. Add a new template after successful sends.
3. Reference new template in a new mail or update an old one to use it and change state to "RETRY"
4. When it fails, redeploy extension
5. Win

8:40:21.836 am | ext-firestore-send-email-processQueue | loaded template 'reset'
8:40:37.340 am | ext-firestore-send-email-processQueue | Function execution started
8:40:37.349 am | ext-firestore-send-email-processQueue | Started execution of extension with configuration { location: 'us-central1', mailCollection: 'mail', smtpConnectionUri: '<omitted>', defaultFrom: 'noreply@murray-staging.bioblend.net', defaultReplyTo: undefined, usersCollection: 'users', templatesCollection: 'templates' }
8:40:37.468 am | ext-firestore-send-email-processQueue | Attempting delivery for message: mail/OagLhtDRXlslmCJJAxNa
8:40:37.468 am | ext-firestore-send-email-processQueue | Error when delivering message=mail/OagLhtDRXlslmCJJAxNa: Error: tried to render non-existent template 'reset'

##### Expected result
I expected the newly loaded template to be used without error

##### Actual result
Receive an error until I redeployed.

**Comment by mbleigh** [comment]
Thanks for the report, this seems like a bug. @Ehesp can you investigate?

**Comment by Ehesp** [comment]
@mbleigh seems to only happen when updating the document (and changing the status back to `RETRY`). I'm guessing there's a reason as to why the template code subscribes to the templates? Thinking logically, would it not make more sense to directly query the template collection and check if a document exists? Not sure if you did that to reduce the amount of queries though?

**Comment by mbleigh** [comment]
Yeah it's to reduce reads -- templates should change quite infrequently so it would be less optimal to trigger a read every time we're trying to send a message. In addition, since Handlebars templates have to be compiled before they're used, if we refetch the template every time and recompile it as well that might add up to non-trivial amounts of CPU time, especially if it's a large HTML template.

I'm wondering if we're hanging onto an outdated reference in the code somewhere and that's causing the issue...

**Comment by Ehesp** [comment]
Make sense to me, they're fair points. 

> I'm wondering if we're hanging onto an outdated reference in the code somewhere and that's causing the issue...

Yeah it seems so, we'll do some more digging. Cheers!

**Comment by russellwheatley** [comment]
Hello @MichaelRShelton, I thought I had this bug reproduced on Friday evening. This morning, I've redeployed five different times. I've sent new emails & retried previously successful emails referencing freshly created templates, they've all been successfully delivered. The logic seems fine, and I'm at a loss at reproducing this error.  I was wondering whether you could dig through your logs and let me know if there are any errors leading up to the issue?

This [comment](https://github.com/firebase/extensions/issues/92#issuecomment-550513687) in the similar issue makes me wonder if there is a bug with respect to the cloud function spinning up on a cold start.

Just to clarify, does it also happen repeatedly until you redeploy?

**Comment by Salakar** [comment]
Closing during to inactivity, if this is still an issue for you please let us know. Thanks!

**Comment by dmvvilela** [comment]
Is there an update on this? Just installed the extension and it is not finding my templates.

**Comment by markhilton** [comment]
I am still experiencing this issue. Not being able to pin point exactly whats happening, because I was able to send out an email using template, but then adding few more, deleting, updating templates I constantly get "Error when delivering message=email/VmxqFR7bFIVo7EXi7DmG: Error: tried to render non-existent template 'default'", replace 'default' with few others I tested. 

My template documents contain fields: name, html & subject.

**Comment by RafaelZasas** [comment]
I'm having the same issue.
Cloud Firestore path: `Home/templates/template1` 
which contains two _string fields,_ **subject** and **html**

I then add a template attribute to the document being added to the `/mail` collection.

```
      template: {
        name: 'template1',
        data: {
          x: y.z,
          a: b.c
        }
      }
```

I also made sure the extension is configured with the **templatesCollection** set to **templates**.

I keep getting the error: tried to render non-existent template

**Comment by dackers86** [comment]
Below is an overview of this issue along with some potential solutions.

## Why is this happening?

The extension currently only updates the templates from the defined `collection` when it is initialised.

```js
if (config.templatesCollection) {
    templates = new Templates(
      admin.firestore().collection(config.templatesCollection)
    );
}
```

The reason this is only ran once is to reduce the number of reads from the database. For every sent email a read would have to occur for every template available which would occur additional costs.

## Current solutions

If you see the error `Error: tried to render non-existent template`.

Updating or reinstalling the extension is recommended solution. Once reinstalled any newly defined templates will be available. Should any new templates be added after installation then you will need to repeat the re-installation.

## Possible (longer term) solutions

1. We could listen to any writes on the templates collection, this would mean that the templates field in now a required and an additional function would be required to process when a template is added. (https://github.com/firebase/extensions/pull/709)

**Comment by mbleigh** [comment]
It *shouldn't* be the case that new templates and updates to existing templates aren't picked up automatically -- it uses an [onSnapshot](https://github.com/firebase/extensions/blob/next/firestore-send-email/functions/src/templates.ts#L41) listener on the entire templates collection which should mean that new templates are picked up automatically.

We have seen that's not happening in practice, though.

I wonder about a fallback solution along the lines of: "If a template is requested and not found in the in-memory cache (even though it *should* be up to date in realtime), do a `get()` for that template to confirm its existence or not."

While this does add additional reads, it only does so for missing templates which should limit the over-reading to an edge case and might solve this bug entirely. WDYT?

**Comment by dackers86** [comment]
@mbleigh I think your suggestion would be a better solution. I have updated the above description to match your comments. The only other solution suggested so far also includes reads, so a fallback solution would be good just for edge cases.

After more testing the issue does appear to be difficult to recreate.

What was curious was a delay in the logging of any updates (this was around a minute in some earlier scenarios). Could there a type of caching that could exist on function - it does seem a strange bug!

I'll draft up a PR for a fallback solution (and see if I can replicate the issue while doing so)
