### ISSUE TITLE
🐛 [firestore-bigquery-export] multi-db selection isn't working for Firestore triggers

### ISSUE THREAD

**Issue by pr-Mais** [firebase/extensions#2090]
### [REQUIRED] Step 3: Describe the problem

The current version of the Stream Firestore to BigQuery extension allows specifying a secondary project for the Firestore triggers, however this doesn't work as the triggers are all 1st gen. Need to remove the feature.

See #2072

**Comment by titan-graham** [comment]
Found this issue via (#2072):

We are somewhat confused/bemused that the current version of the extension allows a non `(default)` database ID, but a non default database ID is not supported by the underlying technology (gen1 functions) that the extension relies on. 

`Error creating trigger: The request was invalid: generic::invalid_argument: source filter must follow '//firestore.googleapis.com/projects/{projectId}/databases/(default)'.`

We've wasted pointless hours on this where in fact the extension as published simply cannot work in the way it's advertised. How is it possible this feature even made it into a release?
