### ISSUE TITLE
Documentation Update: Firebase-Counter Deletes Subcollection/Shards Once Aggregated

### ISSUE THREAD

**Issue by tommyc38** [firebase/extensions#21]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** (`storage-resize-images`, `firestore-send-email`, etc)
- Configuration values (redact info where appropriate):
  - **\_**
  - **\_**

### [REQUIRED] Step 3: Describe the problem
The documentation would lead you to believe that you will have a persistent subcollection in your documents that have a counter containing count shards.  However, this isn't necessarily the case because once the shards are aggregated they get deleted.  I thought I was going crazy because I could not find any subcollection with shards but yet somehow the function was accurately counting.  It left me scratching my head wondering what was getting counted if they aren't in the DB.
#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.

##### Expected result
I think it would be helpful to make it more clear that if you are running a few simple tests, you will not see any of these subcollections.

**Comment by Ehesp** [comment]
Hi @tommyc38 thanks for opening the issue. Although this intended, I do think it would be best to let users know about this, to ensure they are only using the "master" counter. 

@rachelsaunders would this be best placed [here](https://github.com/firebase/extensions/blob/master/firestore-counter/POSTINSTALL.md#L74) or do you think it requires an explanation within the PREINSTALL doc?

**Comment by rachelsaunders** [comment]
For clarification - does the extension delete the subcollections each time the scheduled function runs?

**Comment by tommyc38** [comment]
@rachelsaunders, either I am experiencing a bug or it does indeed delete the sub collection if it has no more shards (docs) to count.  Assuming this is intended, having a line or two about this in the docs will be helpful to others who run tests and expect to see a sub collection but don't.

**Comment by rachelsaunders** [comment]
@Ehesp Friendly ping on my clarification question above?  Thx!

**Comment by Ehesp** [comment]
Hi @rachelsaunders - it deletes them once they have been aggregated yes. Users should sync with the 'master' doc created, as it's unreliable to sync with the aggregators (as they can be removed anytime).

**Comment by rachelsaunders** [comment]
closed w/ merge of PR #62
