### ISSUE TITLE
🐛 [firestore-vector-search] model: 'text-multilingual-embedding-002'

### ISSUE THREAD

**Issue by karloti** [firebase/extensions#2103]
### Option to choose another text embedding model.

I want to use **multilingual** model:

![image](https://github.com/firebase/extensions/assets/6735500/4e3cfb39-b229-4b60-a15b-126515d4f682)

Your embedding not working for me!
My text field for embedding is in **Bulgarian**.

here is a code snippet from your [function](https://github.com/GoogleCloudPlatform/firebase-extensions/blob/main/firestore-vector-search/functions/src/embeddings/client/text/gemini.ts)
`const model = this.client.getGenerativeModel({model: 'embedding-001'});`

**Comment by pr-Mais** [comment]
@karloti thanks for reporting this issue! this extension source is not in this repository, it's in https://github.com/GoogleCloudPlatform/firebase-extensions, so please open the same issue there, so we can track and fix it.
