### ISSUE TITLE
🐛 Stream Firestore to BigQuery - disable changelog

### ISSUE THREAD

**Issue by Tigmelikyan** [firebase/extensions#2104]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **Stream Firestore to BigQuery** 

### What feature would you like to see?

Is there a possibility to disable changelog table creation or at least don't have data transferred to it? 
We don't use it at I think BQ is quite costly.
![image](https://github.com/firebase/extensions/assets/159790458/fdc43090-274c-49a9-8b4e-45175df003b9)

thank you in advance

**Comment by pr-Mais** [comment]
Hi @Tigmelikyan, thanks for opening this request. It's being tracked in #1608, so please feel free to upvote the original issue.
