### ISSUE TITLE
Custom extensions

### ISSUE THREAD

**Issue by long1eu** [firebase/extensions#213]
Is it possible to create my own extensions and distribute them?

**Comment by russellwheatley** [comment]
As far as I can tell, you have a couple of options. You could leave feedback [here](https://firebase.google.com/support/troubleshooter/report/features) for an extension feature request which the Firebase Extension team would consider. 

Alternatively, if you're looking to distribute something yourself, you might consider writing your own [cloud function](https://firebase.google.com/docs/functions/?gclid=CjwKCAiAnfjyBRBxEiwA-EECLH8vkG6m4gHgteDivPnCIPxvdMvcqpxuBLLywVwU6i7WPZr44cyTExoCnVEQAvD_BwE) with the service you had in mind.

**Comment by laurenzlong** [comment]
Hey @long1eu if you're interested in hearing about when you would be able to preview the experience of creating your own extensions, sign up for the Firebase Alpha program: https://services.google.com/fb/forms/firebasealphaprogram/

**Comment by long1eu** [comment]
@laurenzlong Hi! Thanks. I'm already in the Alpha program, but I didn't received anything about this.

**Comment by laurenzlong** [comment]
We haven't announced it yet, but if you're already a part of Firebase Alpha, then you'll get an update when we do launch the producer experience into Alpha :)

**Comment by long1eu** [comment]
@laurenzlong you're the best
