### ISSUE TITLE
fs-bq-schema-views - Syntax error: Unexpected keyword CREATE at [10:106]

### ISSUE THREAD

**Issue by cedgen** [firebase/extensions#218]
### [READ] Step 1: Are you in the right place?

Yes!

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-bigquery-export / fs-bq-schema-views**
- Extension version: **latest**

### Step 3: Describe the problem
While doing fs-bq-schema-views  
 npx @firebaseextensions/fs-bq-schema-views  
--non-interactive   
--project test_project
--dataset firestore_export_organisation   
--table-name-prefix organisation   
--schema-files organisation_schema.json

I get this error
{"code":400,"errors":[{"message":"Syntax error: Unexpected keyword CREATE at [10:106]","domain":"global","reason":"invalidQuery","location":"q","locationType":"parameter"}],"message":"Syntax error: Unexpected keyword CREATE at [10:106]"}
**Syntax error: Unexpected keyword CREATE at [10:106]**

#### Steps to reproduce:

Just do npx @firebaseextensions/fs-bq-schema-views  

##### Expected result

Schema should be uploaded

##### Actual result

Error

**Comment by russellwheatley** [comment]
This appears to be linked with issues #139 & #211. I spent yesterday afternoon trying to run the Big query import script with no success as it is broken (#192). I tried running the [fixed](#197) import script  locally, but I was still getting the same error.  

The import script needs to run before testing the schema view script. I think this probably needs to be looked at by the Firebase Extensions team.

**Comment by laurenzlong** [comment]
Hey @russellwheatley the script has been published, can you proceed with testing the schema view script please? Thank!

**Comment by russellwheatley** [comment]
Hey @laurenzlong, there are further changes needed to both the `firestore-bigquery-change-tracker` & `gen-schema-view` for the `gen-schema-view` script to be fixed. I have a draft PR up at the moment: https://github.com/firebase/extensions/pull/257
