### ISSUE TITLE
auth-mailchimp-sync: Error installing extension

### ISSUE THREAD

**Issue by gmcheese** [firebase/extensions#220]
### Describe your configuration

- Extension name: `auth-mailchimp-sync`
- Extension version: **0.1.0**
- Configuration values (redact info where appropriate):
  -  Cloud Functions Locations: **us-central1**
  -  Contact status Description: **subscribed**

### Describe the problem
Installing the extension after configuration produces the Error:
**Error installing extension. Be aware that a parameter misconfiguration might have caused some extension resources to not successfully deploy.**
```

Error occurred while deploying resources: 
CONDITION_NOT_MET: `/deployments/firebase-ext-auth-mailchimp-sync-93g9/resources/addUserToList->$.properties` 
error: instance type (number) does not match any allowed primitive type (allowed: ["string"])
level: "error" 
schema: {"loadingURI":"#","pointer":"/create/properties/environmentVariables/additionalProperties"} 
instance: {"pointer":"/environmentVariables/MAILCHIMP_AUDIENCE_ID"} 
domain: "validation" 
keyword: "type" 
found: "number" 
expected: ["string"] ; 

CONDITION_NOT_MET: `/deployments/firebase-ext-auth-mailchimp-sync-93g9/resources/removeUserFromList->$.properties` 
error: instance type (number) does not match any allowed primitive type (allowed: ["string"]) 
level: "error" 
schema: {"loadingURI":"#","pointer":"/create/properties/environmentVariables/additionalProperties"} 
instance: {"pointer":"/environmentVariables/MAILCHIMP_AUDIENCE_ID"} 
domain: "validation" 
keyword: "type" found: "number" expected: ["string"]
```

I'm not able to find any related information in terms of configuration in the documentation, so I believe everything is set up correctly. Can it be related to some API update?

#### Steps to reproduce:
I simply created a new blank list in Mailchimp, created a new API key for the account, and filled out the information in configration. I have a pre-existing Firebase Authentication instance running. Unfortunately, the extension does not produce any log as installation failed.

##### Expected result
The extension should install and be able to export contacts to Mailchimp
##### Actual result
The extensions failed installing.

**Comment by Salakar** [comment]
Hey @gmcheese - thanks for the bug report.

cc @laurenzlong - do you know if anything has changed in the way that the extension configuration values are parsed? It looks like a number like value was coming through as a string previously, but is now being coerced into a number or something?

**Comment by laurenzlong** [comment]
@gmcheese Are you installing via the Console or the CLI, and if CLI, what version number of the CLI are you running? (Run `firebase --version` to find out)

**Comment by gmcheese** [comment]
I've tried installing with the console and CLI. They both return the same error.
The CLI version is `7.15.0`

**Comment by laurenzlong** [comment]
Hi @gmcheese I was able to install the extension successfully using both Console and CLI v7.1.5.0. These are my parameter values: 
```
Cloud Functions location Description
us-central1
Mailchimp API key Description
11111111
Audience ID Description
11111111
Contact status Description
subscribed
```
Can you try again? I suspect it was a temporary server issue with Cloud Functions

**Comment by gmcheese** [comment]
I tried installing using your parameters - also using `11111111` as API and ID's. It installed successfully through console. However, when configuring it with my own values, it returns the following error after reconfiguring:

```
There was an unknown error while processing the request. Try again.
```
It seems like the problem is related to my Audience - are there any specific configurations I should be aware of?

**Comment by laurenzlong** [comment]
Hi @gmcheese can you file a [support ticket](https://firebase.google.com/support/troubleshooter/report/bugs), and ask for it to be redirected to Lauren Long? Then in the support ticket you can put in your exact audience ID and I can try to repro and troubleshoot.

**Comment by gmcheese** [comment]
Opening it now. Thanks.

**Comment by gmcheese** [comment]
So, with the help of @laurenzlong I finally got it solved. Turns out the problem was my Audience ID being in the form `XXXXXXeXXX` (X being numbers), was converted as a number in scientific notation by the extension. 

I solved it by creating a new audience with a less obscure ID. 
You can close this issue if you feel like it.
Thanks!

**Comment by laurenzlong** [comment]
Glad you were able to get a new audience ID! Thanks for the update!

**Comment by JimmyPauwaert** [comment]
> So, with the help of @laurenzlong I finally got it solved. Turns out the problem was my Audience ID being in the form `XXXXXXeXXX` (X being numbers), was converted as a number in scientific notation by the extension.
> 
> I solved it by creating a new audience with a less obscure ID.
> You can close this issue if you feel like it.
> Thanks!

Had the exact same issue. Thx for adding your feedback!
