### ISSUE TITLE
storage-resize-images is not automatically creating an access token, making it unusable

### ISSUE THREAD

**Issue by InterwebCounty** [firebase/extensions#223]
- Extension name: storage-resize-images
- Extension version: Version 0.1.5

As seen here: https://github.com/firebase/extensions/issues/174

Is there a setting or configuration?

**Comment by Ehesp** [comment]
Hey @InterwebCounty we've already got an issue discussing this problem: https://github.com/firebase/extensions/issues/140 - I'll close this one so the discussion can be continued on that issue. Thanks!
