### ISSUE TITLE
Storage-Resize-Images Subdirectory Config

### ISSUE THREAD

**Issue by granttj01** [firebase/extensions#232]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **storage-resize-images**

### What feature would you like to see?

Allow for directory config option.

### How would you use it?

To do this we could do the following:

1) Add a config value to config.js
```imageDir: process.env.IMG_DIR,```

2) Add a new logging method
```
export const imagePathInvalid = () => {
  console.log("Image path does not match, no processing is required")
};
```

3) Check for a match between the value we extract [here](https://github.com/firebase/extensions/blob/c7396cd55a18dacba091e21bd94b1d54b3225e72/storage-resize-images/functions/src/index.ts#L69)
```const fileDir = path.dirname(filePath);```
and config.imageDir.
To also take into consideration glob matching we could utilise [minimatch](https://github.com/isaacs/minimatch), or equivalent to allow config to be say
```<somedirectory>/*/<imageDirectory>```
or
```<somedirectory>/**/<imageDirectory>```

What do you think?

**Comment by granttj01** [comment]
Potential solution for:
https://github.com/firebase/extensions/issues/173
https://github.com/firebase/extensions/issues/104

**Comment by russellwheatley** [comment]
Hi @granttj01, sounds like a reasonable candidate for a feature request. Could you please leave a feedback request at: https://firebase.google.com/support/troubleshooter/report/features so the Firebase Extension team can track internally? 

Thank you.

**Comment by granttj01** [comment]
Thanks @russellwheatley Already done yesterday. I accidentally submitted twice but cases 43483 and 43484 👍

**Comment by laurenzlong** [comment]
Hi @granttj01 if I'm understanding you correctly, you want a way to tell the extension to resize only images in a certain directory, not the rest of the bucket. To achieve what you want, the best solution would be to have multiple storage buckets for your app, and use a bucket exclusively for the images you want to resize. Extensions are powered by Cloud Functions, and a storage trigger for cloud function can only be configured at the bucket level, not at the folder level. So even if we were to do what you suggest, the extension would still trigger for every new file in the bucket, this will lead to quota usage and potentially a higher bill.
