### ISSUE TITLE
Firebase email Trigger Custom Domain Error 

### ISSUE THREAD

**Issue by ShreeBhagwat** [firebase/extensions#233]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** (`firestore-send-email`)

### [REQUIRED] Step 3: Describe the problem

So Iam in process to develop an Firestore Flutter Web App.
and when users fill a form I want to send an automatic mail to them.
aim used Firestore as a database and trying to set up cloud function to send email.

I have created an 'email' collection in the database and when data is added to this database the email trigger must work to send email automatically.

I have a custom email.

I have set the SMTP setting properly, and billing to blaze plan.

But when the data is added to the database I get error

>  Error when delivering message=email/wC0n9FGAN0DwQpx5ZdZC: Error: 139258905216832:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

#### Steps to reproduce:
Followed the example given resulted with error. Somewhere I feel it must be related about TSL and SSL, certificates but I tried two different email resulting in the same error

##### Expected result

The mail getting send and the Delivery status to be success

##### Actual result

Error in the mail Delivery and status Error

**Comment by russellwheatley** [comment]
Hi @ShreeBhagwat, do you mind sharing the insensitive (not the password) parts of you smtp URI? The error message above says `unknown protocol` which makes me think the SMTP URI protocol might be incorrectly set.
