### ISSUE TITLE
[FR] Delete User Data : disable listener on deleted elements

### ISSUE THREAD

**Issue by Pitouli** [firebase/extensions#237]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **Delete User Data**

### What feature would you like to see?

A checkbox to disable the listening cloud functions on the documents under the deleted object 

_(perhaps simply by renaming the object about to be deleted so it does not match anymore the trigger conditions?)_

### How would you use it?

I have a collection of users. 

For each user, I have several collections with hundreds of documents, and I have cloud functions that listen to every updates on those documents, to update other documents accordingly _(for example, if the user delete a "company" from his "companies" collection, then a cloud function updates all his "workers" from the "workers" collection to mark them unemployed)_

Today, when the Delete User Data function triggers, it triggers the cloud functions that are in charge of assuring the consistency of the user data ; datas that will have disappeared 20 seconds later anyway.

I observed that deleting less than 50 users (with a total of 1,6k underlying documents) has triggered 30k calls of cloud functions _(some functions triggered on an object will update the object itself which triggers again the same function. and some functions will update several other objects that can themeselves self trigger. Etc.)._

Thanks to this new feature, the cloud functions would ignore all those deletion and save ten of thousands of cloud function call and firestore reads and updates.

**Comment by russellwheatley** [comment]
Thanks for the feature request. Could you please leave a feedback request at: https://firebase.google.com/support/troubleshooter/report/features so the Firebase Extension team can track internally?

Thank you.

**Comment by laurenzlong** [comment]
Hi @Pitouli unfortunately we won't be able to support this since it is quite unique to your use case. I would recommend directly using https://github.com/firebase/user-privacy, which is the project that we based this extension on. Then you'll have an opportunity to add the desired behavior of renaming the document before deleting it.

**Comment by Pitouli** [comment]
Thanks @laurenzlong for your answer. 

In fact, I cannot "move" a document and all its subcollections from one collection (for example "users") to another (for example "users-to-delete") like I would on folder system... 

Renaming implies copy all the document to the new place and delete them from the old place, which would trigger all my cloud functions anyway (plus costing the rewrite... and the delete of the rewrite...)

I suppose the best is to add an attribute to my user document, for example "disable cloud function = true", and have all my cloud function to check the value of this attribute before executing.

**Question: is there a way to cache the result of this check at the cloud function level so I do not have to pay a firestore read for every cloud function execution?** 

For example, is it possible to create a firestore collection "users-with-disabled-cloud-function" (at the root level), and have a cloud function that listen to real time update to this collection to keep a cache of all the users for which Cloud Functions should not be activated? If I have on average 10 users in this list, it means 10 reads every 30 minutes (240 reads per day).
And all the other functions would simply check the cache to see if they have to execute or not, without having any read to do to Firestore.

Is it possible to have a function that keeps in cache "realtime update" (without having the listener restarted at every function call)?

**Comment by laurenzlong** [comment]
Sorry for the late reply! 

You do not pay for Firestore reads if you're simply reading the value of the document that triggered the cloud function. However, if you try to read anything else within the function (its parent collection, another document in the same collection, etc.), you will get charged. Hope that clarifies things. 

You can also look into structuring your data differently, and using more granular Cloud Function triggers (e.g. `onCreate`, `onUpdate`, `onDelete`)

**Comment by Pitouli** [comment]
Is there a way to cache a small set of data, ideally a listener, at the cloud function level? So subsequent calls to the cloud function already have the data?

**Comment by laurenzlong** [comment]
@Pitouli There's no supported way to store data between executions, you can store things in global variables, and it may work occasionally, if an instance was "recycled" for a subsequent execution. But it will not work reliably. So you'll have to try to read from the global variable first, and if it's empty, then do a Firestore read. Since this thread is now about functions rather than extensions, I recommend posting to the Firebase tag on StackOverflow if you have any follow up questions: https://stackoverflow.com/questions/tagged/firebase. Thanks!

**Comment by Pitouli** [comment]
Thanks!
