### ISSUE TITLE
Delete User Data not Deleting user data

### ISSUE THREAD

**Issue by tiagooliveira95** [firebase/extensions#24]
**Firestore structure**

test_users  ->  uid1, uid2 ...
                      
users ->  uid3, uid4 ...

**Cloud Firestore Paths**: users/{UID}, test_users/{UID}

**Logs**: 
Deleted: ' test_users/uid1' from Cloud Firestore
Deleted: ' users/uid1' from Cloud Firestore

**What happen**: Documents were not deleted

**Comment by Ehesp** [comment]
Thanks for the report. 

Have you re-configured the extension and redeployed at all? Or is this happening straight after a fresh install?

**Comment by Ehesp** [comment]
I have just noticed you have spaces in your paths. Spaces are valid in collection paths, so you're technically pointing to a valid path.

When setting up your paths, ensure it is: `users/{UID},test_users/{UID}`. I'll bring this up with the team though, as it's confusing!

**Comment by tiagooliveira95** [comment]
> I have just noticed you have spaces in your paths. Spaces are valid in collection paths, so you're technically pointing to a valid path.
> 
> When setting up your paths, ensure it is: `users/{UID},test_users/{UID}`. I'll bring this up with the team though, as it's confusing!

Oh, ok thank you!

A message warning users to pay attention to spaces between commas would be very useful.

**Comment by Ehesp** [comment]
I agree - the safest option would be to create an additional extensions field which allows "list" type arguments to be added one by one, without commas. cc @karayu
