### ISSUE TITLE
[firestore-send-email] only sending from Default FROM address, even when overridden

### ISSUE THREAD

**Issue by dhstack** [firebase/extensions#241]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **`firestore-send-email`**
- Extension version: **v0.1.4**
- Configuration values (redact info where appropriate):

Cloud Functions location
us-central1

SMTP connection URI
smtps://apikey:*****@smtp.sendgrid.net:465

Email documents collection
emailQueue

Default FROM address
Name <hello@***.io>

Default REPLY-TO address (Optional)
Name <hello@***.io>

Users collection (Optional)
users

Templates collection (Optional)
emailTemplates

#### Steps to reproduce:

1. Install extension v0.1.4.
2. Add a document to the email documents collection from a separate `Firebase Function` (making sure the `from` field uses a different email address than the extension default):
```
    await db.collection('emailQueue').add({
      message: {
        from: 'David <david@****.io>',
        subject: programData?.emails.welcome.emailSubject,
        text: text,
        html: htmlString
      },
      toUids: [uid]
    });
```

Note: This happens even when using a regular email (without the name).

P.S. I tried to uninstall and reinstall and that didn't work either.
P.P.S. I had also changed the Default Reply to variable from the `Cloud Function` dashboard before realizing I could do so from the `Firebase Extensions` dashboard. Then I updated the function from v0.1.3. That's when I started to notice the error since that's when I first started using the `from` field when creating the document.

##### Expected result
I should receive an email from the address specified in the `from` field when adding to the document to the email collection.

##### Actual result
The email is received and the html/text work as expected, but the `from` name is the default name and email from the extension configuration - not the `from` email manually typed in. The document in `Firestore` has the expected `from` email, but the email itself is from the default `from` when it shows up in my Gmail inbox.

**Comment by Ehesp** [comment]
Hey @dhstack - thanks for the issue.

It looks as though you are adding the `from` field to the `message` body when it should be in the root of the document (see [docs here](https://github.com/firebase/extensions/blob/next/firestore-send-email/POSTINSTALL.md#sender-and-recipient-fields)). 

Your code snippet should be:

```js
   await db.collection('emailQueue').add({
      message: {
        subject: programData?.emails.welcome.emailSubject,
        text: text,
        html: htmlString
      },
      from: 'David <david@****.io>',
      toUids: [uid]
    });
```

Let me know you get on!

**Comment by dhstack** [comment]
🤦‍♂ That would do it. Thanks!
