### ISSUE TITLE
firestore-bigquery-export incorrectly exports documents data when keys.with.dots are used

### ISSUE THREAD

**Issue by stari4ek** [firebase/extensions#245]
### [READ] Step 1: Are you in the right place?

yep

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **`firestore-bigquery-export`**
- Extension version: **0.1.1**

### [REQUIRED] Step 3: Describe the problem

When there is Firestore document like:
```json
{
  "key_one": "value1",
  "key.two": "value2"
}
```
it's exported as 
```json
{
  "key_one": "value1",
  "key": {
    "two": "value2"
  }
}
```
#### Steps to reproduce:

export documents with data which has `some.dotted.keys`

##### Expected result

While Firestore uses `.` as path separator - it stores such keys properly (caller should take care of escaping).
I'd expect that exported document should preserve document structure

##### Actual result

described above

**Comment by russellwheatley** [comment]
Hi @stari4ek, I could not reproduce this issue when I mirrored the data using version `0.1.1`:
<img width="442" alt="Screenshot 2020-04-09 at 16 04 56" src="https://user-images.githubusercontent.com/16018629/78910033-37dd3a00-7a7c-11ea-9f62-14ff3931f80b.png">

Nor when I used the import script `npx @firebaseextensions/fs-bq-import-collection`:
<img width="423" alt="Screenshot 2020-04-09 at 16 02 36" src="https://user-images.githubusercontent.com/16018629/78910107-55aa9f00-7a7c-11ea-8c98-7e67c223b1bb.png">

Could you provide more context on how to recreate, please?

**Comment by stari4ek** [comment]
I double checked,
this is not an issue of export, but original documents have incorrect (unexpectedly) structure.

Sorry, for that. Please close the issue.
