### ISSUE TITLE
firestore-bigquery-export-gen-schema-view fails to build due missing chai deps

### ISSUE THREAD

**Issue by stari4ek** [firebase/extensions#246]
### [READ] Step 1: Are you in the right place?

yep

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-bigquery-export**
- Extension version: **07d050ac1f39248e5b77e6503a7aab51a58b68f7**

#### Steps to reproduce:

Checkout branch and build
```bash
cd extensions/firestore-bigquery-export/scripts/gen-schema-view/ && npm run-scipt build
```

```
> @firebaseextensions/fs-bq-schema-views@0.1.2 compile /home/astar/dev/extensions/firestore-bigquery-export/scripts/gen-schema-view
> tsc

error TS2688: Cannot find type definition file for 'chai'.
```

It fails cause it's own `package.json` does not declare devDependencies to `chai`

adding them to it fixes the issue

##### Expected result

No errors during project build

##### Actual result

fails

**Comment by laurenzlong** [comment]
This should have been fixed by https://github.com/firebase/extensions/pull/244. Please let us know if it still is an issue.
