### ISSUE TITLE
firestore-bigquery-export-gen-schema-view fails if field uses forbidden char

### ISSUE THREAD

**Issue by stari4ek** [firebase/extensions#247]
### [READ] Step 1: Are you in the right place?

yep

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-bigquery-export** (`gen-schema-view`)
- Extension version: **07d050ac1f39248e5b77e6503a7aab51a58b68f7**

#### Steps to reproduce:

BigQuery view generation from view schema fails if field contains not-alpha/digit/underscore. For example:

```json
{
  "fields": [
    {
      "name": "subscriber:cancelled",
      "type": "boolean"
    }
  ]
}
```

Error:
```
BigQuery creating schema view audiences_schema_audiences_latest:
Schema:
{"fields":[{"name":"subscriber:cancelled","type":"boolean"}]}
Query:
SELECT
  document_name,
  timestamp,
  operation,
  `PROJECT_ID.firestore_export.firestoreBoolean`(JSON_EXTRACT(data, '$.subscriber:cancelled')) AS subscriber :cancelled
FROM
  `PROJECT_ID.firestore_export.audiences_raw_latest`
{"code":400,"errors":[{"message":"Syntax error: Unexpected \":\" at [5:111]","domain":"global","reason":"invalidQuery","location":"q","locationType":"parameter"}],"message":"Syntax error: Unexpected \":\" at [5:111]"}
Syntax error: Unexpected ":" at [5:111]
```

Quoting qualified name does not fix the issue, since there is requirement for query:
> Fields must contain only letters, numbers, and underscores, start with a letter or underscore, and be at most 128 characters long.

There is no such limitation for fields in firebase documents.

This issue can be fixed with properly generated qualified field name, during SQL schema generation:
```typescript
function qualifyFieldName(prefix: string[], name: string): string {
  const notAlphaDigitUnderscore = /([^a-zA-Z0-9_])/;
  name = name.replace(notAlphaDigitUnderscore, '_');
  // TODO: first char. length limit

  return prefix.concat(name).join("_");
}
```

##### Expected result

Field name should be automatically normalized and no errors occurred

##### Actual result

fails to generate view

**Comment by russellwheatley** [comment]
Hi FE team, as @stari4ek points out, this does break the script. I'm not sure this is something to be fixed so to speak. If you replace the colon to an underscore in the schema field properties, it will not match any properties names in the dataset which use a colon.

**Comment by stari4ek** [comment]
@russellwheatley , don't really get the problem.
It uses a bit different alias name for view field, but json lookup works as exp[ected.
Here is example of generated schema view:
```SQL
`MY_PROJECT.firestore_export.firestoreBoolean`(
  FIRST_VALUE(JSON_EXTRACT(data, '$.subscriber:free_trial')) OVER(
    PARTITION BY document_name
    ORDER BY
      timestamp DESC
  )
) AS subscriber_free_trial,
```

workaround changes alias name (`AS subscriber:free_trial` => `AS subscriber_free_trial`) 

No issues so far with workaround applied.

**Comment by russellwheatley** [comment]
My apologies, @stari4ek, I just ran further tests, and you're correct. 

This makes sense to me as a change. Hey Firebase Extensions team, could you please advise if you would like this change making, and I'll create a PR?

**Comment by stari4ek** [comment]
another way to solve this one is to provide new optional field in scheme to be used as alias in view
