### ISSUE TITLE
Generate Schema - cannot find '@firebaseextensions/firestore-bigquery-change-tracker'

### ISSUE THREAD

**Issue by newadays** [firebase/extensions#250]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **fs-bq-schema-views** 
- Extension version: **n/a**
- Configuration values (redact info where appropriate):
  - **PROJECT_ID: myproject**
  - **COLLECTION PATH: mycollection**
  - **DATASET ID: dataset**
  - **TABLE_PREFIX: table**

### [REQUIRED] Step 3: Describe the problem
When running `npx @firebaseextensions/fs-bq-schema-views \ ...` got an error `cannot find '@firebaseextensions/firestore-bigquery-change-tracker'` with no schema or views created. Tried several times and various prefix but it didn't work.
#### Steps to reproduce:
Follow the steps described in the guide [here](https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md)
What happened? How can we make the problem occur?
The package does not seem to exist.
![error](https://user-images.githubusercontent.com/14118614/78852355-b3d67400-79e1-11ea-941b-16491a17de6c.jpeg)

##### Expected result
Schema and views created
##### Actual result
Error and nothing was created.

**Comment by russellwheatley** [comment]
Hi @newadays, you're correct. The module has not been specified in the `package.json`. I'll be making a PR for the `fs-big-schema-view` in due course. Thank you for raising the issue.
