### ISSUE TITLE
[FR]: firestore-limit-child-nodes

### ISSUE THREAD

**Issue by bendiknesbo** [firebase/extensions#26]
### [REQUIRED] Step 2: Extension name

This feature request is for extension: **firestore-limit-child-nodes** 

### What feature would you like to see?

I would like a `firestore-limit-child-nodes` to be created, just like `rtdb-limit-child-nodes`.

### How would you use it?

Same use-case as for `rtdb-limit-child-nodes`, but for Firestore.

**Comment by Ehesp** [comment]
XFN Team: Should be a fairly straightforward implementation; would make sense to use batched writes to achieve this I think.

**Comment by jhuleatt** [comment]
Added this to our internal tracker of new extension requests. Any other requests for brand new extensions that don't exist in this repository yet can be filed at https://firebase.google.com/support/troubleshooter/extensions/featurerequest
