### ISSUE TITLE
"npm test" fails for firestore-bigquery-change-tracker and gen-schema-view

### ISSUE THREAD

**Issue by laurenzlong** [firebase/extensions#260]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: firestore-bigquery-export
- Extension version: 0.1.3
- Configuration values (redact info where appropriate):
  - **\_**
  - **\_**

### [REQUIRED] Step 3: Describe the problem
Unit tests are not passing for the helper packages for firestore-bigquery-export
#### Steps to reproduce:

cd firestore-bigquery-export/firestore-bigquery-change-tracker
npm test 
// Tests fail
cd ../scripts/gen-schema-view
npm test
// Tests fail

##### Expected result

Tests to pass

##### Actual result
For firestore-bigquery-change-tracker:
![Screen Shot 2020-04-10 at 4 57 18 PM](https://user-images.githubusercontent.com/3990804/79031615-db9a1900-7b54-11ea-9927-2dc72dbed4bf.png)

For gen-schema-view:
![Screen Shot 2020-04-10 at 4 59 38 PM](https://user-images.githubusercontent.com/3990804/79031619-dfc63680-7b54-11ea-874a-0a472e0a0438.png)

**Comment by laurenzlong** [comment]
Once the tests are fixed, they should get hooked up to CI: https://github.com/firebase/extensions/issues/260

**Comment by IanWyszynski** [comment]
Are you running against `0.1.3` or `1.1.3`? In your screenshot it shows `1.1.3`. I can't reproduce this issue on `next`:
<img width="1217" alt="Screen Shot 2020-04-10 at 6 19 00 PM" src="https://user-images.githubusercontent.com/5572676/79032033-16518080-7b58-11ea-8789-47e1b653a913.png">
