### ISSUE TITLE
storage-resize-images memory limit exceeded. Function invocation was interrupted.

### ISSUE THREAD

**Issue by jontysouvik** [firebase/extensions#269]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: storage-resize-images
- Extension version: 0.1.5
- Configuration values (redact info where appropriate):
  { cacheControlHeader: undefined,
  imageSizes: [ '100x100', '300x300', '600x600', '800x800' ],
  resizedImagesPath: 'resize',
  deleteOriginalFile: false }

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.

##### Expected result
Getting Resized Images
##### Actual result

ext-storage-resize-images-generateResizedImage
Error: memory limit exceeded. Function invocation was interrupted.

**Comment by russellwheatley** [comment]
Do you mind sharing the image you're trying to resize, please @jontysouvik? I've tried a 17mb image that worked fine, but I guess, your image is much bigger.

**Comment by jontysouvik** [comment]
![man-wearing-blue-and-yellow-shorts-playing-basketball-1080884](https://user-images.githubusercontent.com/25180379/80271028-bf60b500-86da-11ea-8129-2726f9978e4d.jpg)
This is the file I was trying to convert its only 5.1mb

**Comment by russellwheatley** [comment]
Interesting. A possible solution is to increase the amount of memory for your cloud function (default is 256mb). Here is a set of [instructions](https://stackoverflow.com/a/44506225) on how to achieve that.

**Comment by karayu** [comment]
Hi @jontysouvik, 

Did that solve your issue? Please let us know if you're continuing to have issues!

Kara
