### ISSUE TITLE
chore(*) update all CHANGELOG files to align in tense and issue/PR referencing

### ISSUE THREAD

**Issue by rachelsaunders** [firebase/extensions#276]
For all extension's CHANGELOG files, we need to do the following:

- All leading verb tenses (especially for "fixed" or "changed") are past tense, like so:
"Created this to do that."

- When applicable, the Issue and/or PR are referenced at the end of the line, like so:
"Created this to do that. (Issue #XXX)"
or
"Created this to do that. (Issues #XXX and #YYY)"
or
"Created this to do that. (PR #XXX)"

**Comment by i14h** [comment]
@kevinthecheung do you want to work on this?

**Comment by jhuleatt** [comment]
Given that these are all auto-generated from PR names, it sounds like a lot of work to manually fix these before each release. @kevinthecheung what do you think?

**Comment by jhuleatt** [comment]
I've added this to our release process so the release owner can make these changes, and Kevin can do the final review.
