### ISSUE TITLE
Counter SDK for backend services like "node.js"

### ISSUE THREAD

**Issue by urkopineda** [firebase/extensions#28]
### Extension name

This feature request is for extension: **\firestore-counter**

### What feature would you like to see?

Make the `sharded-counter.js` work not only for the frontend but for backend services like `node.js`. This requirement includes not to depend on requiring / importing `firebase/app` and `firebase/firestore` in the user code, but on the SDK code instead.

### How would you use it?

In our case, we use a backend service to make our web site cleaner and lighter without Firebase SDK, so, all the usage of Firebase occurs in the backend. We would like to use the counter so that's why we need to use it on the backend.

**Comment by lechim** [comment]
Hi I made a quick work around function from the SDK to let this extension work on javascript Firebase functions.

`const uuidv4 = require('uuid/v4');`

`function increment(field, path, val) {`
    `const db = admin.firestore();`
    `const increment = admin.firestore.FieldValue.increment(val);`
    `const update = field.split(".").reverse().reduce((value, name) => ({[name]: value}), increment);`
    `return doc.collection('_counter_shards_').doc(uuidv4()).set(update, {merge: true});`
`}`

It may not be the best solution yet but works.

**Comment by Ehesp** [comment]
XFN Team: Would this be an additional "client" in the project, or would it be appropriate to adapt the web script to work in a Node environment?

**Comment by Ehesp** [comment]
Duplicate: https://github.com/firebase/extensions/issues/55

**Comment by Henry-** [comment]
I think it would be better to adapt the web script to work in a Node environment.

**Comment by voxelbusters** [comment]
Won't increment provided by admin sdk work for distributed counter tasks?

**Comment by jhuleatt** [comment]
@voxelbusters `FieldValue.increment` is the right thing for incrementing a value, but it doesn't solve the underlying problem that a Firestore document can only be updated about once per second. More info [here](https://firebase.google.com/docs/firestore/solutions/counters).

**Comment by jhuleatt** [comment]
We're not planning an official implementation for any other clients at this time, and we've changed the name of the "Web Client SDK" to "client sample" to try to make that a little more clear.

The [typescript sample implementation](https://github.com/firebase/extensions/blob/next/firestore-counter/clients/web/src/index.ts) is a good starting place for a node.js implementation of the counter.

In the future, I'd *like* to see how much of this logic we can move off of the client and into something like a callable function that's installed by the extension itself.
