### ISSUE TITLE
Can you add this FEATURE to storage-resize-images extension?

### ISSUE THREAD

**Issue by inglesuniversal** [firebase/extensions#285]
Auto-rotate images which have an EXIF orientation of 6 which is the problem I have with photos taken on iPhones.

I've requested this before and no answer was received.

Thanks

**Comment by russellwheatley** [comment]
Hi @inglesuniversal, do you mind filling out the issue template for new feature requests, please? And perhaps flesh out your particular problem a bit more and how it could be solved. Thank you.

**Comment by inglesuniversal** [comment]
Could you kindly point me where to find such link to submit my request?

Stay safe

**Comment by russellwheatley** [comment]
No problem, if you click `New Issue`:
<img width="923" alt="Screenshot 2020-04-28 at 08 30 41" src="https://user-images.githubusercontent.com/16018629/80459668-9e8e9e80-892a-11ea-9878-5260ef592ee4.png">


You have the choice of creating a `Feature Request`:
<img width="966" alt="Screenshot 2020-04-28 at 08 28 59" src="https://user-images.githubusercontent.com/16018629/80459577-769f3b00-892a-11ea-8b0e-f242497b07ce.png">

**Comment by inglesuniversal** [comment]
I just added it ... Hope it comes through though.

**Comment by EliasTouil** [comment]
When I upload a iphone photo file from my iPhone it works for me, although it seems like the thumbnails generated are not rotated (?)

**Comment by inglesuniversal** [comment]
would you like to share a link of a demo or sample image? I can read the EXIF data and verify its orientation I you would allow me so.

**Comment by EliasTouil** [comment]
![IMG_5598](https://user-images.githubusercontent.com/4231667/80518462-7caa1180-8954-11ea-9552-d69beac096c4.JPG)

Code previously used to check image rotation, and change it 
```
// from http://stackoverflow.com/a/32490603
function getOrientation(file, callback) {
  var reader = new FileReader();

  reader.onload = function(event) {
    var view = new DataView(event.target.result);

    if (view.getUint16(0, false) !== 0xffd8) return callback(-2);

    var length = view.byteLength,
      offset = 2;

    while (offset < length) {
      var marker = view.getUint16(offset, false);
      offset += 2;

      if (marker === 0xffe1) {
        if (view.getUint32((offset += 2), false) !== 0x45786966) {
          return callback(-1);
        }
        var little = view.getUint16((offset += 6), false) === 0x4949;
        offset += view.getUint32(offset + 4, little);
        var tags = view.getUint16(offset, little);
        offset += 2;

        for (var i = 0; i < tags; i++)
          if (view.getUint16(offset + i * 12, little) === 0x0112)
            return callback(view.getUint16(offset + i * 12 + 8, little));
      } else if ((marker & 0xff00) !== 0xff00) break;
      else offset += view.getUint16(offset, false);
    }
    return callback(-1);
  };

  reader.readAsArrayBuffer(file.slice(0, 64 * 1024));
}

function resetOrientation(file, srcOrientation, callback) {
  var img = new Image();
  img.onload = function() {
    var width = img.width,
      height = img.height,
      canvas = document.createElement("canvas"),
      ctx = canvas.getContext("2d");

    // set proper canvas dimensions before transform & export
    if (4 < srcOrientation && srcOrientation < 9) {
      canvas.width = height;
      canvas.height = width;
    } else {
      canvas.width = width;
      canvas.height = height;
    }

    // transform context before drawing image
    switch (srcOrientation) {
      case 2:
        ctx.transform(-1, 0, 0, 1, width, 0);
        break;
      case 3:
        ctx.transform(-1, 0, 0, -1, width, height);
        break;
      case 4:
        ctx.transform(1, 0, 0, -1, 0, height);
        break;
      case 5:
        ctx.transform(0, 1, 1, 0, 0, 0);
        break;
      case 6:
        ctx.transform(0, 1, -1, 0, height, 0);
        break;
      case 7:
        ctx.transform(0, -1, -1, 0, height, width);
        break;
      case 8:
        ctx.transform(0, -1, 1, 0, 0, width);
        break;
      default:
        break;
    }

    // draw image
    ctx.drawImage(img, 0, 0);
    // export blob
    canvas.toBlob(blob => callback(blob));
  };
  img.src = file;
}

exports.getOrientation = getOrientation;
exports.resetOrientation = resetOrientation;
```

In react component
```
let handleImageInput = e => {
    e.persist();
    e.preventDefault();
    let file = e.target.files[0];
    setImage(prevImg => ({ ...prevImg, file, processing: true }));

		// this has the right orientation in storage
		//uploadImage(e.target.files[0]);

		//This has not
		// getOrientation returns 6
    var reader = new FileReader();
    reader.onload = ee => {
      setImage(prevImg => ({ ...prevImg, fileData: ee.target.result }));
      getOrientation(e.target.files[0], orientation =>
        resetOrientation(ee.target.result, orientation, blob =>
          uploadImage(blob)
        )
      );
    };
    reader.readAsDataURL(file);
  };
  let uploadImage = blob => {
    setImage(prevImg => ({ ...prevImg, uploading: true, processing: false }));
    let storageRef = storage.ref(location).child("original");
    let uploadTask = storageRef.put(blob);

    uploadTask.on(
      "state_changed",
      snapshot => {
        let progress = (snapshot.bytesTransferred / snapshot.totalBytes) * 100;
        setImage(prevImg => ({ ...prevImg, progress }));
      },
      e => handleError(uploadError(e)),
      () =>
        uploadTask.snapshot.ref.getDownloadURL().then(url => {
          setImage(
            prevImg => ({ ...prevImg, url, uploading: false }),
            onImageUploaded(url)
          );
        })
    );
  };
```

**Comment by inglesuniversal** [comment]
oh, I see... If I'm not mistaking you fix to rotation of the image (prior to uploading it)... Am I right?

In my current scenario... I upload it to the bucket and let the image plugin do the rest for me.

**Comment by EliasTouil** [comment]
I edited my previous comment
> I looked into this issue today because I instantiated a new firebase project using 6 months old code.
I had a bit of code covering image orientation before upload, and it seemed broken.
>At some point, I decided to see what would happen if I removed it completely. Is storage rotating the images now? It seems like the extension is not rotating the thumbnails.

**Comment by inglesuniversal** [comment]
Thanks for sharing... In my particular case I found a bunch of code and upload libraries that handle thumbnail creation and rotating prior to upload... but for me there's the uncertainty that some phone may not handle that process completely if there are older models.

So for me to stay on the safe side... I've read an article about image magic with a command named AUTO-ORIENT ... so I simply apply it across the board to all uploads once the function is triggered and it has worked well for me... the only drawback is handling gif files... the thumbnail does show a bit of animation... Which the fixed the a newer update that uses SHARP library instead.

I'm not familiar with that library so I just asked for the feature to be part of the plugin itself... so I don't have to mess with the code on every update afterwards.

Thanks.

**Comment by russellwheatley** [comment]
Please use this issue thread #290 for this feature request.
