### ISSUE TITLE
 [ storage-resize-images-v0.1.6 ]  Generating wrong image when uploading with the same name

### ISSUE THREAD

**Issue by itssidhere** [firebase/extensions#286]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** (`storage-resize-images`, `firestore-send-email`, etc)
- Extension version: **\_**
- Configuration values (redact info where appropriate):
  - **\_**
  - **\_**

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.

##### Actual result

[ storage-resize-images-v0.1.6 ]
If I use the same name while uploading in bucket example dp.jpg, it's generating resized image of the older one . Can someone help me with this? It's happening only with the newer version. How can I downgrade?

**Comment by russellwheatley** [comment]
There has been some changes to this extension recently so I wonder whether this is a side effect. I'll have a look and get back to you @itssidhere. Thanks for raising the issue.

**Comment by russellwheatley** [comment]
Hey @itssidhere, could you confirm that you don't see this in your Firebase logs for the resize image extension, please?
<img width="418" alt="Screenshot 2020-04-28 at 08 22 04" src="https://user-images.githubusercontent.com/16018629/80458991-997d1f80-8929-11ea-9096-52fd23ed98a4.png">

**Comment by itssidhere** [comment]
@russellwheatley  I do see this after the resized image has been generated (which triggers the extension again)

**Comment by russellwheatley** [comment]
Thanks @itssidhere, I am able to reproduce the issue so I'll take a look at solving the problem.
