### ISSUE TITLE
fs-bq-import-collection failure: XXX_raw_changelog already exists

### ISSUE THREAD

**Issue by iislucas** [firebase/extensions#289]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **`firestore-bigquery-export`** (specifically: `fs-bq-import-collection`)
- Extension version: **`@firebaseextensions/fs-bq-import-collection@0.1.6`**
- Configuration values (redact info where appropriate):

```
Cloud Functions locationDescription
us-central1
Collection pathDescription
keens
Dataset IDDescription
firestore_export
Table IDDescription
keens
```

#### Steps to reproduce:

1. add 

```
$ npx @firebaseextensions/fs-bq-import-collection
? What is your Firebase project ID? keen-hacks
? What is the path of the the Cloud Firestore Collection you would like to import from? (This may, or may not, be the same Collection for which you plan to mirror changes.) keens
? What is the ID of the BigQuery dataset that you would like to use? (A dataset will be created if it doesn't already exist) firestore_export
? What is the identifying prefix of the BigQuery table that you would like to import to? (A table will be created if one doesn't already exist) keens
? How many documents should the import stream into BigQuery at once? 300
```

##### Expected result

Exports data to bigquery. 

##### Actual result

```
Importing data from Cloud Firestore Collection: keens, to BigQuery Dataset: firestore_export, Table: keens_raw_changelog
BigQuery dataset already exists: firestore_export
BigQuery table with name keens_raw_changelog already exists in dataset firestore_export!
View with id keens_raw_latest already exists in dataset firestore_export.
Error importing Collection to BigQuery: TypeError: Cannot read property 'constructor' of null
```

**Comment by iislucas** [comment]
maybe a dup of https://github.com/firebase/extensions/issues/284 ?

**Comment by russellwheatley** [comment]
Hey @iislucas, have you tried importing the data recently? The `firestore-bigquery-change-tracker` package was published 13 hours ago https://www.npmjs.com/package/@firebaseextensions/firestore-bigquery-change-tracker which the import script depends upon.

**Comment by iislucas** [comment]
Thanks for quick followup @russellwheatley, I just tried again now and still the same result.

**Comment by iislucas** [comment]
Maybe you need to release a new version of @firebaseextensions/fs-bq-import-collection in npm with the updated dependency so that the sub-dependency will get picked up?

**Comment by iislucas** [comment]
OK, doing a little re-installing of node modules to force myself to have v1.1.6, things seem to work now, so I think this is fixed, thanks! 

Here's what I did: 
```
npm remove -g @firebaseextensions/fs-bq-import-collection
npm install -g @firebaseextensions/firestore-bigquery-change-tracker
npm install -g @firebaseextensions/fs-bq-import-collection
```

(not sure that `npm install -g @firebaseextensions/firestore-bigquery-change-tracker` was needed)
