### ISSUE TITLE
auto-orient images and thumbnails when uploaded to firebase storage

### ISSUE THREAD

**Issue by inglesuniversal** [firebase/extensions#290]
### [REQUIRED] Step 2: Extension name

This feature request is for extension: `storage-resize-images`

### What feature would you like to see?

I have a public script which reads the EXIF data from jpeg images

As you are probably aware of... iPhone photos which are taken on portrait mode would appear sideways if you show the resulting thumbnail or uploaded image to the user inside an image tag even after your plugin completes generating the thumbnails.

I was successfully able to set a sample script to auto-orient the jpeg images by preselecting EXIF orientation image which value is read as: 6 (six)

I do NOT want to mess with the code you offer as prebuilt plugins... So I am kindly asking to include it as soon as possible.

If you need additional data please let me know.

Stay safe

### How would you use it?

**Comment by russellwheatley** [comment]
@inglesuniversal I hope you don't mind, but I updated your issue with the template headers. If you could update the text for each then the Firebase Extension team can assess if this feature is a good fit. Thank you.

**Comment by EliasTouil** [comment]
You can find additional information and screenshots about this request [here #285](https://github.com/firebase/extensions/issues/285#issuecomment-620746210)

**Comment by EliasTouil** [comment]
I would like to add that the original file has all the EXIF necessary to be rotated on the front end, but the thumbnails don't. 
@russellwheatley  Should I open a new issue for this? (please see #285 or link in the comment above).

**Comment by jakob-e** [comment]
Sharp has auto-rotate out of the box 
https://sharp.pixelplumbing.com/api-operation

```
return sharp(originalFile)
  .rotate()
  .resize(parseInt(width, 10), parseInt(height, 10), { fit: "inside" })
  .toFile(resizedFile);
```

**Comment by russellwheatley** [comment]
@EliasTouil If you only care about the image being correctly oriented in Firebase Storage via this extension, then I guess you don't need to create another issue. But if you would like the images metadata being carried over to the resized image(s) then you could create a new issue for a feature request.

**Comment by russellwheatley** [comment]
@jakob-e Thanks for the suggestion 👍

**Comment by inglesuniversal** [comment]
@russellwheatley Hi, do you need additional information to proceed with the update and fulfillment of my request? 

I would like to add, the even though the images can be rotated on the client side before the upload starts. It would be more VALUABLE to have the function run the two scenarios all built-in into the function.

You can't rely on older phones to do the job of rotating an uncertain number of photos that could make the upload process freeze.

I started this journey into GCP by modifying the sample code with ImageMagick and run both tasks once the upload is completed.

Stay safe and good luck!
