### ISSUE TITLE
firestore-bigquery-export: typed arrays for schema views

### ISSUE THREAD

**Issue by iislucas** [firebase/extensions#293]
### [REQUIRED] Step 2: Extension name

This feature request is for extension: **`firestore-bigquery-export`**, and in particular for the [GENERATE_SCHEMA_VIEWS.md](https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md)

### What feature would you like to see?

Support for arrays of different types. For example, some of the arrays in our project have maps inside them. A natural way to handle this would be to create a value field for each of the keys in the map. Even now, it's a bit strange that the array type doesn't specify if it's a string, number, boolean etc. 

### How would you use it?

To import and use bigquery on firestore objects that have arrays of nested maps.

**Comment by russellwheatley** [comment]
Fair enough, could be a Feature Request candidate. Thanks for the suggestion.

**Comment by i14h** [comment]
@fredzqm @IanWyszynski since you wrote the original version of this extension, what do you think about this feature request?

**Comment by IchordeDionysos** [comment]
Also, arrays are a bit weird how they transform values...

Strings will look like this in the database: `name`
Strings in Arrays will look like this in the database: `"name"`

**Comment by fredzqm** [comment]
This would be a very cool addition.
There is no reason this isn't built other than we didn't have time to.

As a reminder, the schema generator just create view with type-safe queries for us. For each individual use case, you can craft that query as well to fit your need.
It is intended to cover enough common cases to help developers get started but does not intend to be covering all use cases. Supporting common asks like "schema within an array" would be a great addition.

See [SQL fixtures](https://github.com/firebase/extensions/tree/next/firestore-bigquery-export/scripts/gen-schema-view/src/__tests__/fixtures/sql) for example of query generated.
This is [the entry point of the schema SQL builder](https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/scripts/gen-schema-view/src/schema.ts#L251-L314) if anyone wants to contribute.

**Comment by gregfenton** [comment]
Does anyone have an example of a schema (or view query) for an array of a simple map?  Something along the lines of:
```
{
    "orderName": "test order",
    "products": [
      { "productName": "crayon", "quantity": 23, "isGift": false},
      { "productName": "glue", "quantity": 1, "isGift": true}
    ]
}
```

**Comment by nwparker** [comment]
> Does anyone have an example of a schema (or view query) for an array of a simple map? Something along the lines of:
> 
> ```
> {
>     "orderName": "test order",
>     "cartItems": [
>       { "productName": "crayon", "quantity": 23, "isGift": false},
>       { "productName": "glue", "quantity": 1, "isGift": true}
>     ]
> }
> ```

You may be interested in:
https://github.com/firebase/extensions/issues/298#issuecomment-682233420
And possibly:
https://github.com/firebase/extensions/issues/292#issuecomment-682273922

**Comment by gregfenton** [comment]
Thank you @nwparker !  I have turned to looking at a combination of `unnest()` and `json_extract_array()` to extract the values from my data.  I suspect I'll be simply adding a hand-coded query to BQ rather than expecting `@firebaseextensions/fs-bq-schema-views` to generate one for me.

I got some good direction from [this question I posted on Stackoverflow](https://stackoverflow.com/questions/65545914/ability-to-get-the-index-or-ordinal-value-for-each-array-entry-in-bigquery).

**Comment by ludvigaldrin** [comment]
Din you guys solve this? I have a bit more simple than the example that I have an array with map objects. I have tried to add first a array field and inside the [] I added the map. But the output is that the array works great but it’s just one field with the whole map object as json. I’m not by my schema json so will post later. But it sounds like this could be solved?

**Comment by AhmetAydemir1** [comment]
did you guys solve?

**Comment by gregfenton** [comment]
@dackers86 how about the Firestore schema I outlined in [my post above](https://github.com/firebase/extensions/issues/293#issuecomment-735549320) ?  Or, if not, what more are you looking for?

**Comment by dackers86** [comment]
Thanks @gregfenton That looks a good starter, i'll use that as a baseline and maybe develop it further. For example:

```js
{
  "fields": [
    {
      "name": "test order",
      "type": "map",
      "fields": [
        {
          "name": "orderNumber",
          "type": "int"
        },
        {
          "name": "orderDate",
          "type": "string"
        },
        {
          "name": "orderTotal",
          "type": "double"
        },
        {
          "name": "cartItems",
          "type": "array",
          "fields": [
            {
              "name": "productName",
              "type": "string"
            },
            {
              "name": "quantity",
              "type": "int"
            },
            {
              "name": "isGift",
              "type": "boolean"
            }
          ]
        }
      ]
    }
  ]
}

```

**Comment by dackers86** [comment]
Initial PR added. For discussion, initial results have produced something similar to the following:

```sql
SELECT
  *
FROM
  (
    SELECT
      document_name,
      document_id,
      timestamp,
      operation,
      JSON_EXTRACT_SCALAR(data, '$.name') AS name,
      JSON_EXTRACT_SCALAR(data, '$.date') AS date,
      JSON_EXTRACT_SCALAR(data, '$.total') AS total,
      JSON_EXTRACT_SCALAR(cartItems, '$.productName') AS productName,
      JSON_EXTRACT_SCALAR(cartItems, '$.quantity') AS quantity,
      JSON_EXTRACT_SCALAR(cartItems, '$.isGift') AS isGift
    FROM
      `dev-extensions-testing.da_testing4.da_testing4_raw_changelog` da_testing4_raw_changelog
      LEFT JOIN UNNEST(
        json_extract_array(da_testing4_raw_changelog.data, '$.cartItems')
      ) cartItems WITH OFFSET _cartItems
  )
```

And for the latest view

```sql
-- Given a user-defined schema over a raw JSON changelog, returns the
-- schema elements of the latest set of live documents in the collection.
--   timestamp: The Firestore timestamp at which the event took place.
--   operation: One of INSERT, UPDATE, DELETE, IMPORT.
--   event_id: The event that wrote this row.
--   <schema-fields>: This can be one, many, or no typed-columns
--                    corresponding to fields defined in the schema.
SELECT
  document_name,
  document_id,
  timestamp,
  operation,
  name,
  date,
  total,
  productName,
  quantity,
  isGift
FROM
  (
    SELECT
      document_name,
      document_id,
      FIRST_VALUE(timestamp) OVER(
        PARTITION BY document_name
        ORDER BY
          timestamp DESC
      ) AS timestamp,
      FIRST_VALUE(operation) OVER(
        PARTITION BY document_name
        ORDER BY
          timestamp DESC
      ) AS operation,
      FIRST_VALUE(operation) OVER(
        PARTITION BY document_name
        ORDER BY
          timestamp DESC
      ) = "DELETE" AS is_deleted,
      FIRST_VALUE(JSON_EXTRACT_SCALAR(data, '$.name')) OVER(
        PARTITION BY document_name
        ORDER BY
          timestamp DESC
      ) AS name,
      FIRST_VALUE(JSON_EXTRACT_SCALAR(data, '$.date')) OVER(
        PARTITION BY document_name
        ORDER BY
          timestamp DESC
      ) AS date,
      FIRST_VALUE(JSON_EXTRACT_SCALAR(data, '$.total')) OVER(
        PARTITION BY document_name
        ORDER BY
          timestamp DESC
      ) AS total,
      JSON_EXTRACT_SCALAR(cartItems, '$.productName') AS productName,
      JSON_EXTRACT_SCALAR(cartItems, '$.quantity') AS quantity,
      JSON_EXTRACT_SCALAR(cartItems, '$.isGift') AS isGift
    FROM
      `dev-extensions-testing.da_testing4.da_testing4_raw_latest`
      LEFT JOIN unnest(
        json_extract_array(
          `dev-extensions-testing.da_testing4.da_testing4_raw_latest`.data,
          '$.cartItems'
        )
      ) cartItems WITH OFFSET _cartItems
  )
WHERE
  NOT is_deleted
GROUP BY
  document_name,
  document_id,
  timestamp,
  operation,
  name,
  date,
  total,
  productName,
  quantity,
  isGift
```

Samples results lead to multiple rows per array item.

![image](https://user-images.githubusercontent.com/2060661/207845981-6ae386e6-5f47-4d5a-8800-fcf2dd2dc00d.png)


## Questions

1. Would developers find this easier, if the array columns are separated into different columns, as opposed to adding multiple rows.
2. The latest view may have some performance issues, the latest BQ updates includes a much more performant script. For readability and ease upgrade. Should this be included in the update or as a separate PR

**Comment by gregfenton** [comment]
Hmmm....I don't think I even considered using `FIRST_VALUE`.  Cool!

# Answers
1. I'm not sure how the columns approach would work?  The number of columns per FS document (e.g. items in the shopping cart) would vary.  So how could BQ handle that?  To me, the multiple rows approach works though it definitely makes "traditional SQL" folks uneasy 😃
2. Personally I'd be cool if there was a script/tool provided that could generate the SQL for me rather than directly update the BQ configuration with it (as view, right?).  I likely will end up wanting to tweak it in some ways.  Having the tool to give me the initial SQL would be a huge help.

**Comment by dackers86** [comment]
BigQuery has a max [columns](https://cloud.google.com/bigquery/quotas#:~:text=A%20table%2C%20query%20result%2C%20or%20view%20definition%20can,have%20up%20to%2010%2C000%20columns.&text=The%20total%20query%20result%20sizes,information%2C%20see%20BigQuery%20Omni%20limitations.&text=With%20on%2Ddemand%20pricing%2C%20your,up%20to%202%2C000%20concurrent%20slots.) of `10,000`.

I believe the [official](https://cloud.google.com/firestore/docs/manage-data/export-import) cloud tool follows the same method for auto-generating columns.

Also agreed the `traditional` SQL.

For creating the views, we could a `silent` flag, as the `gen-schema` tool provides the output, we could provide a flag that ensures the views are not created automatically?
