### ISSUE TITLE
fs-bq-import-collection supports command line arguments

### ISSUE THREAD

**Issue by iislucas** [firebase/extensions#294]
### [REQUIRED] Step 2: Extension name

This feature request is for extension: **firestore-bigquery-export**, specifically the fs-bq-import-collection script.

### What feature would you like to see?

Would be great to be able to provide the arguments on the command line instead of interactively.

### How would you use it?

To save from re-typing stuff so often.

**Comment by russellwheatley** [comment]
Considering it is an option on `gen-schema-view` script, this is a possible idea for a feature request. Thanks again.

**Comment by karayu** [comment]
Closing because PR is merged!
