### ISSUE TITLE
firestore-bigquery-export: Strings imported into bigquery are wrapped in extra quotes

### ISSUE THREAD

**Issue by iislucas** [firebase/extensions#295]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **`firestore-bigquery-export`** in particular for the view creating script (https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md)
- Extension version: **0.1.6**

### [REQUIRED] Step 3: Describe the problem

String values in bigquery are wrapped in extra double-quote characters. So you'll see `"foo"` in bigquery instead of `foo`.

#### Steps to reproduce:

Import data into bigquery that has string values. 

##### Expected result

The string values are the values in bigquery. 

##### Actual result

The strings get an extra double-quote character (`"`) at the start, and one at the end too. This means you can spend a long time wondering why your regexps don't work, only to realise it's bad data. :)

**Comment by russellwheatley** [comment]
@iislucas Do you mind sharing a screenshot (of insensitive data) so I can understand the problem a bit better please? The data from Firestore is stringified (JSON) before being entered into a row in  a BigQuery table.

**Comment by iislucas** [comment]
Good point, sorry I wasn't clear, it's to do with the schema views script. It results in extra quotes in string fields.

**Comment by russellwheatley** [comment]
You're correct, as this example illustrates, there is an extra set of quotes around "url" value when using the `gen-schema-view` script:
<img width="202" alt="Screenshot 2020-05-01 at 12 45 28" src="https://user-images.githubusercontent.com/16018629/80803437-2df5b500-8baa-11ea-9926-92c9ce5e807f.png">

**Comment by iislucas** [comment]
I think this is a bug? (either in documentation, or implementation; I think probably implementation as I don't see any reason to have JSON escaped strings values in bigquery)

**Comment by russellwheatley** [comment]
Yeah, you're right on that one, @iislucas

**Comment by devth** [comment]
It looks like arrays are still wrapped in double quotes: 
![image](https://user-images.githubusercontent.com/86107/98260281-618e0f00-1f40-11eb-9f42-a74262840e5e.png)
