### ISSUE TITLE
FirestoreShardedCounter Swift Client

### ISSUE THREAD

**Issue by naturalui** [firebase/extensions#299]
### [READ] Step 1: Are you in the right place?

Got the extension working with Javascript Sample Client but was wondering if anyone is aware of a Swift port.

### [REQUIRED] Step 2: Extension name

Distributed Counter - https://github.com/firebase/extensions/tree/master/firestore-counter

### What feature would you like to see?

Swift Client Library for firestore-counter

### How would you use it?

In our iOS Application :)

**Comment by russellwheatley** [comment]
Seems like a potential feature request, thanks for the submission.

**Comment by jhuleatt** [comment]
@peterfriese would you be interested in giving this a try before we release it?
