### ISSUE TITLE
Uninstall or change Deployment Location

### ISSUE THREAD

**Issue by bogdannedelcu** [firebase/extensions#3]
Excelent extension the Resize Images, really usefull!

How can I uninstall it or change the location from US to Europe as to be near my storage bucket location?

Best regards,
Bogdan

**Comment by rosariopfernandes** [comment]
@bogdannedelcu Unfortunately, that parameter can't be reconfigured after install. I'd suggest you [uninstall](https://firebase.google.com/docs/extensions/manage-installed-extensions#uninstall) and reinstall the extension.

**Comment by bogdannedelcu** [comment]
The Uninstall button is down bellow the page. Thank you!
