### ISSUE TITLE
Delete User Data extension to allow targeting documents for a given field value

### ISSUE THREAD

**Issue by bhr** [firebase/extensions#305]
### Extension name

This feature request is for extension: **delete-user-data**

### What feature would you like to see?

Ability to target documents that match the user ID as one of the fields in Firestore.
One example would be a collection of `articles` and each article stores the author's UID in the `authorUID` field. When the user decides to delete their account, all articles the user is the author of should be deleted. 

### How would you use it?

I'd use this feature to remove all user associated data in Firestore applications.

**Comment by russellwheatley** [comment]
Hey @bhr, thanks for the feedback. This sounds like a potential feature request candidate.

**Comment by i14h** [comment]
@bhr thanks for the suggestion. We think there's potential value here, but everyone has a slightly different way of storing user data that no amount of customizability will support them. We'll keep looking for signals on this, and if a common theme emerges we'll implement it in future versions. If anyone else has thoughts or ideas on this comment under this issue.

**Comment by TylerAHolden** [comment]
+1

**Comment by YazeedAlKhalaf** [comment]
I think he means a way to query the DB, so it would fit all uses because queries are customizable.

For example:
some user has 50 posts and I would like them to be deleted the moment he deletes his account, we can make a query that deletes all posts he is the author on by checking `authorId` or whatever the name maybe.

That would make the extension a lot more powerful!

**Comment by YazeedAlKhalaf** [comment]
Why is this blocked? I feel it is a very good addition to the extension.

**Comment by YazeedAlKhalaf** [comment]
I think I found a potential solution that is checking if the document has been deleted using a cloud function and if that is the case then delete all posts/articles that have `authorId` as the UID of the deleted user!

**Comment by jhuleatt** [comment]
Thanks for the requests, all. As Iman said, this is a tough problem to solve because everyone's schema is different. We recommend writing your own Cloud Functions to either work in conjunction with this extension, or to use instead of this extension. It's discussed in more detail in the [Extensions codelab](https://developers.google.com/codelabs/firebase-extensions#5):

> However, extensions can't solve every problem, and the issue of user data deletion is a good example of that. Though the Delete User Data extension addresses the current complaint that emails are still exposed after a user deletes their account, the extension won't delete everything. For example, the item listing is still available, and any images in Cloud Storage will stick around, too. The Delete User Data extension does allow us to configure a Cloud Storage path to delete, but since users can upload many different files with lots of different names, you won't be able to configure this extension to automatically delete these artifacts. For situations like this, Cloud Functions for Firebase might be a better fit so that you can write code that is specific to your app's data model.

**Comment by TylerAHolden** [comment]
I cloned this extension and wrote some changes for the config where if you added something like `articles.authorId` it would run a search query on articles first and delete everything where `authorId` matched the user ID. I can see how adding database queries could potentially be unknowingly costly but it seems like something similar is enough to make this function useable in production applications for a wide range of schema styles. I wonder how many production applications get by with ONLY deleting based on UID - it doesn't seem like very many unless you built your schema with this exact methodology in mind. Happy to share snippets if anyone is interested though.

**Comment by JoKuebler** [comment]
> I cloned this extension and wrote some changes for the config where if you added something like `articles.authorId` it would run a search query on articles first and delete everything where `authorId` matched the user ID. I can see how adding database queries could potentially be unknowingly costly but it seems like something similar is enough to make this function useable in production applications for a wide range of schema styles. I wonder how many production applications get by with ONLY deleting based on UID - it doesn't seem like very many unless you built your schema with this exact methodology in mind. Happy to share snippets if anyone is interested though.

I'd be interested in using this. Can you share some snippets?

**Comment by TylerAHolden** [comment]
> I'd be interested in using this. Can you share some snippets?

https://gist.github.com/TylerAHolden/10d0ee986a8a1f743fa09154118b177b

I forgot I also added the ability to delete storage paths based on a field from the userData. In other words, you can pass {DEFAULT}/{userData.avatar} into the storage path variable and it will first get collection('users').doc(UID).get() and then get the avatar field and delete that file from the storage bucket. It's a pretty hasty implementation but it works!

**Comment by dx777** [comment]
This should be the main purpose, for this extension, and you blocked it? No way.

**Comment by i14h** [comment]
we're going to take a deeper look into this in #773
