### ISSUE TITLE
Feature request for "Limit Child Nodes" extension

### ISSUE THREAD

**Issue by devcoderrajarshi** [firebase/extensions#308]
There is a need for multiple child paths and child count to limit the child count using **"Limit Child Nodes" extension**
This feature can be used to apply rules to multiple paths in a project with different child counts.
It can be a array of comma separated paths like ['path1', 'path2'] applied for path filed and child limit field

**Comment by mbleigh** [comment]
This is already possible, but in a slightly different way. The way you do this is to install multiple instances of the extension, one for each path you want to limit.
