### ISSUE TITLE
Getting the exact document name

### ISSUE THREAD

**Issue by jay-shah** [firebase/extensions#309]
The current document_name shows the whole path to get to that document for example `projects/{project name}/databases/(default)/documents/{collection}/{document}`. Is there an easy way to get just the document?

**Comment by Ehesp** [comment]
Hi @jay-shah - would you be able to provide a bit more context please? Which extension are you having issues with?

**Comment by jay-shah** [comment]
Hi @Ehesp, thanks for your reply. It is the bigquery export extension. Please let me know if there is a better place to post my question.

**Comment by russellwheatley** [comment]
Hey @jay-shah, you're in the right place if you have an issue with a Firebase Extension! Could you outline the problem you're having with the bigquery extension, please?

**Comment by Neilpoulin** [comment]
I think i'm having the same problem as the author of this issue. All of the samples (including the readme [here](https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/guides/EXAMPLE_QUERIES.md) indicate that you can query your firestore documents by their documented, using `where document_name = 'some_id'`. However, the `document_name` field in bigquery that is generated from the firebase bigquery export extension is the fully qualified path, like `projects/{project name}/databases/(default)/documents/{collection}/{document}`

When i am writing queries and working in data studio, this is not a reasonable format to do things like joins, etc.

**Comment by jay-shah** [comment]
@Neilpoulin It seems like this has been fixed in Version 0.1.6
