### ISSUE TITLE
"An unexpected error occurred" when installing firestore-bigquery-export

### ISSUE THREAD

**Issue by bfelbo** [firebase/extensions#311]
### [READ] Step 1: Are you in the right place?
Yes

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-bigquery-export**
- Extension version: **0.1.5**
- Configuration values (redact info where appropriate):
```
Cloud Functions location
us-central1

Collection path
posts

Dataset ID
firestore_export

Table ID
posts
```

#### Steps to reproduce:

What happened? How can we make the problem occur?
Inside my project on console.firebase.google.com, I clicked 'Extensions' and then 'Install' under 'Export Collections to BigQuery'. I did not modify any settings (i.e. used the defaults) and clicked install. Then it errored. See screenshots below.

##### Expected result
No error.

##### Actual result
"An unexpected error occurred." error message that prevented our install. 

![image](https://user-images.githubusercontent.com/23178145/82272422-6e398f00-992f-11ea-9ffb-64db36e2ac07.png)

![image](https://user-images.githubusercontent.com/23178145/82272415-6843ae00-992f-11ea-9af7-bf1d6c8c6d9d.png)

**Comment by zchauvin** [comment]
I'm also experiencing this. Things I've tried: 

- Using an existing collections path (both with and without a leading /), or a non-existent collection
- Using an existing dataset ID, or a non-existent dataset ID 
- Installing the extension via the CLI `firebase ext:install firestore-bigquery-export --project=projectId_or_alias`

Unfortunately, I always get "An unexpected error occurred."

**Comment by russellwheatley** [comment]
Hey @bfelbo, I've also had similar problems when trying to install extensions from a new project. We will let you know when the issue has been resolved. Thank you for your patience!

**Comment by laurenzlong** [comment]
Thank you for reporting @bfelbo! We've rolled back a backend change that was problematic. (It was causing not just this extension to fail to install, but all extensions.) You should now be able to install the extension again. Please comment here if you're still having issues.

**Comment by Salakar** [comment]
@bfelbo @zchauvin this should be fixed now, please could you try again?

**Comment by bfelbo** [comment]
Thanks for the quick response. It installed now. 

The guide doesn't seem to make sense though. When going to the link in step 1 (see below), I immediately get this popup that forces me to go to "Cloud Platform", making the rest of the guide useless.

We haven't used Cloud Firestore or any of this in any way so it's surprising that the guide doesn't work for us.

![image](https://user-images.githubusercontent.com/23178145/82504862-3c503600-9ab1-11ea-8411-e3bba88a851e.png)


![image](https://user-images.githubusercontent.com/23178145/82504811-20e52b00-9ab1-11ea-89a4-15d30e592248.png)

**Comment by bfelbo** [comment]
Are we supposed to click on the Switch to Native Mode inside the Cloud Platform UI to be able to follow the rest of the guide?

![image](https://user-images.githubusercontent.com/23178145/82505138-e039e180-9ab1-11ea-87c9-958b837224d5.png)

**Comment by laurenzlong** [comment]
Hi @bfelbo yes please select "switch to native mode" if you are aiming to use Firestore with Firebase SDKs. Most Firebase customers use this mode, so that's why the guide is written assuming that you have Firestore in Native mode. Please see https://cloud.google.com/datastore/docs/firestore-or-datastore#feature_comparison for a feature comparison. 

Did you use Datastore previously? (Or enabled the API at some point?) That might be why you have Firestore in Datastore mode.

**Comment by bfelbo** [comment]
Thanks @laurenzlong. We switched now and can follow the rest of the guide.

I'm pretty sure we've never used Datastore or enabled the API.
