### ISSUE TITLE
firestore-bigquery-export ability to export to partitioned tables

### ISSUE THREAD

**Issue by kevinkaar** [firebase/extensions#316]
This feature request is for extension: firestore-bigquery-export

Would really help with billing to be able to export firestore collections to BigQuery using partitioned (e.g by ingestion time, daily) tables.

**Comment by russellwheatley** [comment]
Hi @kevinkaar, thanks for the suggestion. As far as I can tell from the BigQuery nodejs [documentation](https://googleapis.dev/nodejs/bigquery/latest/index.html), it doesn't seem possible to be able to create partitioned tables. It would have to be via the API. Not sure if this is something the Firebase Extensions will be considering in the short term, but I'm sure they will consider it.

**Comment by seansaleh** [comment]
It does appear to be possible, a link from their docs: https://github.com/googleapis/nodejs-bigquery/blob/master/samples/createTablePartitioned.js
``` js
const options = {
      schema: schema,
      location: 'US',
      timePartitioning: {
        type: 'DAY',
        expirationMs: '7776000000',
        field: 'date',
      },
    };
```

**Comment by russellwheatley** [comment]
@seansaleh nice, I didn't see that 😄

**Comment by russellwheatley** [comment]
Hey @kevinkaar, the Firebase Extension's team have reviewed this idea. As you're probably aware, there are a multitude of features available for BigQuery and that scope has to be limited to a degree. Therefore, the use of partitioned tables has been deemed outside the purview of the BigQuery Firestore extension.  Thanks once again for the suggestion though, if you do have anymore, feel free to raise another issue.

**Comment by mustafaekim** [comment]
Hi, if the extension cannot create a partitioned table, what is the right approach to export a collection of millions of objects into a big query  table? If I use the extension as it is today, the queries become very slow due to the full scan. Before I started to use the extension, I was thinking like I would add indexes into the bigquery table but that does not exist at all. So what is the solution?

**Comment by amirulmanaf** [comment]
> Hi, if the extension cannot create a partitioned table, what is the right approach to export a collection of millions of objects into a big query table? If I use the extension as it is today, the queries become very slow due to the full scan. Before I started to use the extension, I was thinking like I would add indexes into the bigquery table but that does not exist at all. So what is the solution?

agree.  there's a growing concern here because the tables keep growing and the nature of the exported bq table from firestore is such that they aren't immediately usable without a scheduled query running to clean up and rearranging the data on it in order to be consumed by datastudio for example.  and when the table is too large for the BI engine to support, it becomes a requirement that the connecting tables become partitioned ones.  i understand we can easily run those scheduled transforms to feed a partitioned table, but the source table fed by the extension is quickly becoming this gigantic monster of a non-partitioned table, which would then be really expensive to run the scheduled transforms on.

**Comment by amirulmanaf** [comment]
> > Hi, if the extension cannot create a partitioned table, what is the right approach to export a collection of millions of objects into a big query table? If I use the extension as it is today, the queries become very slow due to the full scan. Before I started to use the extension, I was thinking like I would add indexes into the bigquery table but that does not exist at all. So what is the solution?
> 
> agree. there's a growing concern here because the tables keep growing and the nature of the exported bq table from firestore is such that they aren't immediately usable without a scheduled query running to clean up and rearranging the data on it in order to be consumed by datastudio for example. and when the table is too large for the BI engine to support, it becomes a requirement that the connecting tables become partitioned ones. i understand we can easily run those scheduled transforms to feed a partitioned table, but the source table fed by the extension is quickly becoming this gigantic monster of a non-partitioned table, which would then be really expensive to run the scheduled transforms on.

found a workaround to this.  all we have to do is create a timestamp-partitioned table with the exact same contents the original target table fed by the extension, delete the original table, and replace it with another partitioned table with the same name as the original.

what happens now is the extension will start to perform streaming inserts to the new partitioned table and it does so more efficiently by looking at those partitions and inserting them to the correct one as per the timestamp.  this also means our scheduled transforms and BI engine / datastudio would also be much more cost-efficient when drawing from these tables.

**Comment by russellwheatley** [comment]
Hi @amirulmanaf, as a quick update on this. The FE team are reconsidering allowing partitioned tables as an option (on fresh extension installations, you cannot change table type once instantiated). One of the concerns will be to assess whether there are any unforeseen side effects to allowing partitioned tables as part of the extension.

I've ran some preliminary tests and there doesn't appear to be an issue. But I'd be grateful if you could also update this issue feed if you run into any problems of your own. Thanks!

**Comment by amirulmanaf** [comment]
hi @russellwheatley.  so far i've not seen any issues on my side with the extension working on those partitioned tables.  will post here as we find them.

many thanks and superb job on the extensions, FE team!

**Comment by abejr** [comment]
Would this feature help with frequently changing collections? In my case, I have a collection that each document changes many many times, and my BigQuery table is huge already, but there aren't so many documents (maybe 20k). This makes queries in Data Studio too slow. Thanks

**Comment by russellwheatley** [comment]
If you're concerned about query speeds, partitioned tables will improve them. Here is some [documentation](https://cloud.google.com/bigquery/docs/partitioned-tables) on partitioned tables that will help explain.

**Comment by russellwheatley** [comment]
Hey folks, table partitioning does appear to be something the Firebase Extension's team is interested in implementing. There are 3 different ways to partition your data:

1. Ingestion time of data.  This requires only one additional input; Which type of partition you would like: `DAY`, `HOUR`, `MONTH`, and `YEAR`. 
2. DATE/TIMESTAMP/DATETIME. This requires two inputs. The type of partition as described above, and a specific time field in your table (one of `DATE`, `TIMESTAMP`, or `DATETIME`) you would like to sort by.
3. Range partitioning. This requires 4 different inputs. `field`, `start`, `end`, & `interval`. The `field` you'd like to sort by as described in option 2, `start` & `end` uses the field you're sorting by to select the data you'd like to target for partitioning. The `interval` parameter will partition the data into set amounts. The example [here](https://cloud.google.com/bigquery/docs/partitioned-tables#integer_range) is pretty good for explaining this further.

Option 1 seems the likely choice. 

Option 2 doesn't seem necessary to me. We already have a predefined schema. The `timestamp` column would be so similar to ingestion time as to be negligible in my opinion. 

Option 3 still appears to be experimental at this point and requires 4 additional parameters.

What do you think, @jhuleatt?

Hey @abejr, have you experienced any problems with you partitioned tables? What type of partition table did you use?    

Also worth noting this feature will not update existing tables to partitioned tables. Has to be freshly installed (& thus freshly created BigQuery table) `firestore-bigquery-export` extension.

**Comment by russellwheatley** [comment]
Hey @amirulmanaf , have you experienced any problems with you partitioned tables? What type of partition table did you use?

**Comment by jhuleatt** [comment]
Thanks for laying out the options, @russellwheatley. Ingestion time makes a lot of sense to me since that will mirror the time a Firestore write actually happened.

Some other concerns:

- Is there any way to make this backwards-compatible?
- Will we need to modify the import script to support partitioned tables?
- I assume we'll need to update the schema-views script as well?
