### ISSUE TITLE
extensions/firestore-bigquery-export: geopoint function args are incorrect

### ISSUE THREAD

**Issue by vpetlu** [firebase/extensions#318]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your configuration

- Extension name: `firestore-bigquery-export`
- Extension version: 0.1.5
- Configuration values (redact info where appropriate): n/a

### [REQUIRED] Step 3: Describe the problem
When exporting geolocations from Firestore into BigQuery, the args are flipped causing lats and longs to be swapped.

[ST_GEOGPOINT](https://cloud.google.com/bigquery/docs/reference/standard-sql/geography_functions#st_geogpoint) interface definition: `ST_GEOGPOINT(longitude, latitude)`

[firestoreGeopointDefinition](https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/scripts/gen-schema-view/src/udf.ts#L143) code: `(ST_GEOGPOINT(SAFE_CAST(JSON_EXTRACT(json, '$._latitude') AS NUMERIC), SAFE_CAST(JSON_EXTRACT(json, '$._longitude') AS NUMERIC)))`

**Comment by vpetlu** [comment]
FYI, I have a PR ready to address this already.  We've signed a CLA, waiting for the OK from Google before I submit.

**Comment by russellwheatley** [comment]
Thanks for reporting the issue @vpetlu, I'll take a look and report back.

**Comment by vpetlu** [comment]
Thanks.  PR: https://github.com/firebase/extensions/pull/320

**Comment by russellwheatley** [comment]
Hey @vpetlu, your observation is correct, the latitude and longitude values are placed incorrectly. However, I'm having trouble replicating it in my BigQuery table views (changelog and latest). Do you mind providing me with instructions on how to reproduce, please?  Thank you!

**Comment by russellwheatley** [comment]
Thanks for raising the issue @vpetlu I was finally able to see it in the changelog after I fixed another bug in the script. I've approved your PR even though I've also made the same change in my [PR](https://github.com/firebase/extensions/pull/333). I hope yours gets merged in before mine :)
