### ISSUE TITLE
Views generated by the fs-bq-schema-views script don't parse firestore timestamps correctly

### ISSUE THREAD

**Issue by caesarivs** [firebase/extensions#324]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-bigquery-export**
- Extension version: **0.1.5**

#### Steps to reproduce:

1. Have an instance of the extension set up to send updates to BigQuery from a collection where documents have a timestamp field
2. Use the fs-bq-schema-views script to generate views

##### Expected result

View shows timestamps corresponding to the value on firestore

##### Actual result

View has null values

**Comment by caesarivs** [comment]
On the generated view, the query goes something like this:

```
`firestore_export.firestoreTimestamp`(JSON_EXTRACT_SCALAR(data, '$.date')) AS date
```

I tried using `JSON_EXTRACT()` instead and apparently it yielded an actual timestamp

**Comment by caesarivs** [comment]
The script generates two schema views, one for the changelog and one for the latest. The latest schema view ignores the actual date for some reason:

```
SELECT
  *
EXCEPT
  (date)
```

I was able to tinker with the schema views actual queries and get the date part from the timestamp which is what I'm interested in, but I don't think this is an intended behaviour

**Comment by Sterv** [comment]
I'm having the same issue. Here's some other information.

The "latest" schema excludes the timestamp field (for me it is called "createdAt") and two additional fields are created: `createdAt_seconds, createdAt_nanoseconds`.

The query for the "latest" view excludes `createdAt` in the GROUP_BY section, and adds an extra `createdAt_seconds, createdAt_nanoseconds` on the last line, where I expect to find the `createdAt` field name.

**Comment by caesarivs** [comment]
Yes, the firestore timestamp fields appear on the JSON as an object with `_seconds' and `_nanoseconds` keys, the script actually generates a function `firestoreTimestamp()` to convert those seconds and nanoseconds to milliseconds, and then use the result to generate a timestamp with BigQuery's `TIMESTAMP_MILLIS()`. But this doesn't work as intended because of the use of `JSON_EXTRACT_SCALAR()` on the timestamp object. Apparently, changing it to `JSON_EXTRACT()` solves the issue on timestamps.

**Comment by Sterv** [comment]
How can I use the updated script from the `next` branch (rather than the `master`) using npx? 

`npx @firebaseextensions/fs-bq-schema-views#next` does not work for me
