### ISSUE TITLE
Trigger Email extention's SMTP setup is very ambiguous

### ISSUE THREAD

**Issue by bhaskar-nair2** [firebase/extensions#325]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **\firestore-send-email**

### What feature would you like to see?

1. The field to add the smtp client details is very confusing. Even the oldest piece of softwares had very clearly defined fields for the required data along with the caveats associated.

2. There is no "Test" button to test out your settings before/after saving the configuration. One might argue that it can be done via making a new entry the table, but then, we could have stuck to libraries and books, why bother making a seach engine at all.

3. The errors responses make no sense. It might be so that experienced users can understand it. But imho most users won't be as experienced.

### How would you use it?

1. A clearly defined set of fields will not only make it easy for the user to input the required data, it will surely decrease chances of making erros.

2. That would be "Very Convenient".

3.  Something more descriptive to search about will help the community come up with FAQs for the extention.

**Comment by bhaskar-nair2** [comment]
@Ehesp I don't think it is just a documentation issue.

**Comment by Ehesp** [comment]
Hi @bhaskar-nair2

Thanks for your comments. After discussing internally, we have decided to leave the SMTP field open for plain text, otherwise it would be too restrictive having specific fields.

We will however look into seeing if there's a way to validate SMTP credentials are valid before deploying the extension.

Thanks
