### ISSUE TITLE
storage-resize-images resizes SVG files, resulting in wrong content types

### ISSUE THREAD

**Issue by nicoqh** [firebase/extensions#326]
### [READ] Step 1: Are you in the right place?

...

### [REQUIRED] Step 2: Describe your configuration

- Extension name: storage-resize-images
- Extension version: 0.1.8

### [REQUIRED] Step 3: Describe the problem

Without an explicit output format, [Sharp infers it from the input file](https://sharp.pixelplumbing.com/api-output#tofile):

> If no explicit format is set, the output format will match the input image, except GIF and SVG input which become PNG output.

This causes problems with SVG images:

1. Upload an SVG (content type `image/svg+xml`)
2. The extension proceeds because the validation passes (`contentType.startsWith("image/")`)
3. Sharp converts the file to PNG
4. Metadata is copied from the original object, so ContentType is set to `image/svg+xml`
5. The browser (including Firebase Console) isn't able to render the image ("invalid xml")

The extension has to set a content type, otherwise it defaults to `application/octet-stream`.

Possible solutions:

1. Skip vector images. Vector images aren't really resized, so it's probably not an interesting use case for this extension.
2. Set the content type based on the resulting Sharp format

I can make a PR if you'd like. My proposal would be to limit this extension to the formats supported by Sharp (JPEG, PNG, WebP, GIF, SVG and TIFF) *except* SVG.

**Comment by rosariopfernandes** [comment]
+1 for skipping vector images resize

**Comment by Ehesp** [comment]
Makes sense, SVGs are scalable anyway! Will get this flagged for an update.
