### ISSUE TITLE
firestore-bigquery-export backfilled document_names differ from exported document_names

### ISSUE THREAD

**Issue by augustzf** [firebase/extensions#33]
### Configuration

- Extension name: firestore-bigquery-export

### The problem

Backfilled data rows in BigQuery receive different `document_name` values than rows inserted into BigQuery by the Firebase extension:

* Backfilled rows (operation = "IMPORT") have `document_name` values in this format: `<collection_name>/<document_id>`
* Exported rows (operation != "IMPORT") have `document_name` values in this format: 
`<projects/<project_name>/databases/(default)/documents/<collection_name>/<document_id>`

The consequence is that updates to imported documents will cause the original document to be duplicated in the `*_raw_latest` view.

To reproduce:

1. Create a new Firestore collection `test`. Add a document to this collection.
2. Run the importer script. It will create a changelog table (`test_raw_changelog
`) and a view (`test_raw_latest`).
3. Modify the Firestore document.
4. Query the `test_raw_latest` view. The single Firestore document now appears twice, with different document_name.

### Expected result

Expected `document_name` values to be the same for backfilled and exported rows.

**Comment by augustzf** [comment]
This PR is a suggested fix: https://github.com/firebase/extensions/pull/36

**Comment by fredzqm** [comment]
@IanWyszynski Could you update the import script to include `project_name` as well?
