### ISSUE TITLE
chore(*): within all extension.yaml files, change syntax of parameter ref to ${param:PARAMETER_NAME}

### ISSUE THREAD

**Issue by rachelsaunders** [firebase/extensions#331]
Currently, all the official Firebase extensions in their extension.yaml files use the parameter reference syntax of ${PARAMETER_NAME}.  However, with the recent [v8.4.0 release](https://github.com/firebase/firebase-tools/releases/tag/v8.4.0), we can/should use the "universal" syntax of ${param:PARAMETER_NAME} in extension.yaml files.

"universal" = all extension files now support this parameter reference syntax (and it's the preferred syntax :-)

**Comment by Ehesp** [comment]
@rachelsaunders does this also apply to built in parameters (such as `PROJECT_ID`)?

**Comment by rachelsaunders** [comment]
Yep, it's my understanding that it's _any_ parameter, both user-configured and auto-populated.  We can def double-check, though @laurenzlong

**Comment by karayu** [comment]
Let's keep this change unmerged until we get more soak time in the CLI. The CLI supporting this released about a month ago.

**Comment by karayu** [comment]
Assigning to Kevin for FYI/tracking
