### ISSUE TITLE
Possibility to temporarily disable/deactivate an extension without uninstalling it

### ISSUE THREAD

**Issue by RegniBlef** [firebase/extensions#334]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

all extensions

### What feature would you like to see?

An option to temporarily disable/deactivate an extension without having to completely uninstall it.

### How would you use it?

1) Select one of your installed extensions under Firebase extensions

2) Button to temporarily disable/deactivate it.

**Comment by jhuleatt** [comment]
Thanks for the feature request @RegniBlef!

This is a Cloud Functions platform-level request, so I've logged it with the engineering team internally. I'm going to close this issue out, but if you'd like to comment here and provide some more context on when you'd use this feature, it would help the team prioritize this feature request.

**Comment by jhuleatt** [comment]
This is tracked in the Cloud Functions public issue tracker: https://issuetracker.google.com/issues/119335117
