### ISSUE TITLE
Camera Images Upload works fine but when i generate thumbnail it gets rotated  firebase cloud  function 

### ISSUE THREAD

**Issue by HamidRazaGoraya** [firebase/extensions#335]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** (`storage-resize-images`, `firestore-send-email`, etc)
- Extension version: **\_**
- Configuration values (redact info where appropriate):
  - **\_**
  - **\_**

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.

**Comment by russellwheatley** [comment]
Hey @HamidRazaGoraya, could you confirm what version of `storage-resize-images` you're using? 

We have recently added a feature to `storage-resize-images` which will rotate the image based on its EXIF data so that they're oriented correctly. I presume this is the reason your photos are being rotated? You could use one of the many online tools for viewing EXIF data to to peek at the orientation property for your image: https://www.verexif.com/en/

**Comment by HamidRazaGoraya** [comment]
hi thanks for your response .. i am not using extension  as my application
stores the download url of image and thumbnail url in a document so i have
to convert generate thumbnail from url uploaded to document not no storage
upload
so i have modified the code to convert url into storage path

**Comment by russellwheatley** [comment]
Hey @HamidRazaGoraya, this forum is for issues that are related to the use of Firebase Extensions. If you do have a problem with an extension, please feel free to open a new issue.
