### ISSUE TITLE
Multiple fields in translate text extension

### ISSUE THREAD

**Issue by kabirkhan** [firebase/extensions#336]
### Extension name

This feature request is for extension: **translate-text**

### What feature would you like to see?

This extension is great but would be awesome to provide multiple input/output field mappings to make it a bit more generic. 

### How would you use it?

I'd like to translate 2 properties for each document in a collection. It doesn't make sense to concatenate the properties together.

For instance, if you had a products collection, each product might have a title and description and a user might want to provide an English translation of both, rather than only one.

**Comment by russellwheatley** [comment]
Yeah, that's a fair idea, I'm sure the Firebase Extension's team will take a look.

**Comment by schnaps1981** [comment]
i vote for

**Comment by aneps** [comment]
Was gonna dev it myself, but yea! I vote for it :)
would be good if it worked like the language selections:

input: name,details
output: name_translated: {}, details_translated: {}

**Comment by karayu** [comment]
Hi everyone, thanks for the feedback! The way we've recommended people handle this is by installing multiple instances of the the Text Translation extension. Would that work for your use case? What would be missing from that approach?

**Comment by russellwheatley** [comment]
This is in progress: #421

**Comment by optiwiseaican** [comment]
> ### Extension name
> This feature request is for extension: **translate-text**
> 
> ### What feature would you like to see?
> This extension is great but would be awesome to provide multiple input/output field mappings to make it a bit more generic.
> 
> ### How would you use it?
> I'd like to translate 2 properties for each document in a collection. It doesn't make sense to concatenate the properties together.
> 
> For instance, if you had a products collection, each product might have a title and description and a user might want to provide an English translation of both, rather than only one.

Have you found any solution regarding this issue?
