### ISSUE TITLE
Avoid Cropping Images inferior to my MaxDimensions

### ISSUE THREAD

**Issue by doilio** [firebase/extensions#337]
### [REQUIRED] Step 2: Extension name

This feature request is for extension: `storage-resize-images`

### What feature would you like to see?

Current behavior as in the documentation:

> For example, say that you specify a max width of 200px and a max height of 100px. You upload an image that is 480px wide by 640px high, which means a 0.75 aspect ratio. The final resized image will be 75px wide by 100px high to maintain the aspect ratio while also being at or under both of your maximum specified dimensions.

Right now when I upload a **200x200** picture, the extension resizes it to **800x800** making it fit my Max dimensions.
This causes an increase in file size, and stretches the image making it look pixelated.

### How would you use it?

I would like to set my Max Width and Height to **800x800**, upload an image of size inferior to my max dimensions and keep the uploaded image as is.

I only want to resize pictures larger than **800x800**

**Comment by rosariopfernandes** [comment]
@doilio Thanks for finding this. Should be fixed by #338
