### ISSUE TITLE
bigquery-export: Add `document.id` to BigQuery tables

### ISSUE THREAD

**Issue by Neilpoulin** [firebase/extensions#345]
### [REQUIRED] Step 2: Extension name

This feature request is for extension: **`firestore-bigquery-export`**

### What feature would you like to see?

For this feature to be useful to me, I really need the firestore document's `id` exposed as a single field in the generated tables. Currently, the fully qualified `document_name` is provided, but this includes a bunch of additional prefixes that makes it really difficult/cumbersome to join across tables. 

### How would you use it?
I want to use the big query tables to power DataStudio as well as for running one-off queries to better understand my app's usage. 

I often store data semi-normalized using document identifiers, such as `memberId` (which is like a userId), and then need to join to the `memebers` collection, using memberId as the join key. 

Currently, I would have to concact a string together to join on `document_name` in this format 

`projects/XX-project-nameXX/databases/(default)/documents/members/<my member document id>`

**Comment by mustafaekim** [comment]
Hi, it looks like now import has the document id column, however the extension which sync the firestore with bigquery table does not include document id column so the table now has imported rows with document id, created rows without

**Comment by mustafaekim** [comment]
Hi, may I know about the current state of this feature? It looks like IMPORTS generates the document_id filled-id with the document ID however CREATE/UPDATE leave this column blank, which creates inconsistencies

**Comment by russellwheatley** [comment]
@mustafaekim May I ask what version of the `firestore-bigquery-export` extension you're using? You should be able to see it in your Firebase console dashboard in the extension's tab.

**Comment by mustafaekim** [comment]
Hi, it is Version 0.1.5

Thanks for getting back

**Comment by russellwheatley** [comment]
If you head to your `firestore-bigquery-export` extension in the extension's tab on the Firebase console, you ought to be able to update to version `0.1.6` which has the `document_id` update.

**Comment by mustafaekim** [comment]
Great, thanks. Do you have any recommentation to fix the previous records? Should I delete the table and import again?

**Comment by russellwheatley** [comment]
That would be my recommendation 😄 .
