### ISSUE TITLE
Question: Can we create new extensions?

### ISSUE THREAD

**Issue by kellyjandrews** [firebase/extensions#348]
Is it possible to create new extensions and contribute here?  I currently have been working with Vonage APIs and Firebase and would like to create some extensions to make it easier to get setup.

If not - is it possible to install extensions that aren't in the official repo, or some easier process to get a user setup?  My current plan would be to create an SDK of some kind, but would still require efforts on the user's end, and I would like to streamline the process as much as possible.  

Thank you so much!

**Comment by laurenzlong** [comment]
hi @kellyjandrews you can sign up for our Early Access Program here: https://forms.gle/ftBJPiPsYTStzjAH9

**Comment by kellyjandrews** [comment]
Thank you @laurenzlong - filled it out.  Is there a general timeline on when the EAP will begin?
