### ISSUE TITLE
Fix vulnerability alerts by updating dependencies

### ISSUE THREAD

**Issue by laurenzlong** [firebase/extensions#35]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

Multiple

### What feature would you like to see?

Fix vulnerability alerts by updating some dependencies: https://github.com/firebase/extensions/network/alerts

### How would you use it?

Tell us how you'd use this feature in your app.

**Comment by russellwheatley** [comment]
Work in progress PR #200
