### ISSUE TITLE
Unable to specify path of subcollections to be imported via script: npx @ firebaseextensions / fs-bq-import-collection

### ISSUE THREAD

**Issue by teoColomberotto** [firebase/extensions#352]
[REQUIRED] Step 2: Describe your configuration
- Extension name: Export Collections to BigQuery
- Extension version: 0.1.5
- Configuration values (redact info where appropriate):
  - location : europe-west3
  - collectionPath: userData/{userId}/sessions

[REQUIRED] Step 3: Describe the problem
When entering the parameters in command line, it is not allowed to enter the path of the subcollection as no characters other than letters and spaces are accepted.
Despite this, in the documentation it is indicated to insert the path present in the extension

"When prompted, enter the Cloud Firestore collection path that you specified during extension installation, ${COLLECTION_PATH}."

![Annotation 2020-06-15 150332](https://user-images.githubusercontent.com/44233825/84660633-6c0c2580-af19-11ea-9bf4-3ae94ef9819f.png)

**Comment by russellwheatley** [comment]
Hey @teoColomberotto, unfortunately, you cannot currently import from sub-collections. There is already an issue open for this problem: https://github.com/firebase/extensions/issues/17 which you ought to follow for further updates.
