### ISSUE TITLE
Extend extensions

### ISSUE THREAD

**Issue by architechcro** [firebase/extensions#355]
Hi,
I want to update firebase-email-send function
I've cloned the source of extension repository and try to update my extenstion with
`firebase ext:update`
but it always updates from original source - this repository.
I didn't find any details instructions on how to extend and update this extensions.
Hope you can help

**Comment by russellwheatley** [comment]
Hey @architechcro, if you're not sure of the Firebase CLI commands, you can run this command `firebase --help` which lists all the commands with a description. To update your extension with your local changes you need to run the following command:

`firebase ext:update <extension Id> <path to firestore-send-email directory with your changes> --project=<firebase project Id>` .

 Every angled bracket `<>` needs to be replaced with the actual value. Hope this helps.

**Comment by rosariopfernandes** [comment]
@architechcro that feature is still in preview. In order to enable it on the CLI you'll need to run `firebase --open-sesame extdev` before running `firebase ext:update` as @russellwheatley explained.

**Comment by mbleigh** [comment]
Hi, developing / forking extensions is something we're experimenting with in a closed testing program. If you're interested in learning more, please sign up for the [Firebase Alpha](https://services.google.com/fb/forms/firebasealphaprogram/) program.

**Comment by alibad** [comment]
Are there any updates on whether this capability would be enabled? I'm currently using the "Manage Marketing with Mailchimp" and would like to make some changes in its behavior.
