### ISSUE TITLE
File is already a resized image, no processing is required...

### ISSUE THREAD

**Issue by CyrusZei** [firebase/extensions#356]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** (`storage-resize-images`)
- Extension version: **\_** *Version 0.1.9*
- Configuration values (redact info where appropriate):
  - **\_** Cloud Functions location : us-central1
  - **\_** Sizes of resized images : 400x250,200x200,100x100,60x60,40x40
  - **\_** Deletion of original file : false
  - **\_** Cloud Storage path for resized images: thumbs
  - **\_** Cache-Control header for resized images: max-age=86400
  - **\_** node V : node 10

### [REQUIRED] Step 3: Describe the problem

as soon as my users upload an image and the resize image extensions kick in it says `File is already a resized image, no processing is required...` and then my other cloud functions that listen for changes in the firebase storage will never be triggered.

How do I force that resizes extension to resize my images even if it says that they don't need it. I have tried with large images and it keep saying that it does not need to resize the image.

You should have an option to force resize instead of the extension taking that decision for me.

#### Steps to reproduce:

1. install the extension
2. upload a file with the .put without metaData (react native). I have tried both with a small image and with a large one, but it won't trigger.
3. go to your firebase dashboard and look at functions and click on logs for that function.
![Screenshot 2020-06-18 at 21 13 57](https://user-images.githubusercontent.com/5053903/85062341-a17a7280-b1a8-11ea-8d56-206c04339a15.png)

I also have one function that will listen for `functions.storage.object().onFinalize` and trigger as soon as the resize of the image is done. the problem is that this will never be triggered since the extension will not do any resizing.

What happened? How can we make the problem occur?
This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.

##### Expected result

the expected result: trigger the resize so that it will resize the images with the dimensions that I have entered.

##### Actual result
The actual result : It will just say  `File is already a resized image, no processing is required `

If I look at the code for the resize cloud functions I see that it will make this check, can I comment that out ?
![Screenshot 2020-06-18 at 21 23 33](https://user-images.githubusercontent.com/5053903/85063135-f8cd1280-b1a9-11ea-9317-98cd99aeea60.png)

**Comment by rosariopfernandes** [comment]
@CyrusZei please fill in the issue template when submitting an issue. With no details it's hard to reproduce your problem.

**Comment by CyrusZei** [comment]
Will fix this now, sorry for this

**Comment by CyrusZei** [comment]
Updated it 😃

**Comment by rosariopfernandes** [comment]
@CyrusZei looks good! :) 
Can you also tell what's the resolution of the image that you're uploading using `put()` ?

**Comment by CyrusZei** [comment]
@rosariopfernandes I did update the issue template again, sorry for this.

I am using a react-native app and I have tried with a small image that is 400x400px and an image that is 1080x720, but it won't trigger it.

**Comment by CyrusZei** [comment]
I just ran the extension again and I did comment out the line where it checks the metadata ` resizedImage` and the extension went mental again.
![Screenshot 2020-06-18 at 21 58 52](https://user-images.githubusercontent.com/5053903/85066343-151f7e00-b1af-11ea-81da-99b3988139ff.png)

Last time it went mental it created something like 500 000 resized image with 900ist byte of each
![Screenshot 2020-06-18 at 14 57 04](https://user-images.githubusercontent.com/5053903/85066423-397b5a80-b1af-11ea-9819-554645994943.png)

and If you look at the path it just went /thumbs/thumbs/thumbs/thumbs/thumbs/thumbs/thumbs/thumbs/thumbs/thumbs/thumbs/thumbs/thumbs/thumbs/thumbs/ for like ever.

**Comment by CyrusZei** [comment]
Okej, it has to do with this [#447](https://github.com/firebase/firebase-functions/issues/447).
Any update on this?

It looks like I need to set 
`process.env.X_GOOGLE_NEW_FUNCTION_SIGNATURE = 'true';` 
for this to be able to work?

**Comment by russellwheatley** [comment]
Hey @CyrusZei, the reason why you can't remove these lines of code:
```
 if (object.metadata && object.metadata.resizedImage === "true") {
      logs.imageAlreadyResized();
      return;
    }
``` 
is due to the fact that we put a `resizedImage` property on each resized image. This stops the function triggering every time we add a resized image to the storage bucket that would cause an infinite loop, hence why your cloud function invocations skyrocketed.

This console log: `File is already a resized image, no processing is required` will only be called if you have that property on the image's metadata which leads me to believe the images in question have already been resized in the past. Can you confirm that is the case?

**Comment by CyrusZei** [comment]
Hi @russellwheatley,

This makes sense and thanks for clearing this up for me. I did notice this :

I have this option In the resize field `400x250,200x200,100x100,60x60,40x40` and if the image is lower than say 400x250 it won't "resize them up" to that scale. 

Cuz if I am not mistaking I think the  "old" resize image would resize them up?.

I will start looking and refactor my code on behalf of the new "Resize image" extension.

**Comment by russellwheatley** [comment]
Yes, that is correct. When we initially switched from `ImageMagick` to `Sharp` image library, we didn't stop the extension from scaling up images that were smaller than the specified resize dimensions. That was rectified in this [PR](https://github.com/firebase/extensions/pull/338)

**Comment by CyrusZei** [comment]
@russellwheatley ok =/ would have been nice if that would have been an option instead in the extension if you don't want it to resize up that you can tick. "Forcing" it to not resize up as default will break the code for a lot of devs :(

**Comment by Ehesp** [comment]
It was my understanding the previous versions using ImageMagick did not scale up by default, and the update to the Sharp version was to mimic previous functionality.

**Comment by CyrusZei** [comment]
hmm, I am pretty sure that it did? I will look again and come back to you.

**Comment by CyrusZei** [comment]
Okej, it does work, but it really takes some time for it to process the images. When I was on node 8(256 MB) it sort of happened instantly but on node 10 (1gb) it feels like it does 70% of the job and then just won't do the rest until there comes another request. Oh well, I will look into refactoring my cloud functions and see if that might do something.
