### ISSUE TITLE
Enable multiple collections

### ISSUE THREAD

**Issue by nosrednAhsoJ** [firebase/extensions#358]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: firestore-bigquery-export

### What feature would you like to see?

I'd like to be able to configure multiple collections to be sent to BigQuery.

### How would you use it?

I have a handful of key collections that need analysis and I haven't found a way to either run multiple instances of this extension or to configure it to deliver multiple collections to BigQuery.

**Comment by mbleigh** [comment]
Hi Josh, you can install multiple instances of the same extension in a project to get this behavior -- have you tried it and something has gone wrong? If so, can you provide more specifics?

**Comment by nosrednAhsoJ** [comment]
Figured out how to add another instance.  Thanks for pointing out that it was possible!
