### ISSUE TITLE
firebase-bigquery-export: Array Type - No rows results

### ISSUE THREAD

**Issue by diegofhe** [firebase/extensions#359]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\Export Collections to BigQuery** 
- Extension version: **0.1.5**

### [REQUIRED] Step 3: Describe the problem

When generating a view with array type data and querying for latest  returns: 'This query returned no results.'

#### Steps to reproduce:
1.-Install extension on collection 'examples'
2.-Create a collection called 'examples'
3.-Fill collection with document:

![image](https://user-images.githubusercontent.com/30607780/85329692-9ec59900-b498-11ea-8dbd-6c5d4c8b6d08.png)

4.- Create the scheme views with the following example.json 
```json
{
  "fields": [
    {
      "name": "name",
      "type": "string"
    },
    {
      "name":"favorite_numbers",
      "type": "array"
    },
    {
      "name": "last_login",
      "type": "timestamp"
    }
  ]
}
```

5.- Go to google cloud platform big query, and query examples_raw_latest to verify that data exists on big query
![image](https://user-images.githubusercontent.com/30607780/85330016-362aec00-b499-11ea-8b2d-08e27f3b71c3.png)

6.- Go to the created view (examples_schema_example_latest) and query all data (no results)
![image](https://user-images.githubusercontent.com/30607780/85330146-70948900-b499-11ea-961e-b37b49d0a5a1.png)

7.- Create another schema called exampleSimple.json in which the array data type is deleted
```json
{
  "fields": [
    {
      "name": "name",
      "type": "string"
    },
    {
      "name": "last_login",
      "type": "timestamp"
    }
  ]
}
```
Create views and query results:
![image](https://user-images.githubusercontent.com/30607780/85330366-e4cf2c80-b499-11ea-8d2e-bda5a3e1cedb.png)

Now you can see the result.

##### Expected result
Expected to see a row with favorite_numbers_member and favorite_numbers_index

##### Actual result
'This query returned no results.'

**Comment by LucianoGanga** [comment]
I'm having the same issue :( 

@diegofhe , could you make it work? 

Thanks!
Luciano

**Comment by diegofhe** [comment]
Hello @LucianoGanga, my project is still on development , so this issue is not critical to me (I am waiting for the firebase team to merge the fix on [368](https://github.com/firebase/extensions/pull/368)).  The first thing that comes to mind is to twerk the query on ${schema}_latest on "details" tab.
![image](https://user-images.githubusercontent.com/30607780/85886108-0e929700-b7ab-11ea-8a21-eb30fb08f2c3.png)

Have a look at [368](https://github.com/firebase/extensions/pull/368) to dig for info for a hotfix
Good luck!

**Comment by LucianoGanga** [comment]
Thank you @diegofhe !! I really appreciate it :)

**Comment by russellwheatley** [comment]
This was fixed in this PR: https://github.com/firebase/extensions/pull/368
