### ISSUE TITLE
firestore-bigquery-export Obsolete Node 8

### ISSUE THREAD

**Issue by gastsail** [firebase/extensions#360]
All my functions has been updated to Node 10 , but for some reason this firestore-bigquery-export extension function has not been updated yet which says obsolete in my functions dashboard

[Image](https://i.imgur.com/ox27LH1.png)

**Comment by russellwheatley** [comment]
Hey @gastsail, I don't think it is quite as simple as upgrading your cloud functions to use node 10. The team are working hard to upgrade the extensions to use node 10. If you're interested, you might consider following this [issue](https://github.com/firebase/extensions/issues/327) which has become the public issue tracker for node 10 developments.
