### ISSUE TITLE
Fix Documentation Referencing Wildcard Collections are supported

### ISSUE THREAD

**Issue by jakebern** [firebase/extensions#363]
Bug filed in October: https://github.com/firebase/extensions/issues/17
AFAIC, wildcard subcollections are still not supported.  It would be great to update the docs https://firebase.google.com/products/extensions/firestore-bigquery-export.

"Note that this extension only listens for document changes in the collection, but not changes in any subcollection. You can, though, install additional instances of this extension to specifically listen to a subcollection or other collections in your database. Or if you have the same subcollection across documents in a given collection, you can use {wildcard} notation to listen to all those subcollections (for example: chats/{chatid}/posts)."

**Comment by russellwheatley** [comment]
@jakebern, thanks for the heads up! I've created a PR to rectify the docs.

**Comment by jakebern** [comment]
Thanks for the quick fix!  Wish there was a way to quantify developer time saved/lost in terms of accurate documentation to help prioritize things like this...  Maybe there can be a some feedback button... "lost time on old documentation" where you enter a estimated time value.

**Comment by russellwheatley** [comment]
Hi @jakebern, you might be interested in this [thread](https://github.com/firebase/extensions/issues/370#issuecomment-652338351) as I was mistaken about wildcards for this extension. It is actually possible. I'll be closing this [PR](https://github.com/firebase/extensions/pull/366) and opening another PR that uses a regex for capturing incorrect paths.

 Sorry for the confusion!
