### ISSUE TITLE
Option to edit the code before updating the extension

### ISSUE THREAD

**Issue by itssidhere** [firebase/extensions#365]
I am using storage_resize_image extension and I have made some changes for my specific use case ( ignore several paths ) but on updating the plugin every time I loose my changes. Also the new storage resize update which generates new token for resized image will break my code in production and I need to edit it after updating the plugin which will result in a downtime and unexpected behaviours. Can we have an option to edit the code before actually updating the extension? or to select from the list of new features being added? That would really help in preserving the behaviour of the apps in production

**Comment by russellwheatley** [comment]
Hey @itssidhere, thanks for the inquiry. The ability to fork extensions is something currently being experimented with as mentioned [here](https://github.com/firebase/extensions/issues/355#issuecomment-646344290). I don't think selecting what features you'd like to use is feasible.

**Comment by itssidhere** [comment]
Hey @russellwheatley . For my use case, I need to keep the tokens same. I am using the extensions in a chat app and I am using thumbnails to display on the chat screen and original image when the user clicks on it to view it. What I am doing is just invoking a cloud function each time a resized image is generated then I was copying the download URL of the image stored in the user document and appending _200x200 (as the tokens were same) to get the thumbnail URL. Now if I update I have to remove the if condition manually which will result in a downtime of the app. It would be great if that if the condition used some new metadata to decide that would not break the existing code.
