### ISSUE TITLE
Delete-User-Date node 8 deprecation warning 

### ISSUE THREAD

**Issue by jimmykane** [firebase/extensions#369]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

User delete 

#### Steps to reproduce:

Node 8 deprecation warning in console of Firebase 

##### Expected result

Node 10 compat

**Comment by russellwheatley** [comment]
Hey @jimmykane, thanks for the feedback. It is just a warning that you will have to change in the future. You might want to follow this [thread](https://github.com/firebase/extensions/issues/327#issuecomment-637132303) for further Node 10 developments.
