### ISSUE TITLE
[QUESTION] Using templates with Trigger Email extension

### ISSUE THREAD

**Issue by NLegendre** [firebase/extensions#37]
Hi,

Can you provide and example of how to use templates with Trigger Email extension ?

What I'm not sure about :
- how to format the "template" collection in firestore
- how can I define variables in the template 
- is it possible to use logic in template (if, else, loop, ...) (you specified Handlebar so I imagine the answer is yes)
- how to pass variables and template name when creating an email

Some code example would be great :)

Thanks a lot

**Comment by Ehesp** [comment]
Hi @NLegendre - this example may help you: https://github.com/firebase/extensions/blob/master/firestore-send-email/POSTINSTALL.md#using-templates

To summarise:

Create a new document in Firestore for your templates, for example for a template called "Following", create a new document in `templates/following`:

```
{
  subject: "@{{username}} is now following you!",
  html: "Just writing to let you know that <code>@{{username}}</code> ({{name}}) is now following you."
}
```

When adding a new document to your mail collection, pass in a template name with the data which will be injected:

```
  toUids: ['abc123'],
  template: {
    name: 'following',
    data: {
      username: 'ada',
      name: 'Ada Lovelace'
    }
  }
```

On the logical "if statement", it should work yes, however I'll check this myself too and make sure it is working.

**Comment by NLegendre** [comment]
That's perfect !
Thank you very much !

**Comment by thebeingapp** [comment]
tried sending an attachment using the array field 'attachments' in template collection. But the email got delivered with the attachment. Does anyone know if the extension is supposed to work with an attachment in the template?

**Comment by tylerreece22** [comment]
For some reason my emails still cant pick up the templates. I have configured just like above templates collection is created and i have added the object.
```
db.collection('templates').add({
    toUids: ['abc123'],
    template: {
        name: 'following',
        data: {
            username: 'ada',
            name: 'Ada Lovelace'
        }
    }
})
```

When I try to add the below to mail I the this error.
![image](https://user-images.githubusercontent.com/9936635/88748399-edf98c00-d11e-11ea-9741-31243504e9c5.png)

```
{
        to: 'someone@email.com',
        message: {
             subject: 'Hi there!'
        },
        template: {
            name: 'following'
        }
    }
```
