### ISSUE TITLE
firestore-bigquery-export Collection path regex error

### ISSUE THREAD

**Issue by deplorableword** [firebase/extensions#370]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** `firestore-bigquery-export`
- Extension version: **\_** `Version 0.1.5`
- Configuration values (redact info where appropriate):
  - Collection path: foo/{slug}/collection/document

### [REQUIRED] Step 3: Describe the problem

I'm trying to setup this extension to sync a sub-collection with the collection path noted above. During installation I get the following error.

>> Error occurred while deploying resources: RESOURCE_ERROR: `/deployments/firebase-ext-firestore-bigquery-export-discovery/resources/fsexportbigquery` Deployment Field Violation Error: gcp-types/cloudfunctions-v1:projects.locations.functions: INVALID_ARGUMENT: Field: event_trigger (Expected value foo/{slug}/collection/document/{documentId} to match regular expression [^/]+/[^/]+(/[^/]+/[^/]+)*)

**Comment by russellwheatley** [comment]
Hey @deplorableword, if I read your collection path value correctly, you're trying to use a wildcard which isn't possible. This [issue](https://github.com/firebase/extensions/issues/363) was raised to change the documentation which now has a [PR](#366). Sorry for the confiusion!

**Comment by deplorableword** [comment]
@russellwheatley thanks for getting back to me, since posting I've just installed it again trying the path `foo/{slug}/collection/` but it sounds like this won't work correctly either?

**Comment by russellwheatley** [comment]
Yes, you're correct. The wildcard `{slug}` isn't supported I'm afraid. Wildcards in Firestore queries are not possible.

**Comment by deplorableword** [comment]
@russellwheatley Very confused honestly, because it's installed correctly with `foo/{slug}/collection/ ` and I am seeing events come through for the `collection`. The collection itself is subcollection (if that makes any difference)?

**Comment by russellwheatley** [comment]
@deplorableword  You're correct, thank you for bringing this to my attention! It isn't possible to do wildcards via a Firestore query. But this isn't a typical Firestore query, it is a cloud function that listens to documents as described [here](https://firebase.google.com/docs/functions/firestore-events#node.js_3). 

The reason why it failed initially is because you don't have to specify the `document` part of the path as it is interpolated into a string with `documentId` on the path already. See [here](https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/extension.yaml#L59). I'll update this [PR](https://github.com/firebase/extensions/pull/366) accordingly. 

Apologies for the confusion!

**Comment by deplorableword** [comment]
@russellwheatley Gotcha! A possible improvement would be to make the regex error mention the word document, I think that might make it easier for everyone to debug 😀
