### ISSUE TITLE
Trigger Email HandleBar Partials

### ISSUE THREAD

**Issue by ivanchaukn** [firebase/extensions#372]
### [REQUIRED] Step 2: Extension name

firestore-send-email

### What feature would you like to see?

Is there any support for handlebar partials in firestore-send-email? If not, is that something on the roadmap because there's no easy to reuse my code or create shared templates right now.

### How would you use it?

Create shared templates!

**Comment by russellwheatley** [comment]
Hi @ivanchaukn, there is currently no support for handlebar partials. It is something that I think would be non-trivial to implement , but I'm sure the Firebase Extension's team will consider it.

**Comment by jhuleatt** [comment]
@ivanchaukn while we don't support Handlebar partials specifically, you can share templates across emails, as described in the `firestore-send-email` extensions POSTINSTALL file [here](https://github.com/firebase/extensions/blob/next/firestore-send-email/POSTINSTALL.md#using-templates). Does that meet your use case, or is there some additional functionality we need to add?

**Comment by ivanchaukn** [comment]
@jhuleatt, you might be confused with what I'm asking here. I would like build a shared partial that can be used by other templates. (use case: I have a title bar or bottom section that's shared across all my email templates). As the number of templates grow, I would not want to repeat that part that's in every templates

**Comment by kafkas** [comment]
Say you need to make a small change in the footer and you have 30 templates. You need to edit all of them manually, I'm guessing?

**Comment by mbleigh** [comment]
Hey folks, I've drafted #419 as a potential solution to this. Basically you can add `{partial: true}` to a template and then use it elsewhere. The nice thing about the implementation is that it respects the various formats (html, text, amp) so `{{> header }}` in one context will use the partial defined specifically for that context.

Does this seem like a good solution to everyone?
