### ISSUE TITLE
Resize-images doesn't work with gzip option

### ISSUE THREAD

**Issue by ghert** [firebase/extensions#382]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: storage-resize-images
- Extension version: 0.1.10
- Extension configuration: default

### [REQUIRED] Step 3: Describe the problem
When I tried to upload images with enabled gzip option they were getting resized but I couldn't load them in a browser. Link was broken and gave me domain network error.
#### Steps to reproduce:

Upload image trough the admin-sdk with gzip enabled. Generate link and open it in a browser.

**Comment by russellwheatley** [comment]
Hey @ghert, thank you for bringing this to our attention. You're correct, it does indeed cause the resized images to error. I think the FE team will probably review this internally to figure out how/if it is something to be handled as part of the extension.

**Comment by russellwheatley** [comment]
As the [PR](#417) suggests, we're ignoring gzipped images.
