### ISSUE TITLE
Add support for new locations 

### ISSUE THREAD

**Issue by karayu** [firebase/extensions#387]
CF3 has added the following regions recently. Let's add these locations to each extension as well: 
  - `us-west2`
  - `us-west3`
  - `us-west4`
  - `europe-west6`
  - `asia-northeast2`
  - `northamerica-northeast1`
  - `southamerica-east1`
  - `australia-southeast1`

**Comment by karayu** [comment]
Elliot, do you mind triaging and taking a look? It's not super urgent but this is heads up

**Comment by jhuleatt** [comment]
[This is the full list of available locations](https://github.com/firebase/firebase-functions/blob/master/src/function-configuration.ts#L5-L20)

**Comment by rosariopfernandes** [comment]
@karayu Mind if I send a PR addressing this and ask Elliot to review it?

**Comment by Ehesp** [comment]
@rosariopfernandes sure! I'll take a look at this on Friday either way, so if there's a PR I'll review otherwise I'll make a start.

**Comment by karayu** [comment]
Actually, we have 3 new locations! As of July 31, the following locations became available in Cloud Functions: asia-northeast3, asia-south1, and asia-southeast2.

**Comment by rosariopfernandes** [comment]
@karayu I've updated #388 to include these locations. PTAL :)
cc: @Ehesp

**Comment by anthonypirlo** [comment]
Hi all, I'm working on a project in Australia for which this feature would be super useful to keep all of our data processed within the country. Super interested in hearing any updates and excited to see this added.
