### ISSUE TITLE
JSON schema definion for type record / mode repeated does not work

### ISSUE THREAD

**Issue by mustafaekim** [firebase/extensions#389]
Hi,

Below is a part of the json schema definition:

```json
                {
                    "name": "initiator_room_form",
                    "type": "record",
                    "mode": "repeated",
                    "fields": [
                        {
                            "name": "key",
                            "type": "string"
                        },
                        {
                            "name": "value",
                            "type": "string"
                        }
                    ]
                },
```

that results with:

```sql
undefined AS model_initiator_room_form,
```

in the SQL produced for generating the view

how can I create such a schema for typed arrays?

**Comment by russellwheatley** [comment]
Hey @mustafaekim, typed arrays aren't possible for the `gen-schema-view` script, this has been raised as a feature request here: #293 which you may want to track.

**Comment by mustafaekim** [comment]
Hello @russellwheatley , thanks for getting back on this. I had actually seen this post but I was not sure if that was the same issue.

Do you have any suggestion for me until this feature is implemented? I don't know much about bigquery but if I understand correctly, I can actually create such a schema by myself, is that correct? So in this case is the tool just a great helper?

**Comment by russellwheatley** [comment]
The [documentation](https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md) for `gen-schema-view` is pretty handy at explaining how to create schemas.

I think it's best to factor in untyped arrays as a limitation of the tool when weighing up its utility for your use case. I'm afraid I don't have any advice on how to overcome it.

**Comment by russellwheatley** [comment]
Feel free to ask anymore question should you have any, I'm going to close this for now.
