### ISSUE TITLE
Allow multiple documents for "Trigger Email" extension

### ISSUE THREAD

**Issue by andersjr1984** [firebase/extensions#39]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **\firestore-send-email

### What feature would you like to see?

Allow multiple collections to trigger emails.  I tried adding "mail, contactMe" and got the following message:
Error installing. Some extension resources may not be fully provisioned or ready to use.

### How would you use it?

Multiple collections to trigger emails through comma separated list.

**Comment by Ehesp** [comment]
Hi @andersjr1984 at the moment the extension allows only a single collection to be monitored to trigger emails. To add another collection, you can install another instance of the extensions and configure it for a new collection.

**Comment by Ehesp** [comment]
Closing issue - recommended approach right now is to install multiple instances of the extension with differing config options.
