### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by erfabs** [firebase/extensions#391]
### [READ] Step 1: Are you in the right place?

yes

### [REQUIRED] Step 2: Describe your configuration

- Extension name: firestore-bigquery-export (fs-bq-schema-views script)
- Extension version: Latest

### [REQUIRED] Step 3: Describe the problem

I am trying to create BigQuery view of my raw changelog using fs-bq-schema-view script. The persistent functions are created but not the view.

![image](https://user-images.githubusercontent.com/23406161/87913992-491ce600-ca70-11ea-90bc-f77f957f93cd.png)

- raw_changelog table and raw_latest view are correctly created
- Project-id and dataset-id are ok because persistent functions are created in the correct path
- Table-id is the prefix of raw_changelog ("summary")
- Schema file is ok and it is in the correct path too (if I change the file path or modify the file as invalid JSON file I get other different errors)

#### Steps to reproduce:
npx @firebaseextensions/fs-bq-schema-views   
--non-interactive   --project=digitalarts-hmb  
 --dataset=firestore_export  
--table-name-prefix=summary   
--schema-files=./schema_li.json
{}
Cannot read property 'map' of undefined

##### Expected result
View to be created in BigQuery.

##### Actual result
View not getting created in BigQuery.

**Comment by russellwheatley** [comment]
Hey @erfabs, do you mind sharing your schema file so we can reproduce this error? Thanks.

**Comment by erfabs** [comment]
Sorry, my fault. 
The problem was in the JSON file, I had not included the fields inside the fields array.

I've already got it to correctly recognize the json file, but now I am getting an error trying to create the document_id field which doesn't actually exist in the summary_raw_changelog table where there is one called event_id

![image](https://user-images.githubusercontent.com/23406161/87929433-b471b280-ca86-11ea-8043-1c8dbde81564.png)

This is the table schema in Big Query

![image](https://user-images.githubusercontent.com/23406161/87929491-c8b5af80-ca86-11ea-979b-45a9b8540c14.png)

**Comment by russellwheatley** [comment]
I assume you created your changelog table before this [PR](https://github.com/firebase/extensions/pull/377) was merged in which means the `gen-schema-view` script is looking for a `document_id` column in the changelog table that doesn't exist. I think you might have to delete the changelog table and recreate it with the import script so that it will contain the `document_id` column.

**Comment by erfabs** [comment]
You assumed well @russellwheatley 

I have deleted table, updated the extension and added a new document in firestore. This is the error im recieving now:

![image](https://user-images.githubusercontent.com/23406161/87934891-4fbb5580-ca90-11ea-973c-a114946b405a.png)

And this is the schema code:

{
	"fields": [
    {
		  "name": "eventName",
		  "type": "string"
		},
	{
		  "name": "playerID",
		  "type": "string"
		},
	{
		  "name":"summary",
		  "type": "map",
		  "fields": [
			{
			  "name":"arenaLostRow",
			  "type": "integer"
			},
			{
			  "name":"arenaPlays",
			  "type": "integer"
			},
			{
			 "name":"arenaWinRow",
			  "type": "integer"
			},
			{
			  "name":"consumption",
			  "type": "map",
			  "fields": [
			    {
				  "name":"cube_XBasic",
				  "type": "integer"
				},
				{
				  "name":"cube_XPremium",
				  "type": "integer"
				},
				{
				  "name":"gems_XPremium",
				  "type": "integer"
				},
								{
				  "name":"token_special",
				  "type": "integer"
				}
				]
			  }
			]
	
	},
	{
		  "name": "version",
		  "type": "string"
		},	
	]
  }

Thank you for your reponses and support

**Comment by russellwheatley** [comment]
do you mind pasting the schema code here so I can copy? Thanks.

**Comment by russellwheatley** [comment]
I have noticed the `integer` type is incorrect, replace that with `number`. The [documentation](https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md#how-to-configure-schema-files) has a list of all available types.

**Comment by erfabs** [comment]
Oh thank you! 

That was the problem, i was declared as integer instead of numbers in schema.

Thanks a lot, now it works perfectly
