### ISSUE TITLE
Resize Images extension error message onUninstall

### ISSUE THREAD

**Issue by adrielwerlich** [firebase/extensions#393]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: storage-resize-images
- Extension version: 0.1.9

- Configuration values (redact info where appropriate):
 Cloud Functions location Description
us-central1
Cloud Storage bucket for images Description
artlab-eia.appspot.com
Sizes of resized images Description
128x128
Deletion of original file Description
false
Cloud Storage path for resized images (Optional) Description
avatar
Cache-Control header for resized images (Optional) Description
max-age=3600

#### Steps to reproduce:

What happened? How can we make the problem occur?
{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","status":{"code":3,"message":"Invalid function service account requested: ext-storage-resize-images@zzz.iam.gserviceaccount.com"},"authenticationInfo":{"principalEmail":"1072297581434@cloudservices.gserviceaccount.com","serviceAccountDelegationInfo":[{"firstPartyPrincipal":{"principalEmail":"cloud-dm@prod.google.com"}}]},"requestMetadata":{"callerIp":"64.233.172.179","callerSuppliedUserAgent":"Google-Deployment-Manager,gzip(gfe),gzip(gfe)","requestAttributes":{"time":"2020-07-22T15:01:22.851Z","auth":{}},"destinationAttributes":{}},"serviceName":"cloudfunctions.googleapis.com","methodName":"google.cloud.functions.v1.CloudFunctionsService.CreateFunction","authorizationInfo":[{"resource":"projects/zzz/locations/us-central1/functions/ext-storage-resize-images-generateResizedImage","permission":"cloudfunctions.functions.create","granted":true,"resourceAttributes":{}}],"resourceName":"projects/zzz/locations/us-central1/functions/ext-storage-resize-images-generateResizedImage","request":{"@type":"type.googleapis.com/google.cloud.functions.v1.CreateFunctionRequest","location":"projects/zzz/locations/us-central1","function":{"serviceAccountEmail":"ext-storage-resize-images@zzz.iam.gserviceaccount.com","eventTrigger":{"resource":"projects/_/buckets/zzz.appspot.com","eventType":"google.storage.object.finalize"},"runtime":"nodejs8","description":"Listens for new images uploaded to your specified Cloud Storage bucket, resizes the images, then stores the resized images in the same bucket. Optionally keeps or deletes the original images.","entryPoint":"generateResizedImage","sourceArchiveUrl":"gs://firebase-mod-sources-prod/a139bcfefbf19e901b67789105a3841ed208c6e449a896bafcc4a01e43c07844","availableMemoryMb":1024,"name":"projects/zzz/locations/us-central1/functions/ext-storage-resize-images-generateResizedImage","labels":{"deployment-tool":"firebase-extensions","goog-firebase-ext":"storage-resize-images","goog-firebase-ext-iid":"storage-resize-images"}}},"resourceLocation":{"currentLocations":["us-central1"]}}

Error uninstalling extension.
View details
Use the details below to help resolve this error, then retry uninstalling the extension.

; RESOURCE_ERROR at /deployments/firebase-ext-storage-resize-images/resources/generateResizedImage: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"Invalid function service account requested: ext-storage-resize-images@zzz.iam.gserviceaccount.com","status":"INVALID_ARGUMENT","statusMessage":"Bad Request","requestPath":"https://cloudfunctions.googleapis.com/v1/projects/zzz/locations/us-central1/functions","httpMethod":"POST"}}

##### Expected result
Uninstalling the extension and all related funcionality with it

##### Actual result
Error message and uninstall process not proceding

**Comment by russellwheatley** [comment]
Hey @adrielwerlich, I've also encountered this problem before. I've found that if I'm a bit persistent, the extension usually gets uninstalled. If you head to the extension's tab in the Firebase console, you can press the "See details" button next to the erroneously uninstalled extension
![Screenshot 2020-07-23 at 10 48 15](https://user-images.githubusercontent.com/16018629/88274075-0b6bc780-ccd3-11ea-82d7-8d85b70d11fd.png)

You can "Retry uninstalling" although it might take a few tries:
![Screenshot 2020-07-23 at 10 47 44](https://user-images.githubusercontent.com/16018629/88274161-2b9b8680-ccd3-11ea-86cd-67cf42739678.png)

I'm sure the Firebase Extension team will look at this functionality. Let me know if you have any success, please!

**Comment by adrielwerlich** [comment]
Hello @russellwheatley, thanks for the reply. I´ve tried many times, more than 10 uninstalling it. With no success. But anyway, thanks for the comment! I´m just tried it again. Let me see if this time it works.

**Comment by choipd** [comment]
Thank you for your comment! @russellwheatley  
I'd tried several times as you describe. And  I've just tried it again but no success.

**Comment by adrielwerlich** [comment]
Well, I´ve just saw in my firebase panel that the extension is now uninstalled. I don´t know if the request somehow or other just went though it´s way and worked out! But it´s uninstalled now.

**Comment by russellwheatley** [comment]
I'm glad you were able to uninstall @adrielwerlich. I am sorry it hasn't worked out yet @choipd. I've also had similar experiences, It's not an ideal situation. However, I believe the Firebase Extension team are aware of the bug and are trying to rectify the problem. Thank you for your patience!

**Comment by laurenzlong** [comment]
@choipd, and @adrielwerlich to help us diagnose, can you let us know:

- How you originally installed the extension, was it through Console or CLI?
- When approx did you install the extension?

**Comment by laurenzlong** [comment]
Also another workaround to try is to uninstall via the CLI, see https://firebase.google.com/docs/extensions/alpha/manage-installed-extensions_community?platform=cli#uninstall for more info.

**Comment by rosariopfernandes** [comment]
@laurenzlong the link your posted is not available. I think you meant this https://firebase.google.com/docs/extensions/manage-installed-extensions?platform=cli#uninstall

**Comment by laurenzlong** [comment]
@rosariopfernandes Yes, thank you! I revised my comment with the correct link.

**Comment by choipd** [comment]
> @choipd, and @adrielwerlich to help us diagnose, can you let us know:
> 
> * How you originally installed the extension, was it through Console or CLI?
> * When approx did you install the extension?

I installed the extension through Console.
It was around 2020. 7. 21. 3am KST.

Thank you for the inspection.

**Comment by laurenzlong** [comment]
Hi everyone, this has now been fixed. However if you had an extension that previously failed to be uninstalled, it is now stuck in a weird state, and you'll have to uninstall with the CLI by following these instructions:  https://firebase.google.com/docs/extensions/manage-installed-extensions?platform=cli#uninstallfor. (Please note that clicking "retry uninstall" in the console will not work. You have to use the CLI.)

**Comment by carrasc0** [comment]
Cannot uninstall with CLI or console. Please check this!!

**Comment by dackers86** [comment]
Hi @carrasc0.

Can you confirm what version of the extension you are using. 

Are you attempting to update the latest version of the extension?
