### ISSUE TITLE
[FR] only storing resized image

### ISSUE THREAD

**Issue by marvinsxtr** [firebase/extensions#4]
### [READ] Step 1: Are you in the right place?
yes

### [REQUIRED] Step 2: Extension name

This feature request is for extension: `storage-resize-images`

### What feature would you like to see?

I would like to only store the resized image.

### How would you use it?

This could be useful for profile pictures, which are never seen in full resolution.

**Comment by tranceyos2419** [comment]
I want to have a feature that this extension overwrites existent pictures.

**Comment by ItangSanjana** [comment]
Agree. Perhaps by providing some sort of option to save the original image or not.

**Comment by rosariopfernandes** [comment]
@marvinsxtr thanks for sending this FR. It is now live in v.0.1.2 of the extension. You can update using the Firebase Console or the CLI by running:
`firebase ext:update storage-resize-images --project <projectId>`
