### ISSUE TITLE
Attach file in email when using trigger email extension.

### ISSUE THREAD

**Issue by edlgg** [firebase/extensions#40]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: firestore-send-email

### What feature would you like to see?

If would like to be able to attach files when I use the send email extension.

### How would you use it?

I want to send my users some files when they request them.

**Comment by Ehesp** [comment]
Thanks we'll raise this internally as a feature request and let you know if/when it will be implemented.

**Comment by BluebambooSRL** [comment]
@Ehesp how you doing?
Is there any deadline for the delivery of this feature-request?
We are developing a "message & alerts" tier, and wonder to know if this firebase extension will be a good solution. Thanks in advance, Federico

**Comment by Ehesp** [comment]
Hey @BluebambooSRL this is now being reviewed internally. Thanks for your patience 👍

**Comment by bgwissam** [comment]
any update on this issue? have the extension been created?

**Comment by russellwheatley** [comment]
Hey @bgwissam, this issue was closed because we updated the documentation for attaching file. Here's the [PR](https://github.com/firebase/extensions/pull/158/files) if you want to take a look.
