### ISSUE TITLE
Updating Delete User Data Runtime to Node10 or Node12

### ISSUE THREAD

**Issue by zigapovhe** [firebase/extensions#406]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: delete-user-data

### What feature would you like to see?

I would like to see that you update the runtime of delete-user-data function from Node 8 runtime (which is deprecated) to Node 10 or Node 12.

### How would you use it?

The way I use it now.

**Comment by rosariopfernandes** [comment]
@zigapovhe This has been suggested before. You might want to take a look at #327 to see the full discussion.

**Comment by zigapovhe** [comment]
> @zigapovhe This has been suggested before. You might want to take a look at #327 to see the full discussion.

Oh, I'm sorry. Didn't found it before. Best of luck :).
