### ISSUE TITLE
Firestore Export to BigQuery add map as JSON string to schema

### ISSUE THREAD

**Issue by jackforesightmobile** [firebase/extensions#408]
This feature request is for extension: Export Collections to BigQuery

### What feature would you like to see?

In our document, we have a map which has fields whose values are ids, so we can't add these map fields to the schema. Therefore we'd like to add the map as a JSON string to the schema. I've tried specifying the type as a string but the values come through to BigQuery as null. I've also tried specifying the type as array but I get a JSON error. I tried leaving the "name" field empty to see if it would pick up the name of the field but I get a JSON error there too.

Here's a screenshot of the document: 
![image](https://user-images.githubusercontent.com/47739475/89430884-24469500-d737-11ea-8c94-c4e81a000f93.png)

Any help on how to get this issue fixed would be great, thanks!

**Comment by Salakar** [comment]
@jackforesightmobile thanks for raising this issue. Would you be able to provide a bit more detail on what you're expecting to see added as a feature to the extension, I'm a bit confused to what is being asked here 🙈 sorry.

**Comment by jackforesightmobile** [comment]
Hey @Salakar I guess I'm not sure whether it's something I'm doing wrong, or whether it's a new feature, so I wasn't sure whether to add a feature request or a bug. I'll try to clarify some more:

So the default way the whole document comes into BigQuery is as a JSON string. I'm not sure if there's something I'm doing wrong, but I want that questionStats map in my document to come through to BigQuery as a JSON string, while the rest of the fields come through as number, string etc. It's not possible to map the fields inside that questionStats map because the keys of the maps inside questionStats are never the same. Therefore I wanted that whole questionStats map to come through as a JSON string under the field "questionStats" in BigQuery. I guess in the schema there could be a type "json" or something that would output everything in that field as a JSON string. 

What I'm not sure about is whether there's already a way to do this that I'm missing, or whether it's a new feature that needs to be added?

**Comment by russellwheatley** [comment]
Hey @jackforesightmobile, it is not possible to control property types inserted from your Firestore document using the big query extension. The document is stringified and inserted into the `data` column which expects a [string](https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts#L72).

Have you looked into creating your own views using the `gen-schema-view` [script](https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md)?

**Comment by jackforesightmobile** [comment]
Hey @russellwheatley so yeah I'm using that gen-schema-view script. For the document I posted this is my schema:
![image](https://user-images.githubusercontent.com/47739475/89521265-147e8d80-d7d7-11ea-9f2a-806101bd1bb0.png)

I'm wondering if there's a way I can make just the questionStats field stringified, while all the other fields are in the schema. I would use the "map" type in the schema, but since the keys are always changing, I can't use that type as far as I can tell

**Comment by russellwheatley** [comment]
Ok, I think I understand your requirements. There is no way of making a property a `json` type, or stringifying a map in your case. This would have to be a feature request for the `gen-schema-view` script to create a new `json` type that may or may not be outside the scope of this extension. I'm sure the Firebase Extension will review this feature and get back to you. Thanks!

**Comment by alancinacio** [comment]
I have a similar scenario where I have maps where the key is unknown. Is there any supported way to specify something along the lines of
`
{
      "name": "users",
      "type": "map",
      "fields": [
        {
          "name": "*",
          "type": "string",
        }
      ]
    }
`

**Comment by russellwheatley** [comment]
Hey @alancinacio, wildcard queries are not supported I'm afraid, you have to explicitly name the key in the schema.

**Comment by i14h** [comment]
@russellwheatley do you think this is the same as #293?

**Comment by russellwheatley** [comment]
@i14h  No, not the same. This request is to have a type that takes the value from Firestore, stringifies and inserts into BigQuery. This would be useful if you have a map where the keys are unknown before hand. 

The current behaviour of a map requires you to describe the property names. Any property names not described, will be ignored by the `gen-schema-view` script and not inserted into BigQuery.

#293 is a request for the ability to describe the values contained within arrays taken from Firestore. (i.e. an array of numbers), and insert them as numbers (I guess non-numbers would be ignored). Although the feature request is more specifically asking for the ability to describe the shape of maps contained within the arrays which would be a lot more tricky.

The current behaviour takes every value from the array, stringifies and inserts it into BigQuery. 

I think maybe @fredzqm or @IanWyszynski input would be appreciated on this one.

**Comment by dackers86** [comment]
Initial PR added at https://github.com/firebase/extensions/pull/518

**Comment by jhuleatt** [comment]
Closing now that #518 is merged
