### ISSUE TITLE
Allow TLS in the smtp uri

### ISSUE THREAD

**Issue by kresten8** [firebase/extensions#409]
### Extension name

This feature request is for extension: **firestore-send-email**

### What feature would you like to see?

For use with office365 smtp a TLS connection is needed (with port 587). As it is it doesn't work (als not when the port is correctly set).

### How would you use it?

I would suggest something like smtptls://...

**Comment by Salakar** [comment]
Hey @kresten8 - thanks for raising this feature request - we'll review and get back to you, thanks!

**Comment by mbleigh** [comment]
Unless I'm confused about something this is already possible through `smtps://user:pass@some.host.com:587`

**Comment by kresten8** [comment]
Hi,
Thanks for the quick response.

The mail server does not accept SSL, only TLS. An error I get is:
Error when delivering message=mail/<ID>: Error: 68894361679680:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

The rest is not visible in the error console. The smtp server does work with Firebase authentication when STARTTLS is used and it doesn't with the SSL option.

**Comment by oolubayo** [comment]
I'm getting the same error with smtp.office365.com.

**Comment by kresten8** [comment]
Hi,

Any news on this?

Best Kresten

**Comment by Justin2997** [comment]
I will need this update to. Let me know if I can help for someting. 

Thanks a lot !

**Comment by i14h** [comment]
@Salakar @russellwheatley can you see if this can be reproduced? If so let's prioritize it.

**Comment by russellwheatley** [comment]
Change the protocol to `smtp` and it will work.

Example:
`smtp://user:pass@some.host.com:587`

If you set the protocol to `smtps` it will try and connect with a secure connection, and the STARTTLS protocol will fail. If you set it to `smtp`, the connection will be unsecure, and the STARTTLS protocol will be invoked and upgrade the connection to secure.

**Comment by kresten8** [comment]
Thanks, this works!

**Comment by russellwheatley** [comment]
I'm happy it worked for you, @kresten8 👌

**Comment by hamalao** [comment]
Hi, when i set config to this ill get invalid login error.
Could it be a setting in Office 365 that i need to fix? Thanks in advance.
smtp://user:password@smtp.office365.com:587

Error: Invalid login: 535 5.7.3 Authentication unsuccessful [LNXP265CA0003.GBRP265.PROD.OUTLOOK.COM]
