### ISSUE TITLE
StartTLS

### ISSUE THREAD

**Issue by busynest** [firebase/extensions#412]
### Describe your configuration

- Extension name: firestore-send-email
- Extension version: 
- Configuration values:

#### Steps to reproduce:

Setup is good except no input for StartTLS
Domain: stmp.office365.com

##### Expected result

the extension works fine, i think. but the protocal is different.

##### Actual result

Error: 68424247473984:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

**Comment by russellwheatley** [comment]
Hey @busynest, could you provide the full smtp connection uri for me to take a look at? (minus the password). Thanks.

**Comment by busynest** [comment]
stmps://username@email.com:password@stmp.office365.com:123

**Comment by russellwheatley** [comment]
Could you change it to `smtps` protocol and let me know if that works? Thanks.

**Comment by russellwheatley** [comment]
`SMTPS://username@email.com:password@SMTP.office365.com:123` - just to be clear what I mean, I've capitalised what might need to change.

**Comment by busynest** [comment]
firebase does not allow capitalized letters. it throws an error and goes back to backup.

**Comment by russellwheatley** [comment]
You're correct, I was just using capitalisation to show you what changes to make. Do not input literally 😄

**Comment by busynest** [comment]
oh, sorry, it's morining. the factual code is good. i just wrote it backwards here. sorry

**Comment by busynest** [comment]
my sevice provider has a StartLTS protocal, and I have no input for that, I also have a protocal error. The protocal logs in, but the server doesn't accept the protocal

**Comment by busynest** [comment]
why did you cloe it? protocol doesnt work

**Comment by russellwheatley** [comment]
I'm afraid there is no support for using the StartTLS protocol command. The extension takes your [connection uri](https://github.com/firebase/extensions/blob/next/firestore-send-email/functions/src/index.ts#L40) and passes it to the nodemailer client. From reading the nodemailer [documentation](https://nodemailer.com/smtp/#tls-options), it appears you have to make a  plaintext HTTP call to your service provider to upgrade your connection via the StartTLS command.

I might be wrong, but it is my understanding that using port 465 for SMTP gives you implicit TLS.

**Comment by busynest** [comment]
the port :465 helped. The mail is now in PROCESSING, no errors, but not complete.
the port my service provider gave was :587.

**Comment by busynest** [comment]
if I connect my service provided email to google, then maybe firebase could smtp into google, sent service provided email addess.

**Comment by busynest** [comment]
nodemailer: port: 465, secure = ture; port: 587, secure = false;
how do I set secure to false for nodemailer?

**Comment by busynest** [comment]
Yes, you are correct. This the service provider has Organization access to Microsoft Servers. I sent the SMTP to GoDaddy. It works :) THANK YOU!!!!!

**Comment by busynest** [comment]
I used legacy, so it was regular TLS, sent the message, but not secure.
I am still having trouble.

**Comment by busynest** [comment]
damn it, you were correct again! I needed to call service provider to upgrade access!!

**Comment by superdiazzz** [comment]
@dackers86 i have following by change port but still got same issue. i have make some attempt like
smtps://mailketing4024:password@smtp.mailketing.id:587
smtps://ridho@ridhopratama.com:password@smtp.mailketing.id:587
smtps://ridho@ridhopratama.com:password@smtp.mailketing.id:465
but none of them works

**Comment by busynest** [comment]
@dackers86 call your service provider because they approve access to the upgraded route.

**Comment by dackers86** [comment]
Thanks @busynest. 

Hopefully that will provide the solution!
