### ISSUE TITLE
generating bigquery firestore schema

### ISSUE THREAD

**Issue by VictorBaudot** [firebase/extensions#423]
running `npx @firebaseextensions/fs-bq-schema-views` fail if my schema contain one field that is not present inside all my documents

**Comment by russellwheatley** [comment]
Hi @IndigoBee, could you provide the error that you receive in your console, please? Thanks.

**Comment by VictorBaudot** [comment]
Sure @russellwheatley 
`{"code":400,"errors":[{"message":"Provided Schema does not match Table koalendar-prod:koa_events.events_schema_events_schema_changelog. Cannot add fields (field: bookings)","domain":"global","reason":"invalid"}],"response":{"headers":{"alt-svc":"h3-29=\":443\"; ma=2592000,h3-27=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","cache-control":"private","content-encoding":"gzip","content-type":"application/json; charset=UTF-8","date":"Sun, 16 Aug 2020 15:03:08 GMT","etag":"J2W3OzS5LGUa5dxazSiI5A==","server":"ESF","transfer-encoding":"chunked","vary":"Origin, X-Origin, Referer","x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN","x-xss-protection":"0"}},"message":"Provided Schema does not match Table koalendar-prod:koa_events.events_schema_events_schema_changelog. Cannot add fields (field: bookings)"}
Provided Schema does not match Table koalendar-prod:koa_events.events_schema_events_schema_changelog. Cannot add fields (field: bookings)`

**Comment by russellwheatley** [comment]
Are you trying to create a view where one already exists? Please check this view in your BigQuery console `koalendar-prod:koa_events.events_schema_events_schema_changelog` and let me know if it contains a `bookings` column.

**Comment by VictorBaudot** [comment]
Are you trying to create a view where one already exists -> yes
no bookings column in this view

**Comment by russellwheatley** [comment]
You need to update the generated view schemas, you could do it via the BigQuery console by using "Edit schema". 

Alternatively, you could just delete the two views created from the `gen-schema-view` script in the BigQuery console. Then, run the script again using the latest schema.
