### ISSUE TITLE
How would one upgrade to Node 10 for a Firebase extension?

### ISSUE THREAD

**Issue by hrag** [firebase/extensions#429]
General question, the Firebase Support flow brought me here. I have Trigger Email/firestore-send-email running and in the list of Cloud Functions, it's the only one in there that's on Node 8 still (I upgraded my regular Cloud Functions). How would I upgrade an extension to Node 10?

Would uninstalling and reinstalling it do the trick? Just wanted to ask before I go through with that. Seems unfortunate.

Thanks!

**Comment by mbleigh** [comment]
We are working on updating extensions to Node 10 currently, stay tuned for
an available upgrade soon!

**Comment by Ehesp** [comment]
Closing this as a dup of https://github.com/firebase/extensions/issues/327
