### ISSUE TITLE
Target languages field fails to accept one language

### ISSUE THREAD

**Issue by dahliasalem** [firebase/extensions#43]
- Extension name: `firestore-translate-text`
- Configuration values (redact info where appropriate):
  - **Target langs: ar**

#### Steps to reproduce:

1. Use the console or CLI to install the `firestore-translate-text` extension. 
2. In the target languages field list only one language for example `ar` 

##### Expected result

I except for the target languages field to be able to accept ONE target languages

##### Actual result

The target languages field only accepts MORE than one language

![image](https://user-images.githubusercontent.com/8892907/66785532-63e37e00-ee92-11e9-8dcc-75876a9a24ba.png)

OR

![image](https://user-images.githubusercontent.com/8892907/66785542-6940c880-ee92-11e9-8343-a3ea25d5875f.png)

**Comment by dahliasalem** [comment]
Follow up:

It is also possible to input the same language twice:
![image](https://user-images.githubusercontent.com/8892907/66785681-cccaf600-ee92-11e9-95ca-b2440adc1ff6.png)

**Comment by rosariopfernandes** [comment]
@dahliasalem Thanks for reporting this. Should be fixed in #46

**Comment by rosariopfernandes** [comment]
@dahliasalem thanks once again for reporting this. It has been fixed in v.0.1.1 of the extension. You can update using the Firebase Console or the CLI by running:
`firebase ext:update firestore-translate-text --project <projectId>`
