### ISSUE TITLE
firestore-bigquery-export: Add scheduled delete query for stale entries

### ISSUE THREAD

**Issue by mvergarair** [firebase/extensions#444]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **firestore-bigquery-export**

### What feature would you like to see?

It would be nice if when installing the extension, there is an option to create a scheduled query that deletes stale changelog entries. When querying the `latest` view, it queries the entire `changelog` table and this would help maintain query costs low. 
Plus, it's considered a "good idea" by [this blog post](https://cloud.google.com/blog/products/gcp/performing-large-scale-mutations-in-bigquery) from GCP.
### How would you use it?

The scheduled delete query would be optionally selected when installing the extension.

**Comment by russellwheatley** [comment]
Thanks for the suggestion. The Firebase Extension's team will take a look and assess if it is within scope.

**Comment by i14h** [comment]
@jhuleatt what do you think about this? And do you think it makes sense to have it as a feature of this extension or build a separate one with scheduled functions to do the cleanup?

**Comment by jhuleatt** [comment]
Thanks for the suggestion @mvergarair! 

@russellwheatley , for now, let's add docs that describe how to clean up the changelog without actually implementing a second function in the extension. That way, it's easier for those that want to clean up their changelog to do it manually, and we can re-evaluate at a later date if we want to add this to the extension itself (or possibly add another extension that does it).
