### ISSUE TITLE
Translate Text Extension for multiple Collections or multiple Documents in a collection.

### ISSUE THREAD

**Issue by archit-capjk-69** [firebase/extensions#446]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **\_** (`firestore-translate-text`)

### What feature would you like to see?

Configure Translate Text Extension for multiple Collections or multiple Documents in a collection instead of configuring it for only one collection.

### How would you use it?

This feature will be used to translate Text for multiple Collections or multiple Documents in a collection.

**Comment by Ehesp** [comment]
Hello,

This is by design, if you'd like to target multiple collections you can use multiple instance of the extension.

**Comment by archit-capjk-69** [comment]
Please tell me how to implement that.
Now to create multiple instance of an extension ?

**Comment by russellwheatley** [comment]
Hey @archit-capjk-69, if you click on the "install" button for the `firestore-translate-text` extension on this [page](https://firebase.google.com/products/extensions), you can create an instance for your project. You can do this as many times as you want, and create multiple instances for the same Firebase project.

**Comment by archit-capjk-69** [comment]
Thank you very much

**Comment by russellwheatley** [comment]
No problem!
