### ISSUE TITLE
firestore-bigquery-export: Add additional parameter to specify target dataset location in BigQuery

### ISSUE THREAD

**Issue by dachiraju** [firebase/extensions#452]
### [REQUIRED] Step 2: Extension name

Extension name: `firestore-bigquery-export`

### What feature would you like to see?

It would be great if we could expose an additional parameter in extensions.yaml to specify the BigQuery dataset location in the extension config when uploading data from firestore

Reference : [params](https://github.com/firebase/extensions/blob/fbf6532434723c9b2dce82eb368a6424a1f9ce30/firestore-bigquery-export/extension.yaml#L62) 

### How would you use it?

An additional option in extensions.yaml to specify the target dataset location being created in BigQuery will help us configure when installing the extension

**Comment by russellwheatley** [comment]
That's a reasonable request, I'm sure the Firebase team will consider it.  Thanks for the suggestion!

**Comment by jhuleatt** [comment]
Looks like this is doable by adding a param to extension.yml and updating the [`initializeDataset`](https://github.com/firebase/extensions/blob/b33c59383a0904911937f90975977ad44cd2b3b4/firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts#L195) function to call `bq.dataset` with the [`location`](https://googleapis.dev/nodejs/bigquery/latest/Dataset.html#Dataset) option. We'd probably have to update the import script with this option too?

**Comment by russellwheatley** [comment]
@jhuleatt That's correct. We'd have to pass the location [here](https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts#L157). [Documentation](https://googleapis.dev/nodejs/bigquery/latest/BigQuery.html#dataset). 

The `FirestoreBigQueryEventHistoryTracker` class is used by the BigQuery extension and import script.
