### ISSUE TITLE
auth-mailchimp-sync - Use PUT to insert or update

### ISSUE THREAD

**Issue by Reedyuk** [firebase/extensions#453]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** `auth-mailchimp-sync/`
- Extension version: **\_** 0.1.2
- Configuration values (redact info where appropriate): n/a

#### Steps to reproduce:

When adding a user to the mailchimp audience, if they already exist, an error is thrown up to use PUT to insert or update list members.

##### Expected result
Should PUT - or at-least but some sort of config to enable this

##### Actual result
An error exists in the log every time a duplicate user is attempted to be added to the mailchimp audience.

**Comment by Ehesp** [comment]
Hey thanks for the issue!

I think this is reasonable, although the function is triggered "`onCreate`" - what is your use-case for a user being created multiple times (is it while testing)?

**Comment by Reedyuk** [comment]
Most people use Mailchimp lists as a bucket of contacts, so we have multiple sources where we attain the email addresses, there is a small use case where this can overlap(with another service using the same list) and in the case where firebase is the last one to overlap with that user email address, then it causes it throw the error.
Its not the end of the worlds, i guess more of a nice to have.

**Comment by jhuleatt** [comment]
Hi @Reedyuk! To help us decide whether to implement this, what would be your preferred outcome in the case of a collision (Firebase Auth user being added to MailChimp already exists in Mailchimp):

Either:

1. Function doesn't do the `PUT`, but logs a more helpful message instead of the error that it is currently logging. Something like `Skipping user [firebaseAuthUserId] because they already exist in MailChimp.`

Or:

1. Function does to the `PUT` and modifies the user details in MailChimp. This would allow the MailChimp Contact Status to be updated.

**Comment by Reedyuk** [comment]
I think the first is fine, in my use case I'm only bothered about having unique email addresses in the listOn 28 Sep 2020 20:41, Jeff <notifications@github.com> wrote:
Hi @Reedyuk! To help us decide whether to implement this, what would be your preferred outcome in the case of a collision (Firebase Auth user being added to MailChimp already exists in Mailchimp):
Either:
Function doesn't do the PUT, but logs a more helpful message instead of the error that it is currently logging. Something like Skipping user [firebaseAuthUserId] because they already exist in MailChimp.
Or:
Function does to the PUT and modifies the user details in MailChimp. This would allow the MailChimp Contact Status to be updated.

**Comment by dackers86** [comment]
Closing in favour of https://github.com/mailchimp/Firebase/issues/28
