### ISSUE TITLE
Trigger Email SSL issue

### ISSUE THREAD

**Issue by jasonspick** [firebase/extensions#456]
I set up a new Trigger email extension configured for mailgun.  My mailgun credentials work with this tool: https://www.smtper.net/

This is what my smtp uri looks like:  smtps://{username}:{passoword}@smtp.mailgun.org:587

when creating a new document this is the response I get: 
_Error: 69012398901056:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:_

I'm not seeing an issue with outside of the extension, and I am not finding much on my google search.

**Comment by russellwheatley** [comment]
Hi @jasonspick, have you tried using port 465 instead of 587?

**Comment by Justin2997** [comment]
@jasonspick I have the same problem moving from MailGun to Office 365. I was using 465 for MailGun and move to 587 with office. I thinks 587 port seems to be using a ord ssl version so the current version of Trigger Email have error communicate to it. Moving from 587 to 465 will fix your problem.

**Comment by Justin2997** [comment]
You can find more info for STMPS and 465 at : https://www.mailgun.com/blog/which-smtp-port-understanding-ports-25-465-587/#:~:text=Port%20587%3A,587%20as%20the%20default%20port.

**Comment by jasonspick** [comment]
We can mark this closed now. I also believe this is a result of poor documentation on Mailgun side and complete understanding on mine. 

Hope my experience can help someone else. SO initially setting it to port 465 did nothing. I needed to set up separate SMPT credentials for my domain. The sandbox credentials would not work. But once I put those new credentials in. worked like a charm.

1. Have separate SMPT account credentials
2. Use port 465, not 587
