### ISSUE TITLE
Stripe Firebase Subscription Extension (multiple use in a project)

### ISSUE THREAD

**Issue by emaggy** [firebase/extensions#468]
Using the stripe firebase subscription extension, I am trying to create two different checkouts (two separate customer types) which each checkout showing three price plans. However, both checkout websites are showing the same price plans from one Stripe account. Is it possible to use the Stripe extension multiple times on a Firebase project or is there a limit of one per project (can only use 1 Stripe API key per project)?

**Comment by russellwheatley** [comment]
Hey @emaggy, you should be able to add more than one Stripe extension for your Firebase project. It is possible with all the other ones so it ought to be the same for this one. Here's a link for you to [install](https://firebase.google.com/products/extensions/firestore-stripe-subscriptions) it. Just click the button in the top right "Install in console" and select the Firebase project you wish.

**Comment by russellwheatley** [comment]
If you do need any further assistance, let me know 👍
