### ISSUE TITLE
Running firestore-bigquery-export deposits private key into document data

### ISSUE THREAD

**Issue by tbillington** [firebase/extensions#47]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: firestore-bigquery-export

### [REQUIRED] Step 3: Describe the problem

My documents were imported successfully, though I found copies of my iam private key in the document data when querying. Is this expected behaviour?

If this is expected could it be clarified somewhere in the instructions or the extension?

It's not obvious sensitive data like private keys will be included in the table data based upon reading the extension information.

#### Steps to reproduce:

Ran `npx @firebaseextensions/fs-bq-import-collection`

**Comment by Ehesp** [comment]
Hey @tbillington thanks for the report.

I've just imported a fresh dataset myself and I don't see any IAM related private keys. Would you be able to take a screenshot of where the data is (hiding any private info)? Do you mean the keys are within the exported data from Firestore, or are they visible within the BigQuery console?

**Comment by tbillington** [comment]
They are in the data in the `XXXX_raw_changelog` and `XXXX_raw_latest` (the view over changelog)

![Group 1](https://user-images.githubusercontent.com/2771466/66967789-e310c600-f0cd-11e9-89b9-5565d636476e.png)

**Comment by Ehesp** [comment]
Thanks for posting that. I'll do some more investigation and get back to you.

**Comment by russellwheatley** [comment]
Hi @tbillington, I've tried to reproduce this issue without any luck. Here is the line of code that sets the data property that is eventually stringified for BigQuery import: https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/scripts/import/src/index.ts#L207

As you can see it calls `snapshot.data()` which is the correct Firestore call to make if you want just the data from a Firestore record. What you are seeing in your `sessions_raw_latest` table is a `snapshot` which has not had its `data()` method called.

Could you please take a look at the `experience` property in your Firestore `sessions` collection and let me know if you see a `_firestore` object contained within, please? Thank you.

**Comment by tbillington** [comment]
@russellwheatley Yes, I see a `_firestore` object. It has fields like `_settings` and `_projectId`.

**Comment by russellwheatley** [comment]
@tbillington Ok, good to know we've found the issue! Somewhere in your codebase, you're storing the `snapshot` on an `experience` property. You ought to change it to `snapshot.data()` as referenced [here](https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentSnapshot#data)

**Comment by tbillington** [comment]
Ah, ok. This stuff can be easy to miss in JS land. Would have much preferred something like this crash/throw when it tried to be saved. Don't know if there's anything on your end you can do though.

Regardless, I appreciate you getting back on this 😃 cheers
