### ISSUE TITLE
auth-mailchimp-sync - does not create a contact in mailchimp if user account creation happens after anonymous login

### ISSUE THREAD

**Issue by jtestard** [firebase/extensions#478]
### [READ] Step 1: Are you in the right place?

This bug is in regard to a specific extension.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: `auth-mailchimp-sync`
- Extension version: Version 0.1.0

#### Steps to reproduce:

Have a user reach a website which uses anonymous login and then sign up

##### Expected result

User should have been synced with mail chimp

##### Actual result

User is not.

**Comment by jtestard** [comment]
It seems to be because the anonymous sign in is considered the "account creation" as far as the firebase trigger is concerned. But the behavior is obviously the wrong one for this extension.

**Comment by russellwheatley** [comment]
Thanks for the report! This is an interesting problem, I'm not quite sure how to get around it to be honest. An anonymous user by definition doesn't have an email address, and we return out of the [function](https://github.com/firebase/extensions/blob/next/auth-mailchimp-sync/functions/src/index.ts#L44) without an email address. There are only two triggers for Firebase Auth cloud functions; `onCreate` & `onDelete`. So any updates to the `UserRecord` are not captured. I'm sure the FE team will take a look at this problem, but I'm not sure what can be done to get around it. This could be a limitation of the extension 😓 .

**Comment by jhuleatt** [comment]
Thanks @jtestard for the request! As @russellwheatley pointed out, this isn't something supported by the background triggers that this extension uses. This feature would probably have to be some kind of bulk process, which we're tracking in #415, so I'm going to close this request and suggest that we instead use #415.

**Comment by jtestard** [comment]
@jhuleatt the absence of a onUserUpdate trigger in Firebase Cloud Function is an issue with broader consequence. The mailchimp firebase extension suffers from other flaws because of the same limitation (no update if user changes email, for example). There is no way to make a feature request for it on Github, i have sent it via the Firebase feature request tool.

> This feature would probably have to be some kind of bulk process, which we're tracking in #415, so I'm going to close this request and suggest that we instead use #415.

IMO, the resolution to this issue is not a bulk process, but truly the inclusion of an onUserUpdate trigger upstream.
