### ISSUE TITLE
A marketplace for open source firebase extensions 

### ISSUE THREAD

**Issue by arpwal** [firebase/extensions#480]
### Firebase Extensions Marketplace

There are a lot of features that could be quickly developed and iterated upon if developers could contribute and make (or sell) to other developers. 

### How would you use it?

A UI similar to what firebase extensions currently provide, which could be written as `protos` or as a config file.

**Comment by i14h** [comment]
Thanks @arpwal for the suggestion. Yes this is something we're evaluating behind the scenes. If you I have any specific features you'd like to see I suggest submitting a feature request through our [support page](https://firebase.google.com/support)
