### ISSUE TITLE
Delayed emails in the process queue - Trigger Email Extension

### ISSUE THREAD

**Issue by LaravDev** [firebase/extensions#481]
### Trigger Email Extension

This feature request is for extension: **\_** ( `firestore-send-email`)

### What feature would you like to see?

It would be awesome if we could specify the time at which the email should be sent, for example:

```
admin.firestore().collection('mail').add({
  to: 'someone@example.com',
  at: myDateObject,
  message: {
    subject: 'Hello from Firebase!',
    html: 'This is an <code>HTML</code> email body.',
  },
})
```

That way we can delay email to users at the right time... i don't think this sould be too hard to implement since you could for example create a date to the email delivery processing and check for it each x time to send the email, i don't know, something like that it's a basic function to send emails, and would be great to have.

### How would you use it?

By specifying the date in the mail collection in firestore.

```
admin.firestore().collection('mail').add({
  to: 'someone@example.com',
  at: myDateObject,
  message: {
    subject: 'Hello from Firebase!',
    html: 'This is an <code>HTML</code> email body.',
  },
})
```

**Comment by russellwheatley** [comment]
Hey @LaravDev, this is an interesting idea. We could create a scheduled function to check for records that have a specific time to be sent & if they have already been sent. However, there might be backwards compatibility problems, it would also require creating another resource which I'm not sure is desirable. Either way, the Firebase Extension's team will take a look, and get back to you. Thanks for the suggestion!

**Comment by LaravDev** [comment]
You could add the feature as optional in the extension's settings... and beware the users about the extra payload.

Thanks for taking this in consideration... one of the drawbacks of using the extension vs creating the function from the scratch is that we can't delay emails.

Sendgrid has options to achieve this... Also to use dynamic templates, but not possible with the Firebase extension...

Maybe that's another way to try? Check the sendgrid documentation to send the date and delayed email option and then the provider would be the one in charge of the delayed emails.

**Comment by taylorchance** [comment]
This is exactly what I need, please work on developing this feature!

**Comment by Doppelklick** [comment]
🙋‍♂️ same requirement here

**Comment by Bandit** [comment]
Same requirement here

**Comment by Raketten1963** [comment]
Same requirement here, my smtp provider has a max mails per minute etc, and this makes sending bulk emails out so much easier if we could just specify when a specific mail should send...
