### ISSUE TITLE
Firestore BigQuery Export: The backfill script doesn't support wildcards

### ISSUE THREAD

**Issue by dotmanish** [firebase/extensions#484]
- Extension name: **\_** firestore-bigquery-export
- Extension version: **\_** latest

#### Steps to reproduce:

1. Setup Firestore BigQuery Export extension with a wildcard collections path. e.g. `objects/{object}/list`
2. Attempt to backfill existing collections data to BigQuery via https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/guides/IMPORT_EXISTING_DOCUMENTS.md 

##### Expected result

The backfill script should support the same wildcard capability as the extension.

##### Actual result

The backfill script gives an error when a wildcard collection path is entered:
`The collection path must only contain letters or spaces`

**Comment by russellwheatley** [comment]
Hey @dotmanish, thanks for filing the issue. We are [aware](https://github.com/firebase/extensions/issues/370#issuecomment-652338351) of this short coming, but there isn't much we can do about it I'm afraid. Wildcards are allowed in cloud function Firestore triggers, but they aren't possible in Firestore queries.
