### ISSUE TITLE
Support non-default database in extensions that use Realtime Database

### ISSUE THREAD

**Issue by jhuleatt** [firebase/extensions#487]
### [REQUIRED] Step 2: Extension name

This feature request is for **`delete-user-data`** and **`rtdb-limit-child-nodes`**

### What feature would you like to see?

Just as `storage-resize-images` allows you to configure a bucket, our extensions that use Realtime Database should support [multiple Realtime Database instances](https://firebase.google.com/docs/database/usage/sharding#create_multiple_instances). Function triggers do support [multiple instances](https://firebase.google.com/docs/database/extend-with-functions#specify_the_instance_and_path).

We can follow the pattern set by [`storage-resize-images`](https://github.com/firebase/extensions/blob/2c993d1bfc9ba948b10b6c43f3c993819b229312/storage-resize-images/extension.yaml#L119-L130), where it defaults to the default bucket, but allows another bucket name to be entered.

### How would you use it?

Would allow developers that use multiple RTDB instances to use the above extensions on any instance.

**Comment by jhuleatt** [comment]
@Ehesp would it be possible to get this implemented early this week so it could go out in this week's release? It would be nice to support it given the recently announced [second RTDB region](https://firebase.googleblog.com/2020/11/realtime-database-region-and-api.html).

**Comment by dackers86** [comment]
Limit child nodes PR added at https://github.com/firebase/extensions/pull/504

**Comment by dackers86** [comment]
Delete user data PR added at https://github.com/firebase/extensions/pull/505
