### ISSUE TITLE
Add file attachment to "Send Email" feature. 

### ISSUE THREAD

**Issue by MalteMagnussen** [firebase/extensions#494]
### [REQUIRED] Step 2: Extension name

This feature request is for extension: **\_** (`firestore-send-email`)

### What feature would you like to see?

I would like to be able to attach a file to the sent email. 

### How would you use it?

I would like to upload a PDF to the database from my Flutter app, and then send that PDF automatically in an email as an attached file to the customer. 
The idea specifically is that the customer with one click can generate a PDF in the Flutter app and then have it sent to their email, so they can print it from their computer. 
Thinking of making the PDF via this package: https://pub.dev/packages/pdf , and then uploading it to a Firestore collection, and then having that trigger an email. 

Is this possible? Thank you.

**Comment by russellwheatley** [comment]
Hi @MalteMagnussen, it is possible already, but you do need another step. The pdf needs to be hosted somewhere (e.g. Firebase Storage). Grab the public URL for it, and put in a Firestore document. 

If you were using the `firestore-send-email` extension, you would put that URL in the `attachments` option as stated in the message [documentation](https://github.com/firebase/extensions/blob/next/firestore-send-email/POSTINSTALL.md#message-field). This would then send the pdf along with the email when triggered.

**Comment by MalteMagnussen** [comment]
Thank you @russellwheatley !
