### ISSUE TITLE
[BUG] resized images not named properly

### ISSUE THREAD

**Issue by marvinsxtr** [firebase/extensions#5]
### [READ] Step 1: Are you in the right place?

yes

### [REQUIRED] Step 2: Describe your configuration

- Extension name: `storage-resize-images`

### [REQUIRED] Step 3: Describe the problem

When uploading an image, it is only named `_WIDTHxHEIGHT` without the name.

#### Steps to reproduce:

Upload an image to storage bucket.

##### Expected result

The picture in the thumbnails folder should be named with the id corresponding to a firestore database document.

##### Actual result

The picture was named `_WIDTHxHEIGHT`.

**Comment by Salakar** [comment]
Hey @marvinsxtr 👋 thank you for reporting this issue, we'll get this looked at. 

I'll close this issue for now as we can track this on the duplicate issue https://github.com/firebase/extensions/issues/20 instead.
