### ISSUE TITLE
Backfill BigQuery dataset using Cloud Firestore Export

### ISSUE THREAD

**Issue by ashutoshpathak200** [firebase/extensions#510]
###  Describe your configuration

- Extension name: **`firestore-bigquery-export`** 
- Extension version: **v0.1.10**

### Describe the problem
I am fairly new to Cloud Firestore and BigQuery.
 I wish to import my existing documents in a collection using the `fs-bq-import-collection` script. The collection contains around ~2 million entries. 
The `fs-bq-import-collection` docs suggest [ loading data from a Cloud Firestore export into BigQuery](https://cloud.google.com/bigquery/docs/loading-data-cloud-firestore) for large collections.
However, the schema for the exported Cloud Firestore collection from Cloud Storage doesn't match the one with `raw_changelog` table for the collection. How should I go about this?

**Comment by russellwheatley** [comment]
Hey @ashutoshpathak200, thanks for reaching out. This is an interesting problem. The first thing that sticks out for me is the [limitations](https://cloud.google.com/bigquery/docs/loading-data-cloud-firestore#limitations). You have to create a new table or it will overwrite the existing data if you import to an existing table.

The next problem is importing it in the correct schema for the BigQuery extension like you said. I'm not a BigQuery expert but here are my two cents on how I would try:

The documentation says the schema is inferred when importing data from Firestore. Personally, I'd create a fresh table and use the exact schema that the BQ extension uses. i.e:
![Screenshot 2020-11-23 at 11 55 57](https://user-images.githubusercontent.com/16018629/99959406-de174f00-2d82-11eb-9984-d1d4172458ae.png)

I would then create a new collection, convert a fraction of your existing collection (say 100 records for testing purposes) into the schema your BQ table expects and insert into the new collection using the schema outlined above. This includes creating a value for `timestamp` (time now), `event_id` (this is [eventId](https://firebase.google.com/docs/reference/functions/cloud_functions_.eventcontext#eventid) from Firestore cloud trigger, you could create your own IDs I guess) `document_name` (document path in collection), `document_id` (self explanatory), `operation` (use import change [type](https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/firestore-bigquery-change-tracker/src/tracker.ts#L20)) & `data` (`JSON.stringify` the record from your collection. Use this [function](https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts#L92) to help you, you don't want to stringify any `Buffer` types nor any document reference types). 

I'm not sure this will work, hence why I recommend you try with a fraction of your collection to figure it out.

Although it's entirely possible there is an easier path that I've overlooked 😅 

Any thoughts @fredzqm @IanWyszynski?

**Comment by fredzqm** [comment]
Russell gave a great summary of options.

There is a separate Firestore/Datastore -> GCS export -> [BigQuery import)[https://cloud.google.com/bigquery/docs/loading-data-cloud-datastore#loading_cloud_datastore_export_service_data] integation.
It works great. BigQuery will automatically detect schema for you based on columns present there.

The schema do not work out of box with the extensions, but potentially u can create views on base on them to merge data.
We don't have tooling specific for this use case. The view query need to be written in case by case basis.

**Comment by ashutoshpathak200** [comment]
Thanks for the clarifications. As suggested, I will plan to create views on exported schema and try to merge it with the raw changelog file.
