### ISSUE TITLE
Dataset is created in incorrect location

### ISSUE THREAD

**Issue by mothman11** [firebase/extensions#511]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** firestore-bigquery-export
- Extension version: **\_**  v0.1.10
- Configuration values (redact info where appropriate):
  - **\_**
  - **\_** ![image](https://user-images.githubusercontent.com/54343728/100040680-dc6d8a00-2e5b-11eb-908f-3a7374464c4d.png)

### [REQUIRED] Step 3: Describe the problem

in v0.1.10 the update recently added configuration to specify the bigquery dataset location, however specifying a dataset location in sydney still created the dataset in the US

#### Steps to reproduce:

configure a new extension, specify sydney as the location, then check the dataset location in bigquery

##### Expected result

dataset created in location specified

##### Actual result

dataset is created in the US (the default?)

**Comment by mothman11** [comment]
Further thoughts - does the extension create the dataset at the time of installation, or when the first record is transferred?

I configured the extension, and then ran the backfill script, and I don't believe any records were processed before I ran the backfill. So it's possible that the backfill script created the dataset in the US if the dataset hadn't been created before?

**Comment by russellwheatley** [comment]
Hey @mothman11, I believe this has been updated to stop reconfiguration of the dataset location. Here's a screenshot of my update configuration inputs whilst  upgrading the BigQuery extension to `0.1.10`:
![Screenshot 2020-11-24 at 10 18 56](https://user-images.githubusercontent.com/16018629/100081048-79212f00-2e3e-11eb-8824-8b62098c005b.png)

To answer your question; The dataset is created the first time the cloud function is triggered by a Firestore [write](https://firebase.google.com/docs/functions/firestore-events#writing-triggered_functions) in the collection specified in your configuration. 

You can't change the location of an existing dataset once it has been placed somewhere. You would have to create a new instance of the extension which would create a fresh dataset instance in `australia-southeast1` (providing you give it a different dataset ID). 

Hope this helps.

**Comment by mothman11** [comment]
Thanks for that!

The documentation for the import script says:
"You will see redundant rows in your raw changelog table if either of the following happen:
If document changes occur in the time between installing the extension and running the import script."

I must admit I found this a little confusing, but it seemed to indicate that it's better to install the extension and run the import script before any document changes occurred.  If that's the case, for users to create a dataset in their desired location then it looks like they need to create the dataset manually first.

**Comment by russellwheatley** [comment]
The other option would be to pass a dataset location option into the import script.

**Comment by russellwheatley** [comment]
This package `@firebaseextensions/firestore-bigquery-change-tracker` also needs to be published before a different dataset location can be selected. The currently published version is `1.1.10` whilst version `1.1.11` has the dataset location changes.

**Comment by russellwheatley** [comment]
Hey @jhuleatt,  to clarify the problem; If the import script is used before the BigQuery extension is setup, it will automatically set the dataset location to the default location: `us` (multi-regional). If the user then sets up the BigQuery extension and chooses `europe-west2` as the dataset location, they will find the dataset location is actually in the `us`.

Possible solutions:

1. Provide another param input for the import script so the user can choose their dataset location. We would also have to document that once the dataset location is chosen, it cannot be changed even if they select a different location when setting up BigQuery extension. 
2. Update documentation informing user that the BigQuery extension ought to be setup first before backfilling existing data from Firestore collection. 

My preference is for option 2, I could be wrong, but I thought that was how it was designed. 

If we chose option 1, we would also have to update the console UI to stop users from being able to update the dataset location if they'd already used the import script (and thus already instantiated a BigQuery table).

**Comment by jhuleatt** [comment]
Let's take option 2 for now, and if it continues to be a problem we can consider option 1. @russellwheatley, can you start a PR for docs, and you and @kevinthecheung can collab to finalize them?

**Comment by russellwheatley** [comment]
Ok, probably should've read the docs a little more closely as it does actually [state](https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/guides/IMPORT_EXISTING_DOCUMENTS.md#important-notes) explicitly in the guide for the `import` script to run after the extension has been installed. 

It also [states](https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/PREINSTALL.md#backfill-your-bigquery-dataset) it in the BigQuery extension `PREINSTALL.md`  guide:

" **Important:** Run the import script over the entire collection _after_ installing this extension, otherwise all writes to your database during the import might be lost."

I'm going to close this issue for now then.
