### ISSUE TITLE
Gen schema doesnt support non US locations

### ISSUE THREAD

**Issue by fringley** [firebase/extensions#512]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: 
 @firebaseextensions/fs-bq-schema-view
extensions/firestore-bigquery-export/scripts/gen-schema-view/
Latest

#### Steps to reproduce:

Run the script as specified in the help.  BQ Dataset should be set up in a non US location

##### Expected result

Script completes without error

##### Actual result

Script completes with error:

```
{"errors":[{"reason":"notFound","message":"Not found: Dataset xxxxx-results:xxxxxx-results was not found in location US"}] ..... truncated ......
```

**Comment by russellwheatley** [comment]
I've just created a dataset in `europe-west2` and generated views using this script successfully.

Would you be be able to provide further steps/detail on how to reproduce this bug, please?

**Comment by fringley** [comment]
Hi @russellwheatley thanks for your message.  I ended up forking the repo code to add in location information, but it is possible that I also tweaked the name of the dataset or something else in the process. 

I will try and replicate this again if I get some time - but maybe you should close this issue as likely down to user error for now, unless I manage to replicate it!

**Comment by russellwheatley** [comment]
Hey @fringley, no worries! Looking at the code [here](https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/scripts/gen-schema-view/src/schema.ts#L115), it doesn't seem possible to "look" in the wrong location as only the dataset id is used to locate the correct dataset. 

Furthermore, I tested the BigQuery client by passing in a different location like so:

```js
// imagine dataset is actually in "europe-west2"
const dataset = bigquery.dataset("europa", {
  location: "us-central1",
});

// do a data insert...
```

It would still update the correct dataset in `europe-west2` without an error. I'll close the issue for now, but if you are able to replicate then I'd be happy to dig into it 😄

**Comment by fringley** [comment]
Hi @russellwheatley - I've just come to update my Schema, and I've come across this issue again.

I've installed the latest version of the script and included the full (redacted) version of the console message.  Perhaps it is to do with the way I have configured my project or environment?

`❯ npm list -g @firebaseextensions/fs-bq-schema-views
/Users/christingley/.nvm/versions/node/v14.15.4/lib
└── @firebaseextensions/fs-bq-schema-views@0.3.0 

❯ npx @firebaseextensions/fs-bq-schema-views \
  --non-interactive \
  --project=XXXXX-development \
  --dataset=XXXXX-development \
  --table-name-prefix=firestore_exports \
  --schema-files=/Users/christingley/git/XXXXX-lfd-results/schemas/lantern-submission.json
  
{"severity":"WARNING","message":"Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail"}
{"errors":[{"reason":"notFound","message":"Not found: Dataset XXXXX-development:XXXXX-development was not found in location US"}],"response":{"kind":"bigquery#job","etag":"3pG7SsN+PMVblZGHwuGn/w==","id":"XXXXX-development:US.03f54cab-003d-46da-bfdd-c15561931969","selfLink":"https://bigquery.googleapis.com/bigquery/v2/projects/XXXXX-development/jobs/03f54cab-003d-46da-bfdd-c15561931969?location=US","user_email":"chris.tingley@XXXX.co.uk","configuration":{"query":{"query":"CREATE FUNCTION IF NOT EXISTS `XXXXX-development.XXXXX-development.firestoreArray`(json STRING) RETURNS ARRAY < STRING > LANGUAGE js AS \"\"\"\n    function getArray(json) {\n      if(json) {\n        const parsed = JSON.parse(json);\n        \n        if(Array.isArray(parsed)) {\n          return parsed.map(x => JSON.stringify(x));\n        }\n        \n        return [];\n      }\n\n      return [];\n    }\n    \n    return getArray(json);\n    \"\"\";","priority":"INTERACTIVE","useLegacySql":false},"jobType":"QUERY"},"jobReference":{"projectId":"XXXXX-development","jobId":"03f54cab-003d-46da-bfdd-c15561931969","location":"US"},"statistics":{"creationTime":"1613054693914","startTime":"1613054693989","endTime":"1613054693989"},"status":{"errorResult":{"reason":"notFound","message":"Not found: Dataset XXXXX-development:XXXXX-development was not found in location US"},"errors":[{"reason":"notFound","message":"Not found: Dataset XXXXX-development:XXXXX-development was not found in location US"}],"state":"DONE"}},"message":"Not found: Dataset XXXXX-development:XXXXX-development was not found in location US"}

Not found: Dataset XXXXX-development:XXXXX-development was not found in location US`

**Comment by russellwheatley** [comment]
Hey @fringley , if it is an existing table, you cannot change its location I'm afraid.

**Comment by fringley** [comment]
Hi @russellwheatley - actually this is a clone of my original project - so the big query export and dataset is totally fresh...

**Comment by fringley** [comment]
![Screenshot 2021-02-11 at 15 17 22](https://user-images.githubusercontent.com/477265/107656900-83eca280-6c7c-11eb-93bf-40517101b1d7.png)

**Comment by dackers86** [comment]
Hi @fringley.

I'm getting used to this script but should your table be called `xxx-development` as opposed to `firestore_export`?

From the screenshot it appears that you're getting...

(namespace)xxx-development
(TableName)firestore_export

Whereas your error is looking for  `XXXXX-development:XXXXX-development`
 

Was that dataset created manually or as part of the script?

**Comment by fringley** [comment]
Hi @dackers86 yes I think you might be right, that’s a good spot. 

The dataset was created using the firestore BQ export cloud function extension and I think (based on the screenshot) has been created correctly. 

However it looks like perhaps there is a bug in the schema script which is mixing up the namespace and table name?

@russellwheatley perhaps you weren’t able to replicate this before because your namespace and table names were the same- in which case this issue might not occur?

**Comment by russellwheatley** [comment]
@dackers86 is correct. You need to change what params you pass into the script. You're passing the dataset id as `table-name-prefix`. Given your BigQuery setup as per the [screenshot](https://github.com/firebase/extensions/issues/512#issuecomment-777569749) you ought to be passing in the following params:

```bash
npx @firebaseextensions/fs-bq-schema-views \
  --non-interactive \
  --project=XXXXX-development \
  --dataset=firestore_export \
  --table-name-prefix=submissions\
  --schema-files=/Users/christingley/git/XXXXX/schemas/lantern-submission.json
``` 

The namespacing works like such: `[PROJECT_ID][DATASET_ID][TABLE_ID]`. `table-name-prefix` will have `_raw_changelog` & `_raw_latest` appended respectively when targeting the tables generated by the BigQuery extension for generating the views for `gen-schema-view` script.

**Comment by fringley** [comment]
Ha! OK, I feel like an idiot!  Thanks for clarifying this and my apologies for wasting your time on this!

Best wishes,
Chris.

**Comment by dackers86** [comment]
No problem @fringley. Happy it's all working!
