### ISSUE TITLE
auth-mailchimp-sync does not see Facebook user email

### ISSUE THREAD

**Issue by maxymczech** [firebase/extensions#513]
### Step 2: Describe your configuration

- Extension name: **auth-mailchimp-sync**
- Extension version: **0.1.2**
- Configuration values (redact info where appropriate):
  - **Cloud functions location: europe-west3**
  - **Contact status: subscribed**

### Step 3: Describe the problem

Extension works properly with new users that use password authentication method, but for users from Facebook extension logs to console message "User does not have an email", which is clearly not true, because I can see Facebook user emails in Authentication dashboard.

#### Steps to reproduce:

1. Add and activate **auth-mailchimp-sync** extension.
2. Authenticate using Facebook method

##### Expected result

Facebook user email should be added to Mailchimp audience

##### Actual result

Extension falsely claims that "User does not have an email"

**Comment by russellwheatley** [comment]
Hey @maxymczech, thanks for reaching out. I had a dig around and here's a couple of things of note:

1. If the user has not confirmed their Facebook account (i.e. confirmation link sent to email address), the email address will not be confirmed, and will not be passed to FirebaseAuth. Of course, there is nothing you can do if the user hasn't confirmed their email address.
2. Please ensure that you're asking for the email scope when you create the provider. The web setup looks like this for example:

```js
  var provider = new firebase.auth.FacebookAuthProvider();
  provider.addScope('email');
```

Once the above were in place, I was able to receive my email address when signing in with Facebook which is subsequently passed on to my MailChimp audience in the extension.

**Comment by maxymczech** [comment]
Thank you very much, I forgot to do that:

```
provider.addScope('email');
```
