### ISSUE TITLE
"Request contains an invalid argument." when try to update extension firestore-bigquery-export

### ISSUE THREAD

**Issue by liberathor** [firebase/extensions#517]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: firestore-bigquery-export
- Extension version: 0.1.10 
- Configuration values (redact info where appropriate):
     Previuous version: 0.1.9

#### Steps to reproduce:

try to update extesion but fails and shows warring: "Request contains an invalid argument.". but dont show what fields is wrong.

##### Expected result

Starts to update extension.

##### Actual result

Shows warring "Request contains an invalid argument." and stop it.

![imagen](https://user-images.githubusercontent.com/1112502/100458258-75d1b180-3091-11eb-90d5-56e8d5474cb8.png)

**Comment by arenphansen** [comment]
Seconded @liberathor, I'm getting the same issue as well trying to update. Hopefully someone will help us out! :)

**Comment by russellwheatley** [comment]
Hey folks, thanks for reporting this. It is a known [issue](https://github.com/firebase/extensions/issues/319), the workaround is to update the extension via the [CLI](https://firebase.google.com/docs/cli) until a fix is released. Apologies for the inconvenience!
