### ISSUE TITLE
Trigger Email doesn't send email anymore

### ISSUE THREAD

**Issue by mrtalkless** [firebase/extensions#525]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-send-email**
- Extension version: **0.1.6**
- Configuration values (redact info where appropriate):
  - Cloud Functions location : **asia-east2**
  - SMTP connection URI **smtp://noreply@xxx@smtp.office365.com:587**
  - Email documents collection **customer_service/report/report**
  - Default FROM address **noreply@xxx***
  - Default REPLY-TO address (Optional) **developer@xxx**
  - Users collection (Optional) **Parameter not set**
  - Templates collection (Optional) **Parameter not set**

### [REQUIRED] Step 3: Describe the problem

The extension was working before it prompted to update. The delivery.state still SUCCESS but the email didn't come at all. I had help from [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) to check this issue and they're saying that there's no missing configuration on my end and told me to file an issue within this github repository.

#### Steps to reproduce:

I don't know how to reproduce this issue since it was working before and there's no changed configuration.

##### Expected result

Receive email. 

##### Actual result

Email didn't come.

**Comment by russellwheatley** [comment]
Hi  @mrtalkless, sorry for the problem. I've just tested version `0.1.6` and I was able to send an email. Have you tried uninstalling and installing? 

Have you tested the SMTP connection outside of the extension to verify it isn't failing silently & emails are delivered correctly?

**Comment by mrtalkless** [comment]
Hi @russellwheatley, thanks for reply. I've tried checking connection with this tools : 

And here is the result :

> Connected to smtp://smtp.office365.com:587/?starttls=when-available
> << 220 xxx.outlook.office365.com Microsoft ESMTP MAIL Service ready at Tue, 8 Dec 2020 09:08:14 퍍
> >> EHLO [xxx]
> << 250-xxx.outlook.office365.com Hello [xxx]
> << 250-SIZE 157286400
> << 250-PIPELINING
> << 250-DSN
> << 250-ENHANCEDSTATUSCODES
> << 250-STARTTLS
> << 250-8BITMIME
> << 250-BINARYMIME
> << 250-CHUNKING
> << 250 SMTPUTF8
> >> STARTTLS
> << xxx SMTP server ready
> >> EHLO [xxx]
> << 250-xxx.outlook.office365.com Hello [xxx]
> << 250-SIZE 157286400
> << 250-PIPELINING
> << 250-DSN
> << 250-ENHANCEDSTATUSCODES
> << 250-AUTH LOGIN XOAUTH2
> << 250-8BITMIME
> << 250-BINARYMIME
> << 250-CHUNKING
> << 250 SMTPUTF8
> >> AUTH LOGIN
> << 334 xxx
> >> xxx==
> << 334 xxx
> >> xxx=
> << xxx Authentication successful
> >> MAIL FROM:<noreply@xxx> SIZE=567
> >> RCPT TO:<mahdi@xxx>
> << xxx Sender OK
> << xxx Recipient OK
> >> DATA
> << 354 Start mail input; end with <CRLF>.<CRLF>
> >> From: noreply@xxx
> >> Date: Tue, 08 Dec 2020 09:08:33 퍍
> >> Subject: SMTP test from smtp.office365.com
> >> Message-Id: <xxx@WIN-xxx>
> >> To: mahdi@xxx
> >> MIME-Version: 1.0
> >> Content-Type: multipart/alternative; boundary="=-xxx=="
> >>
> >> --=-xxx==
> >> Content-Type: text/plain; charset=utf-8
> >>
> >> Test message
> >> --=-xxx==
> >> Content-Type: text/html; charset=utf-8
> >> Content-Id: <xxx@WIN-xxx>
> >>
> >> <b>Test message</b>
> >> --=-xxx==--
> >> .
> << 250 2.0.0 OK <xxx@WIN-xxx> [Hostname=xxx.ausprd01.prod.outlook.com]

**Comment by russellwheatley** [comment]
Have you tried using `nodemailer` to send an email? This is what the extension uses. Just change the capitalised words:
```js
const nodemailer = require('nodemailer');
const transport  = nodemailer.createTransport('YOUR SMTP CONNECTION');

transport.sendMail({ to : 'TEST EMAIL', subject:'test subject'});
```

You could also try uninstalling and installing. Not much more I can do without a reproducible example I'm afraid.

**Comment by vincekruger** [comment]
I have the same problem. :(

Nodemailer works correctly and SMTP details are correct and functioning as they should, however, the firebase extension is not deploying correctly.  Multiple tries are needed to install and reconfigure the extension.  When it's finally installed/configured, the triggers don't fire.

**Comment by russellwheatley** [comment]
Hey @vincekruger, do you mind sharing the error messages? I wonder whether your problems are linked to this [issue](https://github.com/firebase/extensions/issues/529)

**Comment by vincekruger** [comment]
The only logs I get.


`5:55:18.586 pm
warning	
gmp_mods ext-firestore-send-email-processQueue
 {"@type":"type.googleapis.com/google.cloud.audit.AuditLog","status":{"code":3,"message":"Failed to retrieve function source code"},"authenticationInfo":{"principalEmail":"xxxxxxxx@cloudservices.gserviceaccount.com"},"serviceName":"cloudfunctions.googleapis.com","methodName":"google.cloud.functions.v1.CloudFunctionsService.UpdateFunction","resourceName":"projects/xxxxxx/locations/us-central1/functions/ext-firestore-send-email-processQueue"} 
`


`
5:55:18.126 pm
gmp_mods ext-firestore-send-email-processQueue
 {"@type":"type.googleapis.com/google.cloud.audit.AuditLog","authenticationInfo":{"principalEmail":"xxxxxx@cloudservices.gserviceaccount.com","serviceAccountDelegationInfo":[{"firstPartyPrincipal":{"principalEmail":"cloud-dm@prod.google.com"}}]},"requestMetadata":{"callerIp":"xxxxx","callerSuppliedUserAgent":"Google-Deployment-Manager,gzip(gfe),gzip(gfe)","requestAttributes":{"time":"2020-12-10T16:55:18.342971Z","auth":{}},"destinationAttributes":{}},"serviceName":"cloudfunctions.googleapis.com","methodName":"google.cloud.functions.v1.CloudFunctionsService.UpdateFunction","authorizationInfo":[{"resource":"projects/xxxxxx/locations/us-central1/functions/ext-firestore-send-email-processQueue","permission":"cloudfunctions.functions.update","granted":true,"resourceAttributes":{}}],"resourceName":"projects/xxxxxx/locations/us-central1/functions/ext-firestore-send-email-processQueue","request":{"@type":"type.googleapis.com/google.cloud.functions.v1.UpdateFunctionRequest","function":{"sourceArchiveUrl":"gs://firebase-mod-sources-prod/xxxxxx","description":"Processes document changes in the specified Cloud Firestore collection, delivers emails, and updates the document with delivery status information.","name":"projects/xxxxx/locations/us-central1/functions/ext-firestore-send-email-processQueue","runtime":"nodejs10","labels":{"goog-firebase-ext-iid":"firestore-send-email","goog-dm":"firebase-ext-firestore-send-email","goog-firebase-ext":"firestore-send-email","deployment-tool":"firebase-extensions"},"serviceAccountEmail":"ext-firestore-send-email@xxxxxx.iam.gserviceaccount.com","entryPoint":"processQueue","eventTrigger":{"eventType":"providers/cloud.firestore/eventTypes/document.write","resource":"projects/xxxxxx/databases/(default)/documents/mail/{id}"}},"updateMask":"runtime,description,ingressSettings,availableMemoryMb,environmentVariables,entryPoint,labels,sourceArchiveUrl,eventTrigger,timeout"},"resourceLocation":{"currentLocations":["us-central1"]}}`

**Comment by russellwheatley** [comment]
Thanks, that is very helpful. Like you said, it is the same bug. i.e `Failed to retrieve function source code`. I can only gather it is a bug in the infrastructure. Apologies for the inconvenience, I'd advise tracking this [issue](https://github.com/firebase/extensions/issues/529) as updates will probably occur there to keep issues separate 😄 .

**Comment by russellwheatley** [comment]
I'm going to close this as the bug in the Firebase backend has been [fixed](https://github.com/firebase/extensions/issues/529#issuecomment-744677294), will reopen if there is a verifiable bug in the `firestore-send-email` extension.
