### ISSUE TITLE
Resize images without a file extension

### ISSUE THREAD

**Issue by skotwani** [firebase/extensions#530]
### [READ] Step 1: Are you in the right place?

Ack

### [REQUIRED] Step 2: Extension name

`storage-resize-images`

### What feature would you like to see?

There are times where I obtain an image from a URL and don't deal with a file directly, but rather an array of bytes. I'd like to save an image file without an extension and still have it resized.

### How would you use it?

I'd like to download images from the web and save a resized version.

**Comment by russellwheatley** [comment]
Hey @skotwani, thanks for the suggestion. I'm not sure this is something the Firebase Extension's team will be interested in implementing. I'm sure they'll consider it and get back to you.

As a side note, you can actually set the content type when you upload a buffer to Firebase Storage. This, I believe, will store it as the relevant image file type and will trigger the extension to resize the image. See this SO [answer](https://stackoverflow.com/a/54751065/5681607) for inspiration.

**Comment by skotwani** [comment]
Thanks! I'll try that next time.

**Comment by jhuleatt** [comment]
Since we do support this if the `Content-Type` is set correctly, this seems like a docs issue. @russellwheatley can you please start a PR for a POSTINSTALL update that specifies which file extensions and content-types are valid? @kevinthecheung can review that and help craft it
