### ISSUE TITLE
firestore-bigquery-export: Schema Views Script create columns with mode REPEATED

### ISSUE THREAD

**Issue by yilunc** [firebase/extensions#533]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **\firestore-bigquery-export**: fs-bq-schema-views script

### What feature would you like to see?

The schema views script should be able to handle and create columns with mode `REPEATED`. It is documented in BigQuery that it supports nested and repeated structs but the schema views script is unable to create them. I tried specifying a field like so but the script does not parse the field correctly:

```
    {
      "name": "rates",
      "type": "map",
      "mode": "repeated",
      ...
```

### How would you use it?

The schema views script will be able to create columns with mode repeated so that more complex data types can be streamed from FS to BQ.

**Comment by russellwheatley** [comment]
Hey @yilunc, you can define maps in your schema by doing the following:

```json
{
  "fields": [
    {
      "name": "user",
      "type": "map",
      "fields": [
         //map properties are listed here
        {
          "name": "email",
          "type": "string"
        },
        {
          "name": "hometown",
          "type": "geopoint"
        },
        {
          "name": "name",
          "type": "string"
        }
      ]
    }
  ]
}
``` 
Described [here](https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md#how-to-configure-schema-files) in the docs. You can also keep nesting maps within maps.

Does this fulfil your needs?
