### ISSUE TITLE
[firestore-bigquery-export] JS object fields taking multiple log entries unnecessary 

### ISSUE THREAD

**Issue by leonidasv** [firebase/extensions#536]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **`firestore-bigquery-export`** 
- Extension version: **v0.1.10**
- Configuration values (redact info where appropriate):
  - See attached picture; different configurations results in the same problem.

### [REQUIRED] Step 3: Describe the problem
Log output by the _Export Collections to BigQuery_ extension is taking many log entries when outputting plain JS objects.

![chrome_kbtVVbyoGW-up](https://user-images.githubusercontent.com/17609157/102233365-f6384500-3ece-11eb-817d-f6f75f838c6e.png)

#### Steps to reproduce:

> What happened? How can we make the problem occur?

I've just installed the extension but got my logs polluted by unnecessary entries on Cloud Operations Logging every time some change is sent to BigQuery. This could be improved by using proper logging tools supported by Cloud Logging.

##### Expected result
Some info logs refer to a single operation and, as such, should take just one entry.

##### Actual result
Many log entries are taken, one for each line of an object output (see example above on "Started execution of extension" log).

**Comment by russellwheatley** [comment]
Hey @leonidasv, this is a good suggestion. I'm sure the Firebase Extension's team will consider it and get back to you.

**Comment by russellwheatley** [comment]
I agree, that isn't a great way to consume your logs. I'll see if there is a way of improving the output.
