### ISSUE TITLE
[firestore-bigquery-export] Allow disabling info/debug logs.

### ISSUE THREAD

**Issue by leonidasv** [firebase/extensions#537]
### [REQUIRED] Step 2: Extension name

This feature request is for extension: **firestore-bigquery-export**

### What feature would you like to see?
Sometimes, the extension is watching a Collection with multiple changes per minute. This creates lots of entries on Cloud Logging for debug/info reasons that are not useful, thus polluting the logs. Also, some logs take multiple lines unnecessary (see #536)

### How would you use it?
I would opt for disabling all debug and info logs for my extension installations. Only error/warning and above are useful for my application since data successfully sent by the extension is already available on BigQuery.

**Comment by russellwheatley** [comment]
Hey @leonidasv, the  is a good suggestion. I'm sure the Firebase Extension's team will consider it and get back to you.

**Comment by leonidasv** [comment]
@russellwheatley I've submitted a PR with an implementation: #538.

**Comment by i14h** [comment]
We think once #543 is merged this should be fine

**Comment by russellwheatley** [comment]
Closing this now, as #543 issue has been resolved.
