### ISSUE TITLE
[FR] Add option to make video and GIF thumbnails to the existing Resize Images extension or make a new extension

### ISSUE THREAD

**Issue by zbigniewzolnierowicz** [firebase/extensions#54]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **`storage-resize-images`**

### What feature would you like to see?

I would like to have an option to make it so that instead of just resizing GIFs, it would generate a still frame of that GIF.

Furthermore, extending the extension to be able to generate video thumbnails or making a new extension for that purpose would be greatly appreciated as well.

### How would you use it?

This would greatly improve workflow for social platforms where users upload a mix of GIFs, images and video.

**Comment by Ehesp** [comment]
XFN Team: Related https://github.com/firebase/extensions/issues/84

**Comment by i14h** [comment]
Thanks for the feedback. We think this might be better fit as a new extension request. We'll evaluate this request as we build more extensions.
