### ISSUE TITLE
storage-resize-images: allow to specify location where images should be resized

### ISSUE THREAD

**Issue by aduyng** [firebase/extensions#542]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: `storage-resize-images`

### What feature would you like to see?

Allow to provide a location (path) to a directory that contains image files to be resized or a regex. Currently, all uploaded images are resized without any exception

### How would you use it?

I would like to use one single firebase storage bucket for the entire application. This storage bucket contains more than just image files. There are image files that I don't want to be resized but the current extension resizes all of them.

**Comment by russellwheatley** [comment]
Hey @aduyng, this feature already exists. Check out the [additional setup](https://github.com/firebase/extensions/blob/next/storage-resize-images/README.md#additional-setup) for the `storage-resize-images`. You can either provide a list of paths that you want to be included for resize, or a list of paths that will not resize the image if the image is located there.

Hope this helps!
