### ISSUE TITLE
Audit all extensions for console.log

### ISSUE THREAD

**Issue by jhuleatt** [firebase/extensions#543]
Extensions should use the `logger` library instead of `console.log` to ensure objects are printed correctly. At the same time, we should make sure our logs are using the appropriate log level so that they can be filtered out in the logs viewer.

This would help with cleaner logs, like as requested in #537

**Comment by russellwheatley** [comment]
Hey @jhuleatt, I've left the logs in the `firestore-counter` as they're part of the tests and will not be used by the cloud function logs. Let me know if this is something that is required and I'll create a PR 😄

**Comment by jhuleatt** [comment]
Closing now that PRs cleaning up `console.log` are merged.
