### ISSUE TITLE
Extension doesn't work properly with uploaded images containing capital letters as file extension

### ISSUE THREAD

**Issue by ralphbolliger** [firebase/extensions#544]
Issue
- Extension name: `storage-resize-images`
- Extension version: `0.1.16`
- Configuration values:
  - Location: `europe-west6`
  - Sizes of resized images: `200x200,400x400,600x600,800x800,1000x1000,2000x2000`
  - Deletion of original: `false`
  - Convert image to preferred type: `false`

### Problem description
If the upladed file has capital letters (JPG, PNG) as file extension, the images get converted but named incorrectly (e.g. xps-dpbXgTh0Lac-unsplash.PNG_200x200).

#### Steps to reproduce:

1. **Get and install** the extension `storage-resize-images`.
2. Upload a file with **lower case file extension** (e.g. .jpg or .png).
3. You'll see correctly named converted files on the storage bucket.
4. **Delete those** files on the storage bucket.
5. Rename the same file on your computer so that it now has **capital letters** as file extension (e.g. .JPG or .PNG) and upload it again.
6. Now you'll see strangely named files after conversion (e.g. xps-dpbXgTh0Lac-unsplash.PNG_1000x1000)

<img width="1276" alt="Bildschirmfoto 2020-12-23 um 20 26 17" src="https://user-images.githubusercontent.com/1427508/103033316-7b23fe00-4562-11eb-970c-80121037dbc1.png">

##### Expected result
Correctly named image names after processing/resizing.

##### Actual result
The image sizes (_1000x1000) is attached at the end of the file name.

**Comment by russellwheatley** [comment]
Hey @ralphbolliger, thanks for reporting this. I have confirmed it is a bug.
