### ISSUE TITLE
fs-bq-import-collection printing usage message with no other details/errors

### ISSUE THREAD

**Issue by gregfenton** [firebase/extensions#545]
### Extension: fs-bq-import-collection

- Extension name: **fs-bq-import-collection**
- Extension version: **latest** (run via `npx @firebaseextensions/fs-bq-import-collection`)

### Describe the problem

Running this command in non-interactive mode with documented required parameters simply outputs the usage string.

#### Steps to reproduce:

Run the command: 

```bash
npx @firebaseextensions/fs-bq-import-collection --non-interactive --project t8s-project --source-collection-path act --dataset tick8s --table-name-prefix bqfs_tbl_act --batch-size 300
```

- The project `t8s-project` exists in both Firebase and BigQuery.
- The integration link to BigQuery has been already enabled in Firebase Console.
- The *Export Collections to BigQuery* extension is installed with the same values as the parameters seen in the above command.

##### Expected result

The docs from the `act` collection in Firestore would sync to a table in BigQuery named `bqfs_tbl_act_raw_changelog`

##### Actual result

The *usage* message is output, but with no details as to errors or missing parameters or anything.  No table is created, no data is available.

**Comment by gregfenton** [comment]
Got a working example with:

```
#!/bin/bash

PROJECT_ID=t8s-project
BQ_DATASET=tick8s
SOURCE_FS_COLLECTION=act
TBL_NAME=bqfs_tbl_act
BATCH_SIZE=300

FIREBASE_CONFIG=${PROJECT_ID} GCLOUD_PROJECT=${PROJECT_ID} \
  npx @firebaseextensions/fs-bq-import-collection \
  --non-interactive \
  --project ${PROJECT_ID} \
  --source-collection-path ${SOURCE_FS_COLLECTION} \
  --dataset ${BQ_DATASET} \
  --table-name-prefix ${TBL_NAME} \
  --query-collection-group false \
  --batch-size ${BATCH_SIZE}
```

**Comment by ebapp-dev** [comment]
I am also having the same problem. I've tried with interactive mode and non-interactive mode.
Is there a fix or a cookbook to solution?

**Comment by ebapp-dev** [comment]
I am also having the same problem. I've tried with interactive mode and non-interactive mode.
Is there a fix or a cookbook to solution?
