### ISSUE TITLE
Doc enhancement: example of CLI installation of `firestore-bigquery-export` using --paramsFile

### ISSUE THREAD

**Issue by gregfenton** [firebase/extensions#548]
### Extension: firestore-bigquery-export

This feature request is for extension: **docs enhancement**

### What feature would you like to see?

Documentation for how to install this extension via the CLI non-interactively.  Running `firebase ext:install firestore-bigquery-export --project=t8s-project` requires interactivity in answering the various questions.  The usage string indicates that `--params <paramsFile>` is how one would go about providing param variable values, but there is no further description or example as to what those parameters could (or must) be.

### How would you use it?

Reduce time and - more importantly - errors in setting up new Firebase projects.

**Comment by gregfenton** [comment]
Currently, I am getting:

```
$ cat ./paramsFile.env
LOCATION=us-central1
DATASET_LOCATION=us
COLLECTION_PATH=act
DATASET_ID=t8s-project
TABLE_ID=bqfs_tbl_act

$ firebase  --project=t8s-project ext:install --params ./paramsFile.env firestore-bigquery-export                                       
i  extensions: ensuring required API firebaseextensions.googleapis.com is enabled...
✔  extensions: required API firebaseextensions.googleapis.com is enabled
i  extensions: information about 'firestore-bigquery-export':
Name: Export Collections to BigQuery
Author: Firebase (https://firebase.google.com)
Description: Sends realtime, incremental updates from a specified Cloud Firestore collection to BigQuery.
License: Apache-2.0
Source code: https://github.com/firebase/extensions/tree/master/firestore-bigquery-export

? Would you like to continue installing this extension? (Y/n) 
```

As the last line indicates, this function is still running in interactive mode.

**Comment by gregfenton** [comment]
After reviewing `lib/commands/ext-install.js` it seems that the paramsFile is processed after prompting variants of `do you wish to continue?` 3 times:

1. after `extensionsHelper.confirmInstallInstance()`
2. after `billingMigrationHelper.displayNode10CreateBillingNotice()`
3. after `askUserForConsent.prompt(spec.displayName || spec.name, projectId, roles)`

After answering in the affirmative to the above, a message is displayed: `Installing your extension instance. This usually takes 3 to 5 minutes...` but with no output indicating that the paramsFile has been processed.

So doc enhancements I recommend are:
1. denote that there is no "non-interactive mode"
2. show a simple & valid example paramsFile (see my previous comment), and its use with `--params` parameter.  Note in this example that the user is required to review and affirm some statements.

**Comment by jhuleatt** [comment]
Thanks for the feedback! The `--params` flag is [documented in the Firebase docs](https://firebase.google.com/docs/extensions/install-extensions?platform=cli#install), although it is a bit hidden:

![Screen Shot 2021-01-11 at 2 51 26 PM](https://user-images.githubusercontent.com/3759507/104247407-9aed6a00-541c-11eb-93cf-61653cd642ba.png)

I'm adding in our tech writer @kevinthecheung regarding the feedback that we should update the docs to note that the install command is never *truly* non-interactive.

Regarding the enhancements, @gregfenton can you please file those as a feature request on the [firebase-tools repository](https://github.com/firebase/firebase-tools)? They sound like good ideas worth considering, and all of our install CLI code lives in the firebase-tools repo.

**Comment by gregfenton** [comment]
Feature Request submitted via the Firebase Support page as indicated by the GitHub issues template for the firebase-tools repo.

**Comment by jhuleatt** [comment]
I've filed an issue internally for the docs update to clarify the not-so-non-interactive nature of the non-interactive mode

**Comment by gregfenton** [comment]
FOR FUTURE ME:  I just submitted another feature request to Firebase Support: allow setting of an extension's `instanceId` as a parameter from `--param <paramsFile>`.  Currently on lines 77-92 of `firebase-tools/src/commands/ext-install.js`, if the default instanceId is already in use then it prompts the user for a new ID.  I would like to be able to specify the ID entirely from the command-line and not allow any "defaults" to get in the way.
