### ISSUE TITLE
[firestore-bigquery-export] Clustering possible?

### ISSUE THREAD

**Issue by alexstanbury** [firebase/extensions#550]
This feature request is for extension: firestore-bigquery-export

I can't see any way of enabling [clustering](https://cloud.google.com/bigquery/docs/clustered-tables) using this extension, and I'd really like to be able to do so to speed up query times and save money. Is there any plan to implement this functionality at any point or am I gonna have to roll my own?

**Comment by russellwheatley** [comment]
Hey @alexstanbury, thanks for the feature request. I might be mistaken, but I don't think the nodejs client used by the extension has the ability to cluster a table. I can't see it in the `createTable` [metadata](https://github.com/googleapis/nodejs-bigquery/blob/master/src/table.ts#L128) nor in the client samples in the Google Cloud [docs](https://cloud.google.com/bigquery/docs/creating-clustered-tables#java_1) Unless you have found a way? 

Either way, it is a good suggestion that will be considered, but you might have to roll your own in the mean time.

**Comment by alexstanbury** [comment]
According to the createTable [docs](https://googleapis.dev/nodejs/bigquery/latest/Dataset.html#createTable) you can pass in an [options](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#resource) object that contains a `clustering` property that will enable clustering. That documentation also says the following ```Clustering specification for the table. Must be specified with time-based partitioning, data in the table will be first partitioned and subsequently clustered.``` It's not clear from reading that whether you can only cluster if you also do time-based partitioning, or you have to cluster if you want to do time-based partitioning.

**Comment by russellwheatley** [comment]
I created a question on the BigQuery nodejs client to track [here](https://github.com/googleapis/nodejs-bigquery/issues/910)

**Comment by alexstanbury** [comment]
Thanks, Russell.

**Comment by i14h** [comment]
@dackers86 I moved this to under consideration since according to https://github.com/googleapis/nodejs-bigquery/issues/910 clustering should be supported

**Comment by dackers86** [comment]
Closed via https://github.com/firebase/extensions/pull/891
