### ISSUE TITLE
storage-resize-images seems to delete empty file uploads 

### ISSUE THREAD

**Issue by MrAndrew** [firebase/extensions#554]
### [READ] Step 1: Are you in the right place?

Maybe, not sure if this is a bug or an intended result.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: storage-resize-images
- Extension version: 0.1.16 and at least one other previous version (sorry I don't know which was installed before updating)
- Configuration values (redact info where appropriate):
  - **\_**
  - **\_**

#### Steps to reproduce:

Uploading empty new image files to a storage path from JavaScript client, ex: `var testFile = new File([""], "test_png.png", {type: "image/png"});   storageRef.put(testFile)` results in success but the files never appeared in the console. I then happened to just upgrade the extension to 0.1.16 and tried again during the process and found my empty png files in the console.

Once the function finished upgrading the same deletion issue happened and then I uninstalled it and the empty files again uploaded without any issue.

 I believe the extension was configured on a completely different storage path type then the storage path used to test these png uploads to. The extension was definitely configured to only convert to jpegs.
 
I will reconfirm with a fresh installation and configuration to confirm if this is simply a deletion of an empty file issue or if the path listened to was also an issue. I will update when I do.

##### Expected result

My empty test image file uploads to not be affected at all.

##### Actual result

My empty test image file uploads appeared to be deleted by the extension.

**Comment by MrAndrew** [comment]
I don't seem to be experiencing the same issue after a fresh install. I do know for sure that this was happening earlier though. Maybe something with the way the absolute paths listened to where being set from the console in a previous version.

**Comment by russellwheatley** [comment]
Hey @MrAndrew, just to be clear. When you say "results in success". Do you mean a successful image resize or upload to bucket?

**Comment by MrAndrew** [comment]
> Hey @MrAndrew, just to be clear. When you say "results in success". Do you mean a successful image resize or upload to bucket?

I mean that uploading the image from the client app was successful and threw no errors. Although I can't seem to replicate the results after uninstalling and reinstalling the extension function via the firebase console.

**Comment by russellwheatley** [comment]
hmmm, do you think you may have had the `DELETE_ORIGINAL_FILE ` setting set to `true`?

**Comment by MrAndrew** [comment]
I think it might have been on, yes. So the issue might be that it deleted the original and wrote nothing because of the way it reads an empty file?

**Comment by russellwheatley** [comment]
> I think it might have been on, yes. So the issue might be that it deleted the original and wrote nothing because of the way it reads an empty file?

I think your intuition is correct with a slight tweak. I just tested `sharp` library resizing with an empty image and it threw an error which to my mind is correct as it doesn't seem feasible to resize something that doesn't exist. In previous versions of the extension, the original image would be deleted even if there was an error. In the current version, we do check that the original image was successfully [resized](https://github.com/firebase/extensions/blob/next/storage-resize-images/functions/src/index.ts#L145) before deleting.

Thanks for reporting, but I think the extension is working as intended 😄

**Comment by MrAndrew** [comment]
It appears to be that way. Just a problem of a setting to delete the original and there was nothing to write in a new empty file. Thanks for the clarification and help.
