### ISSUE TITLE
Use wildcards in paths for resizing images

### ISSUE THREAD

**Issue by Hivemind9000** [firebase/extensions#560]
### Extension name

storage-resize-images

### What feature would you like to see?

The ability to use glob-like wildcards in paths for specifying the location of images we want to resize.

E.g. "/user/*/images" will match the image subdirectory of all users (E.g. /user/a2/images, /user/b3/images etc)

Also support ** for directory matching at any depth.

### How would you use it?

As with documents stored in Firestore, where the pathing structure denotes the logical informational hierarchy, the storage bucket paths normally follow the same structure (for storing large objects associated with the Firestore documents). In the example above, storing a user's personal account images.

As it currently stands, I can't make use of this handy extension.

**Comment by russellwheatley** [comment]
Hey @Hivemind9000, thanks for the feature request. As long as it doesn't break existing functionality, it looks something we would implement.  

We also accept pull requests if you are keen to see it implemented. This is the [function](https://github.com/firebase/extensions/blob/next/storage-resize-images/functions/src/util.ts#L10) that checks the path.

Here's a scratch pad with a couple of annotations for illustration:
```js
const imagePath = "/path/storage/bucket/images";

// this will work. It only has to match the initial path so images in any sub-directory are resized
const userInputPaths = ['/path'];

// this won't work
const userInputPaths = ['/path/nope'];

const startsWithArray = (
  userInputPaths,
  imagePath
) => {
  for (let userPath of userInputPaths) {
    const trimmedUserPath = userPath.trim();
    const regex = new RegExp("^" + trimmedUserPath + "(?:/.*|$)");

    if (regex.test(imagePath)) {
      return true;
    }
  }
  return false;
};



console.log(startsWithArray(userInputPaths, imagePath));
```

**Comment by Hivemind9000** [comment]
Thanks @russellwheatley. The documentation is a little light, so it wasn't clear (to me at least) that the top-level partial path would work. For now, I can use this approach to get things working.

I'd still like this feature, so as to be selective/specific about which images I want processed and how - i.e. some may need different sized thumbs. As I have a private beta launch hurtling towards me, I don't have the calendar or head space to look at a PR, but will keep an eye on progress and... you never know. ;-)

**Comment by jhuleatt** [comment]
This sounds like a useful feature request. My understanding is that we'd update the logic behind the `EXCLUDE_PATH_LIST` and `INCLUDE_PATH_LIST` params to support wildcards in the middle of the path.

**Comment by khchong** [comment]
I was hoping this was supported already but looks like it's not. Glad to see it being accepted in the update tracker and can't wait to use it when it's deployed (hopefully soon so I can update my code before we go to prod 🤞 )

**Comment by Hivemind9000** [comment]
Have now hit the point where we really need this feature. @russellwheatley I see the changes have been made and are in review (many thanks btw). How long do you estimate until this is in production?
