### ISSUE TITLE
Visual Studio 2019 c # connection with Firebase

### ISSUE THREAD

**Issue by Agnaldo-MR** [firebase/extensions#562]
I tried hours and even days to look for application examples for connecting VS 2019 (in C #) with firebase, but without any success. I feel that almost nobody uses it for lack of more detailed information.

I downloaded it as FirebaseAuthentication.net, FirebaseDatabase.net and also FireSharp on VS. But, the documents are very superficial and I'm not able to use them.

Example: 1- Send and search for user authentication information with email and password 2- Access nodes and their children for reading and writing. 3- What does .StartAt (???) .LimitToFirst (???) .OnceAsync () mean? (from FirebaseDatabase.net) 4- Main properties of each "using" needed. 5- How to search and send the unique id push command through firebase.

Example:

var firebase = new Firebase.Database.FirebaseClient("https://fir-app-20502.firebaseio.com/");

                    var idUser = await firebase
                      .Child("CSharp")
                      .OrderByKey()
                      .StartAt(???)
                      .LimitToFirst(???)
                      .OnceAsync<???>();

I've been watching some videos of an Indian about firesharp, but there is nothing about authentication.

In the firebase documentation I found nothing about C #. Are there any plans to launch in the future?

Note: If possible with complete words, as it is in English and I am from Brazil.

**Comment by russellwheatley** [comment]
Hey @Agnaldo-MR, this is the wrong repo I'm afraid. Here is a link to the [dotnet](https://github.com/firebase/firebase-admin-dotnet) firebase sdk repository. Here is a link to the documentation [reference](https://firebase.google.com/docs/reference/admin/dotnet) on the firebase website. 

Hope this helps!
