### ISSUE TITLE
FEEDBACK WANTED: storage-resize-images: feature request. put failed resizes in "failed" directory.

### ISSUE THREAD

**Issue by russellwheatley** [firebase/extensions#563]
### [READ] Step 1: Are you in the right place?

Yes.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: `storage-resize-images`

### What feature would you like to see?

In its current form, the `storage-resize-images` extension will not delete the original image if the [Delete on successful resize](https://github.com/firebase/extensions/blob/next/storage-resize-images/extension.yaml#L157) option is configured. Images remain in the bucket and the ones that failed are logged in the cloud logs.

This issue is to track whether there is any interest from users in having an option for a separate directory (e.g. "failed/" directory) where failed image resizes are placed.

**Comment by i14h** [comment]
@karayu this is another usecase for a custom hook, after the operation is performed
