### ISSUE TITLE
[firestore-bigquery-export] Add partitioning to reduce query costs

### ISSUE THREAD

**Issue by jasonberryman** [firebase/extensions#570]
This feature request is for extension: firestore-bigquery-export

Add a partitioning field to allow the table to be partitioned using a particular field in the Firestore document.

This will allow a table to be partitioned on a bespoke field, reducing query costs when handling large datasets.  Partitioning on the UTC `timestamp` is not always optimal, as reports tend to be run at a time local to the user.

**Comment by russellwheatley** [comment]
Hey @jasonberryman, thanks for the feature request! The FE team are currently considering whether to allow table partitioning here: https://github.com/firebase/extensions/issues/316. Please track this issue if you want to be updated 😄
