### ISSUE TITLE
[firestore-bigquery-export] Using Firestore export for importing documents not helpful

### ISSUE THREAD

**Issue by IchordeDionysos** [firebase/extensions#571]
This feature request is for extension: **`firestore-bigquery-export`**

### What feature would you like to see?

The docs suggest that one should use Firestore exports for large collections, but that is not very helpful as an BigQuery import from a Firestore export has a very different [schema](https://cloud.google.com/bigquery/docs/loading-data-cloud-firestore#data_type_conversion) than the schema of the extension.

A better approach would be to make use of the Firestore `getPartitions()` functionality on collection groups and from there spin up various instances (maybe Cloud Run, maybe Compute Engine), run these queries all in parallel.
And each query would then stream the data to a Cloud Storage file that after the query partition is finished gets loaded into BigQuery using a batch (rather than a streaming) import.

### How would you use it?

This would work perfectly for collection with 100k or more rows.

### Questions about concrete implementation

Or is my premise wrong and I am missing something that makes the "import of the Firestore export"-approach compatible?

Is this something that makes sense to you from a architectural approach?
Would it make sense to use Cloud Run if ensuring that the computation time per partition is < 1h. (Probably easier to setup/deploy)
Or would it make sense to go directly with Compute Engine?

**Comment by russellwheatley** [comment]
Hey @IchordeDionysos, there is an import script that batches Firestore records and inserts them into the BigQuery table created by the extension. Documentation [here](https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/guides/IMPORT_EXISTING_DOCUMENTS.md). Does this fulfil your needs?

**Comment by IchordeDionysos** [comment]
@russellwheatley yes, I am aware of, but for larger collections this is not really an option as the import would take much longer and it honestly a bit flaky for that, due to Firestore backend errors in large batch jobs.

The proposed alternative was to use a Firestore export, but as described above this does not really fulfill the need, as the schema is different.

**Comment by russellwheatley** [comment]
That's fair enough. I don't have experience backfilling such a vast amount of documents into an existing BigQuery table created by the extension. 

Hey @fredzqm, do you have any thoughts on a solution to such a problem?

**Comment by fredzqm** [comment]
There exists a way to export Datastore/Firestore and import them into BigQuery.
https://cloud.google.com/bigquery/docs/loading-data-cloud-datastore

The schema, however, isn't compatible. I would recommend using UNION those tables in SQL if desired.
The pro for the managed export pipelines: parallelized, all data exported. It is a good fit if u want a periodically backup and write volume is high. All documents are billed one read for one export.
The pro for the BigQuery export extension: delta based, realtime. It is a good if u want to track all history changes and write volume is low. Cloud Function is billed.

**Comment by jhuleatt** [comment]
@russellwheatley let's try to work out and document some way to do a big initial import. Whether it's making the schemas mesh between [Firestore exports to BQ](https://cloud.google.com/bigquery/docs/loading-data-cloud-firestore) and our import script, or another suggestion on how to do a big import. Right now our docs are a little handwavey:

> The import script can take up to O(collection size) time to finish. If your collection is large, you might want to consider [loading data from a Cloud Firestore export into BigQuery](https://cloud.google.com/bigquery/docs/loading-data-cloud-firestore).
