### ISSUE TITLE
Array of Maps Schema Example

### ISSUE THREAD

**Issue by pauhlbarnes** [firebase/extensions#573]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **\_** (`firestore-bigquery-export`)

### What feature would you like to see?

Please provide a schema example for an array of Maps in the GENERATE_SCHEMA_VIEWS.md
### How would you use it?

To enable breaking out of data stored as an array of maps.

**Comment by dackers86** [comment]
Hi @pauhlbarnes. 

Given the current documentation, i'm not too sure if this something that is available in the schema generation.

Could you provide an example of the data structure you would intend to use, we have an array example, but i'm assuming the following does not apply?

```
{
    "fields": [
      {
        "name": "name",
        "type": "string"
      }
    ],
    "name": "friends",
    "type": "map"
 }
```

**Comment by pauhlbarnes** [comment]
Thanks, my data structure in firestore looks like the attached image

**Comment by dackers86** [comment]
Hi @pauhlbarnes 
 
Apologies, I cannot see an attachment in your previous message? 

Was there an attachment added when the issue was created?

**Comment by hernantz** [comment]
Hi @pauhlbarnes and @dackers86 
I'm facing a similar issue, given this JSON structure
```json
{
    "user": "foo",
    "friends": [
            {
                  "firstName": "John",
                  "lastName": "Doe"
            },
            {
                  "firstName": "Jane",
                  "lastName": "Doe"
            } 
    ]
}
```
This schema representation won't work, right?

```json
{
    "fields": [
       {
            "name": "user",
            "type": "string"
        },
        {
            "name": "friends",
            "type": "map",
            "mode": "repeated",
            "fields": [
                {
                  "name": "firstName",
                  "type": "string"
                }, 
                {
                  "name": "lastName",
                  "type": "string"
                }
            ]
        }
    ]
}
```

Or at least this is what I understand from [this comment](https://github.com/firebase/extensions/issues/583#issuecomment-772538442) from https://github.com/firebase/extensions/issues/583.
Although it would seem to be possible to implement, according to the [BigQuery docs on nested structs](https://cloud.google.com/bigquery/docs/nested-repeated).

**Comment by darnmason** [comment]
Any intentions to support this array of maps?

My use case is similar to @hernantz

**Comment by polenvinagre** [comment]
Hi! I have been using this extension for a year and it is a great tool.
Good job!
Now I have a new project that has an: ARRAY OF MAPS
Could you give some updates about this enhancement?
Thanks in advance!

**Comment by Mr-Goldberg** [comment]
would be great if you implement this feature!

**Comment by zallesov** [comment]
Came here with the same request. 
The current implementation of an array is hazardous. A nested array has multiple entries which will result in multiple copies of a hosted object in BQ. Counting them will yield the wrong results.

**Comment by GaL3n** [comment]
The same thing for me, I have orders in WooCommerce format in a collection, and I can't analyze the meta_data within the line_items :(. 

Exporting the entire collection manually, without using the extension, and importing it into Bigquery works perfectly.

**Comment by dackers86** [comment]
Hi All.

The main discussion for this feature, was include the PR we have recently merged.

This can be found [here](https://github.com/firebase/extensions/pull/1366). 

This update will be released soon.

As this is a tricky issue as there are so many ways this can be improved. 

Please review the PR, if this does provide the solution you are looking for, we're happy to continue the discussion here and further enhance this feature.

**Comment by eigidi** [comment]
the feature supports typed arrays, but it does not seem to work for arrays of maps

**Comment by pr-Mais** [comment]
Hello, since this issue is closed, could you please @eigidi open a new issue with the details of your request to better track it, thank you!

**Comment by eigidi** [comment]
I have submitted this [issue 1963](https://github.com/firebase/extensions/issues/1963)
