### ISSUE TITLE
[storage-resize-images] Multiple image output types for resizer

### ISSUE THREAD

**Issue by japettyjohn** [firebase/extensions#575]
### [REQUIRED] Step 2: Extension name

This feature request is for extension: **storage-resize-images**

### What feature would you like to see?

I'd like to output multiple image formats from one original file, e.g. origin is a JPEG and outputs JPEGs and WEBP.

### How would you use it?

I'd be using it to get the benefits of lower sizes of WebP while maintaining browser compatibility offering JPEGs.

**Comment by dackers86** [comment]
Hi @japettyjohn.

I'll update this for consideration.

In the meantime a solution would be to install another extension for each different image type you require.

**Comment by jhuleatt** [comment]
Thanks for the request @japettyjohn! This sounds like a worthwhile change, given that we already support multiple image sizes in the `IMG_SIZES` param. We can change the `IMAGE_TYPE` param's type to `multiSelect` to get this functionality.

**Comment by dackers86** [comment]
@jhuleatt A multi select seems the best option.

This would remove the `Do not convert` option, i'm assuming that would not be an issue as we are specifying the exact conversions needed.

**Comment by dackers86** [comment]
Initial PR added at https://github.com/firebase/extensions/pull/579
