### ISSUE TITLE
storage-resize-images and COMPRESS!!!

### ISSUE THREAD

**Issue by demiantriebl** [firebase/extensions#576]
Step 2: storage-resize-images

This feature request is for extension: storage-resize-images

### What feature would you like to see?

I would like them to use image compression technology such as squoosh.app, or one that with some artificial intelligence algorithm can detect which is the maximum compression for the definition in question.

### How would you use it?

I really believe that everything that web or mobile applications is full of images, the download weight of the application for the most part is given by images, and many times I cannot depend on the user who is in charge of compressing them previously.

**Comment by dackers86** [comment]
HI @demiantriebl .

This extensions currently uses the https://github.com/lovell/sharp module for resizing and compressing images. The images you have should now much smaller than your original images.

Are you currently seeing issues with the size of your processed images?

**Comment by demiantriebl** [comment]
I used sharp, but the compression that squoosh allows is really higher (my tests gave approximately 30% or more depending on the image between sharp and squoosh), apart from the possibility of seeing the maximum compression without losing quality is very difficult to observe When one put the definition in hard code, at this moment of artificial intelligence and impressive algorithms such as superzoom, applying one to check the maximum compression without losing quality would be a tool that we all use, daily, in all our applications.

**Comment by jhuleatt** [comment]
@demiantriebl thanks for the request! It looks like the Squoosh CLI is still [experimental](https://github.com/GoogleChromeLabs/squoosh/tree/dev/cli#squoosh-cli), so not something we're prepared to add to this extension. Also not sure how compatible it would be with Cloud Functions, as it seems pretty resource-intensive. However, I'll reach out internally to some folks on the Chrome team to see if they're interested in prototyping out an [experimental extension](https://github.com/FirebaseExtended/experimental-extensions) that uses Squoosh.
