### ISSUE TITLE
[Trigger Email] SSL routines:ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by superdiazzz** [firebase/extensions#580]
### [READ] Step 1: Are you in the right place?
Yup

### [REQUIRED] Step 2: Describe your configuration

- Extension name: firestore-send-email
- Extension version: 0.1.7
- Configuration values (redact info where appropriate):
  - **\_**
  - **\_**

#### Steps to reproduce:

I just upgrade into blaze and trying to use Trigger Email, but am stuck with Error where i can produce manually input data in firestore inside `mail` folder. What error said like so:

`Error: 68919280695104:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:`

![Screen Shot 2021-02-01 at 19 12 33](https://user-images.githubusercontent.com/10770867/106457368-789db800-64c1-11eb-8a94-20c64f790354.png)

anyone can explain to me what happen with this?

**Comment by dackers86** [comment]
Hi @superdiazzz 

This could potentially be an issue with your configuration.

Can you confirm in a terminal that your connections works as expected, via...

```
 openssl s_client -connect <hostname>:<port>
```

This is to firstly confirm that it is not a Firebase related issue.

**Comment by superdiazzz** [comment]
Thanks for reply @dackers86 
this is result of my terminal

![Screen Shot 2021-02-01 at 21 06 44](https://user-images.githubusercontent.com/10770867/106469191-8fe4a180-64d1-11eb-9b02-9f43f3bd31f2.png)

**Comment by dackers86** [comment]
After investigating, the following provides a valid certificate...

```
openssl s_client -connect smtp.mailketing.id:587 -starttls smtp
```

**Comment by dackers86** [comment]
@superdiazzz 

The following thread provides a similar issue https://github.com/firebase/extensions/issues/412.

Could this be resolved with your email service provider? https://mailketing.co.id

**Comment by superdiazzz** [comment]
@dackers86 i still getting the issue

**Comment by dackers86** [comment]
@superdiazzz .

Have you had any feedback from `mailketing` to see why your attempts are currently failing?  Quoting `starttls` may help to solve the issue.

They have a live chat support and may provide any insight into any updates / changes needed?

**Comment by russellwheatley** [comment]
Hey @superdiazzz, have you successfully sent an email using your configuration yet? Here's a scratch pad for you to run via nodejs: 

```js
//remember to install nodemailer first 
const nodemailer = require("nodemailer");

async function sendEmail() {
  let transporter = nodemailer.createTransport(
    "INSERT YOUR SMTP URI STRING HERE"
  );

  await transporter.sendMail({
    from: `fake@email.com`, // anything
    to: "fake@email.com", // your email address
    subject: "Hello", // Subject line
    text: "test email", // plain text body
  });
}

sendEmail();

```

**Comment by superdiazzz** [comment]
> @superdiazzz .
> 
> Have you had any feedback from `mailketing` to see why your attempts are currently failing? Quoting `starttls` may help to solve the issue.
> 
> They have a live chat support and may provide any insight into any updates / changes needed?

actually i don't know how to explain to their customer support. Did you think there are something must be enable from their side? can i just copy and paste the error, and they would be understand that ?

**Comment by superdiazzz** [comment]
> Hey @superdiazzz, have you successfully sent an email using your configuration yet? Here's a scratch pad for you to run via nodejs:
> 
> ```js
> //remember to install nodemailer first 
> const nodemailer = require("nodemailer");
> 
> async function sendEmail() {
>   let transporter = nodemailer.createTransport(
>     "INSERT YOUR SMTP URI STRING HERE"
>   );
> 
>   await transporter.sendMail({
>     from: `fake@email.com`, // anything
>     to: "fake@email.com", // your email address
>     subject: "Hello", // Subject line
>     text: "test email", // plain text body
>   });
> }
> 
> sendEmail();
> ```

i have not studied node js yet. Can i use online tools or something else can be execute directly?

**Comment by dackers86** [comment]
@superdiazzz.

Yes their support team has proven very efficient so far. Please refer to there online chat here https://mailketing.co.id. 

Copy the error into  your explanation, at the very least this will be eliminate the problem coming from your email provider.

**Comment by superdiazzz** [comment]
@dackers86 thank you for your advice, my email provider has helped me, they suggested to change `smtps` be `smtp`. Actually it little bit weird because, in input placeholder (in Firebase) says `smtps`. At least error status has gone. it SUCCESS, but why i didn't receive any email yet?
there something i missing?

**Comment by dackers86** [comment]
Hmm that is strange, the response seems to suggest it has been successful. A few suggestions...

- Check your spam email to ensure the message has not been filtered in your `recipients` emails.
- Can you confirm the response still has `queued`? This would suggest a backlog which may be a delay sending the email

**Comment by superdiazzz** [comment]
Yes, i tested for many times.

- I have checked spam, no found there
- and message response still `250 2.0.0 Ok: queued as 451A8C5AC2`

Do you know what happened?

**Comment by dackers86** [comment]
From a Firebase point of view this seems to be working as expected.

This appears to be another issue with either your email provider or the receiving client.

It appears that the email or domain sender must verified in your account, I believe this has now been setup.

Can you please try another attempt at sending an email?

**Comment by superdiazzz** [comment]
@dackers86 you 're right, my provider needs validation from the sender, now i keep in touch with him about this. i think my problem has been solved. thank you very much
