### ISSUE TITLE
Export fs-bq-schema-views does not work with Firecloud Map

### ISSUE THREAD

**Issue by michaelgriffithus** [firebase/extensions#583]
### [READ] Step 1: Are you in the right place?
Yes

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** (`storage-resize-images`, `firestore-send-email`, etc)
- fs-bq-schema-views
- Extension version: **\.01.12**
- Configuration values (redact info where appropriate):
  - **\_**\
  - Function Location: us-east4 
  - Big Query Dataset Location: us 
  - Collection Path: participant-response 
  - Dataset Id: shape_dev 
  - Table Id: participant_response 
  - Schema:
  - 
  {
  "fields": [
    {
      "name": "participantId",
      "type": "string"
    },
    {
      "name": "surveyId",
      "type": "string"
    },
    {
      "name": "profile",
      "type": "string"
    },
    {
      "name": "org",
      "type": "string"
    },
    {
      "name": "profileDOB",
      "type": "string"
    },
    {
      "name": "dateWritten",
      "type": "timestamp"
    },
    {
      "name": "responses",
      "type": "map",
      "fields": [
        {
          "name": "question",
          "type": "string"
        },
        {
          "name": "response",
          "type": "string"
        }]
    }
  ]
}
  - **\_**

#### Steps to reproduce:
Installed extension into my Firebase project and configured the extension, I then ran the script to create the schema and fs-bq-import-collection to import my firebase collection.  All of the fields configured in the schema were created in the big query view with the exception of the map of questions and responses from Firecloud.

What happened? How can we make the problem occur?
This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.
Scripts ran as expected but produced a null field for the map

##### Expected result
Fields from Firecloud map to be included in the BigQuery view

##### Actual result
Fields in the big query view were present for the map but null.   These fields are not null in the Firecloud collection.

**Comment by michaelgriffithus** [comment]
The fields that represent the map in Firecloud collection appear as null
aways.   So in this case I have two fields in each row of the view called
question and response which are always null.
...

{
  "name": "responses",
  "type": "map",
  "fields": [
    {
      "name": "question",
      "type": "string"
    },
    {
      "name": "response",
      "type": "string"
    }]
}

The actual collection is a JSON object array defined as map in the
Firecloud collection and looks like:

{
  "complete": true,
  "dateWritten": {
    "value": {
      "_seconds": 1604416666,
      "_nanoseconds": 976000000
    }
  },
  "profileDOB": "11/03/2017",
  "responses": [
    {
      "question": "d635f126-e754-3f5b-2cff-f713a3b2e42d",
      "response": "This is for Jason"
    },
    {
      "question": "1a0ae85b-610e-b782-60de-c6e6b8e5590d",
      "response": "2"
    },
    {
      "question": "a03a6a2c-9218-f00d-91c9-dd03ced47622",
      "response": "2020-11-3"
    },
    {
      "question": "9249609e-910b-bd25-e041-7ba0514e8cd5",
      "response": [
        "1"
      ]
    },
    {
      "question": "f096ad61-7e1a-3494-6660-2292c268bea5",
      "response": "2"
    },
    {
      "question": "338de24c-a7f7-dc10-a314-04e67d4ee839",
      "response": 26
    },
    {
      "response": "This is a large text area",
      "question": "3d51b7d8-0fb2-4ab5-6bd1-bdd9842e0f21"
    },
    {
      "response": "4",
      "question": "f7c38dfb-74ce-0cdd-9964-afb91f0893be"
    }
  ],
  "questionnaireId": "eeHjsy5knYHv4306tp5o",
  "org": "TEST",
  "participantId": "101",
  "profile": "Jason",
  "surveyId": "N5j9Q997ySvKTNvwjbuh",
}



...

**Comment by russellwheatley** [comment]
That won't work because the schema you have defined is looking for responses with an object type, in your collection, it is an array of nested objects type. In the `gen-schema-view` scripts current implementation, you cannot define a nested array schema type I'm afraid. Here is the [gen-schema-view](https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md) guide which might be helpful.

**Comment by cabljac** [comment]
Going to close this as resolved for now. We have the feature request https://github.com/firebase/extensions/issues/1051 (requested several times).
