### ISSUE TITLE
fs-bq-import-collection - ENOENT error with a non-root collection path

### ISSUE THREAD

**Issue by gregfenton** [firebase/extensions#584]
### Describe your configuration

- Extension name: **firestore-bigquery-export**
- Extension version: **0.1.12**
- Configuration values (redact info where appropriate):
  - Cloud Functions location: **us-central1**
  - BigQuery Dataset location: **us**
  - Collection path: **config/recurring/recur_act**
  - Dataset ID: **tick8s**
  - Table ID: **bqfs_tbl_recur_act**

### Describe the problem

Running the command `@firebaseextensions/fs-bq-import-collection` throws an error (see command and output below).  The exact parameters (see "configuration" section above) do work for the extension -- changing a doc in Firestore does have the record sync to BigQuery.  But running this command to import existing docs to BigQuery fails.  The exact same command works fine for a `--source-collection-path` whose collection is a top-level (a "root") path.

This fails:
```
npx @firebaseextensions/fs-bq-import-collection --non-interactive --project tick8s-test --source-collection-path 'config/recurring/recur_act' --query-collection-group false --dataset tick8s --table-name-prefix bqfs_tbl_xxx --dataset-location us --batch-size 300
{"severity":"WARNING","message":"Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail"}
Importing data from Cloud Firestore Collection: config/recurring/recur_act, to BigQuery Dataset: tick8s, Table: bqfs_tbl_xxx_raw_changelog
{"severity":"INFO","message":"BigQuery dataset already exists: tick8s"}
{"severity":"INFO","message":"Creating BigQuery table: bqfs_tbl_xxx_raw_changelog"}
{"severity":"INFO","message":"Created BigQuery table: bqfs_tbl_xxx_raw_changelog"}
{"severity":"INFO","message":"Creating BigQuery view: bqfs_tbl_xxx_raw_latest\nQuery:\n-- Retrieves the latest document change events for all live documents.\n--   timestamp: The Firestore timestamp at which the event took place.\n--   operation: One of INSERT, UPDATE, DELETE, IMPORT.\n--   event_id: The id of the event that triggered the cloud function mirrored the event.\n--   data: A raw JSON payload of the current state of the document.\n--   document_id: The document id as defined in the Firestore database\nSELECT\n  document_name,\n  document_id,\n  timestamp,\n  event_id,\n  operation,\n  data\nFROM\n  (\n    SELECT\n      document_name,\n      document_id,\n      FIRST_VALUE(timestamp) OVER(\n        PARTITION BY document_name\n        ORDER BY\n          timestamp DESC\n      ) AS timestamp,\n      FIRST_VALUE(event_id) OVER(\n        PARTITION BY document_name\n        ORDER BY\n          timestamp DESC\n      ) AS event_id,\n      FIRST_VALUE(operation) OVER(\n        PARTITION BY document_name\n        ORDER BY\n          timestamp DESC\n      ) AS operation,\n      FIRST_VALUE(data) OVER(\n        PARTITION BY document_name\n        ORDER BY\n          timestamp DESC\n      ) AS data,\n      FIRST_VALUE(operation) OVER(\n        PARTITION BY document_name\n        ORDER BY\n          timestamp DESC\n      ) = \"DELETE\" AS is_deleted\n    FROM\n      `tick8s-test.tick8s.bqfs_tbl_xxx_raw_changelog`\n    ORDER BY\n      document_name,\n      timestamp DESC\n  )\nWHERE\n  NOT is_deleted\nGROUP BY\n  document_name,\n  document_id,\n  timestamp,\n  event_id,\n  operation,\n  data"}
{"severity":"INFO","message":"Created BigQuery view: bqfs_tbl_xxx_raw_latest"}
{"severity":"INFO","message":"Inserting 13 row(s) of data into BigQuery"}
{"severity":"INFO","message":"Inserted 13 row(s) of data into BigQuery"}
Error importing Collection to BigQuery: Error: ENOENT: no such file or directory, open '/Users/greg/.npm/_npx/55957/lib/node_modules/@firebaseextensions/fs-bq-import-collection/lib/from-config/recurring/recur_act-to-tick8s-test_tick8s_bqfs_tbl_xxx_raw_changelog'
```

#### Steps to reproduce:

1. Create a Firestore collection that is NOT at the root.  Any path such as `a/b/c` will do.
2. Install the firestore-bigquery-export extension to your project
3. Run the command as above using `--source-collection-path "a/b/c"`

The docs from `a/b/c` get imported as rows to BigQuery, but you get the "ENOENT" error as above.

##### Expected result

No errors.

##### Actual result

`ENOENT` error as per above.

**Comment by dackers86** [comment]
Hi @gregfenton.

Thanks for this. I'll attempt to recreate from the data provided above to see if I can reproduce the issue.

**Comment by dackers86** [comment]
Hi @gregfenton 

It's my understand based on the following that you will need collectionGroup set to true to access documents not at the root.


```
--query-collection-group true
```

This ensures that a collectionGroup is selected as part of the query...

```js
  if (queryCollectionGroup) {
    query = firebase.firestore().collectionGroup(sourceCollectionPath);
  } else {
    query = firebase.firestore().collection(sourceCollectionPath);
  }
```

Additionally you may need the required indexes setup for queries in order for the documents to be found https://firebase.googleblog.com/2019/06/understanding-collection-group-queries.html

Rules guide is also here 
https://firebase.google.com/docs/firestore/security/rules-query#secure_and_query_documents_based_on_collection_groups

**Comment by gregfenton** [comment]
I do not believe the documentation discusses that the import only works for collections at the root?  If it does, it isn't clear.

I believe this is simply an issue with the script trying to create its cache file by using the sourceCollectionPath value thus failing because the SCP in this use case has `/` in it.  It looks like the actual import itself works (though I didn't try with a large volume of data, so maybe it would fail on the second "page" of values?).

This is not a collection-group-query situation, or at least IMO should not be considered as such.  I am grabbing a specific collection at a specific path, it just so happens that the path has a `/` in it.

I believe that the code "is close to correct", but needs a tweak around the cache file naming and clean-up.

**Comment by dackers86** [comment]
Thanks @gregfenton.

You are correct, i've added a PR above.
