### ISSUE TITLE
fix(*): Code coverage checks block features from merging

### ISSUE THREAD

**Issue by dackers86** [firebase/extensions#587]
When attempting to improve code coverage using the `firestore-send-email` module it is proving difficult to add coverage without breaking the CI. This PR can be seen [here](https://github.com/firebase/extensions/pull/527).

Separate investigations have been attempted to improve the coverage of modules such as the `Firebase Cli`, it is considered the lack of coverage on dependent modules such as the Cli are causing the coverage to drop.

Proposed solution and steps to update:

1. Remove code coverage check in the CI to enable modules to merge without having to hit the current threshold. (fixes https://github.com/firebase/extensions/pull/586).

2. Merge required modules for coverage (fixes https://github.com/firebase/extensions/pull/527)

**Comment by i14h** [comment]
@jhuleatt has fixed this
