### ISSUE TITLE
[firestore-bigquery-export] Use backticks for the schema fields to escape keywords

### ISSUE THREAD

**Issue by kuuuurt** [firebase/extensions#591]
### Describe your configuration

- Extension name: **firestore-bigquery-export** 
- Extension version: **0.1.12**

### Describe the problem

I have a field in my Firestore collection named `hash`. Unfortunately when I try to generate the schema, it'll just give an error `Syntax error: Unexpected keyword HASH at [6:42]`.

#### Steps to reproduce:

1. Create a firestore collection with a document with a field named `hash`
2. Export to BigQuery using the extension
3. Generate schema views using the script with the following schema.json:
```json
{
    "fields": [
        {
            "name": "`hash`",
            "type": "string"
        }
    ]
}
```

I tried to create the view manually and the SQL script generated was 
```sql
JSON_EXTRACT_SCALAR(data, '$.hash') AS hash
```
with the error being `hash` as a keyword in SQL. If the generated field name has backticks: 
```sql
JSON_EXTRACT_SCALAR(data, '$.hash') AS `hash`
```
Then the issue would be resolved.

##### Expected result
It should be able to create the schema view

##### Actual result
Error in creating the schema view: `Syntax error: Unexpected keyword HASH at [6:42]`

**Comment by dackers86** [comment]
Thanks for the issue @kuuuurt.

This looks like something that should be investigated. 

In the meantime would it be possible to rename the `hash` field to something that would conflict?

**Comment by kuuuurt** [comment]
Workaround with #592
