### ISSUE TITLE
[firestore-bigquery-export] Way to handle duplicate fields

### ISSUE THREAD

**Issue by kuuuurt** [firebase/extensions#592]
### Describe your configuration

- Extension name: **firestore-bigquery-export** 
- Extension version: **0.1.12**

### Describe the problem

I have a field in my Firestore collection named `timestamp`. The view already has a `timestamp` field so it conflicts with my `timestamp` field. Is there a way to preserve my field's name and provide an alternative name to prevent the conflict?

#### Steps to reproduce:

1. Create a firestore collection with a document with a field named `timestamp`
2. Export to BigQuery using the extension
3. Generate schema views using the script with the following schema.json:
```json
{
    "fields": [
        {
            "name": "`timestamp`",
            "type": "number"
        }
    ]
}
```

##### Expected result
It should be able to create the schema view

##### Actual result
Error in creating the schema view: `Field timestamp already exists in schema`

**Comment by dackers86** [comment]
@kuuuurt 

I'll need to confirm , but feel that `timestamp` is currently a reserved keyword.

This could potentially be a request for an update that could override `reserved` or `key` fields?

**Comment by kuuuurt** [comment]
Yes. If there's a way we can use the `timestamp` field but maybe we can change the name somehow to prevent collision

```json
{
   "name: "timestamp",
   "type": "number",
   "???": "other_name_for_timestamp" // to be used in the SQL script
```

Just an idea but maybe you could have some better way.

**Comment by dackers86** [comment]
@kuuuurt 

It appears this functionality already exists...

```
{
  "fields": [
    {
      "name": "order", //reserved sql column name
      "type": "string",
      "column_name": "new_column_name"
    },
    {
      "name": "select", //reserved sql column name
      "type": "number",
      "column_name": "other_new_column_name"
    }
  ]
}
```

This is not currently documented, so i'll create a PR for more visibility for the feature.

This will also be a potential solution for https://github.com/firebase/extensions/issues/591

**Comment by kuuuurt** [comment]
It works! For both issues. Thanks!
