### ISSUE TITLE
file renaming after resize is wrong with uppercased file extension 

### ISSUE THREAD

**Issue by damienromito** [firebase/extensions#601]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: `storage-resize-images`
- Extension version: `v0.1.17`
- Configuration values 
![Capture d’écran 2021-02-15 à 14 35 29](https://user-images.githubusercontent.com/603808/107953203-181b7a00-6f9b-11eb-9285-2e6718a1c73b.png)
ct info where appropriate):

### [REQUIRED] Step 3: Describe the problem
If I upload file with file with uppercased extention, je renaming doesn't works 
logo.jpg => logo_100x100.jpg ✅
logo.JPG => logo.JPG_100x100 ✅
![Capture d’écran 2021-02-15 à 14 28 44](https://user-images.githubusercontent.com/603808/107952955-bbb85a80-6f9a-11eb-92c2-0517a5bd47b9.png)
.

##### Expected result
logo_100x100.JPG
##### Actual result
logo.JPG_100x100

**Comment by dackers86** [comment]
@damienromito this has only recently been fixed as part of the following PR https://github.com/firebase/extensions/pull/549.

Is this a recent installation you are using? Reinstalling the extension should hopefully fix the issue based on the above

**Comment by damienromito** [comment]
Thank you very much. It's works perfectly
