### ISSUE TITLE
Allow for datasets to be created in us-central1 

### ISSUE THREAD

**Issue by carloshoyos** [firebase/extensions#602]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **firestore-bigquery-export** 
### What feature would you like to see?

When installing the extension, you can specify the location for the dataset.  However, us-central1 is not available in that drop down.  If you already have other data in that region that you want to combine with this dataset, you need to create it in the same region.  

### How would you use it?

Join newly created data with other datasets that are in the us-central1 region.

**Comment by dackers86** [comment]
Hi @carloshoyos.

Based on https://cloud.google.com/bigquery/docs/locations this could be a viable option. 

I will add this for review
