### ISSUE TITLE
storage-resize-images - custom name suffixes for resized images

### ISSUE THREAD

**Issue by chrisjacobs91** [firebase/extensions#604]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: `storage-resize-images`

### What feature would you like to see?

The ability to map resize dimensions to names that override the suffix appended to the new file's filename.

I have added this as custom code to my installation of the extension. 

I have added a custom IMG_SIZE_NAMES parameter. 
<img width="505" alt="Screenshot 2021-02-20 at 15 31 55" src="https://user-images.githubusercontent.com/25010842/108600910-a2941d00-7391-11eb-8a66-f219fdb49c9a.png">

Then for each resize, the string appended to the filename is determined using this code:
```
const suffixes = IMG_SIZES.map((size, index) => {
  return IMG_SIZE_NAMES[index] || size
})

So the suffix falls back to the size string if there any IMG_SIZE_NAMES values (or if there aren't enough of them).

### How would you use it?
I use this so the client app can reference the _medium image, despite our resizing sizes changing as we support large devices and/or we get increase storage budget.
```

**NOTE** - The reason I want this as an officially supported feature is so I can continue to update to the latest version of the extension without having to rewrite these changes each time.

**Comment by karayu** [comment]
Hi chrisjacobs91, thanks for the feedback! This is a really great idea and use case. We're working on making it easier to reference the resulting images from using the resize images extension. We'll circle back with that solution when it's ready!

**Comment by patrinoua** [comment]
Also no suffix would be great, for the case for example that you just want to resize every picture.
Adding a suffix complicating things, specially in the case when resize went wrong and the resized file was not generated.
So it would be great to just add one filepath on the db as a reference and not one depending on wether there is a suffix or not.
Thank you :)

**Comment by dackers86** [comment]
Hi All, as we would like to limit the amount configuration for each extension and given the complexity of this.

We recently release Events for this extension, which allows customisation of images once they have been resized. Perhaps a guide on how to do this would allow developers to customise the name of their resized extensions?
