### ISSUE TITLE
storage-resize-images: resized smaller images have bigger file size than original

### ISSUE THREAD

**Issue by chrisjacobs91** [firebase/extensions#605]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: `storage-resize-images`
- Extension version: **0.1.18**
- Configuration values (redact info where appropriate):
 - IMG_SIZES: 818x4000

#### Steps to reproduce:
1. Upload a portrait JPEG image (with dimensions 1010x1794)
2. Image is resized to 818x1453 px (where 1453 is the image ratio x 818)
3. Dimensions are smaller than the original, however the file size of the resized image is 171KB (original is 122KB)

##### Expected result
Reduced size image should have smaller file size

##### Actual result
It has a larger file size.

If this is inevitable for images of certain sizes / % of originals, could the function just return the original image, as the larger dimensions but smaller file would be preferable to store.

**Comment by i14h** [comment]
@dackers86 could this be due to difference in `quality`?

**Comment by dackers86** [comment]
@chrisjacobs91 Can you confirm that this configuration is correct?

```
IMG_SIZES: 818x4000
```

Using the value provided I appear to get different results

![image](https://user-images.githubusercontent.com/2060661/108828704-17986a00-75bf-11eb-8f8a-244d871bb6ca.png)


@i14h That has potential, however we do currently set the quality for the image resizer while other examples appear to be ok?

**Comment by chrisjacobs91** [comment]
@dackers86 that's correct, (although I actually used 750x4000 in the end), however I'm getting the following results:
<img width="890" alt="Screenshot 2021-02-23 at 11 21 01" src="https://user-images.githubusercontent.com/25010842/108836839-4582ac00-75c9-11eb-9417-4a6685e1b199.png">

(FYI - I have customised the function to append strings to the filename instead of image sizes, but medium is the 750x4000 resizing)

**Comment by dackers86** [comment]
Thanks @chrisjacobs91.

Apologies, I may be missing something. Is that not correct? The medium image is smaller, following the resize and (i'm assuming) compression from the resize function?

**Comment by chrisjacobs91** [comment]
Sorry! I uploaded the wrong screenshot. 
<img width="633" alt="Screenshot 2021-02-23 at 11 59 56" src="https://user-images.githubusercontent.com/25010842/108840716-a9f43a00-75ce-11eb-9f58-61bec6dd1b74.png">

It seems to only happen when the image aspect ratio is **very** portrait, i.e. much taller than wide. This image was an iPhone X screenshot, but the one I sent before in error was an iPhone portrait photo (which isn't as thin).

This is the original photo if you want to try:
https://firebasestorage.googleapis.com/v0/b/sail-ties-staging.appspot.com/o/voyages%2FF2A8960F-454A-4FB2-9A6A-CE52AC84684D%2Fimages%2F9C767C88-6344-4C1D-88E0-7D869DD48F80%2F9C767C88-6344-4C1D-88E0-7D869DD48F80.jpg?alt=media&token=a32336f1-291a-45ad-857e-0257702c1a73

**Comment by dackers86** [comment]
@chrisjacobs91 Thanks for this.

Using the image provided, you are correct = there does appear to be a scenario where larger images are created. To simplify the issue, I have tested with the following...

```js
const sharp = require("sharp");

(async () => {
  await sharp("./test-sm.jpg")
    .jpeg()
    // .jpeg({ quality: 10 })  Does not exist in the current extension
    .rotate()
    .resize(parseInt(750, 10), parseInt(4000, 10), {
      fit: "inside",
      withoutEnlargement: true,
    })
    .toFile("example.jpeg");
})();
```

I believe @i14h is also correct. As the docs state below, the default quality is 80. This extension does not currently allow the quality settings to be overridden on a Jpeg format...

https://sharp.pixelplumbing.com/api-output#jpeg

Using the example above we can generate smaller images than the original

**Comment by chrisjacobs91** [comment]
Ok thank you, I will try that out :)
