### ISSUE TITLE
firestore-bigquery-export: Arrays containing Strings imported into bigquery are wrapped in double quotes

### ISSUE THREAD

**Issue by peili** [firebase/extensions#611]
[REQUIRED] Step 2: Describe your configuration
Extension name: firestore-bigquery-export in particular for the view creating script (https://github.com/firebase/extensions/blob/master/firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md)
Extension version: v0.1.12
[REQUIRED] Step 3: Describe the problem
Arrays containing String values in bigquery are wrapped in extra double-quote characters. So you'll see "foo" in bigquery instead of foo.

Steps to reproduce:
Import data into bigquery that has an array with string values.

Expected result
The array of strings values is not wrapped in double quotes.

Actual result
The array of strings get an extra double-quote character (") at the start, and one at the end too. 

Related to: https://github.com/firebase/extensions/issues/295

**Comment by dackers86** [comment]
Thanks @peili.

I'll investigate as this issue should fixed with the above related issue.
