### ISSUE TITLE
Allow to create Webp image

### ISSUE THREAD

**Issue by inglesuniversal** [firebase/extensions#616]
Official plugin completely ignores GIF files and does NOT create single frame Webp output file inside predefined thumbs folder. 

Previous versions of plugin did work as expected.

any ideas?

**Comment by dackers86** [comment]
Hi @inglesuniversal

Officially we do not currently support the resizing  of `gif` images. As the imagining library produced mixed results as shown in https://github.com/firebase/extensions/issues/590.

Ultimately we waiting for gif support to fully introduce this a type that be converted, but I can add this for investigation as a `single frame` use case

**Comment by inglesuniversal** [comment]
Please do, keep it open or active as other users/developers may need it.

It would be odd that I would be the only request, as even today, gif files on social media and chat applications are really handy and useful.

**Comment by jhuleatt** [comment]
A little more background: this extensions switched from using `imageMagick` to `sharp` to support webp (https://github.com/firebase/extensions/pull/207). However, sharp [doesn't support GIFs out of the box](https://sharp.pixelplumbing.com/api-output#gif)

**Comment by jhuleatt** [comment]
@inglesuniversal just to double check this is a sharp/imagemagick thing though, which version worked with gifs/webp as expected for you?

**Comment by inglesuniversal** [comment]
It was the same plugin back in 2020, not sure what version was though... I think back then it was converted to gif but your script made a one-frame.gif file as the thumbnail.

**Comment by i14h** [comment]
@inglesuniversal thanks for the suggestion. Since Sharp doesn't support GIFs we'll close this ticket and document that the extension doesn't support GIFs
