### ISSUE TITLE
Export Collections to BigQuery GENERATE_SCHEMA_VIEWS.md Error

### ISSUE THREAD

**Issue by mwe1** [firebase/extensions#617]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-bigquery-export** 
- Extension version: **0.1.13**

#### Steps to reproduce:

1. Running npx @firebaseextensions/fs-bq-schema-views 
2. Providing my project ID, Dataset ID, collection name and schema json file
3. Console output 
{"code":400,"errors":[{"message":"Provided Schema does not match Table {my project ID}:{my dataset ID}.users_schema_user_changelog. Cannot add fields (field: termsAccepted)","domain":"global","reason":"invalid"}],"response":{"headers":{"alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","cache-control":"private","content-encoding":"gzip","content-type":"application/json; charset=UTF-8","date":"Tue, 09 Mar 2021 08:34:13 GMT","etag":"52qmhOin8/vYu1eXWqY2wg==","server":"ESF","transfer-encoding":"chunked","vary":"Origin, X-Origin, Referer","x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN","x-xss-protection":"0"}},"message":"Provided Schema does not match Table {my project ID}:{my dataset ID}.users_schema_user_changelog. Cannot add fields (field: termsAccepted)"}

##### Expected result

It has already worked once and I could successfully generate the schema once. Now I have updated the schema by adding some new fields, and I would expect it to overwrite the old schema with the new one.

##### Actual result

Throwing this 400 error telling me I cannot add a specific field.

**Comment by dackers86** [comment]
Hi @mwe1.

Could the following be related? https://github.com/firebase/extensions/issues/423

**Comment by mwe1** [comment]
Hi @dackers86 ,
thank you it was related and solved the issue. I had to manually delete the views from BigQuery console first and then run the script again.
