### ISSUE TITLE
firestore-bigquery-export: export from multiple collections

### ISSUE THREAD

**Issue by luismolina13** [firebase/extensions#619]
### [REQUIRED] Step 2: Extension name

This feature request is for extension: firestore-bigquery-export

### What feature would you like to see?

Is it possible to export multiple collections instead of only one?

### How would you use it?

I want to export multiple collections from firestore to big query to be able to join and analyze the data better.

**Comment by dackers86** [comment]
Hi @luismolina13 

I believe the extension only handles one collection per installation. 

However, you can install multiple instances of the extension to sync multiple collections. 

Please see https://github.com/firebase/extensions/issues/12

**Comment by luismolina13** [comment]
Thank you!!
