### ISSUE TITLE
[storage-resize-images] Output options

### ISSUE THREAD

**Issue by japettyjohn** [firebase/extensions#620]
### [REQUIRED] Step 2: Extension name

This feature request is for extension: **storage-resize-images**

### What feature would you like to see?

I'd like to set a way of setting output options for the sharp image processor.

### How would you use it?

Change the settings like options.quality for webp and the various configuration options for jpeg.

**Comment by dackers86** [comment]
Hi @japettyjohn.

Thanks for the request, this is something that was recently discussed as part of https://github.com/firebase/extensions/issues/605.

I'll put this up for discussion.
