### ISSUE TITLE
auth-mailchimp-sync: Add "firebase" tag to entry in mailchimp

### ISSUE THREAD

**Issue by alexcastillo** [firebase/extensions#623]
### Extension name

This feature request is for extension: `auth-mailchimp-sync`

### What feature would you like to see?

I'd like to be able to identify the users that firebase has added to Mailchimp. A "firebase" tag would allow me to create a Mailchimp segment and only send emails to firebase users.

Thank you!

**Comment by dackers86** [comment]
Closing in favour of https://github.com/mailchimp/Firebase/issues/27

**Comment by alexcastillo** [comment]
I'm curious, why was the issue closed and referenced in a newly opened ticket?

Since I'm not part of that new ticket, I won't be notified for updates.

**Comment by dackers86** [comment]
Hi @alexcastillo.

This extension is no longer maintained in this repository,  instead it is officially maintained by Mailchimp on their ownGithub.

Apologies for any inconvenience, any further queries for Mailchimp extensions should come from the linked repository

**Comment by alexcastillo** [comment]
No worries at all, that makes sense. Thanks!
