### ISSUE TITLE
error throwing on expectede behaviour

### ISSUE THREAD

**Issue by FredCoen** [firebase/extensions#624]
Removing Errors of expected behavior in the following two scenarios:

Removing a non-existent member throws an error. Non-existence is expected because members unsubscribe regularly from an audience. Should log the info but not throw an error. The final state is the same.

Adding a member who already is part of the audience throws an error. You often have multiple ways users can signup to an audience. Firebase auth is only one of them. Should log the into but not throw an error. The final state is the same.

**Comment by FredCoen** [comment]
PR made : https://github.com/firebase/extensions/pull/600

**Comment by dackers86** [comment]
Thanks @FredCoen. I've added this to our tracker for review.

**Comment by dackers86** [comment]
Closing in favour of https://github.com/mailchimp/Firebase/issues/33.

This extension is now maintained in the official Mailchimp Github organisation.
