### ISSUE TITLE
fs-bq-schema-views script: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by slickorange** [firebase/extensions#627]
### [READ] Step 1: Are you in the right place?
I have an issue with the `fs-bq-schema-views` script for the firestore-bigquery-export extension.
### [REQUIRED] Step 2: Describe your configuration

- Extension name: firestore-bigquery-export
- Extension version: 0.1.13

### [REQUIRED] Step 3: Describe the problem
I get the following error when trying to run the fs-bq-schema-views script.

```
{"severity":"WARNING","message":"Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail"}
{}
Cannot read property 'map' of undefined
```

#### Steps to reproduce:

I am running the command as follows:

```
npx @firebaseextensions/fs-bq-schema-views \
  --non-interactive \
  --project=my-project\
  --dataset=firestore_export_staging \
  --table-name-prefix=orders \
  --schema-files=orders.json 
```

I have made my json file very simple to make sure it is not an issue with the json:

```
{
  "fields": [
    {
      "name": "id",
      "type": "string"
    },
    {
      "name": "systemId",
      "type": "number"
    }
]
}
```
##### Expected result
The relevant view should be generated in BigQuery.

##### Actual result
I get an error in the command line `Cannot read property 'map' of undefined`; I can see the "firestore type" functions (eg firestoreArray) but not the generated view.

**Comment by jhuleatt** [comment]
Hey @slickorange, I'm wondering if the first log line is the issue here:

```
"severity":"WARNING","message":"Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail"
```

Please follow the [set up credentials](https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md#step-2-set-up-credentials) instructions before running the script, and see if that fixes it for you.

**Comment by slickorange** [comment]
@jhuleatt Thanks.. I did follow the instructions to set up the credentials and I did it again now just to make sure. Still having the same issue. Any other ideas? Any ideas on how I can start debugging this?

**Comment by slickorange** [comment]
I have copied the script and I am running it locally.. from what I can tell it seems like `field.fields` schema.js:267 is undefined.. resulting in the failure of the map call on line 125. Still trying to figure out why it is undefined.

**Comment by slickorange** [comment]
I was able to get it running by commenting out the places where it tries to process a "map" field. The script worked (but obviously any map fields were not exported)
Unfortunately I had to get a new computer and I lost my local copy - I am struggling to run the script locally like I did on my previous computer.

**Comment by slickorange** [comment]
I have managed to run the script by doing the following steps:
`npm install @firebaseextensions/fs-bq-schema-views --save`

I then edit the `schema.js` file found under node_modules/@firebaseextensions/fs-bq-schema-views,
commenting out the following lines: (264 - 270)

```
        // if (field.type === "map") {
        //     const subschema = {
        //         fields: updateFirestoreSchemaFields(field.fields),
        //     };
        //     processFirestoreSchemaHelper(datasetId, dataFieldName, prefix.concat(field.name), subschema, arrays, geopoints, extractors, transformer, bigQueryFields, extractPrefix.concat(field.extractor));
        //     return;
        // }
```
Obviously map fields will then not be exported.

I am also still having an issue where some of my string values are null (despite having a value in the raw table)
Not sure if it is related to the above.

**Comment by dackers86** [comment]
Hi @slickorange 

I have added this my task list. The above PR should stop the error you were experiencing, although I was unable to replicate the issue.

Are you still experiencing issues with the script details above?
