### ISSUE TITLE
auth-mailchimp-sync: Plugin fails to add user on linkWithCredential

### ISSUE THREAD

**Issue by klivin** [firebase/extensions#630]
[REQUIRED] Step 2: Describe your configuration

Extension name: _ auth-mailchimp-sync/
Extension version: _ 0.1.2
Configuration values (redact info where appropriate): n/a
[REQUIRED] Step 3: Describe the problem

Steps to reproduce:

When an anonymous user decides to link an email (ie. deferred login flow)

Expected result

I would expect this plugin to detect the new Firebase User email that changes from null to a valid email and add the new user to Mailchimp.

Actual result

No user is created in mailchimp.

**Comment by Ehesp** [comment]
I don't think the `onCreate` trigger for Firebase Auth Functions is called on a linked account, only when a *new* account is created. cc @jhuleatt

**Comment by dackers86** [comment]
Closing in favour of https://github.com/mailchimp/Firebase/issues/26
