### ISSUE TITLE
HOWTO(trigger-email): relaying email via google workspace

### ISSUE THREAD

**Issue by ottob** [firebase/extensions#632]
This was a bit tricky to get working so I thought that I could document it here to help others.

First set up an App password for your user at https://myaccount.google.com/security > Signing in to Google section. If it is not available you need to enable 2 factor authentication for your users in the Google Workspace Admin > Security section.

When I tried to send email I got the following error:

> Error: Server terminates connection. response=421 4.7.0 Try again later, closing connection. (EHLO) z2sm213160eju.142 - gsmtp: 421 4.7.0 Try again later, closing connection. (EHLO) z2sm213160eju.142 - gsmtp

I used the following connection string:
`smtps://myusername@mydomain.com:verylongpassword@smtp-relay.gmail.com:465`

To fix this error I hade to add the `name` parameter like so. Change myusername/password and mydomain.com to match your own:
`smtps://myusername@mydomain.com:verylongpassword@smtp-relay.gmail.com:465?name=mydomain.com`

Then I got another error, so I had to enable smtp relaying in the Google Workspace admin > Apps > G Suite > Settings for Gmail > Advanced settings. Scroll down to `SMTP relay service` add one with these settings:
```
Name: Used by firebase trigger email extension
Allowed senders: Only addresses in my domains
Only accept mail from the specified IP addresses: No
Require SMTP Authentication: Yes
Require TLS encryption: Yes
```

Then it started working 🚀

**Comment by stevenmanton** [comment]
This worked for me. Thanks! The only thing I did differently is store the password as a secret. The `name=mydomain.com` is the piece I really needed. This should really be added to the documentation!

**Comment by i14h** [comment]
Yep good point. @dackers86 @yamankatby

**Comment by MjeTjeu** [comment]
Maybe this helps:

[Laravel-incorrectly-handling-ehlo-for-smtp](https://laracasts.com/discuss/channels/laravel/laravel-incorrectly-handling-ehlo-for-smtp-from-artisancli-issues-with-gmails-smtp-relay-resolved)

**Comment by Tiropz** [comment]
Thank you @ottob, this worked for me as well. 
Followed the instruction to the letter.
