### ISSUE TITLE
Feature Request for: storage-resize-images plugin

### ISSUE THREAD

**Issue by inglesuniversal** [firebase/extensions#633]
I consider it would be crucial and extremely useful, if you add a feature to this very useful plugin, to allow developers like me, to easily include a way to update a FIREBASE FIRESTORE COLLECTION with the resulting path and token of the UPLOADED images and thumbnails which are generated by this plugin.

Thanks and I really hope to see this update in the next release of this plugin.

Best regards and you all  #STAYSAFE

**Comment by i14h** [comment]
thanks for the suggestion and feedback @inglesuniversal! 

@jsdt just in case you're looking for more signals for your extension

**Comment by i14h** [comment]
@inglesuniversal we've released an [storage-mirror-firestore](https://github.com/FirebaseExtended/experimental-extensions/tree/next/storage-mirror-firestore) as experimental for exactly this!

**Comment by inglesuniversal** [comment]
Glad this request passed the front desk ... LOL ... Glad to contribute with ideas

Are you guys having a Firebase virtual booth for the upcoming Google EVENT?
