### ISSUE TITLE
Add a install extension button in Extension

### ISSUE THREAD

**Issue by nonoumasy** [firebase/extensions#635]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: Translate Text, but applicable to all other extensions

### What feature would you like to see?

This is more UX, it's more intuitive and convenient to add some kind of addButton in the Extension page in order to add an extension. Everytime I want to add an extension, I have to go this page:

https://firebase.google.com/products/extensions?authuser=0

It's like entering the back of the car to get to driver seat.

### How would you use it?

Well, at the moment, I'm trying to add several extensions. and I have to go thru the back of the car multiple times.

![Screen Shot 2021-04-08 at 9 00 03 PM](https://user-images.githubusercontent.com/6312676/114126673-c2ce5b80-98ad-11eb-94e9-862ef272a5f6.png)

**Comment by i14h** [comment]
Hi @nonoumasy thanks for the feedback. Can you file a support ticket for this?

**Comment by jhuleatt** [comment]
Support link: https://firebase.google.com/support/troubleshooter/report/features

Since this repo is just focused on the code for extensions themselves, filing a feature request with support will make sure that this platform-level feedback will find its way to the right spot.
