### ISSUE TITLE
[auth-mailchimp-sync] Import existing users

### ISSUE THREAD

**Issue by eduferfer** [firebase/extensions#637]
This feature request is for extension: **auth-mailchimp-sync**

### What feature would you like to see?

After installing the extension, I would like to have an option to import all existing users on Firebase to my Mailchimp audience.

### How would you use it?

Either on the firebase console or as a cloud function to `syncAllExistingUsers()`

**Comment by i14h** [comment]
@desoukya fyi

**Comment by dackers86** [comment]
Closing in favour of https://github.com/mailchimp/Firebase/issues/25
