### ISSUE TITLE
Ensure that firestore-counter only writes to max 100 documents inside a single transaction

### ISSUE THREAD

**Issue by laurenzlong** [firebase/extensions#64]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name: firestore-counter

Currently, in the worst case, firestore-counter will act on 499 documents at once since that's the shard limit. (https://github.com/firebase/extensions/blob/master/firestore-counter/functions/src/worker.ts#L32). This is not recommended by the Firestore team. A transaction will have decreased performance if it writes/deletes more than 100 documents inside a transaction. 

The code needs to be modified to ensure no more than 100 documents are touched inside a single transaction. It might require changing the number of plans: https://github.com/firebase/extensions/blob/master/firestore-counter/functions/src/worker.ts#L186

**Comment by lepatryk** [comment]
The easiest way to achieve it is to lower the max number of shards to 100.

Here's a PR to do that: https://github.com/firebase/extensions/pull/149

**Comment by laurenzlong** [comment]
Thanks!
