### ISSUE TITLE
[Run Subscription Payments with Stripe]

### ISSUE THREAD

**Issue by chihiroyn** [firebase/extensions#642]
Now, we're using "Run Subscription Payments with Stripe" extension for connecting payment by Stripe to Firestore.
https://firebase.google.com/products/extensions/firestore-stripe-subscriptions

We're also using Stripe checkout API.
https://stripe.com/docs/api/checkout/sessions

First we created Stripe session,
then "checkout_sessions" Firestore document is generated.

Then we purchased some Stripe subscription,
then "subscriptions" Firestore document about that is generated.

Our problem is we cannot detect how to relate above "checkout_session" and "subscription".

Are there any solution to relate session and subscription?

**Comment by dackers86** [comment]
Hi @chihiroyn 

This extension is managed by Stripe. 

Can you please add any  issues here https://github.com/stripe/stripe-firebase-extensions and the Stripe team will be able to respond directly.
