### ISSUE TITLE
Trigger Email not working as expected

### ISSUE THREAD

**Issue by mrfsrf** [firebase/extensions#644]
It gives **Invalid login**
I have enabled _allow less secure_

from index.html [hosting]

```
  db.collection("jobs")
      .add({
        to: ["email@example.com"],
        message: {
          subject: `Job Application from ${fName.value} ${lName.value}`,
          html: `<p>Email: ${email.value}</p>`,
        },
        fname: fName.value,
        lname: lName.value,
        email: email.value,
        cv: cvFileName,
      })
      .then((docRef) => {
        console.log("Document written");
      })
      .catch((error) => {
        console.error("Error adding document: ", error);
      });
   ```

**Comment by dackers86** [comment]
Hi @mrfsrf 

Can you provide more details on the error you have received. I am assuming at this point this is not an extension issue but a problem with your provider? Any further error details may help to identity the issue

Also, please double check your credentials for your email provider, this is the most common issue for this type of error.

**Comment by mrfsrf** [comment]
managed to make it work by using 2FA along with app password. Had to disable less secure option first.
