### ISSUE TITLE
firestore-send-email SMTPS field accept only alphanumeric characters

### ISSUE THREAD

**Issue by app-condo** [firebase/extensions#648]
### Describe your configuration

- Extension name: firestore-send-email
- Extension version: 0.1.9
- Configuration values (redact info where appropriate):
  - smtps://xxxx@gmail.com:password@smtp.gmail.com:465

### Describe the problem

firestore-send-email SMTPS accept only alphanumeric characters [A-Za-z0-9]
escaping # character to html & # 3 5 ; don't work

#### Steps to reproduce:

insert a SMTPS password with special character

**Comment by dackers86** [comment]
Hi @app-condo 

I have tested this with some basic special characters, is there a particular character that is causing this issue?

The regular expression for this URI is `^smtps?://[^:]+:[^:]+@.*$` if that helps?

**Comment by antoniosap** [comment]
for example i use # inside password.

**Comment by dackers86** [comment]
Potentially related to https://github.com/firebase/extensions/issues/692

**Comment by dackers86** [comment]
Closing in favour of https://github.com/firebase/extensions/pull/816
