### ISSUE TITLE
Support a Retention policy

### ISSUE THREAD

**Issue by iislucas** [firebase/extensions#652]
### [REQUIRED] Step 2: Extension name

This feature request is for extension: **firestore-bigquery-export**

### What feature would you like to see?

It would be super handy to have the extension provide some data retention support. e.g. for a given table it would be great to be able to say that once a month I want to delete any records that were deleted more than 60 days ago. 

### How would you use it?

This would allow BigQuery to much more easily respect GDPR & related retention policies. (without custom coding)

**Comment by dackers86** [comment]
Thanks @iislucas. I've placed this under consideration

**Comment by i14h** [comment]
@karayu fyi this seems like a interesting feature

**Comment by jhuleatt** [comment]
We document how to clean up stale records in a [sample query](https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/guides/EXAMPLE_QUERIES.md#:~:text=Remove%20stale%20data%20from%20your%20changelog%20table), so I think our first step should be to modify that query to filter for only documents that have been deleted in Firestore. Once we have a query that can reliably get stale deleted records in Firestore, we can consider setting up a scheduled function that runs that query and deletes any returned records.

**Comment by iislucas** [comment]
If I understand it, that query will remove non-deleted live records also - that will be bad for applications that use it e.g. to store user data that hasn't been updated in a while. I'd rather like to remove old updated versions of data, and also any records that were deleted older than, say, 30 days.

**Comment by dackers86** [comment]
Document PR added here https://github.com/firebase/extensions/pull/708

**Comment by iislucas** [comment]
Thanks! That's helpful. I suggest making a variant of this: delete all entries that are older than 1 month and not the latest. This will much more directly map to the common use-case of retention mapping.
