### ISSUE TITLE
Is there a way stop renaming the image with  200x200 at the end? This would be a lot helpful

### ISSUE THREAD

**Issue by vishnusait** [firebase/extensions#653]
### I installed this plugin in my project for resizing the images
This works great except for the renaming of the original file name. I wish there is a checkbox to stop renaming the file if I want to delete the original and keep the resized one.
Please help! 
Thanks!

**Comment by dackers86** [comment]
Thanks @vishnusait. Updated for consideration

**Comment by kalmicka** [comment]
I second that idea! Alternatively it would be great to be able to set the name ourself. Using two different sizes someone could e.g. call 100x100 = small and 1024x1024 = large. Afterwards the developer could still edit the image sizes and still have a consistent result (name of the image).

**Comment by zaidkazi** [comment]
#658 I believe as part of this feature 658 should be considered at the same time.

If we remove the 200x200 from a file name by nature many applications will want to treat the original image and the new optimized image as the same. Having the deletion **immediately**  after does not promote good app behaviour in many cases as thats likely the time apps will need the image the most and there is a slight chance of the gap in between where the image being overwritten that an application may request it.

Would having a delay field of letting us choose when to delete  and resize images be beneficial?

**Comment by i14h** [comment]
@kalmicka @zaidkazi @vishnusait  can you explain what's the user need for this feature and what problem would it solve?

**Comment by zaidkazi** [comment]
@jhuleatt Hello i think thats a good alternative but it would still be easier to not have to worry about what the file name will be in general. If i upload a picture and my application wishes to consume it there is a chance my image will be

image.png
or 
image_200x200.png 

(Depending on if its been processed and deleted in time)

i would rather my application does not have to guess

**Comment by zaidkazi** [comment]
@i14h  sorry forgot to tag you aswell

**Comment by i14h** [comment]
@zaidkazi if we resize in place keeping the original image name it might mess up caching not only in GCS but on all the other potential proxies in between the client and the image. Can your application make a second request in case the original request for the image returns a 404?

**Comment by kalmicka** [comment]
> @kalmicka @zaidkazi @vishnusait can you explain what's the user need for this feature and what problem would it solve?

The problem I am having is that I am setting a size for the images to be converted to e.g. 640x640. As time passes it might be necessary to increase the sizes of the images to 1024x1024. This would require me to provide some logic for changing the resolution. Considering the fact that I could keep the name (e.g. large for 640x640 and afterwards for 1024x1024) no code change would be required. The user would just start seeing better a better quality in their picture. Hope that I made my point clear :)

**Comment by dackers86** [comment]
Because of the above issues, specifically caching and renaming an image as it is being processed a code-based change would not be possible.

We have recently added [events](https://cloud.google.com/eventarc/pricing), which allows developers to run custom functions when the resizing has been completed.

Updating your configuration to use the `firebase.extensions.storage-resize-images.v1.complete` event and renaming through a custom function should be considered the best solution for handling custom resize image names.
