### ISSUE TITLE
fs-bq-import-collection script dependency error after 0.1.11 upgrade

### ISSUE THREAD

**Issue by mothman11** [firebase/extensions#654]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** fs-bq-import-collection
- Extension version: **\_** 0.1.11
- Configuration values (redact info where appropriate):

npx @firebaseextensions/fs-bq-import-collection --non-interactive --project=[redacted] --source-collection-path=ratings --query-collection-group=false --dataset=firestore_export --table-name-prefix=ratings --batch-size=300 --dataset-location=australia-southeast1

#### Steps to reproduce:

I run the import script (fs-bq-import-collection) in non-interactive mode.  Since the last update to 0.1.11, the script errors out 
Cannot find module 'node-pre-gyp/lib/pre-binding'

I have updated node, google cloud sdk, firebase-admin in case that was the issue, but same error.

Running previous version npx @firebaseextensions/fs-bq-import-collection@0.1.10  works fine

##### Expected result
Script runs successfully and imports rows

##### Actual result

C:\Users\mohot\AppData\Local\Google\Cloud SDK>npx @firebaseextensions/fs-bq-import-collection --non-interactive --project=[redacted] --source-collection-path=ratings --query-collection-group=false --dataset=firestore_export --table-name-prefix=ratings --batch-size=300 --dataset-location=australia-southeast1
{"severity":"WARNING","message":"Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail"}
Importing data from Cloud Firestore Collection: ratings, to BigQuery Dataset: firestore_export, Table: ratings_raw_changelog
(node:22580) UnhandledPromiseRejectionWarning: Error: Cannot find module 'node-pre-gyp/lib/pre-binding'
Require stack:
- C:\Users\mohot\AppData\Local\npm-cache\_npx\d906c8461d95e111\node_modules\grpc\src\grpc_extension.js
- C:\Users\mohot\AppData\Local\npm-cache\_npx\d906c8461d95e111\node_modules\grpc\src\client_interceptors.js
- C:\Users\mohot\AppData\Local\npm-cache\_npx\d906c8461d95e111\node_modules\grpc\src\client.js
- C:\Users\mohot\AppData\Local\npm-cache\_npx\d906c8461d95e111\node_modules\grpc\index.js
- C:\Users\mohot\AppData\Local\npm-cache\_npx\d906c8461d95e111\node_modules\google-gax\build\src\grpc.js
- C:\Users\mohot\AppData\Local\npm-cache\_npx\d906c8461d95e111\node_modules\google-gax\build\src\index.js
- C:\Users\mohot\AppData\Local\npm-cache\_npx\d906c8461d95e111\node_modules\@google-cloud\firestore\build\src\v1\firestore_client.js
- C:\Users\mohot\AppData\Local\npm-cache\_npx\d906c8461d95e111\node_modules\@google-cloud\firestore\build\src\v1\index.js
- C:\Users\mohot\AppData\Local\npm-cache\_npx\d906c8461d95e111\node_modules\@google-cloud\firestore\build\src\index.js
- C:\Users\mohot\AppData\Local\npm-cache\_npx\d906c8461d95e111\node_modules\firebase-admin\lib\firebase-namespace.js
- C:\Users\mohot\AppData\Local\npm-cache\_npx\d906c8461d95e111\node_modules\firebase-admin\lib\default-namespace.js
- C:\Users\mohot\AppData\Local\npm-cache\_npx\d906c8461d95e111\node_modules\firebase-admin\lib\index.js
- C:\Users\mohot\AppData\Local\npm-cache\_npx\d906c8461d95e111\node_modules\@firebaseextensions\fs-bq-import-collection\lib\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\mohot\AppData\Local\npm-cache\_npx\d906c8461d95e111\node_modules\grpc\src\grpc_extension.js:26:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22580) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by cdaniele-ciandt** [comment]
I am facing the same problem.

**Comment by mothman11** [comment]
Thanks for that. For the benefit of others - I was able to run the previous version successully:

npm i @firebaseextensions/fs-bq-import-collection@0.1.10
or
npx @firebaseextensions/fs-bq-import-collection@0.1.10

**Comment by dackers86** [comment]
@mothman11 @cdaniele-ciandt 

This looks to be a problem with global npx modules.

Please use the following command `rm -rf $(npm config get cache)/_npx` before trying again.
