### ISSUE TITLE
[storage-resize-images] Add a delay option for deletion

### ISSUE THREAD

**Issue by zaidkazi** [firebase/extensions#658]
Hello love the extension just one small issue often times our app has undesired behaviour because we need to make use of the picture or image right after. This can cause an undesired error when calling makePublic() on the file right after its uploaded and then deleted. Having a timeout to do the deletions at a certain time of time or hour later would be much smoother.

**Comment by i14h** [comment]
Hi @zaidkazi. Thanks for the suggestion. This is an edge case where I think you can solve by not deleting via the extension but with a custom function after you've performed your intended actions on the image. Implementing this in the extension itself would make it too complicated.
