### ISSUE TITLE
Update extensions to Node 14

### ISSUE THREAD

**Issue by dackers86** [firebase/extensions#660]
- [x] storage-resize-images (https://github.com/firebase/extensions/pull/657)
- [x] delete-user-data (https://github.com/firebase/extensions/pull/661)
- [x] firestore-bigquery-export (https://github.com/firebase/extensions/pull/662)
- [x] firestore-counter (https://github.com/firebase/extensions/pull/664)
- [x] firestore-send-email (https://github.com/firebase/extensions/pull/665)
- [x] firestore-shortern-urls-bitly (https://github.com/firebase/extensions/pull/667)
- [x] firestore-translate-text (https://github.com/firebase/extensions/pull/668)
- [x] rtdb-limit-child-nodes (https://github.com/firebase/extensions/pull/669)

**Comment by jhuleatt** [comment]
Once this migration is done, it would also help to merge https://github.com/firebase/extensions/pull/663, which adds a new Cloud Functions region

**Comment by dackers86** [comment]
Completed
