### ISSUE TITLE
Realtime Database instance is required even you don't use it

### ISSUE THREAD

**Issue by davidgaroro** [firebase/extensions#676]
### Describe your configuration

- Extension name: **delete-user-data** 
- Extension version: **0.1.8**
- Configuration values (redact info where appropriate):
  - **Realtime Database instance:** my-instance

### Describe the problem
I'm trying to install the Firebase Delete User Data extension. I only use Firestore so I don't need Realtime Database but to configure the extension, an instance of the realtime database is required.

#### Steps to reproduce:

Install the Delete User Data extension and in the configuration don't put anything in Realtime Database instance.

##### Expected result
Don't show the error message: `Realtime Database instance is required.`

##### Actual result
The error message appears.

##### Screenshot
![image](https://user-images.githubusercontent.com/13784162/120074560-b55b7380-c09d-11eb-99e2-3404dcede91e.png)

##### Note
I don't have any database in Realtime Database and the extension works perfectly for me. I guess you can put anything as an instance as long as you don't use the Realtime Database. I set the rules to block all access just in case.

**Comment by i14h** [comment]
Thanks for reporting this issue @davidgaroro. Unfortunately we don't support conditional parameters in extension configuration yet, so we have to live with this for now until we build better support for these use cases. 

cc @karayu

**Comment by abierbaum** [comment]
Could the description for the realtime database instance parameter be updated to say that you can add anything here to continue?

**Comment by i14h** [comment]
@Salakar lets see if this can be made optional
