### ISSUE TITLE
Export more than one Firestore collection to BigQuery

### ISSUE THREAD

**Issue by SebScoFr** [firebase/extensions#678]
This feature request is for extension: firebase/firestore-bigquery-export

### What feature would you like to see?

Ability to export multiple Firestore collection rather than just one. Without having to install other instances of the extension.

### How would you use it?

I'd like to be able to export more than one Firestore collection

**Comment by i14h** [comment]
@SebScoFr thanks for the feature request. Can you explain why installing multiple extensions won't work in your case?

**Comment by SebScoFr** [comment]
@i14h Thanks for your reply, installing multiple instances does work. It's just that it would feel a lot more straightforward to be able to manage that within just one instance. I have 5 collections that I need to export to BQ so it's not that bad, but I would imagine that for someone with like 100 collections if would get a bit painful.

**Comment by dackers86** [comment]
Hi @SebScoFr 

It is typical for Firebase extensions to be installed across multiple instances, this is because of the way extensions are installed and connected to various Firebase resources.

Could you please share more details on what issues you are experiencing?

**Comment by SebScoFr** [comment]
Hi @dackers86

Ok in which case it's all good. If not facing any particular issue and it does work as expected for me. Like I said my initial thought was that if could be a lot easier to manage multiple export under just one extension instance, but I do understands there are good reasons for not doing that.
You may close this ticket, and thanks for the explanation.

**Comment by dackers86** [comment]
Thanks @SebScoFr!
