### ISSUE TITLE
storage-resize-images: HEIC support

### ISSUE THREAD

**Issue by lud-hu** [firebase/extensions#684]
### [READ] Step 1: Are you in the right place?

yes

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **storage-resize-images**

### What feature would you like to see?

I'd love to see support for resizing and converting **heic** images, as they are the standard format of Apple iOS devices.

### How would you use it?

Upload some heic photos to firebase storage and have them resized and converted by the extension (just as it is like for jpg, png, etc)

**Comment by i14h** [comment]
Thanks for the feature request @lud-hu. According to [Sharp documentation](https://sharp.pixelplumbing.com/api-output#heif) "Support for patent-encumbered HEIC images requires the use of a globally-installed libvips compiled with support for libheif, libde265 and x265" which unfortunately isn't possible on Google Cloud Functions.

**Comment by mhadji05** [comment]
Is there a way to upload .heic image from iphone to firebase storage using Unity, or at least convert it through Unity and then upload it in firebase?
