### ISSUE TITLE
[Delete-User-Data] Support for multiple Realtime database instances

### ISSUE THREAD

**Issue by zigapovhe** [firebase/extensions#685]
### [REQUIRED] Step 2: Extension name

This feature request is for extension: **\_** (`delete-user-data`)

### What feature would you like to see?

It would be awesome if you could enter more than one realtime database instance
### How would you use it?

That would allow me to delete all of our user data - from all realtime database instances.

**Comment by dackers86** [comment]
Hi @zigapovhe.

Our recommendations for this type of scenario are to `install multiple instances` of the extension. 

Each instance can then contain the specific configuration needed, so in this case a second installation can include your secondary database instance.

**Comment by zigapovhe** [comment]
@dackers86 Oh, I didn't know that. Thanks! But is it planned to support multiple instances of realtime db in the future?
