### ISSUE TITLE
Export Collections to BigQuery : Some document ids are missing from the raw_changelog

### ISSUE THREAD

**Issue by kishore-mega** [firebase/extensions#688]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: firestore-bigquery-export
- Extension version: 0.1.13

### [REQUIRED] Step 3: Describe the problem

Some document ids are missing from the raw_changelog. There are no logs present related to the missing data either.
Note : A very small number of documents are missing (about 1 in 100,000).

**Comment by dackers86** [comment]
Hi @kishore-mega.

Can you confirm whether these missing documents have been added before installing the extension? We have an import script which would need to be ran for pre-existing data? https://github.com/firebase/extensions/tree/next/firestore-bigquery-export/scripts/import

**Comment by kishore-mega** [comment]
Hi @dackers86 ,

The pre-existing data is not of concern in our case. Documents created both before and after the missing documents are created in firestore are available in raw_changelog. These missing documents have been created in firestore after installing the extension.

**Comment by dackers86** [comment]
Thanks for that information.

For the next steps, can you confirm if you are receiving any error logs for the extension. These can be found here...

![image](https://user-images.githubusercontent.com/2060661/123764937-2ec4cc80-d8bd-11eb-918d-3bb982925db9.png)

https://console.firebase.google.com/project/{PROJECT_NAME}/extensions/instances/firestore-bigquery-export?tab=config

or 

https://console.firebase.google.com/project/{PROJECT_NAME}/functions/logs?functionFilter=ext-firestore-bigquery-export-fsexportbigquery({LOCATION(US-CENTRAL-1)})&search=&severity=ERROR

**Comment by kishore-mega** [comment]
Found these in the logs but they are not consistent with the timestamp of the missing documents' creation.

`{
  "textPayload": "Error: function terminated. Recommended action: inspect logs for termination reason. Additional troubleshooting documentation can be found at https://cloud.google.com/functions/docs/troubleshooting#logging Function invocation was interrupted."
}`

**Comment by KennyCCK** [comment]
Experienced a similar issue about missing data about 1 in 1,000,000 

No significant errors were observed during the time frame in Cloud Functions logs but just a number of transient errors
`"textPayload: "The request was aborted because there was no available instance."`
(I assume these are retried)

**Comment by i14h** [comment]
We could do a couple of things, since anything might break between the function and bigquery
1. Add more retries (currently 3) 
2. Add more time between retries 
3. Write failed entries to a separate collection in Firestore

**Comment by dackers86** [comment]
Closed via https://github.com/firebase/extensions/pull/891
