### ISSUE TITLE
Mail subject encoding in firestore-send-email

### ISSUE THREAD

**Issue by rphlmr** [firebase/extensions#69]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: `firestore-send-email`
- Configuration values (redact info where appropriate):
  - A working configuration

#### Steps to reproduce:

If the mail subject contains specials characters, they are printed in html code.

##### Expected result

Exemple : 
A field `name: "Jack o'neill"` used in mail subject : `"Welcome to {{name}}"`should be printed `Welcome Jack o'neill` in mail subject.

##### Actual result

`Welcome Jack o&#x27;neill`

Maybe I miss something ?

PS : It works well in email's body

**Comment by rphlmr** [comment]
Ok I found that we have to add one more curly braces pair to escape specials char :D 

Mail subject should be : `"Welcome to {{{name}}}"`

If you confirm, may be we can update the documentation :)

**Comment by Ehesp** [comment]
@rphlmr Thanks for the feedback. Looks like you're right yeah, the triple-stash should work in this case.

I'll get a PR sent up soon with the changes (unless you wanted to take a go?).

**Comment by Ehesp** [comment]
Actually, I was thinking we could set this in the template compiler, however re-reading what you said I think this is a documentation update.

Maybe in the docs we could add a line below the [example](https://github.com/firebase/extensions/blob/next/firestore-send-email/POSTINSTALL.md#using-templates):

```
By default, the extension HTML-escapes values returned by a `{{expression}}`. If you don't want to escape a value, use the "triple-stash", `{{{`.
```

Taken from: https://handlebarsjs.com/#html-escaping

cc @rachelsaunders

**Comment by rphlmr** [comment]
Yes, I think it should be only on the documentation.
It's easier to put it in the template compiler (and transparent for fast doc readers), but if someone wants to escape, it'll no more be configurable.

Last question, do you know why it works without triple-stash in the template body ? (actually it seems that we have 2 diffents behaviours :p )

**Comment by rachelsaunders** [comment]
1) It'd be great to learn the answer to the question from @rphlmr above.

2) A clarification question - this HTML-escaping syntax is only applicable for templates, right?

3) If (2) is true... Since the HTML-escaping syntax is already documented in the handlebar template documentation, I'd prefer to not repeat it in our docs.  It seems pretty easy to find in their docs with a quick ctrl-f of their page.  If we document this syntax in our docs, then we'd be going down the road of documenting all their syntax.

**Comment by Ehesp** [comment]
> 1. It'd be great to learn the answer to the question from @rphlmr above.

So the reason the subject & body have different functionality is how the email client is handling the data. Your body content will be getting escaped by handlebars, but your email client will be then parsing the HTML entities back into valid HTML (as HTML is allowed in the body).

In the subject, only a string is allowed, so it displays the escaped output handlebars generated.

> 2. A clarification question - this HTML-escaping syntax is only applicable for templates, right?

Yep, it's applied to the subject, html/text/amp properties sent on each email.

> 3. If (2) is true... Since the HTML-escaping syntax is already documented in the handlebar template documentation, I'd prefer to not repeat it in our docs. It seems pretty easy to find in their docs with a quick ctrl-f of their page. If we document this syntax in our docs, then we'd be going down the road of documenting all their syntax.

Makes sense, I'll go ahead and close this issue along with the PR.
