### ISSUE TITLE
URL Encode SMTP user & passowrd

### ISSUE THREAD

**Issue by alfredsgenkins** [firebase/extensions#692]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-send-email**
- Extension version: **0.1.10**

#### Steps to reproduce:

Consider the following SMTPS URI: `smtps://XXX:XXX/X+XXX@email-smtp.eu-west-1.amazonaws.com:465`. 

If passed into `nodemailer` / `firestore-send-email` configuration will result in following error when attempting to send email: `getaddrinfo ENOTFOUND XXX`.

To resolve an issue the password and username have to be URL encoded, which is not mentioned anywhere in the configuration description.

##### Expected result

There is a not-to URL encode the password and username.

##### Actual result

There is no such note, which results in confusing error message.

**Comment by dackers86** [comment]
Thanks @alfredsgenkins.

I have updated this for consideration.

**Comment by jhuleatt** [comment]
We should be able to update the extension itself to use [`encodeURI`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) so that someone installing the extension doesn't need to figure out encoding

**Comment by alfredsgenkins** [comment]
I think the problem is that there are no password/username fields. It is required to parse the URL with regex, then encode the result, then use it as a new URI. The biggest problem here would be the case of a password or username containing the `:`. This could lead to the wrong detection of username and password.

Maybe instead, we should switch to declarative transport declaration schema. The port, host, protocol, credentials should be separate fields. In this case, no URL encoding is needed.

Alternatively, the simple notice could be shown in the configuration.

**Comment by dackers86** [comment]
@alfredsgenkins @jhuleatt  After some initial testing, I feel this may be difficult to implement.

**Decoding the uri**
We have specific regex for the smtp uri. With a decoded url, this would make it difficult to provide an alternative `encoded` regex pattern.

**Splitting the uri**
This would solve the issue but add extra complexity with more parameters and a longer installation process.

As we cannot simply insert an encoded uri, it would perhaps be easier for the user to simply encode the urls manually?

**Comment by i14h** [comment]
this is being discussed internally on what's the best way to move forward. Stay tuned!

**Comment by i14h** [comment]
@dackers86 since according to this [link](http://tools.ietf.org/html/rfc2617#section-2)  usernames shouldn't have colons in them, I think we can solve this in the extension. Just assume the first `:` and the last `@` as the separator and encode them before sending them to sendmail

**Comment by higgins** [comment]
FWIW, the firebase authentication mechanism accepts smtp configuration as a form of hostname, username, password, port and it encodes username password correctly
