### ISSUE TITLE
Expand 'Send Email' extension to create and send Notifications through FCM

### ISSUE THREAD

**Issue by mrobraven** [firebase/extensions#694]
### Extension name

This feature request is for extension: `firestore-send-email`

### What feature would you like to see?

It would be great if either this plugin could be expanded or a new one created that looks for changes in both Cloud Firestore and the Realtime Database (like this one does) and sends a FCM notification to a users device based on the change seen in the Database. For example, in a messaging app, it would listen for changes in the Realtime Database's "messages" document and for any new messages created it would send a FCM notification to the device where that user's Uid is logged on. I have seen that many people are creating these functions themselves and hosting them on Firebase so I thought this may be quite a sought after feature.
 
### How would you use it?

I would use it to:
- Send user's notifications based on changes to Cloud Firestore that involve their Uid (for example: new posts, comments left on their existing posts etc...)
- Send user's notifications based on changes to the Realtime Database (for example: new messages from conversations that they are members of)
- Send user's notifications based on their

**Comment by dackers86** [comment]
Thanks for this suggestions @mrobraven.

I've added it for consideration

**Comment by pr-Mais** [comment]
This's a good idea for a new extension, but probably beyond the scope of firestore-send-email.
