### ISSUE TITLE
[firestore-bigquery-export] Cannot import data from subcollections

### ISSUE THREAD

**Issue by dora1998** [firebase/extensions#695]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-bigquery-export** (`storage-resize-images`, `firestore-send-email`, etc)
- Extension version: **0.1.11 (@firebaseextensions/fs-bq-import-collection)**
- Configuration values (redact info where appropriate):

#### Steps to reproduce:

1. Run `npx @firebaseextensions/fs-bq-import-collection`
2. Give a subcollection path like `colA/docA/subcolA`

##### Expected result

Can import data in the dedicated subcollection

##### Actual result

The script emits the error `The collection path must only contain letters or spaces`

This bug is happened by the regex [here](https://github.com/firebase/extensions/blob/61eb0d3a2b954caaca25fe02d559e7a8612281f3/firestore-bigquery-export/scripts/import/src/index.ts#L39), so the script works when I fixed it like `/^.+$/`.

**Comment by dora1998** [comment]
Sorry, it may be fixed by #561

**Comment by dackers86** [comment]
Thanks @dora1998.

This issue will automatically close when the PR is successfully merged.
