### ISSUE TITLE
Any plans on making animated .webp images be resized to .webp animated images?

### ISSUE THREAD

**Issue by lukamo1996** [firebase/extensions#696]
### [REQUIRED] Firebase Resize Image Extension

This feature request is for extension: **\_** (`storage-resize-images`,

### What feature would you like to see?

Uploading an animated .webp-image causes the resized .webp-image to lose its animation.
I want to be able to upload a .webp image and receive the resized and animated .webp-image back. 
Currently, this isn't a supported feature it seems, at least not according to my experiments.

### How would you use it?

I would use it

**Comment by dackers86** [comment]
Hi @lukamo1996 

This extension recently started using the `sharp` image library (https://sharp.pixelplumbing.com/), which unfortunately does not yet support animated conversions.

This thread shows a similar discussion https://github.com/firebase/extensions/issues/590.

Based on this limitation, i'm afraid  animated resizes are unlikely to be supported in the near future

**Comment by kubanac95** [comment]
Interestingly enough the team chose sharp over [squoosh](https://github.com/GoogleChromeLabs/squoosh/tree/dev/libsquoosh) to do the resizing. My guess is that squoosh underperforms compared to sharp?
