### ISSUE TITLE
[firestore-send-email] Retry previously failed documents in mail collection

### ISSUE THREAD

**Issue by brandonrisell** [firebase/extensions#705]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **firestore-send-email**

### What feature would you like to see?

I'd like to be able to trigger retries of mail messages that failed previously.

### How would you use it?

We've had mail messages that hit a service quota, or that were used when the service was configured incorrectly, and it caused the messages to fail their send. After fixing the issue, I'd love to go back and retry any messages in an `ERROR` status.

**Comment by dackers86** [comment]
Thanks @brandonrisell.

I have added this to our tracker for consideration.

**Comment by brandonrisell** [comment]
@dackers86 Thank you!

**Comment by i14h** [comment]
We now write the `delivery.state` value and that can be used to find failed send mails https://github.com/firebase/extensions/blob/3b1cf99df38c1ab9f33266ec795ac0b0c2344ecf/firestore-send-email/functions/src/index.ts#L282
