### ISSUE TITLE
[firestore-bigquery-export] Support join between collection and subcollection efficiently without deconstructing documment name

### ISSUE THREAD

**Issue by anthoneyrimmer** [firebase/extensions#707]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: [firestore-bigquery-export]

### What feature would you like to see?

In the situation where firestore contains a collection 'parent' and a sub-collection 'child' we would like to be able to join from the child to the parent with an efficient and indexed join using the Document ID of the parent stored on the child. i.e a field called 'parent document id' or similar on the child's table. I have searched for similar methods without success, and deconstructing the document name is not computationally efficient or desirable. 

This feature should also support joining in the reverse direction so that finding all children is properly indexed, particularly taking into account the possible grand parent situations that arise where the parent is also a sub collection. 

### How would you use it?
To join to parent information when querying on child records. For example looking up the name of the parent object to include in views and similar bigquery output.

**Comment by dackers86** [comment]
Thanks @anthoneyrimmer.

I have added this to our project board for consideration.

**Comment by jasonberryman** [comment]
@i14h I've modified the view with the following, to get the IDs from the parent collections. There may be a better way.  I hope that this helps/

{table}_raw_changelog
```
document_name: projects/{projectId}/databases/(default)/documents/foo/YsoYx4dbK1ElmNcpUQIe/bar/XdJtbYknjJjj88NjUmG8/baz/S4NxmnBuPP8BvDree44y
```

View:
```
FIRST_VALUE(REGEXP_EXTRACT(document_name, r'/foo\/([A-Za-z0-9]*)\/'))
OVER( PARTITION BY document_name ORDER BY timestamp DESC) AS FooID,

FIRST_VALUE(REGEXP_EXTRACT(document_name, r'/bar\/([A-Za-z0-9]*)\/'))
OVER( PARTITION BY document_name ORDER BY timestamp DESC) AS BarID,
```

Returns:
```
FooID: YsoYx4dbK1ElmNcpUQIe
BarID: XdJtbYknjJjj88NjUmG8
```

**Comment by JarnoRFB** [comment]
Sounds related to #853

**Comment by dackers86** [comment]
Closed via https://github.com/firebase/extensions/pull/891
