### ISSUE TITLE
[firestore-bigquery-export] TypeError: Cannot read property 'seconds' of undefined

### ISSUE THREAD

**Issue by peter-kavall** [firebase/extensions#711]
- Extension name: firestore-bigquery-export`
- Extension version: 0.1.16

I have setup this extension to sync a collection in Firestore to Bigquery. It works really well for the most time, but sometimes all data doesn't get synced, and I see this error in Logs:

```
TypeError: Cannot read property 'seconds' of undefined
    at Function.fromProto (/workspace/node_modules/@google-cloud/firestore/build/src/timestamp.js:135:47)
    at Firestore.snapshot_ (/workspace/node_modules/@google-cloud/firestore/build/src/index.js:575:57)
    at beforeSnapshotConstructor (/workspace/node_modules/firebase-functions/lib/providers/firestore.js:139:30)
    at changeConstructor (/workspace/node_modules/firebase-functions/lib/providers/firestore.js:143:49)
    at cloudFunction (/workspace/node_modules/firebase-functions/lib/cloud-functions.js:133:34) 
```

When that has happened, if I go into the record in Firestore and update any property, that triggers a successful sync of the document over to BigQuery, so the issue is intermittent and I'm not sure how to reproduce.

A typical document in Firestore can contain the following data, broken into individual properties for each JSON field:

`{
    "orderDisplayNumber": 2575,
    "status": "Delivered",
    "statusHistory":
    {
        "orderCreated": "2021-07-28T17:58:48.000Z",
        "orderDelivered": "2021-07-28T18:06:56.000Z"
    },
    "statusMessage": "Your order has been delivered!",
    "userId": "abc123"
}`

The error message complains about "seconds", but worth noting could be that orderCreated and orderDelivered are both string fields in Firestore.

**Comment by lrodrigues-cit** [comment]
I started having this same problem today (2021-07-29) at 19:52
Extension name: firestore-bigquery-export
Extension version: 0.1.13

**Comment by nmf2** [comment]
Same problem here.

Extension name: firestore-bigquery-export
Extension version: 0.1.13

**Comment by dackers86** [comment]
Thanks @peter-kavall @nmf2 

I've added this to our project board.

**Comment by afpatmin** [comment]
Just wanted to report I'm seeing this on version 0.1.9 also

**Comment by lfnovo** [comment]
Some info that might help understand the problem.

It happened to me as well during a period where we were doing a massive update on thousands of documents at the same time. Perhaps this has something to do with a bottleneck somewhere?

**Comment by i14h** [comment]
It seems this was due to the GCF issue mentioned here https://github.com/firebase/firebase-functions/issues/922 and is now resolved
