### ISSUE TITLE
Error : `Error: Greeting never received` 

### ISSUE THREAD

**Issue by Aristidios** [firebase/extensions#714]
I've setup Firebase - **Trigger Email Extension** with SendGrid - everything worked smoothly but then came the time to try to Trigger my first email to be sent 

- I manually created a new document from Firebase like so to trigger the email :

[![Firestore document][1]][1]

Like suggested by Trigger Email Firebase extension 

[![Instructions][2]][2]

But for some reason I get this Error : `Error: Greeting never received` 

*this is the SMPT I used (with my own password)*

`smtp://apikey:SG.IH8vUS.................QzZ1N0@smtp.sendgrid.net:465`

I followed step by step this medium article : https://medium.com/firebase-developers/firebase-extension-trigger-email-5802800bb9ea

[![Error FireStore Mail Delivery][3]][3]

  [1]: https://i.stack.imgur.com/DqhSl.png
  [2]: https://i.stack.imgur.com/TrWya.png
  [3]: https://i.stack.imgur.com/TzvY2.png

**Comment by dackers86** [comment]
Hi @Aristidios.

Your `smtp` server is using an insecure protocol which uses port `587`

I'd recommend updating the protocol to `smtps` and then you will be able to use port `465`.


We have a full guide for emails here https://github.com/firebase/extensions/blob/next/firestore-send-email/README.md

**Comment by Aristidios** [comment]
This worked like magic thank you very much
