### ISSUE TITLE
[firestore-send-email] Template attachments feature breaks message attachments

### ISSUE THREAD

**Issue by mfcoxo** [firebase/extensions#716]
- Extension name: firestore-send-email
- Extension version: 0.1.9+

#### Steps to reproduce:

Seems like updating this extension to the version greater than 0.1.9 has broken message attachments when using templates.
We send emails with templates but each message could have 0 or more attachments.
Our email object is something like:

```
{
  template: {
    data: { ... },
    name
  },
  message: {
    attachments: [...]
  }
}
```

With the PR #519 the change https://github.com/firebase/extensions/blob/255a6d812b49bc6956fc978c6ad7731f2eb7fb52/firestore-send-email/functions/lib/templates.js#L102 is probably squashing our attachments by forcing a null value https://github.com/firebase/extensions/blob/cde67fc0f903422e253d3275f966a6bd0863d456/firestore-send-email/functions/src/index.ts#L106

We are manually downgrading to 0.1.8 as its the last version where this worked correctly.

##### Expected result

It seems like the message being more specific should override template values and not the other way around?
We should get the attachments passed in the message field.

##### Actual result
Attachments don't get sent

**Comment by dackers86** [comment]
Thanks @mfcoxo 

I've added this to our tracker.

**Comment by pedrocarloto** [comment]
Thank you for such a quick fix!

Do you have any prediction when this may be deployed in production?

**Comment by mfcoxo** [comment]
Tested and it works as expected. Thank you!
