### ISSUE TITLE
Resize Image: Extension from contentType

### ISSUE THREAD

**Issue by GeeDollaHolla** [firebase/extensions#72]
### Extension name: Resize-Images

This feature request is for extension: `storage-resize-images`

### What feature would you like to see?

Currently, the file extension is being read from the original file name. If no file extension is provided, the type should be read from the image contentType to generate the new image.

Appending the extension to the resulting resized images should be conditional based on if the original name included the extension.

It is possible that this feature will solve [issue 20](https://github.com/firebase/extensions/issues/20). I experienced the same issue when I first uploaded files w/o extensions.

### How would you use it?

Store images keyed off of a field in a db w/o having the manage the image file type.

**Comment by Ehesp** [comment]
XFN Team: This could either be implemented, or leave as-is with improved documentation explaining images to be resized must include an extension (e.g. `.png) in the filename.

**Comment by laurenzlong** [comment]
Hey @GeeDollaHolla v0.1.3 should already fix the issue of reading the contentType from the original image (https://github.com/firebase/extensions/issues/20). We will work on fixing issue #20 which is a slightly different issue.Thanks for reporting!
