### ISSUE TITLE
[firestore-bigquery-export] Cannot install extension: npm error

### ISSUE THREAD

**Issue by ibobo** [firebase/extensions#727]
- Extension name: `firestore-bigquery-export`
- Extension version: 0.1.17
- Configuration values:
  - Collection path: `edition/{editionId}/event`
  - Dataset ID: `appdata`
  - Table ID: `events`
  - Partitioning: none
  - LOCATION: `europe-west3`
  - DATASET_LOCATION: `eu`

#### Steps to reproduce:

Install the extension either from the CLI or from the Web UI. I tried with two different configurations and both fail.

##### Expected result

The extension installs and starts sending data to BigQuery.

##### Actual result

This error occur:

```
Build failed: npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! 
npm ERR! Missing: @firebaseextensions/firestore-bigquery-change-tracker@^1.1.10
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /www-data-home/.npm/_logs/2021-08-20T10_29_43_100Z-debug.log; Error ID: beaf8772
```

Sometime the installation fails, sometimes succeeds, but the associated cloud function reports the same error in the logs and doesn't start at all.

**Comment by ibobo** [comment]
On a side note the previous version, 0.1.16, works flawlessly.

I could downgrade my existing installation to fix the issue, with this command:

```
firebase ext:update [Instance ID] firestore-bigquery-export@0.1.16
```

you can see the extension Instance ID from the `firebase ext` command. The command will still work even if you're downgrading and not upgrading, it only asks twice for confirmation.

**Comment by i14h** [comment]
@ibobo thanks for reporting this. Yes we rolled back to the previous version and are investigating what caused this version to break.

**Comment by dackers86** [comment]
Fixed via https://github.com/firebase/extensions/pull/740 and a related comment added regarding an update to the extension.
