### ISSUE TITLE
Firebase extension for STT

### ISSUE THREAD

**Issue by pietrop** [firebase/extensions#74]
### What feature would you like to see?

Similar to how there is an extension for Google Translate, I was wondering
 if there are any plans to make an extension for **Google Cloud Speech To Text**?

I'd be happy to contribute to the open source development, if this gets picked up and there are some general directions on how to go about developing a firebase extensions etc..

I've already raised it through [Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly, and they mentioned to raise it here as well.

### How would you use it?

I'd use it to make Apps that have a transcription service component with Firebase, eg [bbc/digital-paper-edit](https://github.com/bbc/digital-paper-edit), [autoedit2](http://autoedit.io).

**Comment by Ehesp** [comment]
Thanks @pietrop 

cc @karayu do we have an internal tracker for feature requests for discussion/implementation?

**Comment by Ehesp** [comment]
Hi @pietrop could you please add the feature request here: https://github.com/firebase/extensions/issues/74 - linking this issue as reference. Thanks!

**Comment by pietrop** [comment]
Thanks @Ehesp , I've just submitted it

**Comment by pietrop** [comment]
👋 I am looking more closely into a possible implementations for this, so thought I'd share some notes for doing [Cloud Function + STT - long running audio files](https://textav.gitbook.io/firebase-react-notes/stt/cloud-function-+-stt-long-running-audio-files)

and some options I've considered

**STT + Cloud function**
Cloud function times out 1min to 9min. So would not be able to get results for a long running audio file.

But would work ok, for shorter files. Hard to estimate what's the max audio length it would support?

**Cloud function - to start STT**
based on the docs, the cloud function could be used to start the STT, and store the name of the operation. This could be saved in firestore, and another function could be used to do some pooling, at a later stage to get the results when ready. Results are stored for 5 days.

**Cloud Function + App Engine**
The Firebase cloud function could trigger an app engine instance, that could run the recognition. I think this would probably not time out like the cloud function, and could save the results to firestore when done.

**Comment by Ehesp** [comment]
> But would work ok, for shorter files. Hard to estimate what's the max audio length it would support?

I'm not very knowledgeable on video files, however I also imagine there would be more to it than the length; quality etc may play a part.

Interesting discussion though to help consider scope.

**Comment by pietrop** [comment]
I think for getting STT of a video, you'd have to first convert it to audio, to meet [the audio specs expected by GCP STT](https://cloud.google.com/speech-to-text/docs/encoding) (eg see [`firebase/functions-samples/ffmpeg-convert-audio`](https://github.com/firebase/functions-samples/tree/master/ffmpeg-convert-audio)) and then send it to GCP STT.


In any case at the moment I am trying the second option (2. **Cloud function - to start STT**) with google cloud tasks.

**Comment by jhuleatt** [comment]
Since we've recorded this request in the internal tracker, I'm closing out this issue.

**Comment by pietrop** [comment]
👋 Since I don't have access to your internal tracker, I am going to flag here that I have done an implementation of GCP STT with Firebase using cloud functions and Google cloud task. At [pietrop/digital-paper-edit-firebase](https://github.com/pietrop/digital-paper-edit-firebase). Happy to provide more details if it is of interest.
