### ISSUE TITLE
Timestamp is 01-01-1970 when exporting Firesbase to BQ

### ISSUE THREAD

**Issue by pfiadDi** [firebase/extensions#741]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: fs-bq-import-collection
- Extension version: firestore-bigquery-export v0.1.18
- Configuration values (redact info where appropriate):
  - $ npx @firebaseextensions/fs-bq-import-collection 
  - ? What is your Firebase project ID? redacted
  - ? What is the path of the the Cloud Firestore Collection you would like to import from? (This may, or may not, be the same Collection for which you plan to mirror changes.) articles
  - ? Would you like to import documents via a Collection Group query? No
  - ? What is the ID of the BigQuery dataset that you would like to use? (A dataset will be created if it doesn't already exist) synced_data
  - ? What is the identifying prefix of the BigQuery table that you would like to import to? (A table will be created if one doesn't already exist) articles
  - ? How many documents should the import stream into BigQuery at once? 300
  - ? Where would you like the BigQuery dataset to be located? eu
  - ? Would you like to run the import across multiple threads? No
  

#### Steps to reproduce:

Start the script and import

##### Expected result

The column timestamp in the table  `${PROJECT_ID}.${COLLECTION_PATH}.${COLLECTION_PATH}_raw_changelog` should have a timestamp with the current time, when it was created.

##### Actual result

1970-01-01 00:00:00 UTC
--

<br class="Apple-interchange-newline">

**Comment by tripp-adam** [comment]
Will this be launched soon? We are hoping to import our firestore data into bigquery but noticed the timestamps were wrong. We can change the timestamps manually after import if this fix won't be launched for a while. Or maybe we could run the script with the patch from PR#835 above.

**Comment by i14h** [comment]
@tripp-adam yes we're in the process of testing the latest changes before publishing the final version
