### ISSUE TITLE
Limit Child Nodes at dynamic named paths

### ISSUE THREAD

**Issue by kiraitami** [firebase/extensions#742]
### Limit Child Nodes

This feature request is for extension: `rtdb-limit-child-nodes`

### What feature would you like to see?

Set Limit Child Nodes to dynamic named child paths

### How would you use it?

For example, limit the `tastes` node inside `userId` node what is dynamically given by `.push()`
- **users**
- - `userId`
- - - **tastes**
- - - - `tasteId`

**Comment by wunderlejohn** [comment]
could we get an example of what using dynamic paths would look like here when setting up this extension?
