### ISSUE TITLE
[storage-resize-images] Ability to specify file type for thumbnails

### ISSUE THREAD

**Issue by Soviut** [firebase/extensions#745]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Extension name

This feature request is for extension: `storage-resize-images`

### What feature would you like to see?

I would like to be able to override the file type of the thumbnails.

### How would you use it?

Someone may upload a JPEG or GIF that I want to keep in its original format so it can be downloaded in the future, but I want to normalize all the thumbnails to to PNG.

**Comment by dackers86** [comment]
Hi @Soviut.

In later versions of the extension, while installing you will be provided with a number of options for file types. 

For your scenario, you can select `original` and `png`. 

Additionally, if you would like to keep the original file that has been uploaded, please select `No` when asked `Delete on successful resize`.

Please let me know if that has answered your question

**Comment by Soviut** [comment]
@dackers86 Thanks. I feel like the help text in the web ui could be clarified.

> Convert image to preferred types:
> The image types you’d like your source image to convert to. The default for this option will be to keep the original file type.

The problem I had was that it kept mentioning the "original file" and "original file types". It might be worth rewording that to just say "destination file types".

**Comment by dackers86** [comment]
Thanks @Soviut 

You're correct, this documentation could do with an update. 

I'll update to under consideration.

**Comment by TangrisJones** [comment]
Hey @dackers86 , is there a way to specify output type for given input file types? 

My use case is that I want to convert everything to a `png`, except for `gifs` which should essentially stay in a `gif` format.

**Comment by dackers86** [comment]
Hi @TangrisJones

I agree this is most likely a new of issue/bug, could you create a separate bug/issue?

This would be much easier track and investigate. Thanks!
