### ISSUE TITLE
[firestore-translate-text] Array elements in an input map are translated as null

### ISSUE THREAD

**Issue by CiriousJoker** [firebase/extensions#751]
- Extension name: **firestore-translate-text**
- Extension version: **0.1.6**
- Configuration values (redact info where appropriate):
  - **target_languages:** en,es,de,fr
  - **collection_path:** some_collection
  - **input_field:** input
  - **output:** translated

#### Steps to reproduce:

Create a document in `some_collection` and add the following property `input`:

```json
"input": {
  "first": [
    "Tree",
    "House"
  ],
  "second": "Hello"
}
```

##### Expected result

```json
"input": {
  "first": [
    "Tree",
    "House"
  ],
  "second": "Hello"
},
"translated": {
  "first": [
    {
      "en": "Tree",
      "de": "Baum",
    },
    {
      "en": "House",
      "de": "Haus",
    },
  ],
  "second": {
      "en": "Hello",
      "de": "Hallo",
  }
}
```

##### Actual result

```json
"input": {
  "first": [
    "Tree",
    "House"
  ],
  "second": "Hello"
},
"translated": {
  "first": {
    "en": null,
    "de": null,
  },
  "second": {
      "en": "Hello",
      "de": "Hallo",
  }
}
```

**Comment by dackers86** [comment]
Thanks @CiriousJoker. I've added this for investigation.

**Comment by CiriousJoker** [comment]
Nesting maps in this way doesn't work either (same result).

Thanks for considering it.

**Comment by Ehesp** [comment]
Hi @CiriousJoker, the extension doesn't support iteration of nested objects like this, it's either a single value:

```
"input": "hello",
"output: {
  "en": "Hello",
  "de": "Hallo",
},
```

or multiple

```
"input": {
  "first": "hello",
  "second: "...",
},
"output: {
  "first": {
    "en": "Hello",
    "de": "Hallo",  
  },
  "second": {
    ...
  },
},
```
