### ISSUE TITLE
[firestore-send-email] Error: Message failed: 450 ... The attachments.0.filename field is required when attachments.0.content is present.

### ISSUE THREAD

**Issue by drosi94** [firebase/extensions#753]
- Extension name: **firebase/firestore-send-email** 
- Extension version: **0.1.11**

# Steps to reproduce:

The exact same mail data worked in the past

Send mail function
```
export const sendWelcomeEmail = (
  userId: string,
  displayName = ""
): Promise<FirebaseFirestore.DocumentReference<FirebaseFirestore.DocumentData>> => {
  return db.collection("mails").add({
    toUids: [userId],
    template: {
      name: "welcome_el",
      data: {
        displayName,
      },
    },
  });
};
```

The mail data

<img width="443" alt="Screenshot 2021-09-26 at 8 03 14 PM" src="https://user-images.githubusercontent.com/3253526/134817061-82af7a1b-d3f7-4ced-b32e-e4f46a5c7689.png">

The template data

###
<img width="823" alt="Screenshot 2021-09-26 at 8 04 10 PM" src="https://user-images.githubusercontent.com/3253526/134817088-e762ade3-d612-4a3d-98bc-3e2a45858be1.png">

##### Expected result

Should send the message

##### Actual result

`Error when delivering message=mails/*id*: Error: Message failed: 450 The given data was invalid. This file type is not supported.,The attachments.0.filename field is required when attachments.0.content is present. `

**Comment by dackers86** [comment]
Hi @drosi94.

Can you confirm the file type of the attachment you are trying to send. `This file type is not supported` suggests there is an issue with the email provider and the attachment you are trying to send?

**Comment by drosi94** [comment]
I am not trying to send a file attachment. I provide the code 

The transactional email provider that I use is Mailersend.

And I have this template 

![Screenshot 2021-09-27 at 3 14 47 PM](https://user-images.githubusercontent.com/3253526/134905963-daceca53-c9c5-49ce-837f-d33de5b9ebf5.png)

With subject, amp, text fields

I will check with my SendGrid credentials and if it works then it's an issue of my provider

```
export const sendWelcomeEmail = (
  userId: string,
  displayName = ""
): Promise<FirebaseFirestore.DocumentReference<FirebaseFirestore.DocumentData>> => {
  return db.collection("mails").add({
    toUids: [userId],
    template: {
      name: "welcome_el",
      data: {
        displayName,
      },
    },
  });
};
```

**Comment by drosi94** [comment]
It seems that it's an issue with MailerSend.


Thank you for your help!
