### ISSUE TITLE
[firestore-bigquery-export] Failed inserts to BQ

### ISSUE THREAD

**Issue by fringley** [firebase/extensions#754]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: `firebase/firestore-bigquery-export`
- Extension version: `0.1.16`
- Configuration values (redact info where appropriate):
  - Cloud Functions location `europe-west2`
  - BigQuery Dataset location `eu`
  - Collection path `barcodes`
  - Dataset ID `firestore_export`
  - Table ID `barcodes`
  - BigQuery SQL table partitioning option `NONE`

#### Steps to reproduce:

We have this extension installed three times, each syncing a different collection to our BQ instance.  This has been running for months with no (known) issues.  We have periodically updated the version in line with our releases.

On the 24th September 2021 from approx. 6pm until approx. 8am the following day, we had a number of attempts (for all) of the instances of the installed extension to configure the extension, followed by a number of timeouts.  Screenshot example attached:

<img width="1380" alt="Screenshot 2021-09-28 at 11 36 27" src="https://user-images.githubusercontent.com/477265/135305307-331ef076-9a4c-4a63-802f-663efe85fccd.png">

##### Expected result

Updated collection documents to be synced to our BQ instance.

##### Actual result

A number of collection documents were not updated within BQ, leading to a discrepancy between our Firestore documents and their related rows in BigQuery (potentially 1,000s of affected documents/rows)

Aside from the fact that this has presented a significant issue in terms of our BI reporting capabilities, I am also unsure how to "rerun" the updates for just the affected time, to bring BQ back inline with the Firestore data.

Finally, is there a mechanism to better identify if this happens again - as it was only through analysis of the data that we spotted this discrepancy?  Perhaps there is a standard way to report on timeouts for these extensions to better surface/highlight problems?

**Comment by dackers86** [comment]
Hi @fringley 

For resynchronising data we have an `import` script that could be of use https://github.com/firebase/extensions/tree/next/firestore-bigquery-export/scripts/import.

I'll add this ticket as a feature request / investigation on how we can improve error handling within the extension.

**Comment by fringley** [comment]
Hi @dackers86 thanks for the info.

We have actually used the import script when our initial GBQ tables were initially created (and empty).

Will the script deal with backfilling a gap in the data?

Regarding the period the extension was not working - are there any theories why this would have happened... anything we can do in terms of logging that might help understand the root of the issue?  It's peculiar that the issue was temporary and fixed itself with no intervention from us.

**Comment by dackers86** [comment]
Yes, the script would help to fill the missing data.

Unfortunately, it would not be able to fill any missing gaps in the data. 

At this stage I would recommend taking a backup and clearing the table. You can then `backfill` with the `import` script, any new data going forward would then continue to be added through the extension.

**Comment by i14h** [comment]
we could also provide a hook for when an insert fails, so the user might set up their own logging or paging

**Comment by fringley** [comment]
> we could also provide a hook for when an insert fails, so the user might set up their own logging or paging

I also see from #688 that a suggestion of adding in a failed log to a firestore collection could be helpful and convenient as this can be set up at the same time as enabling the extension.  It does perhaps look like this timeout issue is the cause of the missing data.  The only difference I can see over that issue, is that the issue we encountered seemed to persist over a few hours - resulting in a lot of missing data.

**Comment by dackers86** [comment]
Closed via https://github.com/firebase/extensions/pull/891
