### ISSUE TITLE
Some images can't be resized due to an error

### ISSUE THREAD

**Issue by thiagohk** [firebase/extensions#755]
Some images get the error "Invalid SOS parameters for sequential JPEG" and can't be converted, it's related to the sharp library bug https://github.com/lovell/sharp/issues/1578.

It seems a easy fix, I already tested on a local code.

This is the full error message:

```
Error when resizing image [Error: vips_realpath: unable to form filename
unix error: No such file or directory
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: Invalid SOS parameters for sequential JPEG
VipsJpeg: out of order read at line 0
VipsJpeg: out of order read at line 0
] 
```

**Comment by dackers86** [comment]
Hi @thiagohk.

If you know a solution we are happy to accept `PRs` for updates to the extensions.

Alternatively, could you provide the current extension `version` you are using as well as any steps tor reproduce the error?

Thanks

**Comment by thiagohk** [comment]
Hi @dackers86 

To reproduce this problem I have specific images that are profile pictures from our users. I found this image on google that has the same issue https://gist.githubusercontent.com/mnaoumov/060166a995eb75666d95203a1d9f468b/raw/6a2b0f46422beb63a4aea4185463edbda96d04cb/5242.jpg

If you use the plugin to resize that image it will throw the error.

We are using the latest version (firebase/storage-resize-images@0.1.22)
