### ISSUE TITLE
Firebase extension for transactional mails

### ISSUE THREAD

**Issue by tobiaseisenschenk** [firebase/extensions#76]
### What feature would you like to see?

I see transactional e-mails as a common use case firebase users will implement. If this feature gets picked I'd be happy to contribute to its development. However I'd appreciate some guidelines as to how a function technically differs from an extension.

### How would you use it?

In my company we currently use [mailjet in combination with firebase functions](https://github.com/nui-os/mailjet-function). This is a minimal example to send welcome mails on authentication events, but other triggers could be useful as well.

**Comment by giammin** [comment]
in my case it is enough [to implement email headers](https://github.com/firebase/extensions/issues/77) but having the ability to access the API would be really usefull

**Comment by Ehesp** [comment]
Reference: https://github.com/firebase/extensions/issues/77

**Comment by karayu** [comment]
Thanks so much for the feature request! I'm closing this for now since we're tracking in #108
