### ISSUE TITLE
@firebaseextensions/fs-bq-import-collection  interactive validation sourceCollectionPath when collection is not on root

### ISSUE THREAD

**Issue by leblancmeneses** [firebase/extensions#761]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: fs-bq-import-collection
- Extension version: 0.1.12
- Configuration values (redact info where appropriate):
  - Collection path: modules/abc/cards
  - Dataset ID: abc_prod
  - Table ID: cards

#### Steps to reproduce:

Run the following in interactive mode:
```$ FIREBASE_CONFIG=$FIREBASE_CONFIG GCLOUD_PROJECT=$GCLOUD_PROJECT npx @firebaseextensions/fs-bq-import-collection```

? What is your Firebase project ID? abc-prod
? What is the path of the the Cloud Firestore Collection you would like to import from? (This may, or may not, be the same Collection for which you pla
n to mirror changes.) modules/abc/cards
>> The collection path does not match the regular expression provided

##### Expected result

Continue asking for more interactive prompts.

##### Actual result

Received a validation error message instead: " >> The collection path does not match the regular expression provided"

Possible solutions:
https://github.com/firebase/extensions/blob/7d7874fa89de85cbb928ad42bbb029471f12be3f/firestore-bigquery-export/scripts/import/src/index.ts#L40

delete FIRESTORE_VALID_CHARACTERS validation would be the simplest. 

OR 

split into two:
FIRESTORE_COLLECTION_GROUP_VALID_CHARACTERS
FIRESTORE_COLLECTION_VALID_CHARACTERS

switch question order to display:
Would you like to import documents via a Collection Group query?
before
What is the path of the the Cloud Firestore Collection you would like to import from? 

so you know which validation to apply.

https://github.com/firebase/extensions/blob/7d7874fa89de85cbb928ad42bbb029471f12be3f/firestore-bigquery-export/scripts/import/src/index.ts#L168

Currently, The only way to bulk import non root collections is to use the non-interactive mode.
```
FIREBASE_CONFIG=$FIREBASE_CONFIG GCLOUD_PROJECT=$GCLOUD_PROJECT npx @firebaseextensions/fs-bq-import-collection --non-interactive  --project abc-prod --source-collection-path 'modules/abc/cards' --query-collection-group false --dataset abc_firestore --table-name-prefix cards --multi-threaded=true --dataset-location us
```

**Comment by dackers86** [comment]
Closing as fixed in #561.
