### ISSUE TITLE
[firestore-bigquery-export] Support partitioned table base on Timestamp field

### ISSUE THREAD

**Issue by alfred-risb** [firebase/extensions#764]
Firestore have extension to export data into bigquery, the table is partitioned base on when the record success push to server (_partitiontime).

My project require to partition table base on specific field (Timestamp or int type) in document, it will be amazing if such feature available in "export to Bigquery" extension

**Comment by jasonberryman** [comment]
@i14h Can we also add support for the partition value to be derived from a ISO8601 datetime string?

**Comment by darnmason** [comment]
another vote for ISO8601 formatted strings, if possible.

**Comment by dackers86** [comment]
For the issue of partitioning based on the `timestamp`, this should be currently working as expected.

The issue can re-opened if it is still as an issue.

For the ISO8601 formatted strings please track https://github.com/firebase/extensions/issues/1483
