### ISSUE TITLE
Send mails with custom headers with firestore-send-email extension

### ISSUE THREAD

**Issue by giammin** [firebase/extensions#77]
### Extension name

firestore-send-email

### What feature would you like to see?

the ability to add custom header in a mail

### How would you use it?

We use Mandrill API to send emails and we can add some [custom metadata ](https://mandrill.zendesk.com/hc/en-us/articles/205582417-Using-Custom-Message-Metadata) to every message.

We can also add metadata sending email with Mandrill smtp but we need to pass them in the X-MC-Metadata header.

It would be great if we can specify in each message and at template level some headers to include in the message

**Comment by Ehesp** [comment]
Thanks for the feature request. I'll pick this up internally & figure out how/if this can be integrated.

**Comment by dasmeet** [comment]
Hi

Would love to have this feature. Am using SES but can't even enable basic SES open and click tracking without custom header.

**Comment by karayu** [comment]
This looks like it's covered by #108
