### ISSUE TITLE
[Delete-User-Data] It's not possible to delete data from a realtime database located in europe-west1

### ISSUE THREAD

**Issue by Andree98** [firebase/extensions#795]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: delete-user-data
- Extension version: 0.1.11 

#### Steps to reproduce:

Configure the extension to delete data from realtime database located in europe-west1

##### Expected result

Should delete data without any problem

##### Actual result

This error

![Screenshot 2021-11-14 124453](https://user-images.githubusercontent.com/34305925/141681815-4a41780d-4c2b-432a-ad92-8170b56f1476.png)

**Comment by dackers86** [comment]
Hi @Andree98.

Can you confirm the region for your `database` and the installed region for the `extension`.

These values will need to match, the extension can be reconfigured in the firebase console should it need to be updated.

**Comment by Andree98** [comment]
Hello @dackers86 

Both are located on europe-west1

Database

![Screenshot 2021-11-15 102853](https://user-images.githubusercontent.com/34305925/141766248-2d059956-4220-4491-8b9a-cf42a8b052b7.png)

Extension

![Screenshot 2021-11-15 102930](https://user-images.githubusercontent.com/34305925/141766253-3524b46e-825c-4668-aad9-2fd17a69338c.png)

**Comment by i14h** [comment]
this seems like its because we omit the region in the initialization url here https://github.com/firebase/extensions/blob/641092c2580d765cdd3f11bb26328b8c85754563/delete-user-data/functions/src/index.ts#L27
