### ISSUE TITLE
Feature Request: storage-resize-images

### ISSUE THREAD

**Issue by inglesuniversal** [firebase/extensions#797]
Add to this extension the ability to create thumbnail from 1st GIF frame of GIF image file.

First frame of GIF file to be converted preferably as Webp image file in the predefined export resolution (e.g. 200x200px)

Thanks

**Comment by dackers86** [comment]
Hi @inglesuniversal.

Thanks for posting. 

Re-adding gif images could offer some confusion as developers may expect this to also re-size images into working `gifs`. This functionality is currently unsupported. 

At this stage i'm not too sure how to allow gif images without adding confusion on how this would be used.

I've added to our project board for discussion.

**Comment by inglesuniversal** [comment]
If you allow me to suggest... As a developer, I would add the note ==> non-animated-gif-thumbnail.webp

**Comment by PaulLVoelker** [comment]
The same would be great for video. To resize a certain frame in a video.

**Comment by dackers86** [comment]
Related to https://github.com/firebase/extensions/issues/797
