### ISSUE TITLE
[storage-resize-images] converting other formats into TIFF. 

### ISSUE THREAD

**Issue by posiek07** [firebase/extensions#807]
### [READ] Step 1: Are you in the right place?

Yes.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **storage-resize-images**
- Extension version: **0.1.24**
- Configuration values:
![Screenshot 2021-11-26 at 10 11 10](https://user-images.githubusercontent.com/64485499/143564247-193a6225-8d24-4249-a822-214f51c17d0d.png)

#### Steps to reproduce:

1. Use my configuration of extension.
2. Upload files in jpg, webp or png format.
3. Try to download the converted TIFF file thru Cloud Storage link in Firebase Console.

When trying to download converted images from jpg, png, webp to TIFF in the live version of the extension I am actually downloading files in their source file format.

I have tried to debug it as well with the Firebase Emulator. The problem is NOT occurring when I am debugging it locally. Everything works as expected so I can download converted TIFF.
![Screenshot 2021-12-07 at 14 38 23](https://user-images.githubusercontent.com/64485499/145774250-9365494e-5665-4490-aa32-defdb88146a5.png)

##### Expected result
When the file (jpg,png,webp) is converted to TIFF you should be able to download this TIFF thru Firebase Storage link in Live Console. 

##### Actual result
When trying to download the converted TIFF file in a live version of Firebase Console in Cloud Storage I am receiving a resized file in its original file format (jpg,png,webp) and filename.
![Screenshot 2021-11-26 at 10 01 36](https://user-images.githubusercontent.com/64485499/143564473-78726a89-2946-4bf5-b88c-7288b0e8be11.png)

**Comment by i14h** [comment]
if this works in the emulator potentially its not a Sharp library issue

**Comment by dackers86** [comment]
This issue occurs as the underlying metaData in Firebase storage is not currently updated when resizing the file. 

```js
   // filename\*=utf-8''  selects any string match the filename notation.
    // [^;\s]+ searches any following string until either a space or semi-colon.
    const contentDisposition = objectMetadata.contentDisposition.replace(
      /(filename\*=utf-8''[^;\s]+)/,
      `filename*=utf-8''${modifiedFileName}`
    );

    // Cloud Storage files.
    const metadata: { [key: string]: any } = {
      contentDisposition,
      contentEncoding: objectMetadata.contentEncoding,
      contentLanguage: objectMetadata.contentLanguage,
      contentType: imageContentType,
      metadata: objectMetadata.metadata || {},
    };
```
