### ISSUE TITLE
Permission denied error to reconfigure/uninstall the extension

### ISSUE THREAD

**Issue by binoyudayan** [firebase/extensions#824]
### [READ] Step 1: Are you in the right place?

Yes, I tried raising this issue firebase support and got redirected to me github issue after making necessary checks from their end.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: `firebase/firestore-send-email`
- Extension version: 0.1.6-rc.1 / 0.1.12
- Configuration values (redact info where appropriate):
![image](https://user-images.githubusercontent.com/10575062/145195237-b9e261b6-b192-400b-b5aa-7c5e41ec79ea.png)

#### Steps to reproduce:

What happened? How can we make the problem occur?
We tried updating the configuration and the update started throwing error. So we tried uninstalling the extension it didn't work. So we tried installing new version of the extension, neither did it work. Now the extension is completely not working.

Today i managed to update the extension to latest version `0.1.12 `
Getting the following error while trying to reconfigure:
`; RESOURCE_ERROR at /deployments/firebase-ext-firestore-send-email-6ns1/resources/mods-api-enable-iam: {"ResourceType":"deploymentmanager.v2.virtual.enableService","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission denied to enable service [iam.googleapis.com]\nHelp Token: <token>","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.PreconditionFailure","violations":[{"type":"googleapis.com","subject":"110002"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"AUTH_PERMISSION_DENIED","domain":"serviceusage.googleapis.com"}],"statusMessage":"Forbidden","requestPath":"https://serviceusage.googleapis.com/v1/projects/prot-4dc6e/services/iam.googleapis.com:enable","httpMethod":"POST"}}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-send-email-6ns1/resources/mods-api-enable-cloudfunctions: {"ResourceType":"deploymentmanager.v2.virtual.enableService","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission denied to enable service [cloudfunctions.googleapis.com]\nHelp Token: <token>","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.PreconditionFailure","violations":[{"type":"googleapis.com","subject":"110002"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"AUTH_PERMISSION_DENIED","domain":"serviceusage.googleapis.com"}],"statusMessage":"Forbidden","requestPath":"https://serviceusage.googleapis.com/v1/projects/prot-4dc6e/services/cloudfunctions.googleapis.com:enable","httpMethod":"POST"}}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-send-email-6ns1/resources/mods-api-enable-cloudbuild: {"ResourceType":"deploymentmanager.v2.virtual.enableService","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission denied to enable service [cloudbuild.googleapis.com]\nHelp Token: <token>","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.PreconditionFailure","violations":[{"type":"googleapis.com","subject":"110002"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"AUTH_PERMISSION_DENIED","domain":"serviceusage.googleapis.com"}],"statusMessage":"Forbidden","requestPath":"https://serviceusage.googleapis.com/v1/projects/prot-4dc6e/services/cloudbuild.googleapis.com:enable","httpMethod":"POST"}}; RESOURCE_ERROR at /deployments/firebase-ext-firestore-send-email-6ns1/resources/mods-api-enable-firebase: {"ResourceType":"deploymentmanager.v2.virtual.enableService","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission denied to enable service [firebase.googleapis.com]\nHelp Token: <token>","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.PreconditionFailure","violations":[{"type":"googleapis.com","subject":"110002"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"AUTH_PERMISSION_DENIED","domain":"serviceusage.googleapis.com"}],"statusMessage":"Forbidden","requestPath":"https://serviceusage.googleapis.com/v1/projects/prot-4dc6e/services/firebase.googleapis.com:enable","httpMethod":"POST"}}`

Uninstallation error from the other version(`0.1.6-rc.1`):
`; RESOURCE_ERROR at /deployments/firebase-ext-firestore-send-email/resources/processQueue: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"403","ResourceErrorMessage":{"code":403,"message":"Permission 'cloudfunctions.functions.get' denied on resource 'projects/prot-4dc6e/locations/europe-west1/functions/ext-firestore-send-email-processQueue' (or resource may not exist).","status":"PERMISSION_DENIED","statusMessage":"Forbidden","requestPath":"https://cloudfunctions.googleapis.com/v1/projects/prot-4dc6e/locations/europe-west1/functions/ext-firestore-send-email-processQueue","httpMethod":"GET"}}
`
The cloud function `ext-firestore-send-email-processQueue` already got deleted. I think this could be one reason for un-installation failure.

The extension service account has the following permission in IAM
1. Cloud Datastore User
2. Cloud Run Service Agent 

I even tried adding `Cloud Function Admin` permission, but still didn't work.

**Tried both both firebase console as well as cli, getting the same error.**

##### Expected result
Possible to reconfigure/uninstall the extension.

##### Actual result
1. Unable to reconfigure the extension.
2. Unable to uninstall the extension.

**Comment by dackers86** [comment]
Hi @binoyudayan 


I have tried to replicate the issue to confirm this is an issue with a new version release.

The installation installed successfully for me.


Using the `cli`, can you try the following...


`firebase ext:update {ext-name} . --project={project-name}` from the `firestore-send-email` directory

**Comment by binoyudayan** [comment]
Hi @dackers86,
Thank you for the quick reply. I have tried and updated the extension from `0.1.11` to `0.1.12`. The problem is I'm unable to reconfigure the updated extension and uninstall the old version of the extension. I have pasted the error from console/cli: there are some permission error being thrown. As per the firebase support, the user has all the permission needed. Actual issue started on version `0.1.6-rc.1` while we were trying to update the configuration. Now i'm stuck because i can not update the configure and delete the old version of the extension.

**Comment by dackers86** [comment]
Can you try deploying a basic function with the same name as `ext-firestore-send-email-processQueue` and then re-triggering the re-installation?

**Comment by binoyudayan** [comment]
Still same errors for both configuration update and uninstall :(

**Comment by binoyudayan** [comment]
I couldn't find any version older than the one I deployed yesterday. Version 2 & 3 is from yesterday.

![image](https://user-images.githubusercontent.com/10575062/145358493-83e9e37d-c904-4b6a-837c-cadd0440c449.png)

**Comment by binoyudayan** [comment]
okay. The user has `Editor` has permission as i mentioned before. So shall I contact firebase support again?

**Comment by dackers86** [comment]
@binoyudayan I think that although this was a firebase installation issue, the solution may be something Firebase support could potentially provide a solution for. 

I'm not sure which permission is required to uninstall, I could take a long time when trying to replicate.

Can you contact Firebase support and include the response here?

**Comment by binoyudayan** [comment]
@dackers86 Sure, thank you for the support. :+1:

**Comment by dackers86** [comment]
Closing until further feedback provided.

**Comment by Acterion** [comment]
Did you get any updates on this issue? I'm having the same thing on 0.1.13 here. It is infuriating. My production email notifications are down because of this issue!

**Comment by Acterion** [comment]
> Did you get any updates on this issue? I'm having the same thing on 0.1.13 here. It is infuriating. My production email notifications are down because of this issue!

Complete reinstall solved the issue for me

**Comment by rbedemann** [comment]
In my case the cloud service account had not enough permissions anymore. Seems like they got somehow lost on the way...

Double check that your Google Cloud API Service Agent (`<project-id>@cloudservices.gserviceaccount.com`) has all required roles. By default it should have "Editor" (`roles/editor`)

**Comment by binoyudayan** [comment]
H, Finally this worked after adding `Project IAM Admin` and `Security Admin`  roles for the user. The user already has `Editor` permission. Something happened on the way as @rbedemann mentioned. 
I wanted to update it here as it might help someone.

**Comment by Jethro87** [comment]
@rbedemann Thanks so much, your comment [here](https://github.com/firebase/extensions/issues/824#issuecomment-1067862577) solved the issue for me.

**Comment by albernaz** [comment]
Heads up!

Be sure to check if you are changing **Google APIs Service Agent** 

It should look something like this:

**99674383783@cloudservices.gserviceaccount.com**

then add Basic -> Editor permission. That's it.
