### ISSUE TITLE
Apply to create my own firebase extension 

### ISSUE THREAD

**Issue by mfbx9da4** [firebase/extensions#831]
Hi I would like to develop my own firebase extension. (Specifically to securely distribute private-public-key-pairs for E2EE applications). 

AFICS, that's not possible yet. When might it be possible?

**Comment by dackers86** [comment]
HI @mfbx9da4.

We are currently still in the Alpha stage for community extensions but is something that we are hoping to look at more in the future. According to https://firebase.googleblog.com/2021/01/firebase-extensions-experimental.html

> To share extensions with other developers, you need to become an Extension Publisher. Register as a publisher by joining the Firebase Alpha program, and indicate you're interested in building Community Extensions in the comments field

In the meantime, please use the following https://services.google.com/fb/forms/firebasealphaprogram/ to apply for consideration.
