### ISSUE TITLE
Blurry resized images

### ISSUE THREAD

**Issue by yahavt** [firebase/extensions#84]
Extension name: storage-resize-images
Problem: When resizing images the output image is blurry

According to https://imagemagick.org/Usage/resize/#resize_unsharp
there needs to be a call to "-unsharp 0x6+0.5+0" in order to resolve this issue.

The issue is in index.ts line 175

Thanks

**Comment by jhuleatt** [comment]
Adding `-unsharp 0x6+0.5+0` should be a really simple change. We'd modify this line: https://github.com/firebase/extensions/blob/506f56b6a98b4197dd8799e46b16ccb8ca4c564d/storage-resize-images/functions/src/index.ts#L175

To add the unsharp option:

```ts
await spawn("convert", [originalFile, "-resize", `${size}>`, "-unsharp", "0x6+0.5+0", resizedFile], {
```

However, picking the correct params for sharpening is more of an art than a science. The imagemagick docs linked above suggested multiple different unsharp configs besides `0x6+0.5+0` for different scenarios. [This forum post](http://www.imagemagick.org/discourse-server/viewtopic.php?t=22998) shows how involved this discussion can be.

**Comment by jhuleatt** [comment]
Might be worth considering #124 as part of this

**Comment by karayu** [comment]
Hi Tako, 

Thanks so much for the feedback! After reviewing with the team, we realized that ImageMagick is pretty involved and would change the scope of this extension significantly. We're going to hold off on making this change and instead consider building a new extension for ImageMagick. I'll close this for now and track that effort internally. 

Thanks again for using extensions!
Kara
