### ISSUE TITLE
auto delete does not works

### ISSUE THREAD

**Issue by tanosugi** [firebase/extensions#842]
I delete the customer on the stripe dashboard but Authentication User is not deleted.
It worked three months ago but it does not works today at latest version.

- Extension name: stripe/firestore-stripe-payments
- Extension version: 0.2.4
- Configuration values:
  - Automatically delete Stripe customer objects: Auto delete

**Comment by dackers86** [comment]
Hi @tanosugi 

This extension is currently managed on the official Stripe github  repository https://github.com/stripe/stripe-firebase-extensions.

However I can offer support, do you have the `Automatically delete Stripe customer objects` configuration  set to  `Auto delete` on the installed extnesion?

**Comment by tanosugi** [comment]
Hi @dackers86
Sorry for writing in not appropriate place. and thanks for your response.
I had some mistake for web hook setting and problem were solved after I fix the web hook setting.
Sorry for taking time.

**Comment by dackers86** [comment]
Thanks @tanosugi.

Happy it's working!
