### ISSUE TITLE
[Firestore Trigger Email Extension] Specify sender name with Trigger Email

### ISSUE THREAD

**Issue by dylangarrett** [firebase/extensions#848]
I can't find any documentation in relation to specifying the name of sender, alongside the from email address.

See attached screenshot for example. My domain is hello@myapp.com, and emails arrive with the name 'hello'. Ideally I'd like to specify the name as MyApp. 

![image](https://user-images.githubusercontent.com/44604861/149409267-cef28889-4b6c-4111-b3b7-c01b882af069.png)

When I send test emails from my SMTP provider (SendGrid) the email appears as I would like, from MyApp.

Any assistance would be appreciated, thanks!

**Comment by posiek07** [comment]
Hi @dylangarrett,

Sorry to hear about your inconvenience.
Could you tell me what is your `Default FROM address` option string in your extension setting, please? If you didn't you may try to use `MyApp <hello@myapp.com>` format.

Please let us know if that helps.

**Comment by dylangarrett** [comment]
Hey @posiek07 

Thanks for the help! By setting the default value of the from address in the format provided, emails appear as expected. 

It's worth noting that I tried specifying the from address as a top-level field in the document in the format `MyApp <hello@myapp.com>` it did not appear to resolve the issue. Specifying it specifically as the default value works though.
