### ISSUE TITLE
firestore-bigquery-export: Include path parameters as columns directly

### ISSUE THREAD

**Issue by JarnoRFB** [firebase/extensions#853]
This feature request is for extension: `firestore-bigquery-export`

### What feature would you like to see?

When streaming data from firestore to BigQuery, the tables include both the `document_name` and the `document_id`. However, data from document_ids at higher levels is not directly accessible and has to parsed from the `document_name` column. I think it would increase usability if the wilcard parameters could be directly included as separate columns, either directly in the streaming cloud function, or at least in the `_latest`  or `_schema` views. 

Ideally, if one runs `npx firebase ext:install firebase/firestore-bigquery-export` with `COLLECTION_PATH=my-collection/{collection_id}/subcollection`, a column named `collection_id` should be included in the `raw_changelog` table.

### How would you use it?

I am trying to split operational and analytic workloads between firestore and BigQuery. As subcollections as used in firestore to group related data, that information is required for analytics as well, were the entire collection group is merged into one table. Having the grouping information directly available as a column, instead of having to parse it from a string would make things simpler and more robust.

**Comment by i14h** [comment]
Thanks @JarnoRFB. Would it be helpful if we added the collection structure as a json in a separate column? we're trying to avoid adding too many features into the extension directly and at the same time allow for more advanced usecases to have a solution (fyi semi-structured data in [bigquery is now supported](https://cloud.google.com/blog/products/data-analytics/bigquery-now-natively-supports-semi-structured-data))

**Comment by JarnoRFB** [comment]
@i14h thanks for the reply!
> Would it be helpful if we added the collection structure as a json in a separate column?

If I understand you correctly, I would imaging that if I stream from `COLLECTION_PATH=my-collection/{collection_id}/subcollection` the new column would contain the json `{"collection_id": "the_id"}`. That would indeed satisfy my needs, as from there one could either build a view with homogeneously typed columns like [schema views](https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/guides/GENERATE_SCHEMA_VIEWS.md) or, as you pointed out, simply use the new native json type (thanks for the pointer, I call that timing).

**Comment by i14h** [comment]
@JarnoRFB we're thinking of different ways to implements this. We'll keep you posted.

**Comment by dackers86** [comment]
We have started a discussion on the potential solutions for this issue. Please find all details and proposed solutions here https://github.com/firebase/extensions/discussions/867

**Comment by dackers86** [comment]
Closed via https://github.com/firebase/extensions/pull/891
