### ISSUE TITLE
Add non interactive mode for installing firestore Big Query export

### ISSUE THREAD

**Issue by krishnadubeyQ** [firebase/extensions#858]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: Firestore Big Query Export

### What feature would you like to see?

1. When installing firestore big query extension please provide a way for installing it in non-interactive way
2. Add more flags in install command options like "--instance_id" for providing instance id of our choice all time (either first instance or multiple). Currently we get option of providing instance id only when the particular instance id ("firestore-bigquery-export" on first time installation) is already available and that too in interactive mode.
3. Either flag or in params.env file provide a way to give instance id when installing extension.

### How would you use it?

- We have several environments in which I have to replicate the extension installation process.
- I am writing a script for installing all the extension in different environments but I am not able to make it work because of the above mentioned issue.
- If I get to install extension in non-interactive way with "--instance_id" flag or "instance_id" variable in params.env file then my script will just work fine.
- Hope to see this update ASAP.

Thanks for the extension!!

**Comment by dackers86** [comment]
Thanks @krishnadubeyQ.

This is not an update that can applied to a specific extension and would rely on an update to the https://github.com/firebase/firebase-tools repository.

We will continue to track this on project board.

**Comment by krishnadubeyQ** [comment]
Thanks @dackers86 for actively looking into this issue.
Do I need to raise this issue separately in the repository you mentioned?

**Comment by dackers86** [comment]
@krishnadubeyQ  I see you have already commented on https://github.com/firebase/firebase-tools/issues/3885.

This would probably be the best source for any updates regarding this feature.

**Comment by krishnadubeyQ** [comment]
Sure, then I will track that issue.
Closing this issue, thanks for the help.
