### ISSUE TITLE
When using firestore-bigquery-export extension with a batched write, some documents are not available in the raw_data_raw_latest

### ISSUE THREAD

**Issue by rtarnec** [firebase/extensions#869]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: firestore-bigquery-export
- Extension version:  0.1.20
- Configuration values (redact info where appropriate):
- Cloud Functions location: europe-west1
 - BigQuery Dataset location: europe-west1

#### Steps to reproduce:

1/ Configure the extension following the standard way
2/ Use a batched write to populate the source Firestore collection with some new documents
3/ Check in BigQuery if the number of rows in the raw_data_raw_latest view corresponds to the number of docs in the collection

##### Expected result

The number of rows in the BigQuery raw_data_raw_latest view corresponds to the number of docs in the collection

##### Actual result

The number of rows in the BigQuery raw_data_raw_latest view **does not** corresponds to the number of docs in the collection. This happens with a batched write containing 499 Firestore document but also for a batched write with only 7 documents.

**Comment by dackers86** [comment]
Hi @rtarnec .

Could this be a duplicate of https://github.com/firebase/extensions/issues/688?

We currently have a PR which would log any missing records https://github.com/firebase/extensions/pull/861

**Comment by i14h** [comment]
@rtarnec do you see any errors in the logs? Can you paste them here. Seeing the issue with only 7 inserts is concerning.

**Comment by i14h** [comment]
@rtarnec can you also paste the code you're using to write in batch?

**Comment by rtarnec** [comment]
@i14h Please find below the code of a Node.js script based on the Admin SDK. I've just tried it again with a freshly installed extension, an **empty** Firestore source collection on a new Firebase project and there is only one document in Big Query and 7 docs in Firestore. 

But, I can see 6 times the same error in the Cloud Functions Log, "'Already Exists: Table ******:firestore_export.testext_raw_latest',", see below for the full trace (note that the project name was repleced with ******)

**Node.js script code:**

```
#!/usr/bin/node
const admin = require("firebase-admin");

admin.initializeApp({
    credential: admin.credential.cert("**************.json")
});

const db = admin.firestore();
const batch = db.batch();

for (let i = 0; i < 7; i++) {
    const docRef = db.collection("testext").doc();
    const obj = { name: `name${i}`, age: i*6 };
    batch.set(docRef, obj);
}

batch.commit()
.then(() => {
    console.log("Batch committed");
})
.catch(error => {
    console.log(error);
})
```

**Error stack trace:**

```
Error when mirroring data to BigQuery ApiError: Already Exists: Table *********:firestore_export.testext_raw_latest
    at new ApiError (/workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:58:15)
    at Util.parseHttpRespBody (/workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:193:38)
    at Util.handleResp (/workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:134:117)
    at /workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:432:22
    at onResponse (/workspace/node_modules/retry-request/index.js:228:7)
    at /workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/teeny-request/build/src/index.js:233:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 409,
  errors: [
    {
      message: 'Already Exists: Table *********:firestore_export.testext_raw_latest',
      domain: 'global',
      reason: 'duplicate'
    }
  ],
  response: Gunzip {
    _writeState: Uint32Array(2) [ 16024, 0 ],
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      destroyed: true,
      errored: null,
      closed: true,
      closeEmitted: true,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      prefinish: [Function: prefinish],
      error: [Array],
      data: [Function (anonymous)],
      end: [Function (anonymous)]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: true,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: true
    },
    allowHalfOpen: true,
    bytesWritten: 202,
    _handle: null,
    _outBuffer: <Buffer 7b 0a 20 20 22 65 72 72 6f 72 22 3a 20 7b 0a 20 20 20 20 22 63 6f 64 65 22 3a 20 34 30 39 2c 0a 20 20 20 20 22 6d 65 73 73 61 67 65 22 3a 20 22 41 6c ... 16334 more bytes>,
    _outOffset: 360,
    _chunkSize: 16384,
    _defaultFlushFlag: 2,
    _finishFlushFlag: 2,
    _defaultFullFlushFlag: 3,
    _info: undefined,
    _maxOutputLength: 4294967295,
    _level: -1,
    _strategy: 0,
    statusCode: 409,
    statusMessage: 'Conflict',
    request: {
      agent: [Agent],
      headers: [Object],
      href: 'https://bigquery.googleapis.com/bigquery/v2/projects/*********/datasets/firestore_export/tables'
    },
    body: '{\n' +
      '  "error": {\n' +
      '    "code": 409,\n' +
      '    "message": "Already Exists: Table *********:firestore_export.testext_raw_latest",\n' +
      '    "errors": [\n' +
      '      {\n' +
      '        "message": "Already Exists: Table *********:firestore_export.testext_raw_latest",\n' +
      '        "domain": "global",\n' +
      '        "reason": "duplicate"\n' +
      '      }\n' +
      '    ],\n' +
      '    "status": "ALREADY_EXISTS"\n' +
      '  }\n' +
      '}\n',
    headers: {
      'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
      'cache-control': 'private',
      'content-encoding': 'gzip',
      'content-type': 'application/json; charset=UTF-8',
      date: 'Wed, 02 Feb 2022 08:48:11 GMT',
      server: 'ESF',
      'transfer-encoding': 'chunked',
      vary: 'Origin, X-Origin, Referer',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '0'
    },
    toJSON: [Function: toJSON],
    [Symbol(kCapture)]: false,
    [Symbol(kTransformState)]: {
      afterTransform: [Function: bound afterTransform],
      needTransform: false,
      transforming: false,
      writecb: null,
      writechunk: null,
      writeencoding: 'buffer'
    },
    [Symbol(kError)]: null
  }
} 
```

**Comment by i14h** [comment]
Thanks for replying back. Hmm, does this happen only when the BigQuery dataset and raw changelog tables need to be initialized? in that case @dackers86 do you think there's a race condition happening [here](https://github.com/firebase/extensions/blob/eec2964ce4ba363b9f742edf055cae38fb7e1596/firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/index.ts#L72)?

**Comment by dackers86** [comment]
@i14h There is a race condition here, the first records seem to inconsistently fail as the the creation of the `datasets` and `tables`, only occurs when the documents are written - should the tables ever be deleted then they will be recreated on the first write (causing some writes to fail).

I have attempted to see if this issue continues following the first batch and no other issue occurs. 

Although I did find delays of up-to 5 seconds while the data `propegates` to BigQuery

**Comment by rtarnec** [comment]
@i14h Q: "Does this happen only when the BigQuery dataset and raw changelog tables need to be initialized? " A : Yes, after the first initialization it seems to work correctly.

@dackers86 "I have attempted to see if this issue continues following the first batch and no other issue occurs." Yes, I can confirm that behaviour: after the first batch no other issues, which seems to confirm the BigQuery dataset & table/vue creation problem.
