### ISSUE TITLE
firestore-bigquery-export: Release updated version of @firebaseextensions/fs-bq-import-collection to NPM

### ISSUE THREAD

**Issue by dylan-sharp** [firebase/extensions#879]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-bigquery-export**
- Extension version: **0.1.20**
- Script name: **fs-bq-import-collection**

### [REQUIRED] Step 3: Describe the problem

The current version of `@firebaseextensions/fs-bq-import-collection` on npm is outdated and needs to be updated.  

In `extensions/firestore-bigquery-export/scripts/import/src/index.ts` an update has been made on master that changes the `FIRESTORE_VALID_CHARACTERS` regex to allow for `/` and `\` characters when specifying collection paths. ([see this commit](https://github.com/firebase/extensions/commit/df2c10598a198ec8f70da2ac2f17f4af5ea059ee))  What is currently on npm does not allow for those characters when specifying the import of an nested collection into big query not allowing a user of the script to import a nested collection from firestore into bigquery.  This commit needs to be released to npm to fix this issue.

#### Steps to reproduce:

1. Run `npx @firebaseextensions/fs-bq-import-collection@latest`
2. When Prompted enter project id
3. When prompted for collection enter a nested collection such as `company/google/stats`

##### Expected result

The expected result should be that the script will allow you to continue and import all documents in `company/google/stats` into big query.  

##### Actual result

The script states 
> The collection path does not match the regular expression provided

and does not let the user continue on with the script.

**Comment by KishinNextCompara** [comment]
Any update? I have the same problem :C

**Comment by dackers86** [comment]
@Dylan-Sharp @KishinNextCompara 

Thanks for the update. I've tagged this in our release column for visibility.
