### ISSUE TITLE
Ability to configure outbound traffic via vpcConnector for IP whitelisting

### ISSUE THREAD

**Issue by andreimarcut** [firebase/extensions#881]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: `firestore-send-email`

### What feature would you like to see?

I would like to be able to configure the extension with a static outbound IP [vpcconnector setup](https://firebase.google.com/docs/reference/functions/function_configuration.runtimeoptions#vpcconnector) such that I can use the more secure Google Workspace IP authentication feature.

### How would you use it?

I would already have the VPC Connector set up before starting to configure the extension.
I would already have the Google Workspace Gmail Relay Configuration set to only accept connections from the matching outbound IP.

I would pass the name of my `vpcConnector` parameter and `vpcConnectorEgressSettings` during extension configuration steps.

**Comment by FBuervenich** [comment]
@andreimarcut in case you still need a solution, it's possible. See my other comment for more details: https://github.com/firebase/extensions/issues/1040#issuecomment-1561745548

**Comment by andreimarcut** [comment]
That's good to know, thanks for sharing.
