### ISSUE TITLE
Trigger Email Without A Recpient and just bcc

### ISSUE THREAD

**Issue by joshpetit** [firebase/extensions#886]
### [REQUIRED] Step 2: Extension name

This feature request is for extension: **firestore-send-email**

### What feature would you like to see?

Being able to send an email without recipients and only bcc people

### How would you use it?

I would create an email of this structure:

```json
{
      message: message,
      from: "me@me.com",
      bcc: largerUserBaseArray,
}
```

**Comment by joshpetit** [comment]
whoops I was supposed to use bccUid not bcc, complete oversight my apologies!

**Comment by dackers86** [comment]
Hi @joshpetit 

Glad it is sorted! Thanks for the reply explaining the issue.
