### ISSUE TITLE
firestore-counter web client compatible with the modular API of firebase 9+

### ISSUE THREAD

**Issue by watafu-hibiki** [firebase/extensions#888]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: firebase/firestore-counter@0.2.4

### What feature would you like to see?

I'd like to have a version of this file compatible with the modular API of firebase 9+: 
https://github.com/firebase/extensions/blob/next/firestore-counter/clients/web/src/index.ts 

### How would you use it?
I'd be able to implement firestore distributed counters in angular applications that have the following dependencies:
angular 13+
firebase 9.6.7
@angular/fire 7.2.1

**Comment by dackers86** [comment]
Hi @watafu-hibiki. Thanks for the request.

This issue may potentially already be in progress, you can track it here https://github.com/firebase/extensions/pull/836.

Related to https://github.com/firebase/extensions/issues/666

**Comment by SamuelMichelRiad** [comment]
Is there any update on this issue?
