### ISSUE TITLE
Resize Image too cool!

### ISSUE THREAD

**Issue by Starscream9559** [firebase/extensions#9]
OMG I know this is not a BUG or REPORT post but I gotta let the team behind this knows that this extensions works very wonderful. Tried upload a JPG image of 787kB and after a refresh it resize the size to a freaking 13kB! That's a massive reduction of pixel as well as sizes. I wonder what happens if I reupload all my WEBP format.

**Comment by samtstern** [comment]
@Starscream9559 glad you're enjoying it!  Thanks for giving extensions a try on Day 1!
