### ISSUE TITLE
bug(firestore-bigquery-export): Partitioning column remains null for valid Firestore Timestamp values

### ISSUE THREAD

**Issue by kim-nocapinc** [firebase/extensions#904]
Describe your configuration

- Extension name: `firestore-bigquery-export`
- Extension version: firebase/firestore-bigquery-export@0.1.21
- Configuration values (redact info where appropriate):

<img width="509" alt="bq-export-config" src="https://user-images.githubusercontent.com/80534699/157188145-a06b3728-60c0-40cb-8abb-1fffe622683d.png">

Describe the problem

#### Steps to reproduce:

1. Configure the extension as shown in above image
2. Create a document in the collection with Timestamp field, e.g.:
<img width="459" alt="createdTimestamp" src="https://user-images.githubusercontent.com/80534699/157188973-1752ff71-734e-428c-9ce8-a08998bc646e.png">

##### Expected result
Matching BigQuery record has a `created` column populated with the corresponding Firestore value. 

##### Actual result
Matching BigQuery record has null in `created` column and logs read `Wrong type of Firestore Field for TimePartitioning. Accepts only strings in BigQuery format (DATE, DATETIME, TIMESTAMP) and Firestore Timestamp. Firestore Document field path: <redacted>/databases/(default)/documents/feed/<redacted>. Field name: created. Field data: [object Object]. Schema field "created" value will be null.` 

For some reason, `Timestamp` value does not pass `isValidPartitionTypeDate` even though the Firebase console shows it is a Firestore Timestamp. 

Related extension code: https://github.com/firebase/extensions/blob/ef272b27449d2d346df5c51387797a8d0abec53f/firestore-bigquery-export/firestore-bigquery-change-tracker/src/bigquery/partitioning.ts#L52 

Related PRs: #890 
Related Issues: #764

**Comment by dackers86** [comment]
Thanks for detailed issue @kim-nocapinc 

I've added a PR for investigating this issue.

**Comment by kim-nocapinc** [comment]
Thank _you_ @dackers86 for the quick response and taking the time to investigate! Really appreciate it!
