### ISSUE TITLE
[firestore-bigquery-export] Table not updated (while raw changelog is updated)

### ISSUE THREAD

**Issue by tgpsantos** [firebase/extensions#910]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: firestore-bigquery-export@0.1.21 
- Extension version: 0.1.21 

### [REQUIRED] Step 3: Describe the problem

I added a new sync export collection to bigquery using firebase export extension. 

I started by:
- creating export function to my_project.groups.all_groups
- after it completed, added all the docs from the original collection to the table (followed [these steps](https://cloud.google.com/bigquery/docs/loading-data-cloud-firestore))

The problem is that whenever a new change occurs, my all_groups table is not updated. Strangely, the all_groups_raw_changelog is updated correctly.

Then I went to the function to see the logs:
![imagem](https://user-images.githubusercontent.com/48353485/157901572-fc258323-560b-4a06-bf6b-585bea274cf6.png)

I have no idea if the problem is associated to this partition warning or not, but I created a new function without the TIME partitioning set. Same problem occurred afterwards.

I have no idea what I messed up in the process, I'd be grateful if you could help me. Happy to provide more info!

**Comment by dackers86** [comment]
HI @tgpsantos.

Can you confirm that your BigQuery datasets/tables and extension configuration are pointing to the same location?

Additionally, on your extension configuration we now have a pre-filled option for the project you would like to sync with, does this have the correct name?

**Comment by tgpsantos** [comment]
> HI @tgpsantos.
> 
> Can you confirm that your BigQuery datasets/tables and extension configuration are pointing to the same location?
> 
> Additionally, on your extension configuration there is have a pre-filled option for the project you would like to sync with, does this have the correct name?

I've checked the extension config and even compared it with a different export I have for another collection. 
I checked again and those params seem to be defined correctly.
Would the raw_changelog table be updated if any of those params was incorrect?

**Comment by dackers86** [comment]
> I've checked the extension config and even compared it with a different export I have for another collection. I checked again and those params seem to be defined correctly. Would the raw_changelog table be updated if any of those params was incorrect?

That seems ok, the location of the function or database would only be an issue if they are both showing incorrect results.

Apologies if breaking this down step by step, the logs suggest the data has been written - I just want to make sure we are looking in the right place.

Can you ensure that you are checking the `all_groups_raw_latest` view to see any updated information. Additionally, can you add a `new document` to the Firestore collection to produce a newly inserted records? Thanks!

**Comment by tgpsantos** [comment]
This [log highlighted in red ](https://user-images.githubusercontent.com/48353485/157943629-47c1176e-09d3-4796-97c7-7cc4b7d71f58.png) is also strange because my bq dataset is **groups** and my table is **all_groups**

**Comment by tgpsantos** [comment]
> > I've checked the extension config and even compared it with a different export I have for another collection. I checked again and those params seem to be defined correctly. Would the raw_changelog table be updated if any of those params was incorrect?
> 
> That seems ok, the location of the function or database would only be an issue if they are both showing incorrect results.
> 
> Apologies if breaking this down step by step, the logs suggest the data has been written - I just want to make sure we are looking in the right place.
> 
> Can you ensure that you are checking the `all_groups_raw_latest` view to see any updated information. Additionally, can you add a `new document` to the Firestore collection to produce a newly inserted records? Thanks!

I've added a document (that suffered immediate updates as you'll see in changelog) and this is the result for both tables:
- [all_groups_raw_latest](https://user-images.githubusercontent.com/48353485/157948265-ac4b7c7d-ca92-4d12-ac45-b6eec4156057.png)
- [all_groups_raw_latest](https://user-images.githubusercontent.com/48353485/157948265-ac4b7c7d-ca92-4d12-ac45-b6eec4156057.png)
- [all_groups_raw_changelog](https://user-images.githubusercontent.com/48353485/157948514-0e61f988-4701-47ed-a75c-db48ab3d13e9.png)

**Comment by dackers86** [comment]
Thanks @tgpsantos.

I've added to our project board for investigation.

**Comment by tgpsantos** [comment]
Thank you. I'm eager to solve this! Let me know if I can do anything to help with the troubleshoot. I'm available for 1on1 call if it helps

**Comment by tgpsantos** [comment]
I just noticed I've been getting these errors:

![imagem](https://user-images.githubusercontent.com/48353485/158446451-0dbdac70-e053-4e06-a088-e8a54bb417d2.png)


<details>
<summary>More details: </summary>

![imagem](https://user-images.githubusercontent.com/48353485/158446697-8b3aba07-064a-473e-a5b3-9f6667dae600.png)

![imagem](https://user-images.githubusercontent.com/48353485/158446808-a29c3e3b-7cb0-4f79-9af9-e2dd629bb8f8.png)

![imagem](https://user-images.githubusercontent.com/48353485/158446870-0ce91ec5-0a18-489c-b09f-40aa146346eb.png)

</details>

**Comment by dackers86** [comment]
Hi @tgpsantos.

Can you please reach out through either my twitter or email at https://github.com/dackers86 to see if I can offer some additional support from there. Thanks.

**Comment by jumojer** [comment]
Correction, on #923 downgrading, did NOT solve the problem :)
