### ISSUE TITLE
firestore-send-email : template not updated

### ISSUE THREAD

**Issue by rphlmr** [firebase/extensions#92]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: `firestore-send-email`
- Configuration values (redact info where appropriate):
  - all config require (extension is working, except that if I modify a template, modifications are not applied)

#### Steps to reproduce:

In firestore-send-email, if I modify a template, these modifications are not applied.
The html code is good, there is all my modifications, but the function still send the old template version.

##### Expected result

The updated template.

##### Actual result

Mail send with the old template

**Comment by rphlmr** [comment]
NB : to solve that, I have to reconfigure my extension ;)

**Comment by mbleigh** [comment]
Templates should be updated in realtime (see [templates.ts](https://github.com/firebase/extensions/blob/next/firestore-send-email/functions/src/templates.ts) in the source). The `onSnapshot` should be calling `updateTemplates` whenever one changes.

If not, that's a bug...

**Comment by rphlmr** [comment]
I don't remind it happened weeks ago when I start playing with this function. But we are still in version 0.1.0.
Maybe it could help : before I try to update my template, the function throw an error about could start (opened issue). Maybe after that something broke ?

**Comment by rphlmr** [comment]
Hello there,

I tried again and it works. I really think it was due to called start error.
Now that's fixed, maybe it's no more a bug ?

**Comment by Ehesp** [comment]
Ok let's go ahead and close this one. Logically the code is working fine, however we'll keep an eye on it. Thanks!

**Comment by tyler-aligned-hq** [comment]
This exact same bug is happening to me on firebase/firestore-send-email@0.1.34. The extension seems to be caching my templates and only updating them after some arbitrary amount of time (sometimes over an hour). My template collection updates right away and there is no evidence of any of the old templates, but the old templates keep getting emailed out regardless.
