### ISSUE TITLE
firestore-bigquery-export: Configuration errors for non-required values

### ISSUE THREAD

**Issue by JarnoRFB** [firebase/extensions#924]
### Describe your configuration

- Extension name: **firestore-bigquery-export** 
- Extension version: **0.1.20**
- Configuration values (redact info where appropriate):

```
LOCATION=europe-west1
DATASET_LOCATION=europe-west1
COLLECTION_PATH=mycollection
TABLE_ID=mycollection
```

### Describe the problem
I am using the firebase CLI to install the bigquery extension. I have a script that installs the extension for all collections that I stream into bigquery. Now I wanted to add a collection and got errors even for my collections that had the extension already installed. Usually I just get a 409 for those collection. As the parameters `WILDCARD_IDS` and `TIME_PARTITIONING_FIELD_TYPE` are not required https://github.com/firebase/extensions/blob/15d65a02fea0d98a28b163e91ef1b17c06b8615b/firestore-bigquery-export/extension.yaml#L226 , I do not understand why the installation complains that they are missing. Once I add the values to the env file 

```
WILDCARD_IDS=false
TIME_PARTITIONING_FIELD_TYPE=omit
```

the installation produces the usual 409 error again, but also does not update the extension.

#### Steps to reproduce:

`npx firebase ext:install firebase/firestore-bigquery-export --force --params params.env`

##### Expected result
The extension updates or installs for collections where it has previously not been installed.

##### Actual result

The extension complains about missing config values.

```
⚠  undefined is not a valid option for WILDCARD_IDS.
⚠  undefined is not a valid option for TIME_PARTITIONING_FIELD_TYPE.
```

**Comment by JarnoRFB** [comment]
Update: Once I manually update the extension to version `0.1.21` I was able to get 409 code with my old config that does not contain  `WILDCARD_IDS` and `TIME_PARTITIONING_FIELD_TYPE`.

**Comment by dackers86** [comment]
Hi @JarnoRFB.

Is this still an issue for you? I can attempt to replicate locally, early assumption is because there are new required fields for the extension on the latest version. This may need investigating.

**Comment by i14h** [comment]
@dackers86 maybe this points to adding better documentation around the new features as well

**Comment by JarnoRFB** [comment]
@dackers86 As described I get around it by either specifying the values in the .env file or by manually updating the extension. I can confirm though, that the issue still persists. So it's less an urgent problem, but more pertaining the general developer experience.

**Comment by dackers86** [comment]
Thanks @JarnoRFB. We will certainly look to improve this to avoid any future confusion.

**Comment by SanujBansal** [comment]
@JarnoRFB Can you share your params.env file for reference

**Comment by JarnoRFB** [comment]
@SanujBansal my script is in `package.json` and looks like.

`"bigQueryStreaming:install": "for f in bq-streaming/config/*; do   echo \"firestore-bigquery-export-$(basename ${f%.env})\" | tr '_' '-' | npx firebase ext:install firebase/firestore-bigquery-export --force --params \"$f\"; done",
`

Then in `bq-streaming/config` I have the config file for all collections I want to install the extension for, such as `some_collection.env`. The `--force` suppresses the interactive input.

**Comment by gregfenton** [comment]
I confirm the issue as reported.  A previously scripted installation that has worked across a dozen installation now fails with the reported error:

```
⚠  undefined is not a valid option for WILDCARD_IDS.
⚠  undefined is not a valid option for TIME_PARTITIONING_FIELD_TYPE.
```

Adding the following to my `.env` files seems to resolve the issue:

```
WILDCARD_IDS=false
TIME_PARTITIONING_FIELD_TYPE=omit
```

**Comment by gregfenton** [comment]
I'm unclear of the terminology being used here....if it is "inside the code" or talking about the external view (the "user experience").

If the latter, having a *required parameter* that has a *default value* is awkward.  A parameter being *required* (from the user's point of view) means they need to specify it on the command line, even though it has a default value?

**Comment by dackers86** [comment]
@gregfenton I see what you mean.

I will attempt to get clarification on this terminology, I suppose for now we could assume if you are presented a multi-select, then it is required to select.

Also, this field could now be considered, `not required` but still a multi-select option.

**Comment by yamankatby** [comment]
Hi there,
Closing this issue, as a solution has been provided but the example now only suits the previous versions that do not have the change. Feel free to reopen if you are still facing the issue or need more support.
