### ISSUE TITLE
Translate Text should use Multiselect type for language list param

### ISSUE THREAD

**Issue by andieromero** [firebase/extensions#94]
### Extension name: 
storage-resize-images

### Describe the problem
This is not a behavioral issue with the extension, but rather a UX bug. Typing in a list of languages seems tedious and there is a MULTISELECT param type that would be more appropriate here. I'd like to browse through the available languages and select from there.

#### Other considerations
If the list is quite long, the UX in the CLI might be tedious. Maybe they could be alphabetized.

**Comment by rosariopfernandes** [comment]
@andrianabeltran I agree typing in a list of languages can be tedious. But I think having it as a multiselect param would not only make the CLI UX tedious, but would also require us to keep track of languages supported by Cloud Translation and update the extension every time a new language is added.

**Comment by Ehesp** [comment]
XFN Team: This would benefit from Richer Param Types. As it isn't blocking at the moment, it maybe worth sitting on for the time being?

**Comment by laurenzlong** [comment]
We plan to address in the new year by considering a new param type that allows more ergonomic way to input multiple string.

**Comment by jhuleatt** [comment]
Closing out this issue since it's extensions platform work that's being tracked internally
