### ISSUE TITLE
[firestore-send-email] connection uri regexp does not accept query params

### ISSUE THREAD

**Issue by spiritory** [firebase/extensions#940]
### [REQUIRED] Step 2: Describe your configuration

- Extension name:  firestore-send-email
- Extension version: 0.1.16

#### Steps to reproduce:

I'm using o365 as smtp server and the only way I was able to make that work was to use this connection uri:

`smtps://username:password@smtp.office365.com:587/?service=Outlook365&tls.ciphers=SSLv3`

Last working extension version is 0.1.13

##### Expected result

uri with params is accepted

##### Actual result

regexp validation fails

**Comment by dackers86** [comment]
Hi @spiritory 

You mentioned that the above `uri` was accepted.

```
smtps://username:password@smtp.office365.com:587/?service=Outlook365&tls.ciphers=SSLv3
```

Can you confirm which `uri` example was not accepted and providing a failed validation?

**Comment by spiritory** [comment]
It was accepted in version 0.1.13, in the current version (0.1.16) I get this error:

"Invalid SMTP connection URI. Must be in the form `smtp(s)://username:password@hostname:port` or smtp(s)://username@hostname:port`."

**Comment by dackers86** [comment]
This appears to be a bug as the latest update does not allow query strings. 

Suggested regex to improve this could be `^(smtp[s]*:\/\/.*?:[0-9]+.*$)` .

Testing use cases at https://regex101.com/r/Ya9rUW/1

**Comment by ottob** [comment]
I ran into this issue too while trying to set up a new project today. The uri I needed to use and that worked with firestore-send-email@0.1.11: `smtps://myuser@mydomain.com@smtp-relay.gmail.com:465?name=mydomain.com`

**Comment by yamankatby** [comment]
> This appears to be a bug as the latest update does not allow query strings.
> 
> Suggested regex to improve this could be `^(smtp[s]*:\/\/.*?:[0-9]+.*$)` .
> 
> Testing use cases at https://regex101.com/r/Ya9rUW/1

This Regex works fine
