### ISSUE TITLE
[storage-resize-images] Please release 0.1.28 with fix from @joehan

### ISSUE THREAD

**Issue by otopba** [firebase/extensions#941]
[joehan](https://github.com/firebase/extensions/commits?author=joehan) committed 5 days ago https://github.com/firebase/extensions/commit/02e7fea8cd5e575f57f872c77160d94561ba5054

Without this I catch error:

```
 Error while parsing "Output options for selected format". Parameter will be ignored SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at convertType (/workspace/lib/resize-image.js:41:30)
    at Object.exports.modifyImage (/workspace/lib/resize-image.js:158:41) 
```

**Comment by dackers86** [comment]
@otopba Thanks for the update. I've moved this to our launch column for visibility.

**Comment by dackers86** [comment]
Version release https://firebase.google.com/products/extensions/firebase-storage-resize-images?authuser=0&hl=en

Closing issue.
