### ISSUE TITLE
[FS-BQ-Export] Cannot export whole rows, missing most of rows.

### ISSUE THREAD

**Issue by jamestalano** [firebase/extensions#945]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

[firestore-bigquery-export] 0.1.22

#### Steps to reproduce:

I have updated the collections on firestore from iOS device, swift app by batch writing. It was working well to get the right result when I use normal writing to firestore, but only for batch writing, I cannot see some of rows. It seems like only 2 of 10 rows are exported.

##### Actual result
Only display only 90 rows.
<img width="521" alt="Screen Shot 2022-04-21 at 11 34 21 AM" src="https://user-images.githubusercontent.com/43224497/164508501-9ed38a18-132f-49f6-8910-8f80c92c6113.png">
<img width="744" alt="Screen Shot 2022-04-21 at 11 34 38 AM" src="https://user-images.githubusercontent.com/43224497/164508508-18a02294-62ee-417b-ba68-8c56d877c61c.png">
<img width="954" alt="Screen Shot 2022-04-21 at 11 35 55 AM" src="https://user-images.githubusercontent.com/43224497/164508705-b4d8316b-e80c-4f64-b04c-a4b425efb726.png">

**Comment by dackers86** [comment]
Hi @jamestalano 

Could you provide an example of some output from the extension logs?

**Comment by jamestalano** [comment]
Hi @dackers86 
Thanks for your reply. I already attached the screenshots. What kind of example you need please?

**Comment by dackers86** [comment]
The above screenshot only appears to show timestamps and no output messages.

We have a known issue reporting logs files state that an `IF_MATCH` condition has not been met I just wanted to confirm if this issue was related or if a different issue has been encountered. Thanks!

**Comment by jamestalano** [comment]
Error when mirroring data to BigQuery ApiError: Resource vifive-home:firestore_export.keypoint_snapshots_raw_latest did not meet condition IF_MATCH
    at new ApiError (/workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:58:15)
    at Util.parseHttpRespBody (/workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:193:38)
    at Util.handleResp (/workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:134:117)
    at /workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:432:22
    at onResponse (/workspace/node_modules/retry-request/index.js:228:7)
    at /workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/teeny-request/build/src/index.js:233:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 412,
  errors: [
    {
      message: 'Resource vifive-home:firestore_export.keypoint_snapshots_raw_latest did not meet condition IF_MATCH',
      domain: 'global',
      reason: 'conditionNotMet',
      location: 'If-Match',
      locationType: 'header'
    }
  ],
  response: Gunzip {
    _writeState: Uint32Array(2) [ 15901, 0 ],
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      destroyed: true,
      errored: null,
      closed: true,
      closeEmitted: true,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      prefinish: [Function: prefinish],
      error: [Array],
      data: [Function (anonymous)],
      end: [Function (anonymous)]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: true,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: true
    },
    allowHalfOpen: true,
    bytesWritten: 254,
    _handle: null,
    _outBuffer: <Buffer 7b 0a 20 20 22 65 72 72 6f 72 22 3a 20 7b 0a 20 20 20 20 22 63 6f 64 65 22 3a 20 34 31 32 2c 0a 20 20 20 20 22 6d 65 73 73 61 67 65 22 3a 20 22 52 65 ... 16334 more bytes>,
    _outOffset: 483,
    _chunkSize: 16384,
    _defaultFlushFlag: 2,
    _finishFlushFlag: 2,
    _defaultFullFlushFlag: 3,
    _info: undefined,
    _maxOutputLength: 4294967295,
    _level: -1,
    _strategy: 0,
    statusCode: 412,
    statusMessage: 'Precondition Failed',
    request: {
      agent: [Agent],
      headers: [Object],
      href: 'https://bigquery.googleapis.com/bigquery/v2/projects/vifive-home/datasets/firestore_export/tables/keypoint_snapshots_raw_latest?'
    },
    body: '{\n' +
      '  "error": {\n' +
      '    "code": 412,\n' +
      '    "message": "Resource vifive-home:firestore_export.keypoint_snapshots_raw_latest did not meet condition IF_MATCH",\n' +
      '    "errors": [\n' +
      '      {\n' +
      '        "message": "Resource vifive-home:firestore_export.keypoint_snapshots_raw_latest did not meet condition IF_MATCH",\n' +
      '        "domain": "global",\n' +
      '        "reason": "conditionNotMet",\n' +
      '        "location": "If-Match",\n' +
      '        "locationType": "header"\n' +
      '      }\n' +
      '    ],\n' +
      '    "status": "FAILED_PRECONDITION"\n' +
      '  }\n' +
      '}\n',
    headers: {
      'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
      'cache-control': 'private',
      'content-encoding': 'gzip',
      'content-type': 'application/json; charset=UTF-8',
      date: 'Thu, 28 Apr 2022 12:21:26 GMT',
      etag: 'EXUiokxZIYT3njVmKvNUaQ==',
      server: 'ESF',
      'transfer-encoding': 'chunked',
      vary: 'Origin, X-Origin, Referer',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '0'
    },
    toJSON: [Function: toJSON],
    [Symbol(kCapture)]: false,
    [Symbol(kTransformState)]: {
      afterTransform: [Function: bound afterTransform],
      needTransform: false,
      transforming: false,
      writecb: null,
      writechunk: null,
      writeencoding: 'buffer'
    },
    [Symbol(kError)]: null
  }
}

**Comment by jamestalano** [comment]
ext-firestore-bigquery-export-qggk-fsexportbigquery
Error when mirroring data to BigQuery ApiError: Precondition check failed. at new ApiError (/workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:58:15) at Util.parseHttpRespBody (/workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:193:38) at Util.handleResp (/workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:134:117) at /workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:432:22 at onResponse (/workspace/node_modules/retry-request/index.js:228:7) at /workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/teeny-request/build/src/index.js:233:13 at processTicksAndRejections (internal/process/task_queues.js:95:5) { code: 412, errors: [ { message: 'Precondition check failed.', domain: 'global', reason: 'failedPrecondition' } ], response: Gunzip { _writeState: Uint32Array(2) [ 16110, 0 ], _readableState: ReadableState { objectMode: false, highWaterMark: 16384, buffer: BufferList { head: null, tail: null, length: 0 }, length: 0, pipes: [], flowing: true, ended: true, endEmitted: true, reading: false, sync: false, needReadable: false, emittedReadable: false, readableListening: false, resumeScheduled: false, errorEmitted: false, emitClose: true, autoDestroy: true, destroyed: true, errored: null, closed: true, closeEmitted: true, defaultEncoding: 'utf8', awaitDrainWriters: null, multiAwaitDrain: false, readingMore: false, dataEmitted: true, decoder: null, encoding: null, [Symbol(kPaused)]: false }, _events: [Object: null prototype] { prefinish: [Function: prefinish], error: [Array], data: [Function (anonymous)], end: [Function (anonymous)] }, _eventsCount: 4, _maxListeners: undefined, _writableState: WritableState { objectMode: false, highWaterMark: 16384, finalCalled: false, needDrain: false, ending: true, ended: true, finished: true, destroyed: true, decodeStrings: true, defaultEncoding: 'utf8', length: 0, writing: false, corked: 0, sync: false, bufferProcessing: false, onwrite: [Function: bound onwrite], writecb: null, writelen: 0, afterWriteTickInfo: null, buffered: [], bufferedIndex: 0, allBuffers: true, allNoop: true, pendingcb: 0, prefinished: true, errorEmitted: false, emitClose: true, autoDestroy: true, errored: null, closed: true }, allowHalfOpen: true, bytesWritten: 171, _handle: null, _outBuffer: <Buffer 7b 0a 20 20 22 65 72 72 6f 72 22 3a 20 7b 0a 20 20 20 20 22 63 6f 64 65 22 3a 20 34 31 32 2c 0a 20 20 20 20 22 6d 65 73 73 61 67 65 22 3a 20 22 50 72 ... 16334 more bytes>, _outOffset: 274, _chunkSize: 16384, _defaultFlushFlag: 2, _finishFlushFlag: 2, _defaultFullFlushFlag: 3, _info: undefined, _maxOutputLength: 4294967295, _level: -1, _strategy: 0, statusCode: 412, statusMessage: 'Precondition Failed', request: { agent: [Agent], headers: [Object], href: 'https://bigquery.googleapis.com/bigquery/v2/projects/vifive-home/datasets/firestore_export/tables/keypoint_snapshots_raw_latest?' }, body: '{\n' + ' "error": {\n' + ' "code": 412,\n' + ' "message": "Precondition check failed.",\n' + ' "errors": [\n' + ' {\n' + ' "message": "Precondition check failed.",\n' + ' "domain": "global",\n' + ' "reason": "failedPrecondition"\n' + ' }\n' + ' ],\n' + ' "status": "FAILED_PRECONDITION"\n' + ' }\n' + '}\n', headers: { 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'cache-control': 'private', 'content-encoding': 'gzip', 'content-type': 'application/json; charset=UTF-8', date: 'Wed, 27 Apr 2022 16:35:44 GMT', etag: 'g1R7a+glVQGohVNtxYjv9A==', server: 'ESF', 'transfer-encoding': 'chunked', vary: 'Origin, X-Origin, Referer', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '0' }, toJSON: [Function: toJSON], [Symbol(kCapture)]: false, [Symbol(kTransformState)]: { afterTransform: [Function: bound afterTransform], needTransform: false, transforming: false, writecb: null, writechunk: null, writeencoding: 'buffer' }, [Symbol(kError)]: null } }

**Comment by jamestalano** [comment]
As you can see, we get two types of errors. Can you please take a look and let us know the result? Thanks

**Comment by jamestalano** [comment]
@dackers86  Just checking in on you.

**Comment by dackers86** [comment]
Hey @jamestalano.

Apologies for the late reply, the error logs provided show what I expected, displaying an `IF_MATCH` error.

We currently have a PR in review which should fix this issue. Please follow https://github.com/firebase/extensions/issues/923 for progress on this issue.

**Comment by jamestalano** [comment]
wow that sounds great! Thank you so much @dackers86

**Comment by jamestalano** [comment]
@dackers86  Could you please update me? I think the PR already got an approval, when it can be available to the product? Thanks

**Comment by dackers86** [comment]
Hi @jamestalano. I cannot give a definitive date on the next release at the moment. 

I'll ping this to see if we can get a release date organised.

**Comment by manikant-prasad** [comment]
Hi @dackers86 , any update on this issue?

**Comment by dackers86** [comment]
Hi @manikant-prasad We are looking to release an updated this week! I'll keep you posted
