### ISSUE TITLE
`path_params` for importing firestore documents to BigQuery

### ISSUE THREAD

**Issue by randyumi** [firebase/extensions#947]
### [REQUIRED] Step 2: Extension name

This feature request is for extension: firestore-bigquery-export

### What feature would you like to see?

I would like an [importing script](https://github.com/firebase/extensions/tree/next/firestore-bigquery-export/scripts/import) to write document ID of a sub-collection's parent.

Thanks to #871, the document ID of sub-collection's parent is recorded in the `path_params` column to BigQuery table.
However, when I use the importing script with `COLLECTION_GROUP_QUERY=true`, the `path_params` will be `null`. I think it is because the importing script does not provide `path_params` while converting documents to BigQuery record https://github.com/firebase/extensions/blob/next/firestore-bigquery-export/scripts/import/src/worker.ts#L55-L66

To write `path_params` to a BigQuery table, the program should know which part of document path is a "parameter" and the name of that. If we realize this feature, I think the program should add an option like `--subcollection-parameter-template path/${to}/document` to recognize the path_param.

### How would you use it?

I'd like to use `path_params` to join other BigQuery tables.

**Comment by dackers86** [comment]
Thanks @randyumi.

It appears that the importer will need updating to allow this new feature.
