### ISSUE TITLE
MessageBird Extension

### ISSUE THREAD

**Issue by paulaegido** [firebase/extensions#953]
I am not able to successfully process the sending of an sms through the firebase extension. Attached is the code of my js code to generate the document in the firestore collection, as well as the document created by the extension, where you can see the parameters received and the error. I have talked to messagebird support and they do not handle this error. The problem must be with firebase.

`firestoredb.collection('messages').add({
channelId: 'mychannelID',
originator : 'Testing',
recipients : ['34689454416'],
type: 'sms',
body : 'This is a test',
});`

![image](https://user-images.githubusercontent.com/43550305/165507797-a0de0e1d-170c-431d-9638-8f63e6fa516c.png)

**Comment by dackers86** [comment]
Thanks for the detailed error @paulaegido.

This extension is managed on the official MessageBird repository https://github.com/messagebird/firestore-send-msg/issues.

Could you update the MessageBird repository with this bug? Thanks!

**Comment by huangjeff5** [comment]
Yeah, looking at the extension code, there's an explicit check that the `to` field exists in each message document. If you want to send in bulk, you can create one document per recipient, and each document write will trigger a separate handler to send the message. 

Perhaps you can also request `bulk send within a single document` as a feature request on the messagebird repo :)

**Comment by dackers86** [comment]
As stated above, it does seem like a new feature request would need to be added on the MessageBird repository if you would like to send to multiple contacts per request.

A `string` value will fix the current error message as stated. Examples can also be found in the POSTINSTALL https://github.com/messagebird/firestore-send-msg/blob/master/POSTINSTALL.md


Closing the issue for now.
