### ISSUE TITLE
[storage-resize-images] Can't set "Convert image to preferred types"

### ISSUE THREAD

**Issue by otopba** [firebase/extensions#959]
firebase/storage-resize-images@0.1.27

I'm trying to change the extension. But it always resets to the initial value

https://user-images.githubusercontent.com/4225279/166405495-cf1e6a56-1064-4153-9f46-bbb96880edc0.mov

**Comment by i14h** [comment]
the engineering team will be rolling out a change pretty soon to fix this. I'll keep this issue open until the change is rolled out to 100% of users.

**Comment by tjlav5** [comment]
Should be good now, fix made it out Thurs/Friday.
