### ISSUE TITLE
[Docs/GUI Update Request] List the options and defaults for Sharp Output Options in storage-resize-images

### ISSUE THREAD

**Issue by crevulus** [firebase/extensions#963]
### [READ] Step 1: Are you in the right place? ✅ 

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

This feature request is for extension: **\storage-resize-images**

### What feature would you like to see?

Typings and/or documentation for Sharp Output Options, along with the defaults currently used by the extension

### How would you use it?

Currently this is all we get to see when we try to configure the Sharp Output Options:
<img width="686" alt="Screenshot 2022-05-04 at 12 02 24" src="https://user-images.githubusercontent.com/50107046/166661493-3f1b5550-2c87-4b52-90fb-07e66de8e7d8.png">

This is not enough information, as we do not know what options are available or what the defaults are that firebase uses. Some more information on how to configure the image optimisation would be very helpful.

**Comment by dackers86** [comment]
Api source can found be found here https://sharp.pixelplumbing.com/api-output#jpeg with jpeg as an example.
