### ISSUE TITLE
[fs-bq-import-collection] Error importing Collection to BigQuery: TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by meyerovb** [firebase/extensions#965]
fs-bq-import-collection
Works fine on one collection, try it on another one of mine and consistently get this:
Error importing Collection to BigQuery: TypeError: Cannot read property 'forEach' of undefined

**Comment by dackers86** [comment]
Updated PR. #946 will fix this by checking if errors exist before logging.
