### ISSUE TITLE
"unknown error" download extension to stream firestore collection to bq

### ISSUE THREAD

**Issue by ipcleary** [firebase/extensions#968]
Same error as seen here: 
![image](https://user-images.githubusercontent.com/90464398/167157912-c3e70095-ed58-4d81-9d66-f30116a8b7a2.png)

Interestingly, I am able to install the same extension for another project to an identical collection.

**Comment by dackers86** [comment]
Hi @ipcleary.

This an issue that the Firebase team is currently investigating. 

You can use the firebase  cli in the meantime to get around this problem.

**Comment by ipcleary** [comment]
@dackers86 good to know, thank you!
