### ISSUE TITLE
Rate limit errors when streaming from Firestore to BigQuery

### ISSUE THREAD

**Issue by joehan** [firebase/extensions#975]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: `firestore-bigquery-export`
- Extension version: 0.1.22
- Configuration values (redact info where appropriate):
  - **\_**
  - **\_**

### [REQUIRED] Step 3: Describe the problem
Mirroring internal bug b/230826037 here. May be a copy of #923 
After upgrading to 0.1.22, customer noticed that they started getting the following error  from bigquery:
```Error: Exceeded rate limits: too many api requests per user per method for this user_method```
 According to our [public docs](https://cloud.google.com/bigquery/docs/troubleshoot-quotas#ts-maximum-api-request-limit), this error relates to quota for non-streaming inserts to BigQuery. On the other hand, this extension should be using streaming inserts as [documented](https://firebase.google.com/products/extensions/firebase-firestore-bigquery-export#:~:text=this%20extension%20writes%20to%20BigQuery).

#### Steps to reproduce:

- Installed the latest version 0.1.22 for "Stream Collections to BigQuery" extension in test project for Firestore collection customers.
- Followed this [quickstart](https://www.cloudskillsboost.google/focuses/8392?parent=catalog) to generate & load 10,000 new dummy documents in my Firestore database collections customers
- Observed similar precondition & rate limited errors. Out of 10,000 new documents, only 277 documents were loaded in Bigquery 
-Downgraded the extension to older version 0.1.20 using below steps.
$ firebase ext:export
## Update the version for the extension to 0.1.20
$ nano firebase.json
## deploy changes to your project
$ firebase deploy --only extensions 
- No new errors were observed. All 10,000 documents were inserted

##### Expected result
Documents are inserted without problems
##### Actual result
Almost all documents were not successfully inserted.

**Comment by dackers86** [comment]
@joehan I saw some similar error logs when developing the above PR. This looks to time a delay when checking dataset and table availability.

We are also looking to invert the logic in further development. This will potentially try the write to BQ first and then catching to ensure the resources are created if they do not exist.

**Comment by rmkol** [comment]
I see that this issue is already closed, but we are still getting rate limit errors even with the latest extension version 0.1.32.
And looks like this issue is similar to https://github.com/firebase/extensions/issues/1394.

**Comment by rmkol** [comment]
@joehan were you able to fix it on your side?
