### ISSUE TITLE
[firestore-send-email] Special characters in SMTP password

### ISSUE THREAD

**Issue by stevenmanton** [firebase/extensions#992]
### [READ] Step 1: Are you in the right place?

Yes

### [REQUIRED] Step 2: Describe your configuration

- Extension name: `firestore-send-email`
- Extension version: `0.1.17`
- Configuration values (redact info where appropriate):
  - SMTP connection uri: `smtps://info@mydomain@smtp-relay.gmail.com:465`
  - SMTP password: <redacted>

#### Steps to reproduce:

I'm trying to send emails through my Google Workspace account and I ran into the error shown below, which I only found by looking at the logs for the `ext-firestore-send-email-processQueue` Function. Eventually, I tracked down the issue to be with the password I'm using, which is the random password I set up for my user account. Since the password has special characters, it seems to fail the URI validation. It would appear SMTP passwords shouldn't have certain special characters (though I'm not sure what the valid list is).

```
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Url.parse (url.js:355:19)
    at Object.urlParse [as parse] (url.js:158:13)
    at Object.module.exports.parseConnectionUrl (/workspace/node_modules/nodemailer/lib/shared/index.js:241:13)
    at Object.module.exports.createTransport (/workspace/node_modules/nodemailer/lib/nodemailer.js:33:30)
    at Object.exports.setSmtpCredentials (/workspace/lib/helpers.js:18:30)
    at transportLayer (/workspace/lib/index.js:56:22)
    at initialize (/workspace/lib/index.js:40:23) 
```

You can also get the same error with this example code:

```node
const nodemailer = require("nodemailer")
const url = require("url");
let uri = new url.URL("smtps://info@mydomain.com@smtp-relay.gmail.com:465");
uri.password = "omgaspecialcharacter*!"
const transport = nodemailer.createTransport(uri.href);
```

##### Expected result

One fix would be to add better logging and error handling in the Function. A better fix would be to validate on the UI that the password doesn't contain invalid characters.

##### Actual result

The failure shown above.

**Comment by yamankatby** [comment]
Hi @stevenmanton, thank you for reporting this issue.
I've tried to run the code snippet you provided and it works perfectly, with no errors.

The "malformed URI" is a general error that occurs when URI encoding or decoding wasn't successful.

I have a question do you use the URL and password provided in the issue in your example, if not can you run `encodeURI("...your URL");` `encodeURIComponent("...your password");` in the console and use the output of them as URL and password. see if anything changes.

**Comment by i14h** [comment]
@stevenmanton does this issue also show up when you're using secrets? you know we advise against using the cleartext form of passwords in this extension

**Comment by stevenmanton** [comment]
Thanks @yamankatby and @i14h for the tips! So it turns out the special character that actually causes the URI decode error is `%`, for example `password%`. I did a quick search through other special characters and couldn't find any other that cause that error.

Also, yes, I'm using the secret manager for the SMTP password.
