### ISSUE TITLE
[Trigger Email] Error: Missing credentials for "PLAIN"

### ISSUE THREAD

**Issue by niklasbartsch** [firebase/extensions#996]
I am using the Trigger Email Extension and it failes.
I get the following error: `Error: Missing credentials for "PLAIN"`

I tried a smtps and smtp configuration
smtps://w123456.kasserver.com:465

I already tried to deinstall and reinstall the extension, because I couln't change the password
I deleted all the previous configurations in the Secret Manager.

Has anyone a solution?

**Comment by dackers86** [comment]
Hi @niklasbartsch Updates to the extension now try to use a url validator to ensure credentials are appropriate. 

We have a current PR to fix any password updates, if you password contains any special characters. -`?` has been the most obvious so far, then you have a few options from here...

## Downgrade
Use the cli to install a specific version of the extension via `firebase install firestore-send-email@0.1.17--project={project_name}`

## Install via the PR manually (not recommended)
 `firebase ext:install firestore-send-email . --project={project_name}` 
 `firebase ext:update firestore-send-email {extension-name} . --project={project_name}` 

source: https://github.com/firebase/extensions/pull/985

## Wait for the next release
We have approved the PR and looking to release this fix soon.

Downgrade is probably the best option currently!

**Comment by knownasilya** [comment]
Has this been released?

**Comment by dackers86** [comment]
Hi @knownasilya 

Yes, this has been released.  Does the emulator work if you update your env file to be `env.local`?

**Comment by knownasilya** [comment]
@dackers86 same error as before. I'm on `firebase/firestore-send-email@0.1.23`

**Comment by dackers86** [comment]
Ah, you're correct @knownasilya We use a local smtp server when `TESTING` has been added.

This could be a potential documentation update.

**Comment by knownasilya** [comment]
Should it still work though when no `TESTING ` supplied?

**Comment by dackers86** [comment]
When using the emulator those credentials are not needed for this extension.

The test that runs uses the above `TESTING=true`  which means that the credentials are not passed in the the nodemailer transport:

```
  if (config.testing) {
    return nodemailer.createTransport({
      host: "localhost",
      port: 8132,
      secure: false,
      tls: {
        rejectUnauthorized: false,
      },
    });
  }

  return setSmtpCredentials(config);
```

The credentials would be only for a prod installation.

What command are you running to receive the error?

```
FirebaseError: HTTP Error: 404, Secret [projects/<project-id-here>/secrets/undefined] not found or has no versions.
```

For the emulator for example I would expect something similar to `firebase emualtors:start --project={project_id}`?

**Comment by knownasilya** [comment]
I was trying to get it to replicate production locally. I didn't have `TESTING` but did have local credentials. This is where I saw the error. Afterwards I saw `TESTING` in the code you linked above and tried that, which worked and helps for now, but would still like to do a real test at some point.
